### ISSUE TITLE
Range figures based on usable_battery_level and battery_level mixed up

### ISSUE THREAD

**Issue by leewillis77** [teslamate-org/teslamate#1121]
**Describe the bug**

On the "Projected range - Battery level" and "Projected Range - Outdoor temperature" graphs there are two separate figures, one based on `battery_level` and once based on `usable_battery_level`. My understanding was that `battery_level` should always be equal to, or higher than the `usable_battery_level` since `usable_battery_level` is reduced when cold. 

However, the two figures seem switched on my graphs, as the range based on `battery_level` is almost entirely "higher" than the one based on `usable_battery_level`. 

**Screenshots**

![Screenshot 2020-12-15 at 10 09 29](https://user-images.githubusercontent.com/1097338/102201195-abfa9800-3ebd-11eb-94fa-07e96aa4b8bd.png)

![Screenshot 2020-12-15 at 10 09 39](https://user-images.githubusercontent.com/1097338/102201208-aef58880-3ebd-11eb-895b-19ee8d0ceed0.png)

**Environment**

- TeslaMate version: 1.20.1
- Type of installation: Docker
- OS TeslaMate is installed on: Raspberry Pi
- User OS & Browser: Chrome / MacOS

**Comment by leewillis77** [comment]
This zoom-in perhaps shows the issue better:

![Screenshot 2020-12-15 at 13 14 48](https://user-images.githubusercontent.com/1097338/102219861-f25cf080-3ed7-11eb-92eb-d462eae56f6d.png)

**Comment by petariga** [comment]
I noticed this TeslaMate behaviour too. It might be just a confusion of the names, however it also might be rooted much deeper in the system. For example the same strange behaviour has the range in the mouse over of the percentage State of Charge of the TeslaMate homepage. It states longer range when the batteries are frozen (with the snowflake).

**Comment by leewillis77** [comment]
It's definitely strange. The underlying data looks accurate, and correctly imported. The query looks sensible*, but for some reason the values shown in grafana are incorrect. 

\* The use of `SUM()` rather than `MIN()` or `MAX()` confuses me a little but that doesn't seem related to this issue...

**Comment by dyxyl** [comment]
I think this is expected. The API gives the ``battery_range``, i.e. the range based on the current state of charge. To calculate the projected range, i.e. the range at 100% SoC, you need to divide the ``battery_range`` by the ``battery_level`` (%SoC) and multiply by 100. Therefore dividing by the smaller ``usable_battery_level`` gives a higher projected range.

**Comment by petariga** [comment]
However, IMHO it is not logical - with less usable battery level you must have also less projected range, not more...

**Comment by dyxyl** [comment]
It is logical, because the projected range is the range at 100% SoC under some specific conditions, not the current conditions.

Also, the ``usable_battery_level`` tells you what you can use under current conditions, not what you will have used if you drive until SoC reaches 0% when the conditions might be different (e.g. warmer).
