### ISSUE TITLE
TeslaFi Import-- Missing Data

### ISSUE THREAD

**Issue by stvhay** [teslamate-org/teslamate#1357]
**Describe the bug**

There is data available through the TeslaFi interface that does not appear to have imported into Teslamate. This outage is coincident with, but expands a broader time period than the Dec 2019 time period relating to the failed import bug.

https://github.com/adriankumpf/teslamate/issues/1351

**Expected behavior**

Data expected to be present for the time 11/2019 thru 1/2020.

**How to reproduce it (as minimally and precisely as possible)**:

Perhaps there is a way to privately share the drive data for multiple months?

**Relevant entries from the logs**

Nothing showing up in the logs, really.

**Screenshots**

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/1269071/108117018-677cab80-706a-11eb-8ef1-4c925879a739.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1269071/108117125-88450100-706a-11eb-9917-3a703a858b0e.png">

**Data**

Here is the missing chunk of data.

```
id,car_id,drive_id,date,elevation,speed,power,odometer,ideal_battery_range_km,est_battery_range_km,rated_battery_range_km,battery_level,usable_battery_level,battery_heater_no_power,battery_heater_on,battery_heater,inside_temp,outside_temp,fan_status,driver_temp_setting,passenger_temp_setting,is_climate_on,is_rear_defroster_on,is_front_defroster_on
8215,1,,2019-11-27 18:03:45,,,0,2047.610097,94.31,65.79,94.31,19,19,,f,,20.9,20.5,0,21.1,21.1,f,f,f
8216,1,,2019-11-28 17:55:28,,,0,2047.610097,92.94,64.84,92.94,19,19,,f,,20.7,19.5,0,21.1,21.1,f,f,f
8217,1,,2019-11-29 22:38:32,,,0,2047.610097,88.85,61.98,88.85,18,18,,f,,19.8,18.5,0,21.1,21.1,f,f,f
8218,1,,2019-12-01 00:57:37,,,0,2047.610097,86.12,60.06,86.12,18,17,,f,,18.2,17.5,0,21.1,21.1,f,f,f
8219,1,,2020-01-01 05:06:30,,,0,2422.715116,321.85,218.53,321.85,65,65,,,,16.6,16.5,0,21.7,21.7,,,
8220,1,,2020-01-01 07:19:45,,,0,2422.715116,317.73,215.73,317.73,64,64,,,,17.2,17.0,0,21.7,21.7,,,
8222,1,,2020-01-01 07:40:34,,,0,2422.715116,320.48,217.60,320.48,65,64,,,,17.1,17.0,0,21.7,21.7,,,
8221,1,,2020-01-01 07:40:34,,,0,2422.715116,320.48,217.60,320.48,65,64,,,,17.1,17.0,0,21.7,21.7,,,
8224,1,159,2020-01-01 18:11:45,7,18,29,2423.007115,319.79,215.44,319.79,65,64,,,,21.1,15.0,3,21.7,21.7,,,
8223,1,,2020-01-01 18:11:45,,18,29,2423.007115,319.79,215.44,319.79,65,64,,,,21.1,15.0,3,21.7,21.7,,,
8225,1,159,2020-01-01 18:12:07,9,31,-18,2423.139115,318.44,212.67,318.44,65,64,,,,21.2,14.0,3,21.7,21.7,,,
8226,1,159,2020-01-01 18:12:30,11,18,17,2423.280115,318.44,212.11,318.44,65,64,,,,21.3,13.5,3,21.7,21.7,,,
8227,1,159,2020-01-01 18:12:51,12,34,35,2423.420115,317.75,210.45,317.75,64,64,,,,21.4,13.0,3,21.7,21.7,,,
8228,1,159,2020-01-01 18:13:13,12,0,2,2423.533115,317.75,210.42,317.75,64,64,,,,21.4,13.0,3,21.7,21.7,,,
```

**Environment**

- TeslaMate version: edge
- Type of installation: Docker 
- OS TeslaMate is installed on: Debian 10
- User OS & Browser: N/A
- Others:

**Comment by adriankumpf** [comment]
Without having the exported csv data at hand it is pretty much impossible to debug it. Can you replace the `latitude`/`longitude`, `vin`, `vehicle_id` and `id` columns and upload the file?

**Comment by stvhay** [comment]
[11_and_12.zip](https://github.com/adriankumpf/teslamate/files/6000547/11_and_12.zip)

**Comment by cyrillopez** [comment]
Hi @adriankumpf 
Do you any update on this issue
I have same issue 
Sometimes, Teslamate stop logging for some hours or days without i understand why
But when i try to upload data missing from TeslaFi, nothing is imported

**Comment by denisjoshua** [comment]
Hi there all, 
I subscribe it cause I have same problem. 

I downloaded the 05 and 06 mounth from Teslafi and imported it. 
But when I go to "Drives" I can't see it. 

```
It's strange cause from the Teslamate log i see all ok: 
[info] Found 2 file(s) at '/opt/app/import'. Starting in import mode!
2021-07-05 11:36:14.278 [info] Migrations already up
[info] Found 2 file(s) at '/opt/app/import'. Starting in import mode!
2021-07-05 11:36:15.463 [info] System Info: Erlang/OTP 24 (jit)
2021-07-05 11:36:15.463 [info] Version: 1.23.4
2021-07-05 11:36:16.043 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (562.971 ms)
2021-07-05 11:36:16.952 [info] POST https://owner-api.teslamotors.com/oauth/token -> 200 (908.843 ms)
2021-07-05 11:36:16.952 [info] Refreshed api tokens
2021-07-05 11:36:16.955 [info] Scheduling token refresh in 5 wk 5 d
2021-07-05 11:36:16.957 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2021-07-05 11:36:16.958 [info] Access TeslaMateWeb.Endpoint at http://localhost
2021-07-05 11:36:18.940 [info] GET /
2021-07-05 11:36:18.945 [info] Sent 302 in 5ms
2021-07-05 11:36:18.952 [info] GET /import
2021-07-05 11:36:18.958 [info] Sent 200 in 6ms
2021-07-05 11:37:28.549 [info] Importing 2 file(s) ...
2021-07-05 11:37:28.551 [info] Starting logger for 'Tesa'
2021-07-05 11:37:28.744 [info] Import complete!
```


Thanks in advance 
Denis

**Comment by JakobLichterfeld** [comment]
stale
