### ISSUE TITLE
Drive stats page showing value in miles when Km selected

### ISSUE THREAD

**Issue by gmarques33** [teslamate-org/teslamate#1503]
**Describe the bug**

Drive stats page showing value in miles when km selected.

If I got to the drive stats page it says that I've driven 13 km, but it is 13 miles. I expected to see 21 km there.

<img width="919" alt="Screenshot 2021-04-02 at 18 00 37" src="https://user-images.githubusercontent.com/1514555/113436985-b34aa080-93dd-11eb-9eb8-6104afafb9cd.png">

The sum of all my trips is 21.9 km, that is 13.61 miles.

<img width="114" alt="Screenshot 2021-04-02 at 18 08 23" src="https://user-images.githubusercontent.com/1514555/113437382-7206c080-93de-11eb-835b-ea68cc496022.png">

**Expected behavior**
Show the correct value in KM in the stats page.

**How to reproduce it (as minimally and precisely as possible)**:
Set the UI to show values in KM and go to the drive stats page.

**Environment**

- TeslaMate version: 1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian 10
- User OS & Browser: Mac OS - Chrome

**Comment by Dulanic** [comment]
This is not a km/mi conversion issue. It's a timeframe issue. dashboard mi = date version, the drives use  timestamp. It can be fixed, but it is not a km/mi issue.
