### ISSUE TITLE
Cannot enter cost per kWh to more than 2 decimal places

### ISSUE THREAD

**Issue by bigjools** [teslamate-org/teslamate#1540]
**Describe the bug**

When entering a cost per kWh in the charge-cost page, I need to use 4 decimal places as my supplier charges in fractions of cents. For example, if I enter 0.1446, it responds with:
`Please enter a valid value. The two nearest valid values are 0.14 and 0.15.`

**Expected behavior**

I should be able to precisely enter my charge cost rates.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to a charge session
2. Click on "cost" to set the cost
3. Set the drop-down to per-kwh and enter the cost to more than 2 decimal places

**Relevant entries from the logs**

```
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11657873/114659024-29cc9400-9d36-11eb-95b9-a9b331bd9973.png)

**Environment**

- TeslaMate version: 1.21.6
- Type of installation: Docker
- OS TeslaMate is installed on: Ubuntu
- User OS & Browser: Ubuntu / Chrome
- Others:

**Comment by bigjools** [comment]
This is possibly related to https://github.com/adriankumpf/teslamate/issues/1064

**Comment by Ed-M72** [comment]
@bigjools - Would you mind upgrading and testing with 1.22.0 please.  In my testing v1.22.0 has the ability to save to 4 decimal places.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/64371467/116627534-37446980-a945-11eb-9e53-d81b55a43255.png">

**Comment by bigjools** [comment]
Sadly not working, it still has the same error.

**Comment by bigjools** [comment]
Ok I see where the problem is - you can set this to 4 places on the geofence page, but not when you click through from the charges cost link in the Grafana dashboard.

**Comment by AkshayRao27** [comment]
When responding to #4454, I remembered that this ticket existed and wanted to ask if this is something that can be reconsidered.

Some charging providers have minute-based prices that have three decimals. These prices are valid throughout Austria, and sometimes, even in other countries. An example of such a provider is WienEnergie, the Energy Provider for the city of Vienna:
![Image](https://github.com/user-attachments/assets/b9df14e7-1813-43cf-8a02-dc97b3fdcdc5)
