### ISSUE TITLE
Blank start/end point on Drives dashboard

### ISSUE THREAD

**Issue by youzer-name** [teslamate-org/teslamate#1652]
**Describe the bug**

For drives beginning or ending at a particular location the Drives dashboard shows nothing for the start / end point that should be that location. The location is a parking lot within a local Park. This has repeated at least three round-trips to this location with each drive to the Park having a blank ending location and each drive away from the Park having a blank starting position.

**Expected behavior**

The Drives listing should show a location where the drive began or ended. 

**How to reproduce it (as minimally and precisely as possible)**:

Start or end a drive at approximately 39.516076 latitude, -77.401980 longitude.

**Relevant entries from the logs**

```
N/A
```

**Screenshots**

N/A

**Data**

Below is a cut & paste of a query of the position data from the positions table that corresponds to the start_position_id for the drive with a blank starting point.

teslamate=# select * from positions where id = '1315870';
   id    |          date           | latitude  | longitude  | speed | power |  odometer   | ideal_battery_ran
ge_km | battery_level | outside_temp | elevation | fan_status | driver_temp_setting | passenger_temp_setting 
| is_climate_on | is_rear_defroster_on | is_front_defroster_on | car_id | drive_id | inside_temp | battery_he
ater | battery_heater_on | battery_heater_no_power | est_battery_range_km | rated_battery_range_km | usable_b
attery_level 
---------+-------------------------+-----------+------------+-------+-------+-------------+------------------
------+---------------+--------------+-----------+------------+---------------------+------------------------
+---------------+----------------------+-----------------------+--------+----------+-------------+-----------
-----+-------------------+-------------------------+----------------------+------------------------+---------
-------------
 1315870 | 2021-05-31 19:01:39.348 | 39.516097 | -77.402076 |     0 |     1 | 3091.871693 |                  
      |            69 |              |       122 |            |                     |                        
|               |                      |                       |      2 |      834 |             |           
     |                   |                         |                      |                        |         

**Environment**

- TeslaMate version: 1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspeberry Pi 4
- User OS & Browser: N/A

**Comment by youzer-name** [comment]
I see you added the 'more information needed' label. What additional information would be helpful? I'm not familiar enough with the system to know what other data might help. If there is a lat/long recorded for the drive start or end point, shouldn't something populate in the 'Drives' dashboard in grafana?
I created a Geofence around this location to see if that would make it show up, but even with a Geofence that contains these lat/lon coordinates, the start/end point fields are blank.

**Comment by DrMichael** [comment]
Well, start/end are taken from geofences and addresses, e.g. with start_address_id and start_geofence_id.  Can you query those for the respective drive?

**Comment by youzer-name** [comment]
So the issue seems to be that for this address the name, road, house_number and city are all blank. Maybe when all of those are null it should use the display_name column which is not null.


Using the 2nd query above:

     name | road | house_number | city 
    ------+------+--------------+------
          |      |              | 


Here is the full select * from addresses for that address:

    teslamate=# select * from addresses where id = '122';
     id  |                   display_name                   | latitude  | longitude  | name | house_number | road 
    | neighbourhood | city |      county      | postcode |  state   | state_district |    country    |                                                                                                                                                                                                                                                                                                                                      
     raw                                                                                                                                                                                                                                                                                                                                        |     
    inserted_at     |     updated_at      |  osm_id   | osm_type 
    -----+--------------------------------------------------+-----------+------------+------+--------------+------
    +---------------+------+------------------+----------+----------+----------------+---------------
    +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    +---------------------+---------------------+-----------+----------
     122 | Frederick County, Maryland, 21705, United States | 39.516040 | -77.401593 |      |              |      
    |               |      | Frederick County | 21705    | Maryland |               | United States | 
    {"lat": "39.51603953095803", "lon": "-77.40159264652196", "name": null, "type": "unclassified", "osm_id": 447605966, "address": {"state": "Maryland ", "county": "Frederick County", "country": "United States", "postcode": "21705", "country_code": "us"}, "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright", "category": "highway", "osm_type": "way", "place_id": 190561316, "extratags": {}, "importance": 0.09999999999999998, "place_rank": 26, "addresstype": "road", "boundingbox": ["39.5157972", "39.5163573", "-77.4016437", "-77.4015257"], "namedetails": {}, "display_name": "Frederick County, Maryland, 21705, United States"} 
    | 2021-05-06 13:53:46 | 2021-05-06 13:53:46 | 447605966 | way

**Comment by DrMichael** [comment]
Well, strange. Could you unzip and insert this SQL?
[drives.zip](https://github.com/adriankumpf/teslamate/files/6591931/drives.zip)

**Comment by adriankumpf** [comment]
> So the issue seems to be that for this address the name, road, house_number and city are all blank. Maybe when all of those are null it should use the display_name column which is not null.

I mean that would be a pragmatic solution. But would the display_name `"Frederick County, Maryland, 21705, United States"` actually be meaningful here? Looks like the actual fix would  be to correct the entry in OpenStreeMap.

**Comment by youzer-name** [comment]
@adriankumpf  Fixing the OSM entry would fix this one location, but modifying the application to more gracefully deal with the error on OSM would help for future locations that have the same issue. The display name would definitely be more meaningful than a blank value in the start or end location column. Plus, showing the display name would allow me to click on it and create a geofence. With it being blank I had to find the lat/lon values and create the Geofence manually which is much less convenient. 

@DrMichael I ran a modified version of the SQL you provided as it was throwing errors on the text inside double brackets and the WHERE clause which was referring to variables like $car_id. I thought I was pretty good with SQL but I'm new to PostgreSQL so the best I could do was remove anything using the brackets and remove the WHERE clause. Since I have a geofence set up for this location the returned data shows the name associated with the geofence and the address/location name.

**Comment by DrMichael** [comment]
> @DrMichael I ran a modified version of the SQL you provided as it was throwing errors on the text inside double brackets and the WHERE clause which was referring to variables like $car_id. I thought I was pretty good with SQL but I'm new to PostgreSQL so the best I could do was remove anything using the brackets and remove the WHERE clause. Since I have a geofence set up for this location the returned data shows the name associated with the geofence and the address/location name.

Ah, you should have inserted it into the Grafana dashboard query part... :-)

**Comment by DrMichael** [comment]
> @adriankumpf Plus, showing the display name would allow me to click on it and create a geofence. With it being blank I had to find the lat/lon values and create the Geofence manually which is much less convenient.

That is definitely a point... So, either display_name or at least "unnamed location" would be helpful.

Given, that finding a location name is happen rather often in the dashboards, how about to put it into a database function? E.g. `find_location_name(<geofence_id>, <address_id>)`?

**Comment by JakobLichterfeld** [comment]
Follow https://docs.teslamate.org/docs/maintenance/manually_fixing_data
