### ISSUE TITLE
Missing charge states at some of underground charge stations without network cover.

### ISSUE THREAD

**Issue by ericdum** [teslamate-org/teslamate#1899]
Those states should be **Charging** which are in the red frames. Notice the SOC diff, that's positive.
Is it possible solve to those the states? 

![20210810155151](https://user-images.githubusercontent.com/690825/128829689-509afd6e-28f5-4e37-9160-88bfc6aa464a.jpg)

**Comment by DrMichael** [comment]
That is pretty strange. Why is Charging in the upper is missing? What says Charges?

In general, when charging, there should be one Charging and one Parking entry, with (almost) identical SoC and SoC Diff:
![image](https://user-images.githubusercontent.com/8087682/128846642-613a4f2d-9e5c-485c-97d6-95b50364fc69.png)

**Comment by ericdum** [comment]
I think the reason is that there is no network connection while it's charging, no wifi, no cellular network.

**Comment by ericdum** [comment]
I think the reason is that there is no network connection while it's charging, no wifi, no cellular network. 

So if the charging state trigger/creates by some vehicle message, there's not.
If the program could recognize positive SoC Diff after Parking, it could fix the missing Charging state.

**Comment by adriankumpf** [comment]
This feature is already implemented. If the car was offline for at least five minutes and gained more than 5 km of range a charging session is added. Not sure why it did not work. Can you provide the logs of that time period?

**Comment by ericdum** [comment]
> This feature is already implemented. If the car was offline for at least five minutes and gained more than 5 km of range a charging session is added. Not sure why it did not work. Can you provide the logs of that time period?

sure, how to get the logs?

**Comment by adriankumpf** [comment]
> sure, how to get the logs?

If you're using Docker, you can do that with: `docker-compose logs teslamate`

**Comment by JoaoAradas** [comment]
This is happening to me too, as you can see here.

![Charging missing](https://user-images.githubusercontent.com/8694244/156342361-a011aec9-f15a-4b91-9002-c0a4938fa2ce.png)

Please find attached the logs

[docker_teslamate_1.csv](https://github.com/adriankumpf/teslamate/files/8168765/docker_teslamate_1.csv)

Hopefully you can help as all my home charges are made in the underground basement that has zero connectivity. Ironically the only charge at home "loged" was created after I did my first charge online in a public stall. And it is not correct as it is not showing all the information.

![Charging missing-2](https://user-images.githubusercontent.com/8694244/156345547-51c082d8-3cb8-44c7-a73a-3e4c4cccc4a7.png)

As you can see I only have public charging, but not any of the charges done in the basement ever since.

Appreciate all the help you can give me and I'll can support you in further troubleshoot.

**Comment by cwanja** [comment]
> Hopefully you can help as all my home charges are made in the underground basement that has zero connectivity.

There’s not much (or really anything) TeslaMate can do if your car cannot be connected to the internet. Tesla does not store the data and then make it available to backfill. TeslaMate only scrapes the data live via the API. If you can extend a WiFi network down there, that would solve the problem.

**Comment by cwanja** [comment]
> > > This feature is already implemented. If the car was offline for at least five minutes and gained more than 5 km of range a charging session is added. Not sure why it did not work. Can you provide the logs of that time period?
> > 
> > 
> > sure, how to get the logs?
> 
> Thanks for the input cwanja, but as it was mentioning above, this functionality should be working as per described above by adriankumpf.

Thanks for pointing that out, my bad on that. I did not know it had an ability to backfill data if a gap in kilometers driven is identified. Hopefully Adrian can help out!

**Comment by JoaoAradas** [comment]
@adriankumpf, can you support? I've provided adicional information as this continues to happen with me. Let me know if you need any more information.

**Comment by llgiordano** [comment]
> > This feature is already implemented. If the car was offline for at least five minutes and gained more than 5 km of range a charging session is added.
> 
> A question regarding this:
> 
> I charged underground without signal. The charging session is visible in the list. But the 'Added' column is empty:
> 
> <img alt="Bildschirmfoto 2021-09-11 um 11 43 53" width="1561" src="https://user-images.githubusercontent.com/3201804/132943771-5902ead3-9751-4b73-b6e1-3e3981c40256.png">
> 
> When checking the details of the charging session, it show that 28.2 kWh were added:
> 
> <img alt="Bildschirmfoto 2021-09-11 um 11 44 43" width="586" src="https://user-images.githubusercontent.com/3201804/132943779-cab192e3-9fac-4527-808b-87f0fc344dd0.png">
> 
> But this amount is not taken into account. It is also missing in the total stats.

Any solution for this problem? I have the same issue on one underground charging session, where the added kWh are shown in the charging session page, but not in the stats

**Comment by llgiordano** [comment]
Hi @adriankumpf , any chance to solve the issue? I have one charging session done without network coverage which is showing in the stats with zero values

![image](https://user-images.githubusercontent.com/91390170/180610938-fe55b3d0-ebd1-4751-bf8a-bf77ebb13890.jpeg)

![image](https://user-images.githubusercontent.com/91390170/180611005-8216d50e-b6fb-4411-a74b-c8663c463f01.jpeg)
![image](https://user-images.githubusercontent.com/91390170/180611009-8b1ede7e-f46b-48ce-9a19-bcfd44ebf6b1.jpeg)

Thank you for the fantastic software 

Luigi

**Comment by cwanja** [comment]
> Hi @adriankumpf , any chance to solve the issue? I have one charging session done without network coverage which is showing in the stats with zero values
> 
> ![image](https://user-images.githubusercontent.com/91390170/180610938-fe55b3d0-ebd1-4751-bf8a-bf77ebb13890.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/91390170/180611005-8216d50e-b6fb-4411-a74b-c8663c463f01.jpeg) ![image](https://user-images.githubusercontent.com/91390170/180611009-8b1ede7e-f46b-48ce-9a19-bcfd44ebf6b1.jpeg)
> 
> Thank you for the fantastic software
> 
> Luigi

Is the Tesla app able to connect while you are charging? If the application cannot connect to the car, there is no way TeslaMate can. TeslaMate has to access the Tesla API and if the API is not accessible (e.g. the Tesla app), then TeslaMate itself cannot render the data.

**Comment by llgiordano** [comment]
Hi @cwanja ,

No, the car was out of coverage during the complete charging and therefore not reachable by the Tesla App.

Yes, Teslamate cleverly monitors if there is a SOC increase over a period of time offline and if so, it generates automatically a charge event. This is perfectly working on my system.

The problem is that the added energy isn't correctly reported in the statistics

Luigi

**Comment by cwanja** [comment]
> Hi @cwanja ,
> 
> No, the car was out of coverage during the complete charging and therefore not reachable by the Tesla App.
> 
> Yes, Teslamate cleverly monitors if there is a SOC increase over a period of time offline and if so, it generates automatically a charge event. This is perfectly working on my system.
> 
> The problem is that the added energy isn't correctly reported in the statistics
> 
> Luigi

It would really behove me to read my previous responses. I already stuck my foot in my mouth once in this thread not knowing about this aspect. Were you able to pull the logs for Adrian, per a previous response? 

> > sure, how to get the logs?
> 
> If you're using Docker, you can do that with: `docker-compose logs teslamate`

**Comment by JoaoAradas** [comment]
Hi,

I’ve attached the logs a few months ago on a post earlier on March 2nd. Can you check those? The problems is the same.

**Comment by llgiordano** [comment]
here is my log file
[log.txt](https://github.com/adriankumpf/teslamate/files/9174177/log.txt)

**Comment by cwanja** [comment]
> here is my log file
> 
> [log.txt](https://github.com/adriankumpf/teslamate/files/9174177/log.txt)
> 
> 

Your logs start at 7/15 and the screenshots are from 5/25. Any older logs? Or logs only from the time stamped issue?

**Comment by llgiordano** [comment]
@cwanja sorry, I don't have old logs. The interesting point is that Teslamate correctly estimated the offline charging event with 9.4 kWh (see attached screenshot) , but then this kWh value is not used in the charging statistics dashboard ![image](https://user-images.githubusercontent.com/91390170/180617040-89b19877-1deb-4b85-8a90-d125afcbdfcd.jpeg)

**Comment by JakobLichterfeld** [comment]
closed. Follow https://docs.teslamate.org/docs/maintenance/manually_fixing_data
