### ISSUE TITLE
Installation/upgrade instructions needs updating due to docker-compose 2.0 package changes

### ISSUE THREAD

**Issue by paulhargreaves** [teslamate-org/teslamate#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On upgrading docker-compose to 2.0, the docker-compose command no longer exists and is replaced by docker compose.
I have not installed compose-switch, which would have re-installed a docker-compose command, because it's not necessary on my system.

https://github.com/docker/compose shows the change.

### Expected Behavior

Instructions which say 'docker-compose' are updated to say 'If you are using a version of docker-compose prior to 2.0 then use docker-compose pull' (etc), 'If you are using docker-compose 2.0+ then use docker compose pull'

### Steps To Reproduce

On arch-linux, just pacman -Syu to get the new version of docker-compose.
Discover docker-compose is no longer in the path, and just use docker compose (i.e. no -) to start the containers.

### Relevant log output

```shell
No logs.
```

### Type of installation

Docker

### Version

v1.24.2

**Comment by JakobLichterfeld** [comment]
closed as completed, latest change #3626
