### ISSUE TITLE
"no data" in the dashboard Drive Stats

### ISSUE THREAD

**Issue by curlybraces** [teslamate-org/teslamate#2038]
![image](https://user-images.githubusercontent.com/91390170/136009373-30db59f0-dc58-4fa0-8010-72e84d921095.jpeg)

Since upgrading to v1.24.2, I have several "no data" in the dashboard Drive Stats.

The problem is on both my cars

The problem happens independently on the selected time frame

Installation is on Docker / RaspberryPi 

All the rest works properly 

Any idea about what I'm doing wrong?

_Originally posted by @llgiordano in https://github.com/adriankumpf/teslamate/discussions/2034_

**Comment by curlybraces** [comment]
Updated my OS and docker and it fixed it

**Comment by llgiordano** [comment]
@adriankumpf update did not help in my case, I think closing the issue was premature

**Comment by curlybraces** [comment]
What version of raspbian are you on?

what version of docker?

**Comment by dadelandia** [comment]
I'm in the same situation.. any news about it?

**Comment by zorgu64** [comment]
Same here. any update? 
Raspbian 10 on Raspberry p4, docker 20.10.10, docker-compose 1.29.2

**Comment by moringus** [comment]
I have the same issue since a while back. Running on Pi4 with Docker 20.10.11.

**Comment by llgiordano** [comment]
@adriankumpf : have also again the issue, since the last update

**Comment by jopotti** [comment]
Same here with Beaglebone Black running Debian and Teslamate 1.25.0.
I noticed mosquitto logging continuosly this:
2021-12-19T17:05:39.837768312Z 0: New connection from 172.19.0.3 on port 1883.,
2021-12-19T17:05:39.840671592Z 0: Client <unknown> has exceeded timeout, disconnecting.,
2021-12-19T17:05:40.253110886Z 0: New connection from 172.19.0.3 on port 1883.,
2021-12-19T17:05:40.254753082Z 0: Client <unknown> has exceeded timeout, disconnecting.,
2021-12-19T17:05:41.066936666Z 0: New connection from 172.19.0.3 on port 1883.,
2021-12-19T17:05:41.069836988Z 0: Client <unknown> has exceeded timeout, disconnecting.
Could this be the reason?

Trip is missing something important like drives.
![image](https://user-images.githubusercontent.com/96387260/146684171-50866066-e92e-4463-ab8f-874ed2d65d6b.png)

**Comment by adriankumpf** [comment]
Can someone try if upgrading to Raspbian Bullseye will solve the problem?

**Comment by llgiordano** [comment]
@adriankumpf just made a fresh new install of Bullseye, restoring the previous data, and I can confirm that the actual version works perfectly and the Drive Stats page shows correctly.
