### ISSUE TITLE
Statistics - Time Driven Not Displaying Correctly for Years

### ISSUE THREAD

**Issue by rhummer** [teslamate-org/teslamate#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When viewing the Statistic tab and change the Period to Years if there is a year with over 100hrs of driving it is truncated.

### Expected Behavior

The total time shouldn't be truncated

### Steps To Reproduce

1. Navigate to the Statistics tab
2. Changed the Period to years
3. Observe any year that should be over 100hrs of driving and notice it shows under 100hrs of driving

### Relevant log output

```shell
Log is attached with additional data.
```

### Screenshots

Here is an example where 2020 says Time Driven is 10hrs
![BadYearSum](https://user-images.githubusercontent.com/902102/138192646-a72bc420-1cb9-46b1-81ae-5527bf9bc982.png)

Looking at the month breakdown for 2020 shows over 200hrs of Time Driven
![YearValues](https://user-images.githubusercontent.com/902102/138192647-b03ca78f-ebc2-473c-adec-d1ad96f4a43d.png)

### Additional data

Export of drives for the year 2020: [drives.csv](https://github.com/adriankumpf/teslamate/files/7385152/drives.csv)
Log file: [teslamate.log](https://github.com/adriankumpf/teslamate/files/7385155/teslamate.log)

### Type of installation

Docker

### Version

1.24.2

**Comment by DrMichael** [comment]
@rhummer you might want to try the new version in https://github.com/teslamate-org/teslamate/issues/3857#issuecomment-2066592205

**Comment by DrMichael** [comment]
PR created https://github.com/teslamate-org/teslamate/pull/3862. Please test and discuss there.

**Comment by DrMichael** [comment]
@rhummer could you test latest version https://github.com/DrMichael/teslamate/blob/master/grafana/dashboards/statistics.json?
