### ISSUE TITLE
Battery heater indicator not working?

### ISSUE THREAD

**Issue by woyteck1** [teslamate-org/teslamate#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My battery is cold, I can see that no extra juice is coming in, that car is pulling electricity, so battery heating is happening, however the battery heater indicator is not on.
model 3 SR+

### Expected Behavior

Battery heater on charging graph should be on.

### Steps To Reproduce

1. have a cold battery (below 10'C)
2. Start charging on lower power (2kW)
3. Observe extended charging time, not charge added, yet no battery heater indicator on.

### Relevant log output

```shell
teslamate_1  | 2021-11-05 11:57:05.309 car_id=1 [info] Start / :online
teslamate_1  | 2021-11-05 11:57:05.327 car_id=1 [info] Connecting ...
teslamate_1  | 2021-11-05 11:57:54.254 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2021-11-05 11:57:55.515 car_id=1 [info] Charging detected: -2 kW
teslamate_1  | 2021-11-05 11:57:55.516 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2021-11-05 11:57:57.004 car_id=1 [info] Charging detected: -1 kW
teslamate_1  | 2021-11-05 11:57:57.004 car_id=1 [info] Fetch already in progress ...
teslamate_1  | 2021-11-05 11:57:59.447 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (299.356 ms)
teslamate_1  | 2021-11-05 11:57:59.461 car_id=1 [info] Charging / SOC: 62% / Home
teslamate_1  | 2021-11-05 11:57:59.461 car_id=1 [info] Disconnecting ...
teslamate_1  | 2021-11-05 12:04:38.366 [info] GET /
teslamate_1  | 2021-11-05 12:04:38.375 [info] Sent 200 in 8ms
teslamate_1  | 2021-11-05 12:06:52.991 [info] GET /
teslamate_1  | 2021-11-05 12:06:52.999 [info] Sent 200 in 7ms
```

### Screenshots

![no-battery-heater-indicator](https://user-images.githubusercontent.com/25311523/140509317-08d39706-3ee8-4879-a225-caa9aababc8a.png)

### Type of installation

Docker

### Version

v1.24.2

**Comment by BabyYeggie** [comment]
My 2019 is showing no battery heater as well. What year is yours? From what I understand, the heat comes from running the motor in stall mode to generate heat, so maybe that's why the battery heater is showing zero.

**Comment by woyteck1** [comment]
Mine is 2021 SR+.Does model S/X have the heater?
Sent from Yahoo Mail on Android 
 
  On Thu, 30 Dec 2021 at 9:48, ***@***.***> wrote:   


My 2019 is showing no battery heater as well. What year is yours? From what I understand, the heat comes from running the motor in stall mode to generate heat, so maybe that's why the battery heater is showing zero.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ktsenvolt** [comment]
Same issue for my 2020 SR +

**Comment by adjego** [comment]
I think this issue comes from that there are two battery heater indications from the API.

I noticed when i have the car set to preheat at a specific time, it nowadays will always also preheat the battery, indicated with the heat icon next to the battery indication in the app. In this scenario, in Teslamate you also can't see the car is online for preparing the battery, and Teslamate will just indicate it's online and tries to get it to sleep again.

But the api only shows at one place the battery heater is active and that is in the "climate" part of the API.

`  "climate_state": {
      "battery_heater": false,`

But there is also one at Charge_state:

` "charge_state": {
      "battery_heater_on": false,`

When my battery is being preconditioned only the climate_state one is active on my car.

Tesla Model 3 SR+ 2019
2021.44.30

**Comment by ktsenvolt** [comment]
![image](https://user-images.githubusercontent.com/80360674/151683065-7b40b5b6-f8b7-493f-a305-04b5417c5f64.png)
Tesla Model 3 SR + 2020  v 2021.44.30.11
Just tested today Battery heater indicated zero.

**Comment by ToniA** [comment]
I wonder if this is somehow specific to Model S and Model X (I'm the original author of this little feature). It works fine on '16 MS75
![image](https://user-images.githubusercontent.com/2128464/152116351-a05bcba6-0ede-4666-9d86-99de46da6206.png)

**Comment by woyteck1** [comment]
Probably M3 doesn't have a separate heater per say.
However, when my M3 is preconditioning (for drive), and it's plugged-in, the Tesla App shows the cable as orange. So they know that there is some process that started. Any chances checking which variable triggers this?

**Comment by orcunbaslak** [comment]
I checked the db, there are 3 parameters;
battery_heater
battery_heater_on
battery_heater_no_power

Only "battery_heater" becomes 1 during charging. "batter_heater_on" is always "false".

Could that be the issue?

**Comment by ToniA** [comment]
Model 3 (and probably also Y) obviously use a different parameter, so fixing this would probably by just a simple OR in the SQL query. Or actually into this case-when statement: `(case when battery_heater_on then 1 else 0 end) as \"Battery heater\"`

https://github.com/adriankumpf/teslamate/commit/d7afc82330f927418e5e9fa2936efa93e2c788ad

**Comment by ToniA** [comment]
I wonder if the SQL should be changes so that is says: `(case when battery_heater or battery_heater_on then 1 else 0 end)`, or maybe `(case when battery_heater then 1 else 0 end)` would be the universal solution?

**Comment by woyteck1** [comment]
Is preconditioning info used for battery heater as well? Can you monitor the preconditioning value during charging?

While driving my M3 - I did now get the preconditioning signal in teslamate, as shown on the screen shot, so that works.
![image](https://user-images.githubusercontent.com/25311523/157058583-867532c5-1abb-4c08-8c14-a5fed395999b.png)
