### ISSUE TITLE
Raspberry Pi: clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)

### ISSUE THREAD

**Issue by KennethEgholm** [teslamate-org/teslamate#2302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The main container of teslamate keeps restarting.

### Relevant log output

```shell
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
```

### Type of installation

Docker

### Version

v1.25.2

**Comment by KennethEgholm** [comment]
ke@new-rasp:~/temp $ uname -a
Linux new-rasp 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
ke@new-rasp:~/temp $ docker -v
Docker version 20.10.7, build f0df350
ke@new-rasp:~/temp $

**Comment by KennethEgholm** [comment]
Reverting back to 1.25.0 makes the bootloop stop..

**Comment by cwanja** [comment]
Similar issues.

**Comment by vanruix** [comment]
> Reverting back to 1.25.0 makes the bootloop stop..

Could you tell me how you do this ?

**Comment by cwanja** [comment]
> > Reverting back to 1.25.0 makes the bootloop stop..
> 
> Could you tell me how you do this ?

Change the yml file from 
```
services:
  teslamate:
    image: teslamate/teslamate:latest
```

To
```
services:
  teslamate:
    image: teslamate/teslamate:1.25.0
```

**Comment by adriankumpf** [comment]
@leewillis77 posted a soluation here:  https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010905276

**Comment by petebocken** [comment]
I upgraded directly to v1.25.2 and I cannot load teslamate at port 4000. Grafana on 3000 loads to a login window.

pi@teslamate:~ $ docker-compose --version
docker-compose version 1.29.2, build unknown
pi@teslamate:~ $ docker --version
Docker version 20.10.12, build e91ed57
pi@teslamate:~ $ cat /sys/firmware/devicetree/base/model
Raspberry Pi 3 Model B Plus Rev 1.3

I believe it actually upgraded to v1.25.2, how do I find the current installed version?

Appears I'm up-to-date:

pi@teslamate:~ $ docker-compose pull
Pulling teslamate ... done
Pulling database  ... done
Pulling grafana   ... done
Pulling mosquitto ... done
pi@teslamate:~ $ docker-compose up -d
pi_grafana_1 is up-to-date
pi_database_1 is up-to-date
pi_mosquitto_1 is up-to-date
pi_teslamate_1 is up-to-date

**Comment by cwanja** [comment]
> I upgraded directly to v1.25.2 and I cannot load teslamate at port 4000. Grafana on 3000 loads to a login window.
> 
> pi@teslamate:~ $ docker-compose --version docker-compose version 1.29.2, build unknown pi@teslamate:~ $ docker --version Docker version 20.10.12, build e91ed57 pi@teslamate:~ $ cat /sys/firmware/devicetree/base/model Raspberry Pi 3 Model B Plus Rev 1.3
> 
> I believe it actually upgraded to v1.25.2, how do I find the current installed version?
> 
> Appears I'm up-to-date:
> 
> pi@teslamate:~ $ docker-compose pull Pulling teslamate ... done Pulling database ... done Pulling grafana ... done Pulling mosquitto ... done pi@teslamate:~ $ docker-compose up -d pi_grafana_1 is up-to-date pi_database_1 is up-to-date pi_mosquitto_1 is up-to-date pi_teslamate_1 is up-to-date

If you did not modify anything in your YML file and the teslamate service says `latest` then that is 1.25.2. You can also pull the first couple logs of the teslamate container (if you can, mine was flooded with errors) and it will post the version.

**Comment by leewillis77** [comment]
> how do I find the current installed version?

@petebocken 
`docker ps -a`

**Comment by cwanja** [comment]
> @leewillis77 posted a soluation here: [#2300 (comment)](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010905276)

@leewillis77 - do you happen to have a small or quick right up for your fix as linked above?

**Comment by petebocken** [comment]
> docker ps -a

That doesn't appear to show any versions.. It does show latest cause that's what my config is set to. I did first try switching that to 1.25.0 and try to downgrade, but that didn't appear to downgrade at all.

pi@teslamate:~ $ docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
03668f36cb36   teslamate/teslamate:latest   "tini -- /bin/sh /en…"   15 minutes ago   Up 47 seconds             0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   pi_teslamate_1
a19c57b8f61d   teslamate/grafana:latest     "/run.sh"                16 minutes ago   Up 13 minutes             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   pi_grafana_1
1de50c51422c   postgres:12                  "docker-entrypoint.s…"   16 minutes ago   Up 13 minutes             5432/tcp                                    pi_database_1
bbe0088d545c   eclipse-mosquitto:1.6        "/docker-entrypoint.…"   16 minutes ago   Up 13 minutes             0.0.0.0:1883->1883/tcp, :::1883->1883/tcp   pi_mosquitto_1
46ee2b91c708   hello-world                  "/hello"                 7 months ago     Exited (0) 7 months ago                                               hungry_yalow

**Comment by petebocken** [comment]
> > I upgraded directly to v1.25.2 and I cannot load teslamate at port 4000. Grafana on 3000 loads to a login window.
> > pi@teslamate:~ $ docker-compose --version docker-compose version 1.29.2, build unknown pi@teslamate:~ $ docker --version Docker version 20.10.12, build e91ed57 pi@teslamate:~ $ cat /sys/firmware/devicetree/base/model Raspberry Pi 3 Model B Plus Rev 1.3
> > I believe it actually upgraded to v1.25.2, how do I find the current installed version?
> > Appears I'm up-to-date:
> > pi@teslamate:~ $ docker-compose pull Pulling teslamate ... done Pulling database ... done Pulling grafana ... done Pulling mosquitto ... done pi@teslamate:~ $ docker-compose up -d pi_grafana_1 is up-to-date pi_database_1 is up-to-date pi_mosquitto_1 is up-to-date pi_teslamate_1 is up-to-date
> 
> If you did not modify anything in your YML file and the teslamate service says `latest` then that is 1.25.2. You can also pull the first couple logs of the teslamate container (if you can, mine was flooded with errors) and it will post the version.

Yup, mine is throwing errors like crazy:

=ERROR REPORT==== 12-Jan-2022::18:13:49.931687 ===
erts_poll_wait() failed: eperm (1)

**Comment by leewillis77** [comment]
@cwanja There's not much to say really - download package, and install. I'm not really sure I want to provide step-by-step instructions as I'm not *wholly* convinced that it's a valid fix. From my understanding of how debian manage their repositories it *probably* is, and I'm comfortable applying that fix to my server, but I'm not (personally) comfortable declaring it as the "proper" fix for everyone.

**Comment by cwanja** [comment]
> 03668f36cb36 **teslamate/teslamate:latest** "tini -- /bin/sh /en…" 15 minutes ago Up 47 seconds 0.0.0.0:4000->4000/tcp, :::4000->4000/tcp pi_teslamate_1

That tells us that you are running the "latest" version. Which would be 1.25.2.

**Comment by cwanja** [comment]
> > > 03668f36cb36 **teslamate/teslamate:latest** "tini -- /bin/sh /en…" 15 minutes ago Up 47 seconds 0.0.0.0:4000->4000/tcp, :::4000->4000/tcp pi_teslamate_1
> > 
> > 
> > That tells us that you are running the "latest" version. Which would be 1.25.2.
> 
> Figured. But i'm still dead in the water. I went straight from whatever the last version was before today to 1.25.2 and it won't let me load teslamate in the browser.

You definitely should be able to downgrade. I have gone from 1.25.0 to .2 back to .0 then to .1 and back to .0. You might need to do a `docker system prune` in between there to remove any lingering images.

**Comment by leewillis77** [comment]
@petebocken see https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010717150 for info on how to downgrade the teslamate image to 1.25.0

**Comment by petebocken** [comment]
> @petebocken see [#2300 (comment)](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010717150) for info on how to downgrade the teslamate image to 1.25.0

Yup, that's what I did the first time, but I had to run `docker system prune` first. I got downgraded back to 1.25.0 and then teslamate opened up fine. Then I tried switching config back to latest and updated and then teslamate won't open again and logs are flooded.

I downgraded to 1.25.0 again and it's working. Soooo apparently this isn't fixed in 1.25.2 or am I dealing with a different issue?

```
(no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015831}}
(no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015844}}
(no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015863}}
=ERROR REPORT==== 12-Jan-2022::18:40:29.015876 ===
erts_poll_wait() failed: eperm (1)


=ERROR REPORT==== 12-Jan-2022::18:40:29.015889 ===
erts_poll_wait() failed: eperm (1)


=ERROR REPORT==== 12-Jan-2022::18:40:29.015902 ===
erts_poll_wait() failed: eperm (1)
```

**Comment by petebocken** [comment]
Ah, teslamate loads fine, but grafana still sits at a login window.

**Comment by cwanja** [comment]
> Ah, teslamate loads fine on 1.25.0, but grafana still sits at a login window.

admin | admin unless you changed it.

**Comment by cwanja** [comment]
> > @petebocken see [#2300 (comment)](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010717150) for info on how to downgrade the teslamate image to 1.25.0
> 
> Yup, that's what I did the first time, but I had to run `docker system prune` first. I got downgraded back to 1.25.0 and then teslamate opened up fine. Then I tried switching config back to latest and updated and then teslamate won't open again and logs are flooded.
> 
> I downgraded to 1.25.0 again and it's working. Soooo apparently this isn't fixed in 1.25.2 or am I dealing with a different issue?
> 
> ```
> (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015831}}
> (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015844}}
> (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015863}}
> =ERROR REPORT==== 12-Jan-2022::18:40:29.015876 ===
> erts_poll_wait() failed: eperm (1)
> 
> 
> =ERROR REPORT==== 12-Jan-2022::18:40:29.015889 ===
> erts_poll_wait() failed: eperm (1)
> 
> 
> =ERROR REPORT==== 12-Jan-2022::18:40:29.015902 ===
> erts_poll_wait() failed: eperm (1)
> ```

You have the same errors I do in 1.25.2 which leads us back to @leewillis77 post [here](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010905276). Yet to sit down and try and fix it, but I assume you would be running Debian v10 and that is why you are facing the errors on 1.25.2.

**Comment by petebocken** [comment]
> > Ah, teslamate loads fine on 1.25.0, but grafana still sits at a login window.
> 
> admin | admin unless you changed it.

Thanks, that worked

**Comment by petebocken** [comment]
> > > @petebocken see [#2300 (comment)](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010717150) for info on how to downgrade the teslamate image to 1.25.0
> > 
> > 
> > Yup, that's what I did the first time, but I had to run `docker system prune` first. I got downgraded back to 1.25.0 and then teslamate opened up fine. Then I tried switching config back to latest and updated and then teslamate won't open again and logs are flooded.
> > I downgraded to 1.25.0 again and it's working. Soooo apparently this isn't fixed in 1.25.2 or am I dealing with a different issue?
> > ```
> > (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015831}}
> > (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015844}}
> > (no logger present) unexpected logger message: {log,error,"~s~n",["erts_poll_wait() failed: eperm (1)\n"],#{error_logger=>#{emulator=>true,tag=>error},time=>1642012829015863}}
> > =ERROR REPORT==== 12-Jan-2022::18:40:29.015876 ===
> > erts_poll_wait() failed: eperm (1)
> > 
> > 
> > =ERROR REPORT==== 12-Jan-2022::18:40:29.015889 ===
> > erts_poll_wait() failed: eperm (1)
> > 
> > 
> > =ERROR REPORT==== 12-Jan-2022::18:40:29.015902 ===
> > erts_poll_wait() failed: eperm (1)
> > ```
> 
> You have the same errors I do in 1.25.2 which leads us back to @leewillis77 post [here](https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010905276). Yet to sit down and try and fix it, but I assume you would be running Debian v10 and that is why you are facing the errors on 1.25.2.

Yup, I'm on Debian Buster 10.  I'll sit tight on 1.25.0. :-)

**Comment by cwanja** [comment]
So I do not want to solicit this as an "official" fix, but I find this fix pretty good. 
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/

Specifically this section:
>The steps for libseccomp2 are well documented, as this has been a problem on multiple platforms (not just RPI4). You could do a 'oneshot' installation of a newer version, which can be found here https://github.com/itzg/docker-minecraft-server/issues/755#issuecomment-781615497
>
>Personally I feel the better method is to install it from the Buster Backports repo, which is very safe to add. It also means any future updates to libseccomp will be applied to the Pi.
>
```
# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports
```
I was able to follow that and got 1.25.2 working. 
```
pi@teslapi:~/Documents/teslamate $ docker-compose logs teslamate
Attaching to teslamate_teslamate_1
teslamate_1  | 2022-01-12 19:02:54.294 [info] Migrations already up
teslamate_1  | 2022-01-12 19:03:00.696 [info] System Info: Erlang/OTP 24 (emu)
teslamate_1  | 2022-01-12 19:03:00.697 [info] Version: 1.25.2
```
This will also ensure that any future `libseccomp` updates are included when I update the Pi. 

Apply at your own will and risk.

**Comment by ploegy** [comment]
I have the same Issue on a Raspberry Pi 3 Model B Rev 1.2,
1.25.0 works fine
1.25.1 Only Grafana 
1.25.2 Not starting

**Comment by cwanja** [comment]
> I have the same Issue on a Raspberry Pi 3 Model B Rev 1.2,
> 1.25.0 works fine
> 1.25.1 Only Grafana
> 1.25.2 Not starting

1.25 was the last "known" working version
1.25.1 introduced an error, referenced in #2300 
1.25.2 fixed that error, but seemed to introduce a new range of errors as outlined in this thread. There is a fix back in @leewillis77 comment on #2300 or outlined in my comment above.

**Comment by adriankumpf** [comment]
The TeslaMate Docker image is based the official `Elixir` image which in turn is based on the official `erlang` image. A month ago, the latter was upgraded from Debian Buster to Bullseye even though the major version did not change: https://github.com/erlang/docker-erlang-otp/commit/f14a791cec08903d5ac34a562861bae675cf2ff8#diff-d12fb60cfa187f3314e96974fb7d9c0bc5f5667838c6d86211ae00cb1d64ccccL1

TeslaMate images built after this change are therefore implicitly also based on Debian Bullseye, although no changes have been made by TeslaMate. Thus, unfortunately, we cannot undo this.

Raspberry Pi users therefore unfortunately have no choice but to either upgrade Raspbian or perform the workarounds described above.

**Comment by brianmay** [comment]
Normally the packages on the host system shouldn't matter when running docker packages. Looks like this is one of the exceptions. I suspect the package is altering the config on the kernel which is shared.

**Comment by petebocken** [comment]
Well, that was a wild ride. I upgraded from Buster to Bullseye. Updated to 1.25.2 and everything works fine. Thanks all for the assistance today.

**Comment by cwanja** [comment]
> Well, that was a wild ride. I upgraded from Buster to Bullseye. Updated to 1.25.2 and everything works fine. Thanks all for the assistance today.

Probably will be something I will undertake in the coming weeks. Have a good guide by chance?

**Comment by petebocken** [comment]
> Have a good guide by chance?

I used this one:
https://blues.io/blog/guide-upgrade-raspberry-pi-buster-bullseye/

I had to reinstall docker-compose after, but otherwise worked well.

**Comment by dkny1123a** [comment]
> Well, that was a wild ride. I upgraded from Buster to Bullseye. Updated to 1.25.2 and everything works fine. Thanks all for the assistance today.

So do I.Thx for everyone in this issue.

**Comment by KennethEgholm** [comment]
I can confirm that the workaround here works - now running latest teslamate 1.25.2 ..
https://github.com/adriankumpf/teslamate/issues/2300#issuecomment-1010905276

**Comment by dranreb38** [comment]
> So I do not want to solicit this as an "official" fix, but I find this fix working and comfortable applying. https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
> 
> Specifically this section:
> 
> > The steps for libseccomp2 are well documented, as this has been a problem on multiple platforms (not just RPI4). You could do a 'oneshot' installation of a newer version, which can be found here [itzg/docker-minecraft-server#755 (comment)](https://github.com/itzg/docker-minecraft-server/issues/755#issuecomment-781615497)
> > Personally I feel the better method is to install it from the Buster Backports repo, which is very safe to add. It also means any future updates to libseccomp will be applied to the Pi.
> 
> ```
> # Get signing keys to verify the new packages, otherwise they will not install
> rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> # Add the Buster backport repository to apt sources.list
> rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
> rpi ~$ sudo apt update
> rpi ~$ sudo apt install libseccomp2 -t buster-backports
> ```
> 
> I was able to follow that and got 1.25.2 working.
> 
> ```
> pi@teslapi:~/Documents/teslamate $ docker-compose logs teslamate
> Attaching to teslamate_teslamate_1
> teslamate_1  | 2022-01-12 19:02:54.294 [info] Migrations already up
> teslamate_1  | 2022-01-12 19:03:00.696 [info] System Info: Erlang/OTP 24 (emu)
> teslamate_1  | 2022-01-12 19:03:00.697 [info] Version: 1.25.2
> ```
> 
> This will also ensure that any future `libseccomp` updates are included when I update the Pi.
> 
> Apply at your own will and risk.

It's **ok with a Raspberry 4** under buster without updating to bullseye!

**Comment by denzel1994** [comment]
> > So I do not want to solicit this as an "official" fix, but I find this fix working and comfortable applying. https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
> > Specifically this section:
> > > The steps for libseccomp2 are well documented, as this has been a problem on multiple platforms (not just RPI4). You could do a 'oneshot' installation of a newer version, which can be found here [itzg/docker-minecraft-server#755 (comment)](https://github.com/itzg/docker-minecraft-server/issues/755#issuecomment-781615497)
> > > Personally I feel the better method is to install it from the Buster Backports repo, which is very safe to add. It also means any future updates to libseccomp will be applied to the Pi.
> > 
> > 
> > ```
> > # Get signing keys to verify the new packages, otherwise they will not install
> > rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
> > # Add the Buster backport repository to apt sources.list
> > rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
> > rpi ~$ sudo apt update
> > rpi ~$ sudo apt install libseccomp2 -t buster-backports
> > ```
> 
> > Apply at your own will and risk.
> 
> It's **ok with a Raspberry 4** under buster without updating to bullseye ! Thank

Worked for me as well. Pi 4 with Buster installed.

**Comment by zwuba** [comment]
I'm also on Buster on a RPi4 but when I'm trying to apply the fix I'm getting the following error:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
Executing: /tmp/apt-key-gpghome.Vn2rkWVxTp/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
gpg: keyserver receive failed: Server indicated a failure
```

Anyone out there that can help on that?

**Comment by thunder2k** [comment]
Hi,
The workaround is not working for me.
I've performed the following commands:
`# Get signing keys to verify the new packages, otherwise they will not install
rpi ~$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
# Add the Buster backport repository to apt sources.list
rpi ~$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
rpi ~$ sudo apt update
rpi ~$ sudo apt install libseccomp2 -t buster-backports`

But I'm still getting the error from this issue title
`teslamate_1       | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1       | Aborted (core dumped)`

Dose anyone have any more suggestions?

**Comment by brianmay** [comment]
Have you tried rebooting?

Not sure I really understand what is going wrong, and how upgrading a shared library on the host can help, but if my theory is correct that the library is changing the kernel config, this step might be important.

**Comment by thunder2k** [comment]
> Have you tried rebooting?
> 
> Not sure I really understand what is going wrong, and how upgrading a shared library on the host can help, but if my theory is correct that the library is changing the kernel config, this step might be important.

I just tried your suggestion but no luck.

Could that be because my docker is version 18.09.7?
If that's the case, any hints on how to update it?

Thanks!

**Comment by thunder2k** [comment]
> You can fix this by adding hosts /etc/timezone and /etc/localtime as volumes to the container. Change the docker-composer.yml this way:
> 
> ```
> services:
>   teslamate:
>     image: teslamate/teslamate:latest
>     restart: always
>     environment:
>       - DATABASE_USER=teslamate
>       - DATABASE_PASS=secret
>       - DATABASE_NAME=teslamate
>       - DATABASE_HOST=database
>       - MQTT_HOST=mosquitto
>     ports:
>       - 4000:4000
>     volumes:
>       - ./import:/opt/app/import
>       - /etc/timezone:/etc/timezone:ro
>       - /etc/localtime:/etc/localtime:ro
>     cap_drop:
>       - all
> ```

This didn't work for me, same error message appeared in the logs

**Comment by Warlord711** [comment]
> This didn't work for me, same error message appeared in the logs

Hmm, weird. My first solution was to run the container with full privileges.
That worked for sure but was way to much privs.

If you run only local or can take the risk, you can add
`privileged: true`

But the volumes: entry should also do the trick.
Have you rebooted or at least restarted docker ?

**Comment by thunder2k** [comment]
> > This didn't work for me, same error message appeared in the logs
> 
> Hmm, weird. My first solution was to run the container with full privileges. That worked for sure but was way to much privs.
> 
> If you run only local or can take the risk, you can add `privileged: true`
> 
> But the volumes: entry should also do the trick. Have you rebooted or at least restarted docker ?

Thanks for the advice, I'd rather not run it full privileges :)

What I did was to add the 2 extra lines on the volumes and then I run the following commands:
`docker-compose pull
docker-compose up -d`

Is this right?

**Comment by jakest** [comment]
> You can fix this by adding hosts /etc/timezone and /etc/localtime as volumes to the container. Change the docker-composer.yml this way:
> 
> ```
>       - /etc/timezone:/etc/timezone:ro
>       - /etc/localtime:/etc/localtime:ro
> ```

I can confirm that unfortunately, adding these two entries doesn't work, even after restarting Docker, and/or the machine it's running on. Looks like I'm stuck on 1.25.0 for now.

**Comment by umb87** [comment]
I resolved add previleges : true on docker compose for teslamate image

**Comment by Warlord711** [comment]
Latest build gave me same error again but couln't be fiexed with volumes mout nor add privileges

**Comment by namoona1** [comment]
After upgrading to bullseye on raspberry pi whenever I start up teslamate in docker it seems to be unable to connect to the internet. I tried running my container in privileged mode with no luck either. Without the docker container running I am able to ping external servers. Any suggestions what I am doing wrong here?

**Comment by cwanja** [comment]
> After upgrading to bullseye on raspberry pi whenever I start up teslamate in docker it seems to be unable to connect to the internet. I tried running my container in privileged mode with no luck either. Without the docker container running I am able to ping external servers. Any suggestions what I am doing wrong here?

Are you able to connect to any sites on the Pi? I had to reconfigure Ethernet configuration post upgrade.

**Comment by namoona1** [comment]
This is on my Wireless LAN and yes I am able to connect to sites if I keep my Docker container shut down.

**Comment by thunder2k** [comment]
I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again

**Comment by natrlhy** [comment]
> I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again 

I did this...

https://github.com/adriankumpf/teslamate/issues/2320#issuecomment-1013636322

**Comment by namoona1** [comment]
I followed this guide https://blues.io/blog/guide-upgrade-raspberry-pi-buster-bullseye/ and after the upgrade reinstalled docker compose

**Comment by thunder2k** [comment]
Thanks both for your suggestion.. I'll find a moment to try it ASAP

**Comment by cwanja** [comment]
> I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again



> Thanks both for your suggestion.. I'll find a moment to try it ASAP

For you, backporting the required file will probably be the safer solution.

**Comment by thunder2k** [comment]
> > I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again
> 
> > Thanks both for your suggestion.. I'll find a moment to try it ASAP
> 
> For you, backporting the required file will probably be the safer solution. [#2302 (comment)](https://github.com/adriankumpf/teslamate/issues/2302#issuecomment-1011362938)

Thanks for your comment, unfortunately I've already tried it but it doesn't work for 1.26. Is it working for you on the latest version?

**Comment by cwanja** [comment]
> > > I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again
> > 
> > 
> > > Thanks both for your suggestion.. I'll find a moment to try it ASAP
> > 
> > 
> > For you, backporting the required file will probably be the safer solution. [#2302 (comment)](https://github.com/adriankumpf/teslamate/issues/2302#issuecomment-1011362938)
> 
> Thanks for your comment, unfortunately I've already tried it but it doesn't work for 1.26. Is it working for you on the latest version?

I backported for 1.25.X to work. Then upgraded on top of it and it was still working. Currently running the latest version.

**Comment by thunder2k** [comment]
I think I've tried it directly on the latest but without upgrading to Bullseye and it didn't work. I guess it's a mandatory step regardless the backport install

**Comment by thunder2k** [comment]
> > > > I know we're going a bit off topic here, but which guide did you follow to upgrade to Bullseye? I have a lot of stuff running on my Pi and I'm scared it'll take me ages to be up&running again
> > > 
> > > 
> > > > Thanks both for your suggestion.. I'll find a moment to try it ASAP
> > > 
> > > 
> > > For you, backporting the required file will probably be the safer solution. [#2302 (comment)](https://github.com/adriankumpf/teslamate/issues/2302#issuecomment-1011362938)
> > 
> > 
> > Thanks for your comment, unfortunately I've already tried it but it doesn't work for 1.26. Is it working for you on the latest version?
> 
> I backported for 1.25.X to work. Then upgraded Bullseye on top of it and it was still working. Currently running the latest version of TeslaMate no issues.

So this morning I upgraded my docker version with the following guide:
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/

and now 1.25.2 works fine!

Now I just need to find the time to upgrade to Bullseye and the to the latest teslamate image

**Comment by cwanja** [comment]
> @cwanja I'm wondering if, after upgrading to Bullseye,did you remove the Apt Preferences file /etc/apt/preferences.d/bullseye-docker.pref ?

I did not. 

To get TeslaMate upgraded on Buster, all you needed to do was update `libseccomp2`. Nevertheless, glad to see you were able to get to 1.26.1.

**Comment by natrlhy** [comment]
Everything has been running fine on bullseye and version 1.26.1. Today though the TeslaMate and grafana containers keep restarting over and over

**Comment by cwanja** [comment]
What are in the logs?

**Comment by natrlhy** [comment]
It never stays up long enough to view the logs

**Comment by natrlhy** [comment]
Sorry, looks like it's the DB and grafana that won't stay up:

**Comment by tsl367** [comment]
It's because of libseccomp version, we can upgrade libseccomp.
You can download it from https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1+b1_armhf.deb
then install it
```
curl https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.4-1+b1_armhf.deb -o libseccomp2.deb
sudo dpkg -i libseccomp2.deb
```
