### ISSUE TITLE
Grafana dashboard sending to `about:blank`

### ISSUE THREAD

**Issue by cwanja** [teslamate-org/teslamate#2389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At least on the `Drives` dashboard, the hyperlinks under the `Duration` and Winter icons are sending links to `about:blank`. I do not know what these should have linked to originally before the upgrade.

### Expected Behavior

Any previous behavior or remove the links. It looks like these are intended to be tooltips - to display more information (duration in hours and minutes and what cold weather icon means). But I wonder if there is a way to present these without the `about:blank` HTML link.

### Steps To Reproduce

1. Open the Drives dashboard
2. Hover over and click on the link in a row under the `Duration` or `Winter` column

### Relevant log output

```shell
N/A
```

### Screenshots

![Screen Shot 2022-01-27 at 10 45 55 AM](https://user-images.githubusercontent.com/54645561/151404483-59b27b75-3466-4884-80c4-bbcff66af80f.png)
![Screen Shot 2022-01-27 at 10 46 01 AM](https://user-images.githubusercontent.com/54645561/151404486-ef4069f8-290f-4e1f-abe1-9dced86db270.png)

### Type of installation

Docker

### Version

1.26

**Comment by horst789github** [comment]
I'm on v1.25.2 and it is not linked and accordingly does not lead anywhere.

**Comment by cwanja** [comment]
> I'm on v1.25.2 and it is not linked and accordingly does not lead anywhere.

interesting. Must be a 1.26 / Grafana 8 issue.

**Comment by adriankumpf** [comment]
These fields are configured as a link because we need a way to display a message on hover. I think with previous Grafana versions the hover text was displayed but the field was not clickable.
