### ISSUE TITLE
Wrong summary in charges dashboard

### ISSUE THREAD

**Issue by PalleRaa** [teslamate-org/teslamate#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I use the statistics dashboard on weekly setting. If I then click the number of charges for a specific week it go to a time boxed "charges" dashboard. The list of charges seems to be correct, but in the bottom there is a summary for energy added, energy used and cost. These seem to use a different time period as the individual charges does not add up to this number.

It seems to add in an additional charge from the week after. In my case it then adds up. The cost of the additional charge was 0, which is also why the cost is correct in the screenshot.

### Expected Behavior

A clear corrolation between the listed charge sessions and the total number presented at the bottom of the screen. 

### Steps To Reproduce

1. Open the statistics dashboard
2. Set it weekly based
3. Click the underlined number under "# of charges" for a week
4. You are now presented with a time boxed "Charges" dashboard
5. Adding the energy used for the different charge session does not add up to the numbers in the bottom of the screen.

### Relevant log output

```shell
N/A
```

### Screenshots

<img width="919" alt="image" src="https://user-images.githubusercontent.com/95851907/154924261-2a640dbc-59c1-400b-96d3-da9f9bfacbc6.png">

### Type of installation

Docker

### Version

1.26.1

**Comment by JakobLichterfeld** [comment]
Is your issue still present with latest version (the dashboards got updated a lot). If so, please open a new ticket.
