### ISSUE TITLE
Typo in Docs for fixing drives/ charges prevents from fixing them 

### ISSUE THREAD

**Issue by woyteck1** [teslamate-org/teslamate#2524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a drive, or charge needs fixing, there is Documentation page that explains how to do it and gives the command.
However I found that command not working and after some debugging I found 1 extra character (an Exclamation mark) that, when removed, fixes the issue.

### Expected Behavior

Expected behaviour is when there is no exclamation mark and it's working fine:

```
$ docker-compose exec teslamate bin/teslamate rpc     "TeslaMate.Repo.get(TeslaMate.Log.Drive, 408) |> TeslaMate.Log.close_drive()"

09:29:07.288 [info]  GET https://nominatim.openstreetmap.org/reverse -> 200 (67.402 ms)

09:29:07.784 [info]  GET https://nominatim.openstreetmap.org/reverse -> 200 (491.593 ms)
```

### Steps To Reproduce

1. Have a bloken (unclosed) drive or charge
2. Go to https://docs.teslamate.org/docs/maintenance/manually_fixing_data/
3. Try the command for either:
4. Get bash error: 
```
$ docker-compose exec teslamate bin/teslamate rpc \
>     "TeslaMate.Repo.get!(TeslaMate.Log.ChargingProcess, 408) |> TeslaMate.Log.complete_charging_process()"
bash: !: event not found
>
ERROR: RPC expects an expression as argument
```

### Relevant log output

```shell
Not really needed I guess as this is already fixable.
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by Dulanic** [comment]
Not able to duplicate in 1.27.4

**Comment by djpalmis** [comment]
Hi guys we mast reopen this issue!

**Comment by JakobLichterfeld** [comment]
> Hi guys we shall reopen this issue!

No typo, no reproducable most likly a copy paste error on user side

**Comment by Hjlfmir** [comment]
Hello, I confirm. Need to remove the "!" to make it work (2 different installations, same issue, same fix).
