### ISSUE TITLE
Discrepancy in projected range with suggested fix.

### ISSUE THREAD

**Issue by woyteck1** [teslamate-org/teslamate#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a discrepancy between:
Projected Range (using usable_battery_level)
Projected Range (using battery_level)

The thing is that the one using "usable_battery_level", when different, it's ALWAYS higher than the one using "battery_level".
I think it goes down to the arithmetic of this. I have tried to fix it myself but I keep getting the "cannot divide by zero" too much.

![image](https://user-images.githubusercontent.com/25311523/164003796-6a8e399e-0955-42d8-9fb9-9c0a439f25f8.png)

### Expected Behavior

Expected behaviour ????:
Say 100% battery gives us 500 km range.
An current battery is 83%, and we know that max prodicted range should be 500 km
And when usable battery range is lower, say 81%, that means 2% of battery are not available so
the range should be: X = 500 - (500 * (83-81)/100) 
X = 500 - 10 = 490 km

Current behaviour:
```
	convert_km(sum([[preferred_range]]_battery_range_km) / sum(coalesce(usable_battery_level,battery_level)) * 100, '$length_unit') AS "Projected Range (using usable_battery_level) [$length_unit]",
	convert_km(sum([[preferred_range]]_battery_range_km) / sum(battery_level) * 100, '$length_unit') AS "Projected Range (using battery_level) [$length_unit]"
```
The Grafana formula for these value is incorrect:
It basically is (current range / battery_level) * 100 for Projected range using "battery_level"
and (current range / usable_battery_level) * 100 for Projected range using "usable_battery_level".

So, if current range is 415 km and battery lvl is at 83% the max range will be:  (415/83)*100 = 500 km
however if the usable battery level is 81, with the same range used, the result will be higher: (415/81)*100 = 512 km 

And this doesn't make much sense.

What would need to be used IMO as a formula for expected range at :
projected_range_at_battery_level = (current_range / battery_level) * 100
projected_range_at_usable_battery_level = projected_range_at_battery_level - ( projected_range_at_battery_level * ((battery_level - usable_battery_level) / 100 )) 

So it should be calculated like: 
X = 500 - ( 500 * ((83 - 81)/100))
X = 500 - (500 * (2/100))
X = 500 - 10
X = 490

Also if battery_level and usable_battery_level were the same, it would just cancel out .
This works correctly as far as I can confirm (avg for battery_level and usable_battery_level instead of sum where we need substract one from another):
```
SELECT
	$__timeGroup(date,[[interval]]) AS time,
	convert_km((sum([[preferred_range]]_battery_range_km) / sum(battery_level) * 100 ) - (sum([[preferred_range]]_battery_range_km) / sum(battery_level) * 100 * (avg(battery_level)-avg(coalesce(usable_battery_level,battery_level)))/100 ), '$length_unit') AS "Projected Range (using usable_battery_level) [$length_unit]",
	convert_km(max([[preferred_range]]_battery_range_km) / max(battery_level) * 100, '$length_unit') AS "Projected Range (using battery_level)[$length_unit]"

```

### Relevant log output

```shell
.
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by woyteck1** [comment]
Also, - the sum wasn't working that well for me, avg was braking things, so max seems better.

**Comment by woyteck1** [comment]
Now my graph looks like this: 

![image](https://user-images.githubusercontent.com/25311523/164059595-f4573a97-4407-4267-a000-05a9aa6a6362.png)

**Comment by leewillis77** [comment]
See #1121

**Comment by woyteck1** [comment]
Yup. My change seems to fix it. 
I may need to make a branch for it (but i'm using the docker version and it's a bit more tricky to keep fidling with it...
