### ISSUE TITLE
Missing Supercharger Session

### ISSUE THREAD

**Issue by whoistheg** [teslamate-org/teslamate#2618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We went on a road trip last week and did a lot of DC fast charging.

I have noticed Telsamate has missed a lot of the Telsa Supercharging sessions.

This is my Teslamate
![Screenshot of SafariScreenshot of Safari (27-4-2022, 14-52-23)](https://user-images.githubusercontent.com/47014588/165443344-59d42021-8354-4291-bfc4-7920f0776b87.jpg)

This is my Telsa account

![Screenshot of SafariScreenshot of Safari (27-4-2022, 14-53-22)](https://user-images.githubusercontent.com/47014588/165444264-4b8cb17d-7b26-4ed3-bbf4-179fe634ce2d.jpg)

### Relevant log output

```shell
no logs
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by cwanja** [comment]
What were the TeslaMate logs during those Supercharging sessions? Were the drives before and after included?

**Comment by kfmes** [comment]
Facing same problem.  Drive history recode is fine. And charge log seems logged. But charge session not inserted.
![Screenshot_20221026_171127](https://user-images.githubusercontent.com/4520884/197971315-01cb56a5-1dad-42a1-a550-fa3530936070.jpg)
