### ISSUE TITLE
"Locations" is missing Paramater "Time Range"

### ISSUE THREAD

**Issue by Azrael-Masters** [teslamate-org/teslamate#2622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was analyzing my Drives and for that I noticed differences between the Dashboards "Locations" and "Drive Stats".
In "Drive Stats" I filtered for the current year and the count for the visited location "City" is "6".
When I viewed "Locations" the count for this City is "2".
As I found out, that the "Locations" Dashboard is hard coded to "Last 30 days", while "Drive Stats" is using the filter "Time Range".

Would be great if you could fix it :)
Thanks a lot and best regards

### Expected Behavior

When I view Dashboard "Locations" the count for this City should be "6" or better, lets enable the Filteroption "Time Range".

### Steps To Reproduce

see "What happend"

### Relevant log output

```shell
-
```

### Type of installation

Docker

### Version

v1.26.1

**Comment by adriankumpf** [comment]
None of the queries on the Locations dashboard take the (hidden) time range filter into account, if I am not mistaken. Could you run the affected SQL queries and post the output?
