### ISSUE TITLE
Drive Stats 'mi driven' total is wrong

### ISSUE THREAD

**Issue by youzer-name** [teslamate-org/teslamate#2701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I pulled stats for the past two days to review a road trip. I have two Teslas and this involves car #2 in case that matters. On the 'drives' screen it shows 8 drives with a total mileage of about 464 miles:

![image](https://user-images.githubusercontent.com/57046429/173416026-a7ce3230-c1e3-4080-b273-afa17e57a0ef.png)

On the drive stats screen it shows 8 drives, but the 'mi driven' is only 271:

![image](https://user-images.githubusercontent.com/57046429/173416102-9544a11a-bf0c-48bf-98b5-5a7170cd4d27.png)

With 'Last 2 days' as the time setting, when I inspect the 'mi driven' query in Grafana I see this:

![image](https://user-images.githubusercontent.com/57046429/173416311-45929aa1-b71c-462f-bb80-c15940f92d02.png)

As you can see, 'Last 2 days' captures 6/12/2022 to 6/13/2022 in the drives dashboard, but 6/11/2022 to 6/12/2022 in the drive stats dashboard. (I am in EDT, UTC -0400, so it shows 6/10/2022 2000 hours and 6/11/2022 2000 hours)

To see if I could get it to count the part of the drive that happened after midnight local (on 6/13/2022) I put in an absolute date range of 2022-06-11 00:00:00 to 2022-06-15 23:59:59 EDT, but that still results in the wrong mileage:

![image](https://user-images.githubusercontent.com/57046429/173416908-0273b888-2c9d-4c8c-8f85-56e72429c127.png)

![image](https://user-images.githubusercontent.com/57046429/173416962-46fec6d7-8cb9-4838-8958-e136aa4c9207.png)

![image](https://user-images.githubusercontent.com/57046429/173417014-c54bef4c-8af9-45e9-b178-44b237c20ff1.png)

The Query for the absolute date range shows as:

'''
WITH since as (
	SELECT date FROM positions
	WHERE car_id = '2'
	ORDER BY date ASC
	LIMIT 1
),
actual AS (
	SELECT
		date_trunc('day', date)::date AS date,
		max(odometer) - min(odometer) AS distance
	FROM positions
	WHERE car_id = '2'
	GROUP BY 1
),
base_line AS (
	SELECT date_trunc('day', dd)::date AS date
  FROM generate_series((select date from since) , now(), '1 day'::interval) dd
)
SELECT 
  base_line.date AS "time", 
  convert_km(COALESCE(distance, 0)::numeric, 'mi') as "distance_mi"
FROM base_line
LEFT JOIN actual ON actual.date = base_line.date
WHERE base_line.date BETWEEN '2022-06-11T04:00:00Z' AND '2022-06-16T03:59:59Z'
ORDER BY 1;
'''

I don't understand the query well enough to figure out where the discrepancy is happening.

### Expected Behavior

I expected the Drive Stats -> mi driven panel to show 464 miles.

### Steps To Reproduce

I'm not sure. Is it because one of the drives spans two different dates (started before midnight, ended after) in local time, or is something else wrong with the drive stats -> mi driven query?

### Relevant log output

```shell
No relevant logs.
```

### Additional data

[drives.csv](https://github.com/adriankumpf/teslamate/files/8893505/drives.csv)
[positions.csv](https://github.com/adriankumpf/teslamate/files/8893506/positions.csv)

### Type of installation

Docker

### Version

v1.26.1

**Comment by DrMichael** [comment]
Try the following in "mi driven":
```
SELECT
	start_date AS time,
	convert_km(sum(end_km - start_km)::numeric, '$length_unit') AS distance
FROM drives
WHERE car_id = '1'AND
  $__timeFilter(start_date)
GROUP BY 1;
```

**Comment by DrMichael** [comment]
@adriankumpf @cwanja Do you know, why we have such a complicated query in the Drive Stats? If not, I would push that here...

**Comment by cwanja** [comment]
> @adriankumpf @cwanja Do you know, why we have such a complicated query in the Drive Stats? If not, I would push that here...

Unknown to me. If there is a similar method, I would definitely go that route. I feel like I have seen other threads where the count in drive stats, versus trips, versus drives are all different variables.

**Comment by youzer-name** [comment]
I think I see issues with the extrapolated monthly mileage and annual mileage on this dashboard also.

It appears that it is using only the days where the car was driven, not the total number of days in the time range, to determine the extrapolated mileage. For example if I select "Last 7 days" I get 607 miles total. The extrapolated monthly mileage is 3,036 and annual is 36.940.

The average daily mileage is: 607/7 ~= 87

In a 30-day month that would be 2,610 miles per month. In a 365-day year that would be: 87 * 365 = 31,755

I think this is because there was one day in the past 7 that the car was not driven. If I divide the mileage by 6 instead of 7 to get the daily mean, then I get numbers closer to what the dashboard shows.

Using only 6 days, 607/6 = 101.166. In a 30 day month that would be 101.166 * 365 = 3,035 miles per month (within 1 mi of the dashboard result). In a 52-week year that would be 101.166 * 365 = 36,925 (within 15 miles of the dashboard result).

This only gets worse if you have fewer days driven. I just tried from 2022-06-12 to 2022-06-18 (which includes future dates), resulting in 470 miles driven in that 7 day span. There are only drives for 2 of the 7 days in that span. (Actually there is a 3rd day, but the mileage is <1 mile so I think it gets filtered out). The extrapolated annual mileage is 85,834, which is what you would get using 470 / 2 * 365, but using the average of all 7 days it should be 470 / 7 = 67.14 | 67.14 * 365 = 24,506. 

Shouldn't the extrapolated mileage include zero-mile days? If I drive 100 miles once a week, then my extrapolated annual mileage is 5,200 miles, not 36,500.

**Comment by youzer-name** [comment]
@DrMichael  I don't think it is using the median. For the last scenario I described (470 miles, 7-day span, 3 days driven) my median distance per day is 230 miles. (per drive is only 3.02... it definitely isn't using that). 

Monthly:
230 / 7 = 32.86 | 32.86 * 30 = 986 miles per month (dashboard shows 4,703)
230 / 3 = 76.66 | 76.66 * 30 = 2,300 miles per month (dashboard shows 4,703)

Annual:
230 / 7 = 32.86 | 32.86 * 365 = 11,994 per year (dashboard shows 57,223)
230 / 3 = 76.66 | 76.66 * 365 = 27,981 per year (dashboard shows 57,233)

The only way to get the result the dashboard is showing is 

Total mileage / (number of days with a drive) * (30 or 365)

It should be:

Total mileage / (number if days in the range) * (30 or 365)

**Comment by DrMichael** [comment]
Perhaps Drive Stats is more for the long term observation, Trip might be better for short term...
