### ISSUE TITLE
Drives and Charges tables completely broken in Grafana

### ISSUE THREAD

**Issue by markusdd** [teslamate-org/teslamate#2707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All the Dashboard pages work fine except drives and charges, funny enough, their detail pages work fine, so I expect the database is ok.
The columns seem to be wrongly assigned:

![grafik](https://user-images.githubusercontent.com/25175069/174502918-343f6f7a-5540-44ed-a251-14e23563f0cd.png)
![grafik](https://user-images.githubusercontent.com/25175069/174503037-61e27a82-e7af-4e17-8313-f5900aa18be4.png)

### Expected Behavior

The tables do display the data correctly

### Steps To Reproduce

hard to say, as I do not know what the root cause is and how it started...

### Relevant log output

```shell
logs are not really interesting as everything seem to be working fine...
```

### Screenshots

see above

### Additional data

I am happy to provide dumps if necessary, without location data if possible.

But I guess this is more a dashbaord issue.

I btw have checked that after latest update dashbaords have again be imported using the provided dashboard.sh script.

### Type of installation

Manual

### Version

v1.26.1

**Comment by markusdd** [comment]
Addition: The Vampire drain table is also broken:
![grafik](https://user-images.githubusercontent.com/25175069/174503650-2b893a40-fb89-432e-b432-d7c21d834058.png)

**Comment by markusdd** [comment]
Ok, I want to provide an update here as it might help some people encountering a similar problem:

It is gone for me now, everything is back to normal, so what did I do:
I updated my LXC container which runs my TeslaMate instance form Debian buster to bullseye and with it also the erlang and postresql repos.
So it seems there has been a creeping incompatability with the older versions on buster.

Should we somehow document this? Because it is not entirely obvious as everything else works fine.

**Comment by flojon** [comment]
Also had this for a while. Just upgrade to the latest docker container and tried to reapply the grafana dashboard but the issue is still there.
