### ISSUE TITLE
Tokens are not accepted

### ISSUE THREAD

**Issue by marineboy0122** [teslamate-org/teslamate#2720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Tokens are not accepted.
The correct token value is entered, but the message 'Error: Tokens are invalid' continues to occur.

### Relevant log output

```shell
teslamate_1  | 2022-06-26 09:29:19.408 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8002.858 ms)
teslamate_1  | 2022-06-26 09:31:47.317 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8003.354 ms)
```

### Screenshots

![mate](https://user-images.githubusercontent.com/83511237/175808155-0223c923-7adb-48c7-96af-b1d14bc6d918.jpg)

https://user-images.githubusercontent.com/83511237/175808156-aa9db80f-8428-4a21-a4d9-0f2c8fc22390.mp4

### Type of installation

Docker

### Version

latest

**Comment by DrMichael** [comment]
Name resolution in the teslamate service doesn't work... Try to stop und restart the service.

**Comment by HoonE122** [comment]
> Name resolution in the teslamate service doesn't work... Try to stop und restart the service.

It has absolutely nothing to do with it.  I've already tried it several times.😭

**Comment by DrMichael** [comment]
Well, the message says, that it cannot resolve **auth.tesla.com**.

**Comment by HoonE122** [comment]
If I keep trying to log in with the token, it somehow succeeds.
However, no data is accumulated in Grafana.
![55A38C4B-B824-4DF2-AEDD-42727A4B463C](https://user-images.githubusercontent.com/83511237/176439421-f82fb678-2185-4d13-9a5e-4f5145bb07b4.jpeg)
![26F5A3CB-2938-4901-935B-C1C0257A32E6](https://user-images.githubusercontent.com/83511237/176439549-3cc9ca1e-1212-4f3c-bed3-3dbecd1888cc.jpeg)

**Comment by HoonE122** [comment]
> What does it say, when you hover over the red triangles?

![6FD277D8-0B3E-40B4-BE54-68912332E248](https://user-images.githubusercontent.com/83511237/176444792-2e717bc3-9f59-4a99-aed7-fbedba80dc97.jpeg)
😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by eliluong** [comment]
You can try TeslaLogger. It is very similar software.

**Comment by Lizzard44** [comment]
> You can try TeslaLogger. It is very similar software.

no, not real. 

it cannot resolve auth.tesla.com. 
this is not a problem of teslamate but of the NAS. :P

**Comment by DumSkidderik** [comment]
100% a DNS problem. I've seen Docker have problems with the internal DNS resolver if you don't run in bridge mode etc.
Try something simple like nslookup and see which DNS server doesn't reply, probably the internal one.

**Comment by HoonE122** [comment]
No, it was a matter of time zone setting.
Currently working normally

**Comment by DumSkidderik** [comment]
> No, it was a matter of time zone setting. Currently working normally

Timestamp needs to be valid on order to query DNS

**Comment by JakobLichterfeld** [comment]
closed as stale
