### ISSUE TITLE
Trip/Select last three drives is not working

### ISSUE THREAD

**Issue by GaPhi** [teslamate-org/teslamate#2756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Nothing happen when clicking on 'Select last three drives' button in Trip dashboard.

### Expected Behavior

Select last three drives as it did some (long) time ago.

### Steps To Reproduce

Go to Trip
Click on 'Select last three drives'

### Relevant log output

```shell
Nothing actually relevant
```

### Type of installation

Docker

### Version

v1.27.0

**Comment by DrMichael** [comment]
I wonder, whether that has ever worked. It does not currently and the implementation cannot work.
I'd say, we shall remove that.

**Comment by DrMichael** [comment]
It does not work reliably in the same tab. It works in a new tab. https://github.com/teslamate-org/teslamate/commit/ca9816ba4905c653b5f4daad533bf2caf2fe1d9c
