### ISSUE TITLE
Updates Dashboard Seems to Max Out at 1 Month

### ISSUE THREAD

**Issue by PlaysWithTrons** [teslamate-org/teslamate#2839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My updates dashboard does not seem to display "Since Previous Update" Lengths greater than one month. 

04/04/2022, 06:02:33 PM to 06/01/2022, 06:02:53 PM - Listed as 1 Month since the previous update.
the 

### Expected Behavior

04/04/2022, 06:02:33 PM to 06/01/2022, 06:02:53 PM - Listed as 8 weeks since the previous update.

### Relevant log output

```shell
teslamate_1  | 2022-08-06 19:11:00.757 [info] GET /
```

### Screenshots

<img width="483" alt="Screen Shot 2022-08-06 at 3 03 02 PM" src="https://user-images.githubusercontent.com/87242624/183262754-b4374f98-a138-4c6c-aa35-a194a0f20e15.png">

### Type of installation

Docker

### Version

V1.27.1

**Comment by cwanja** [comment]
I am going to make an assumption here, but since it is only 58 days it is not considered "two full months" since the last update. It is closer to two months than one month, I agree. But it is working as intended. Maybe we can add a tool tip similar to the drives where Grafana can give the specific number of days like it gives the specific hours and minutes from the drive. @DrMichael can validate my logic, being the Grafana and SQL expert.

**Comment by DrMichael** [comment]
> @DrMichael can validate my logic, being the Grafana and SQL expert.

Ah, no I am not... :-)

One could do
![image](https://user-images.githubusercontent.com/8087682/183299344-972aee89-f7fc-4fd8-a3ae-8754c5aaf1cb.png)
But tha looks ugly...

**Comment by CrowMash** [comment]
With the idea of cwanja, you could do something like that.

1. Modify the last select to add the 5th line (**since_last_update_days**)
```
select	
  u.start_date as time,
  extract(EPOCH FROM u.end_date - u.start_date) AS update_duration,
  extract(EPOCH FROM u.start_date - lag(u.start_date) OVER (ORDER BY u.start_date)) AS since_last_update,
  trunc(extract(EPOCH FROM u.start_date - lag(u.start_date) OVER (ORDER BY u.start_date)) / 24 / 60 / 60) AS since_last_update_days,
  split_part(u.version, ' ', 1) as version,
  count(distinct cp.id) as chg_ct,
  convert_km(avg(r.battery_rng), '$length_unit')::numeric(6,2) AS avg_[[preferred_range]]_range_[[length_unit]]
```

2. Add overide to **since_last_update_days** column  to hide it in table
3. Add overide to **since_last_update** column to add a data link title: `${__data.fields.since_last_update_days} days`

As I started using Grafana a couple months ago, I'm pretty sure there are better ways to do it, but it's a start.

**Comment by JakobLichterfeld** [comment]
@swiffer : In the updates dashboard, the time since last update is maxed out at 1 month, issue still present in 1.30.1. May I ask you to look into this enhancement if you find the time to do so? Thanks.

**Comment by JakobLichterfeld** [comment]
> Should we switch to SQL based rounding / output? that would give us more control.

Does this result in performance decrease?

**Comment by swiffer** [comment]
no - opened a pr ;)

**Comment by JakobLichterfeld** [comment]
awesome, ty!
