### ISSUE TITLE
Feature request : ability to fix variable cost of KWh

### ISSUE THREAD

**Issue by cdlp34** [teslamate-org/teslamate#2875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At this moment we could have a cost by Khw or by minute.

### Expected Behavior

Would be great to have complex rules for various cost of KWh.

Example :
- Hours : From 6 am to 10 pm : this is Full Hour with specific cost of KWh, and from 10 pm to 6 am, this is off-peak hour with another specific cost of KWh
- Days : All the Year we have a "blue days" cost, almost cheap. Some days in the year of high consumption on the electrical network, there is more expansive costs ("white days") to encourage people to reduce their consumption. Some days in the year of VERY HIGH consumption on the electrical network, there is VERY   expansive costs ("Red days") to encourage people to really reduce their consumption. 

Of course, there is different costs in full hours costs & off-peak hours costs, for each color of days.....

See full exemple table here : https://images.prismic.io/ekwateur-edito/ff58a9e7-053a-4597-b24f-476aa63ac143_grille-tarifaire-edf-tempo.PNG?auto=compress,format

It would therefore be necessary to have historical costs by period: at a given date or between 2 given dates.

### Relevant log output

```shell
No log needed
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by renatohtpc** [comment]
This would be a great addition.

**Comment by andrewjw** [comment]
The project https://github.com/MattJeanes/TeslaMateAgile has a functionality very close to this, you might find it already does what you would like.

**Comment by cdlp34** [comment]
Hi @andrewjw ,

Thanks for the link to TelslaMateAgile project.

Unfortunately, this is not yet sufficient at this time, but I have opened a [request #31](https://github.com/MattJeanes/TeslaMateAgile/issues/31) for a new provider, using RTE API. 

Thx
