### ISSUE TITLE
Cant get into web interface

### ISSUE THREAD

**Issue by zikronix** [teslamate-org/teslamate#2878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading the web interface doesnt work. Restarting the container didnt solve the problem

### Expected Behavior

after upgrade the web page should work

### Steps To Reproduce

upgrade from an older version

### Relevant log output

```shell
dont have logs
```

### Type of installation

Docker

### Version

1.27.1

**Comment by cwanja** [comment]
Going to need to provide more information. There should be logs from Docker, what is the web error, what happen during the upgrade, etc.
