### ISSUE TITLE
Importing from TeslaFi doesn't appear to be working

### ISSUE THREAD

**Issue by SlothCroissant** [teslamate-org/teslamate#2896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Importing from TeslaFi doesn't appear to be working. The app detects the files, offers to import them, *appears* to import them, but no data populates. 

There hasn't been a relevant issue for this in several years, so opening a fresh issue to account for recent app updates.

### Expected Behavior

When importing, the data should show in Teslamate.

### Steps To Reproduce

1. Export data from TeslaFi
2. Copy via SSH to Docker mapped volume at `/opt/app/import`. Optionally, `chown` the file(s) as 10000:10001
3. Restart teslamate per the docs
4. Click Import to confirm the files to be imported

### Relevant log output

```shell
2022-09-13 01:25:07.859 [info] Migrations already up
[info] Found 2 file(s) at '/opt/app/import'. Starting in import mode!
2022-09-13 01:25:14.574 [info] System Info: Erlang/OTP 24 (jit)
2022-09-13 01:25:14.574 [info] Version: 1.27.1
2022-09-13 01:25:15.039 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (363.677 ms)
2022-09-13 01:25:15.039 [info] Refreshed api tokens
2022-09-13 01:25:15.055 [info] Scheduling token refresh in 6 h
2022-09-13 01:25:15.071 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
2022-09-13 01:25:15.074 [info] Access TeslaMateWeb.Endpoint at http://localhost
2022-09-13 01:25:18.371 [info] GET /settings
2022-09-13 01:25:18.417 [info] Sent 200 in 45ms
2022-09-13 01:25:29.786 [info] GET /
2022-09-13 01:25:29.801 [info] Sent 302 in 12ms
2022-09-13 01:25:29.814 [info] GET /import
2022-09-13 01:25:29.840 [info] Sent 200 in 26ms
2022-09-13 01:25:39.817 [info] Importing 2 file(s) ...
2022-09-13 01:25:39.834 [info] Starting logger for 'Tess'
2022-09-13 01:25:40.053 [info] Import complete!
```

### Screenshots

<img width="1025" alt="Screen Shot 2022-09-12 at 20 25 58" src="https://user-images.githubusercontent.com/5846854/189787531-1debc622-eef5-4443-a4af-168128ffafec.png">

(notice the icon difference - not sure if relevant)

### Type of installation

Docker

### Version

v1.27.1

**Comment by SorenLan** [comment]
Do you have a foreign character in you vehicle name? I got exactly that problem when I had an 'å' in my vehicle name. I did a search and replace in the csv file and then there was no problem with the import to TeslaMate.

**Comment by SlothCroissant** [comment]
> Do you have a foreign character in you vehicle name?

Unfortunately no, my car is simply named "Tess", so shouldn't be an issue. 

Wonder if there are any debug logging features in the Docker image that I can enable to see what's happening beyond "Import complete". If it's getting hung up somewhere, etc. will poke around, if anyone has tips please do let me know.

**Comment by aounakram** [comment]
Having the same issue here
![7DB22E90-1564-45C5-9655-51EF2959DC05](https://user-images.githubusercontent.com/57077179/194499579-046fb3b5-2310-4b65-b62f-d4a74dd68c41.jpeg)

**Comment by choke55** [comment]
Sorry to borrow this - but I have a problem/question about the opt/app/import/
Should that be in standard docker or in @docker/opt/app/import/ ?
I thougt it should be in the @docker/import - but nathing hapens for me.
Thanks
Lars

**Comment by aounakram** [comment]
Files need to be placed in the folder defined by the docker-compose file: “./import:/opt/app/import”. ./ refers to the location where the docker-import file was created and ran from. You should see an import folder in the same directory. After placing the files, you do need to restart the teslamate docker. Then you should see the import screen after navigating to teslamate in a browser. (localhost/ipaddress:4000)

**Comment by choke55** [comment]
Thanks
Sorry for stupid question - but is this the right place and I am not sur how to create the sub folders
root@TheNasForChoke:/volume2/@docker# dir
total 4
drwx--x--x  1 root  root   212 Nov  8 11:27 .
drwxr-xr-x  1 root  root   378 Nov  7 16:43 ..
drwx-----x  1 root  root    20 Aug  4  2021 btrfs
drwx--x--x  1 root  root   132 Aug  4  2021 buildkit
drwx--x--x  1 root  root    12 Aug  4  2021 containerd
drwx-----x  1 root  root   896 Nov  8 11:13 containers
-rwxrwxrwx+ 1 Choke users 1282 Nov  7 15:19 docker-compose.yml
drwx------  1 root  root    10 Aug  4  2021 image
drwx------  1 root  root    34 Nov  9 17:06 import
drwx------  1 root  root     0 Nov  8 11:27 in
drwxr-x---  1 root  root    10 Aug  4  2021 network
drwx------  1 root  root    20 Aug  4  2021 plugins
drwx------  1 root  root     0 Nov  7 16:45 runtimes
drwx------  1 root  root     0 Aug  4  2021 swarm
drwx------  1 root  root     0 Nov  8 11:13 tmp
drwx------  1 root  root     0 Aug  4  2021 trust
drwx-----x  1 root  root   364 Nov  8 11:13 volumes
root@TheNasForChoke:/volume2/@docker# cd import
root@TheNasForChoke:/volume2/@docker/import# dir
total 3656
drwx------  1 root  root       34 Nov  9 17:06 .
drwx--x--x  1 root  root      212 Nov  8 11:27 ..
-rwxrwxrwx+ 1 Choke users 3741853 Nov  9 16:51 TeslaFi112022.csv
root@TheNasForChoke:/volume2/@docker/import#

**Comment by choke55** [comment]
Hi
I got a problem with your answer
I not sure where I can find opt/app/import folder?
Could you be so kind to give me some hint where I can place it?
I tried this - but I do not get the import browser when I have restarted Teslamate and logged in again

***@***.***:/opt/app/import#
***@***.***:/opt/app/import# dir
total 3664
drwx------ 2 root  root     4096 Nov 10 14:24 .
drwx------ 3 root  root     4096 Nov 10 14:14 ..
-rwxrwxrwx 1 Choke users 3741853 Nov  9 16:51 TeslaFi112022.csv
***@***.***:/opt/app/import#

Thanks



Lars-Åke ”Choke” Nygren
Mobil 0709-712 651
Web:  www.choke.se<http://www.choke.se>
e-post ***@***.******@***.***>



[cid:6248BA53-69ED-4403-8311-E52316F34591]

9 nov. 2022 kl. 18:08 skrev aounakram ***@***.******@***.***>>:



Files need to be placed in the folder defined by the docker-compose file: “./import:/opt/app/import”. ./ refers to the location where the docker-import file was created and ran from. You should see an import folder in the same directory. After placing the files, you do need to restart the teslamate docker. Then you should see the import screen after navigating to teslamate in a browser. (localhost/ipaddress:4000)

**Comment by MagoKimbra** [comment]
![image](https://user-images.githubusercontent.com/7785361/234573975-36b349fd-11cf-4848-ae83-ffd669ce014d.png)
Same problem, I try to click on import, but it doesn't give me the V check and I can't find the data then in teslamate.
I reboot every time after importing.
Just FK car name: K.I.T.T.
I don't know if the dots in the name can cause problems.

**Comment by erichstark** [comment]
I have the same issue. Today I have tried to do the import, but I didn't saw any checkmark after that.
![image](https://github.com/teslamate-org/teslamate/assets/1123805/f8af9497-8889-4315-9e37-8d5f5a3e2538)

I checked also logs with `sudo docker compose logs teslamate` and got this

`teslamate-teslamate-1  | [info] Found 6 file(s) at '/opt/app/import'. Starting in import mode!
teslamate-teslamate-1  | 2023-12-23 21:44:36.891 [info] System Info: Erlang/OTP 26 (jit)
teslamate-teslamate-1  | 2023-12-23 21:44:36.891 [info] Version: 1.28.2
teslamate-teslamate-1  | 2023-12-23 21:44:38.086 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (672.471 ms)
teslamate-teslamate-1  | 2023-12-23 21:44:38.088 [info] Refreshed api tokens
teslamate-teslamate-1  | 2023-12-23 21:44:38.118 [info] Scheduling token refresh in 6 h
teslamate-teslamate-1  | 2023-12-23 21:44:38.132 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-teslamate-1  | 2023-12-23 21:44:38.143 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate-teslamate-1  | 2023-12-23 21:45:36.366 [info] GET /import
teslamate-teslamate-1  | 2023-12-23 21:45:36.429 [info] Sent 200 in 62ms
teslamate-teslamate-1  | 2023-12-23 21:45:39.493 [info] GET /
teslamate-teslamate-1  | 2023-12-23 21:45:39.510 [info] Sent 302 in 17ms
teslamate-teslamate-1  | 2023-12-23 21:45:39.526 [info] GET /import
teslamate-teslamate-1  | 2023-12-23 21:45:39.563 [info] Sent 200 in 36ms
teslamate-teslamate-1  | 2023-12-23 21:45:45.451 [info] Importing 6 file(s) ...
teslamate-teslamate-1  | 2023-12-23 21:50:25.850 [error] GenStateMachine TeslaMate.Import terminating
teslamate-teslamate-1  | ** (RuntimeError) vehicle data is incomplete
teslamate-teslamate-1  |     (teslamate 1.28.2) lib/teslamate/import.ex:274: TeslaMate.Import.create_car/1
teslamate-teslamate-1  |     (teslamate 1.28.2) lib/teslamate/import.ex:128: TeslaMate.Import.handle_event/4
teslamate-teslamate-1  |     (stdlib 5.1.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate-teslamate-1  |     (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3`

**Comment by debruyneOneTouch** [comment]
I have same problem as erichstark.

 Teslamate Import screen shows TeslaFi files but they do not import

sudo docker compose logs teslamate

teslamate_1  | [info] Found 4 file(s) at '/opt/app/import'. Starting in import mode!
teslamate_1  | 2023-12-26 22:57:34.699 [info] Migrations already up
teslamate_1  | [info] Found 4 file(s) at '/opt/app/import'. Starting in import mode!
teslamate_1  | 2023-12-26 22:57:37.601 [info] System Info: Erlang/OTP 26 (emu)
teslamate_1  | 2023-12-26 22:57:37.601 [info] Version: 1.28.2
teslamate_1  | 2023-12-26 22:57:38.100 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (406.194 ms)
teslamate_1  | 2023-12-26 22:57:38.101 [info] Refreshed api tokens
teslamate_1  | 2023-12-26 22:57:38.111 [info] Scheduling token refresh in 6 h
teslamate_1  | 2023-12-26 22:57:38.116 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate_1  | 2023-12-26 22:57:38.118 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2023-12-26 22:57:38.248 [info] GET /import
teslamate_1  | 2023-12-26 22:57:38.283 [info] Sent 200 in 34ms
teslamate_1  | 2023-12-26 22:57:41.382 [info] Importing 4 file(s) ...
teslamate_1  | 2023-12-26 22:57:53.130 [error] GenStateMachine TeslaMate.Import terminating
teslamate_1  | ** (RuntimeError) vehicle data is incomplete
teslamate_1  |     (teslamate 1.28.2) lib/teslamate/import.ex:274: TeslaMate.Import.create_car/1
teslamate_1  |     (teslamate 1.28.2) lib/teslamate/import.ex:128: TeslaMate.Import.handle_event/4
teslamate_1  |     (stdlib 5.1.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

**Comment by debruyneOneTouch** [comment]
I got import to work by using this csv editor to add vehicle id WHILE maintaining the date formatting.
[https://www.convertcsv.com/csv-viewer-editor.htm?utm_content=cmp-true ]
#3158

**Comment by erichstark** [comment]
@debruyneOneTouch I have tried it also, added id 1 to every column, also car name as suggested in some issue but helped only for 072023, not for 08-12 in 2023 :/

**Comment by tw1015** [comment]
Not working for me either, but it's worse.
I don't think it even finds the import folder. And I never get an import page on starting teslamate.
My .yml file contains
  volumes:
     - ./import:/opt/app/import
  
In the services..teslamate section.
The files are named TeslaFiA.csv and TeslaFiB.csv and are in the /import directory which sits at the same level as the .yml .env and .htpasswd files.
Everything else seems to work fine.

Any ideas why?
Do I need to create the opt/app/import directory? /opt exists but I don't see anything under it.

**Comment by spinecho31** [comment]
Having the same issue here.
The csv files are inside the import folder but upon restart of the container, the import page never shows up.

Any idea why?

**Comment by jaswals** [comment]
I am having the same issue as OP, logs show import complete but nothing shows up in DB or in Grafana
Only first file shows checkmark out of 3
vehicle ID is present
Data format is correct
Display Name of Car is there

`teslamate-teslamate-1  | [info] Found 3 file(s) at '/opt/app/import'. Starting in import mode!
teslamate-teslamate-1  | 2025-01-26 19:59:28.569 [info] System Info: Erlang/OTP 26 (jit)
teslamate-teslamate-1  | 2025-01-26 19:59:28.569 [info] Version: 1.32.0
teslamate-teslamate-1  | 2025-01-26 19:59:29.026 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (382.104 ms)
teslamate-teslamate-1  | 2025-01-26 19:59:29.026 [info] Refreshed api tokens
teslamate-teslamate-1  | 2025-01-26 19:59:29.070 [info] Scheduling token refresh in 6 h
teslamate-teslamate-1  | 2025-01-26 19:59:29.085 [info] Running TeslaMateWeb.Endpoint with cowboy 2.12.0 at :::4000 (http)
teslamate-teslamate-1  | 2025-01-26 19:59:29.086 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate-teslamate-1  | 2025-01-26 19:59:29.974 [info] GET /
teslamate-teslamate-1  | 2025-01-26 19:59:29.980 [info] Sent 302 in 6ms
teslamate-teslamate-1  | 2025-01-26 19:59:29.989 [info] GET /import
teslamate-teslamate-1  | 2025-01-26 19:59:29.998 [info] Sent 200 in 9ms
teslamate-teslamate-1  | 2025-01-26 19:59:39.732 [info] Importing 3 file(s) ...
teslamate-teslamate-1  | 2025-01-26 19:59:39.739 [info] Starting logger for 'Tesla'
teslamate-teslamate-1  | 2025-01-26 19:59:40.258 [info] Import complete!`
