### ISSUE TITLE
cannot put car in sleep mode, car always has status online

### ISSUE THREAD

**Issue by mikephung** [teslamate-org/teslamate#2911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

i followed the FAQ for MCU1 setting already

The settings needed to enable the sleep mode with MCU1 are:

'Display' -> 'Energy saving' -> ON
'Display' -> 'Always connected' -> unchecked
'Safety & security' -> 'Cabin overheat protection' -> OFF

### What happened?

i use teslamate to put my car into the sleep mode, it told me that the car went to sleep, but it is not the true, the query still show that the car is online:

`select start_date AS "time", state from states where car_id = '1' order by start_date desc limit 1;
`
It also make the car online for very long time, until i came some how to sleep. 

log 
`2022-09-23 09:53:59.459 [info] Starting logger for 'Starlight'
2022-09-23 09:53:59.466 [info] Sent 200 in 9312ms
2022-09-23 09:53:59.468 [info] MQTT connection has been established
2022-09-23 09:54:08.954 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492931737331192/vehicle_data -> 408 (9245.868 ms)
2022-09-23 09:54:08.954 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 09:54:08.954 car_id=1 [error] Error / :unknown
2022-09-23 09:54:39.605 car_id=1 [info] Start / :online
2022-09-23 09:54:39.655 car_id=1 [info] Connecting ...
2022-09-23 09:54:56.654 [info] GET /
2022-09-23 09:54:56.657 [info] Sent 200 in 2ms
2022-09-23 09:55:05.810 car_id=1 [info] Suspending logging [Triggered manually]
2022-09-23 10:01:06.114 [info] GET /settings
2022-09-23 10:01:06.125 [info] Sent 200 in 10ms
2022-09-23 10:01:09.204 [info] GET /
2022-09-23 10:01:09.207 [info] Sent 302 in 2ms
2022-09-23 10:01:09.397 [info] GET /sign_in
2022-09-23 10:01:09.401 [info] Sent 200 in 3ms
2022-09-23 10:01:29.544 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (121.535 ms)
2022-09-23 10:01:29.551 [info] Scheduling token refresh in 6 h
2022-09-23 10:01:30.009 [info] GET /
2022-09-23 10:01:33.764 [info] Starting logger for 'Starlight'
2022-09-23 10:01:33.769 [info] Sent 200 in 3759ms
2022-09-23 10:01:34.396 car_id=1 [info] Start / :online
2022-09-23 10:01:34.406 car_id=1 [info] Connecting ...
2022-09-23 10:02:00.428 car_id=1 [info] Suspending logging [Triggered manually]`

### Expected Behavior

the car should go to sleep immediately and the query in grafana dashboard should return asleep

### Steps To Reproduce

go to teslamate dashboard
press try to sleep, there is an error message: "an error occurred ", then the button "try to sleep" is available again.^
in log i see this
`2022-09-23 10:09:13.622 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/Attaching to docker-teslamate_teslamate_1
teslamate_1  | 2022-09-23 09:53:46.960 [info] == Running 20220123131732 TeslaMate.Repo.Migrations.EncryptApiTokens.change/0 forward
teslamate_1  | 2022-09-23 09:53:46.967 [info] alter table tokens
teslamate_1  | 2022-09-23 09:53:47.016 [info] alter table tokens
teslamate_1  | 2022-09-23 09:53:47.024 [info] rename column encrypted_access to access on table tokens
teslamate_1  | 2022-09-23 09:53:47.024 [info] rename column encrypted_refresh to refresh on table tokens
teslamate_1  | 2022-09-23 09:53:47.033 [info] == Migrated 20220123131732 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.066 [info] == Running 20220422132017 TeslaMate.Repo.Migrations.AddMarketingNameToCar.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.066 [info] alter table cars
teslamate_1  | 2022-09-23 09:53:47.068 [info] == Migrated 20220422132017 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.070 [info] == Running 20220617170400 TeslaMate.Repo.Migrations.AddTirePressures.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.071 [info] alter table positions
teslamate_1  | 2022-09-23 09:53:47.076 [info] execute "CREATE OR REPLACE FUNCTION public.convert_tire_pressure(n numeric(6,2), character varying)\nRETURNS numeric(6,2)\nLANGUAGE 'sql'\nCOST 100\nVOLATILE\nAS $BODY$\nSELECT\nCASE $2 WHEN 'bar' THEN $1\n    WHEN 'psi' THEN $1 * 14.503773773\nEND;\n$BODY$;\n"
teslamate_1  | 2022-09-23 09:53:47.086 [info] == Migrated 20220617170400 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.089 [info] == Running 20220718085412 TeslaMate.Repo.Migrations.AddUnitOfPressureToGlobalSettings.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.089 [info] execute "CREATE TYPE unit_of_pressure AS ENUM ('bar', 'psi')"
teslamate_1  | 2022-09-23 09:53:47.095 [info] alter table settings
teslamate_1  | 2022-09-23 09:53:47.098 [info] == Migrated 20220718085412 in 0.0s
teslamate_1  | 2022-09-23 09:53:49.264 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-09-23 09:53:49.264 [info] Version: 1.27.1
teslamate_1  | 2022-09-23 09:53:49.515 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (220.740 ms)
teslamate_1  | 2022-09-23 09:53:49.515 [info] Refreshed api tokens
teslamate_1  | 2022-09-23 09:53:49.520 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-23 09:53:49.522 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-09-23 09:53:49.524 [info] Access TeslaMateWeb.Endpoint at http://xxxxxx.xxxxx.com
teslamate_1  | 2022-09-23 09:53:50.153 [info] GET /
teslamate_1  | 2022-09-23 09:53:52.379 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 16 Aug 2022 01:15:47 GMT.
teslamate_1  | 2022-09-23 09:53:53.254 [info] Tzdata has updated the release from 2021e to 2022c
teslamate_1  | 2022-09-23 09:53:59.458 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxx/vehicle_data -> 408 (9253.615 ms)
teslamate_1  | 2022-09-23 09:53:59.459 [warning] TeslaApi.Error / %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "{\"error\": \"timeout\"}",
teslamate_1  |       "error_description" => "",
teslamate_1  |       "response" => nil
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-txid", "d3e3d59e741a2da53dd903009ec974d5"},
teslamate_1  |       {"content-type", "application/json; charset=utf-8"},
teslamate_1  |       {"x-request-id", "60205676-79c8-4092-bad2-9cf1dca6d565"},
teslamate_1  |       {"content-length", "75"},
teslamate_1  |       {"x-envoy-upstream-service-time", "9171"},
teslamate_1  |       {"x-envoy-upstream-cluster", "owner-api"},
teslamate_1  |       {"date", "Fri, 23 Sep 2022 07:53:59 GMT"},
teslamate_1  |       {"server", "envoy"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"strict-transport-security", "max-age=31536000; includeSubDomains"},
teslamate_1  |       {"cache-control", "no-cache, no-store, private, s-max-age=0"}
teslamate_1  |     ],
teslamate_1  |     method: :get,
teslamate_1  |     opts: [
teslamate_1  |       access_token: "removed"
teslamate_1  |     ],
teslamate_1  |     query: [],
teslamate_1  |     status: 408,
teslamate_1  |     url: "https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxx/vehicle_data"
teslamate_1  |   },
teslamate_1  |   message: "%{\"error\" => \"{\\\"error\\\": \\\"timeout\\\"}\", \"error_description\" => \"\", \"response\" => nil}",
teslamate_1  |   reason: :unknown
teslamate_1  | }
teslamate_1  | 2022-09-23 09:53:59.459 [info] Starting logger for 'Starlight'
teslamate_1  | 2022-09-23 09:53:59.466 [info] Sent 200 in 9312ms
teslamate_1  | 2022-09-23 09:53:59.468 [info] MQTT connection has been established
teslamate_1  | 2022-09-23 09:54:08.954 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxx/vehicle_data -> 408 (9245.868 ms)
teslamate_1  | 2022-09-23 09:54:08.954 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 09:54:08.954 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 09:54:39.605 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-23 09:54:39.655 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-23 09:54:56.654 [info] GET /
teslamate_1  | 2022-09-23 09:54:56.657 [info] Sent 200 in 2ms
teslamate_1  | 2022-09-23 09:55:05.810 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:01:06.114 [info] GET /settings
teslamate_1  | 2022-09-23 10:01:06.125 [info] Sent 200 in 10ms
teslamate_1  | 2022-09-23 10:01:09.204 [info] GET /
teslamate_1  | 2022-09-23 10:01:09.207 [info] Sent 302 in 2ms
teslamate_1  | 2022-09-23 10:01:09.397 [info] GET /sign_in
teslamate_1  | 2022-09-23 10:01:09.401 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:01:29.544 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (121.535 ms)
teslamate_1  | 2022-09-23 10:01:29.551 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-23 10:01:30.009 [info] GET /
teslamate_1  | 2022-09-23 10:01:33.764 [info] Starting logger for 'Starlight'
teslamate_1  | 2022-09-23 10:01:33.769 [info] Sent 200 in 3759ms
teslamate_1  | 2022-09-23 10:01:34.396 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-23 10:01:34.406 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-23 10:02:00.428 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:06:35.167 [info] GET /
teslamate_1  | 2022-09-23 10:06:35.170 [info] Sent 200 in 2ms
teslamate_1  | 2022-09-23 10:08:09.872 [info] GET /
teslamate_1  | 2022-09-23 10:08:09.875 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:12.295 [info] GET /
teslamate_1  | 2022-09-23 10:08:12.298 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:30.128 [info] GET /settings
teslamate_1  | 2022-09-23 10:08:30.135 [info] Sent 200 in 7ms
teslamate_1  | 2022-09-23 10:08:36.941 [info] GET /settings
teslamate_1  | 2022-09-23 10:08:36.946 [info] Sent 200 in 5ms
teslamate_1  | 2022-09-23 10:08:42.059 [info] GET /
teslamate_1  | 2022-09-23 10:08:42.063 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:46.857 car_id=1 [info] Resuming logging
teslamate_1  | 2022-09-23 10:09:13.622 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxx/vehicle_data -> 408 (9881.730 ms)
teslamate_1  | 2022-09-23 10:09:13.622 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:09:33.998 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxx/vehicle_data -> 408 (9246.034 ms)
teslamate_1  | 2022-09-23 10:09:33.998 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:09:33.998 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:03.267 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxx/vehicle_data -> 408 (9267.594 ms)
teslamate_1  | 2022-09-23 10:10:03.268 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:10:03.268 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:33.243 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9973.944 ms)
teslamate_1  | 2022-09-23 10:10:33.243 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:10:33.243 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:55.241 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9245.608 ms)
teslamate_1  | 2022-09-23 10:10:55.241 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:11:04.510 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9267.406 ms)
teslamate_1  | 2022-09-23 10:11:04.510 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:11:07.800 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:11:07.804 car_id=1 [info] Unhandled fetch result: {:error, :unknown}/vehicle_data -> 408 (9881.730 ms)
2022-09-23 10:09:13.622 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:09:33.998 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9246.034 ms)
2022-09-23 10:09:33.998 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:09:33.998 car_id=1 [error] Error / :unknown
2022-09-23 10:10:03.267 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9267.594 ms)
2022-09-23 10:10:03.268 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:10:03.268 car_id=1 [error] Error / :unknown`

press again "try to sleep"

now there is a success message in the log 
`2022-09-23 10:09:13.622 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9881.730 ms)
2022-09-23 10:09:13.622 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:09:33.998 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9246.034 ms)
2022-09-23 10:09:33.998 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:09:33.998 car_id=1 [error] Error / :unknown
2022-09-23 10:10:03.267 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9267.594 ms)
2022-09-23 10:10:03.268 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:10:03.268 car_id=1 [error] Error / :unknown
2022-09-23 10:10:33.243 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9973.944 ms)
2022-09-23 10:10:33.243 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:10:33.243 car_id=1 [error] Error / :unknown
2022-09-23 10:10:55.241 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9245.608 ms)
2022-09-23 10:10:55.241 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:11:04.510 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9267.406 ms)
2022-09-23 10:11:04.510 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2022-09-23 10:11:07.800 car_id=1 [info] Suspending logging [Triggered manually]
2022-09-23 10:11:07.804 car_id=1 [info] Unhandled fetch result: {:error, :unknown}`

the button turned to "cancel sleep attempt", but the SQL query still return "online"

### Relevant log output

```shell
Attaching to docker-teslamate_teslamate_1
teslamate_1  | 2022-09-23 09:53:46.960 [info] == Running 20220123131732 TeslaMate.Repo.Migrations.EncryptApiTokens.change/0 forward
teslamate_1  | 2022-09-23 09:53:46.967 [info] alter table tokens
teslamate_1  | 2022-09-23 09:53:47.016 [info] alter table tokens
teslamate_1  | 2022-09-23 09:53:47.024 [info] rename column encrypted_access to access on table tokens
teslamate_1  | 2022-09-23 09:53:47.024 [info] rename column encrypted_refresh to refresh on table tokens
teslamate_1  | 2022-09-23 09:53:47.033 [info] == Migrated 20220123131732 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.066 [info] == Running 20220422132017 TeslaMate.Repo.Migrations.AddMarketingNameToCar.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.066 [info] alter table cars
teslamate_1  | 2022-09-23 09:53:47.068 [info] == Migrated 20220422132017 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.070 [info] == Running 20220617170400 TeslaMate.Repo.Migrations.AddTirePressures.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.071 [info] alter table positions
teslamate_1  | 2022-09-23 09:53:47.076 [info] execute "CREATE OR REPLACE FUNCTION public.convert_tire_pressure(n numeric(6,2), character varying)\nRETURNS numeric(6,2)\nLANGUAGE 'sql'\nCOST 100\nVOLATILE\nAS $BODY$\nSELECT\nCASE $2 WHEN 'bar' THEN $1\n    WHEN 'psi' THEN $1 * 14.503773773\nEND;\n$BODY$;\n"
teslamate_1  | 2022-09-23 09:53:47.086 [info] == Migrated 20220617170400 in 0.0s
teslamate_1  | 2022-09-23 09:53:47.089 [info] == Running 20220718085412 TeslaMate.Repo.Migrations.AddUnitOfPressureToGlobalSettings.change/0 forward
teslamate_1  | 2022-09-23 09:53:47.089 [info] execute "CREATE TYPE unit_of_pressure AS ENUM ('bar', 'psi')"
teslamate_1  | 2022-09-23 09:53:47.095 [info] alter table settings
teslamate_1  | 2022-09-23 09:53:47.098 [info] == Migrated 20220718085412 in 0.0s
teslamate_1  | 2022-09-23 09:53:49.264 [info] System Info: Erlang/OTP 24 (jit)
teslamate_1  | 2022-09-23 09:53:49.264 [info] Version: 1.27.1
teslamate_1  | 2022-09-23 09:53:49.515 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (220.740 ms)
teslamate_1  | 2022-09-23 09:53:49.515 [info] Refreshed api tokens
teslamate_1  | 2022-09-23 09:53:49.520 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-23 09:53:49.522 [info] Running TeslaMateWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
teslamate_1  | 2022-09-23 09:53:49.524 [info] Access TeslaMateWeb.Endpoint at http://xxxxxx.xxxxx.com
teslamate_1  | 2022-09-23 09:53:50.153 [info] GET /
teslamate_1  | 2022-09-23 09:53:52.379 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 16 Aug 2022 01:15:47 GMT.
teslamate_1  | 2022-09-23 09:53:53.254 [info] Tzdata has updated the release from 2021e to 2022c
teslamate_1  | 2022-09-23 09:53:59.458 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxx/vehicle_data -> 408 (9253.615 ms)
teslamate_1  | 2022-09-23 09:53:59.459 [warning] TeslaApi.Error / %TeslaApi.Error{
teslamate_1  |   env: %Tesla.Env{
teslamate_1  |     __client__: %Tesla.Client{adapter: nil, fun: nil, post: [], pre: []},
teslamate_1  |     __module__: TeslaApi,
teslamate_1  |     body: %{
teslamate_1  |       "error" => "{\"error\": \"timeout\"}",
teslamate_1  |       "error_description" => "",
teslamate_1  |       "response" => nil
teslamate_1  |     },
teslamate_1  |     headers: [
teslamate_1  |       {"x-xss-protection", "1; mode=block"},
teslamate_1  |       {"x-txid", "d3e3d59e741a2da53dd903009ec974d5"},
teslamate_1  |       {"content-type", "application/json; charset=utf-8"},
teslamate_1  |       {"x-request-id", "60205676-79c8-4092-bad2-9cf1dca6d565"},
teslamate_1  |       {"content-length", "75"},
teslamate_1  |       {"x-envoy-upstream-service-time", "9171"},
teslamate_1  |       {"x-envoy-upstream-cluster", "owner-api"},
teslamate_1  |       {"date", "Fri, 23 Sep 2022 07:53:59 GMT"},
teslamate_1  |       {"server", "envoy"},
teslamate_1  |       {"x-frame-options", "DENY"},
teslamate_1  |       {"x-content-type-options", "nosniff"},
teslamate_1  |       {"strict-transport-security", "max-age=31536000; includeSubDomains"},
teslamate_1  |       {"cache-control", "no-cache, no-store, private, s-max-age=0"}
teslamate_1  |     ],
teslamate_1  |     method: :get,
teslamate_1  |     opts: [
teslamate_1  |       access_token: "removed"
teslamate_1  |     ],
teslamate_1  |     query: [],
teslamate_1  |     status: 408,
teslamate_1  |     url: "https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxxx/vehicle_data"
teslamate_1  |   },
teslamate_1  |   message: "%{\"error\" => \"{\\\"error\\\": \\\"timeout\\\"}\", \"error_description\" => \"\", \"response\" => nil}",
teslamate_1  |   reason: :unknown
teslamate_1  | }
teslamate_1  | 2022-09-23 09:53:59.459 [info] Starting logger for 'Starlight'
teslamate_1  | 2022-09-23 09:53:59.466 [info] Sent 200 in 9312ms
teslamate_1  | 2022-09-23 09:53:59.468 [info] MQTT connection has been established
teslamate_1  | 2022-09-23 09:54:08.954 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxx/vehicle_data -> 408 (9245.868 ms)
teslamate_1  | 2022-09-23 09:54:08.954 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 09:54:08.954 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 09:54:39.605 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-23 09:54:39.655 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-23 09:54:56.654 [info] GET /
teslamate_1  | 2022-09-23 09:54:56.657 [info] Sent 200 in 2ms
teslamate_1  | 2022-09-23 09:55:05.810 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:01:06.114 [info] GET /settings
teslamate_1  | 2022-09-23 10:01:06.125 [info] Sent 200 in 10ms
teslamate_1  | 2022-09-23 10:01:09.204 [info] GET /
teslamate_1  | 2022-09-23 10:01:09.207 [info] Sent 302 in 2ms
teslamate_1  | 2022-09-23 10:01:09.397 [info] GET /sign_in
teslamate_1  | 2022-09-23 10:01:09.401 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:01:29.544 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (121.535 ms)
teslamate_1  | 2022-09-23 10:01:29.551 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-09-23 10:01:30.009 [info] GET /
teslamate_1  | 2022-09-23 10:01:33.764 [info] Starting logger for 'Starlight'
teslamate_1  | 2022-09-23 10:01:33.769 [info] Sent 200 in 3759ms
teslamate_1  | 2022-09-23 10:01:34.396 car_id=1 [info] Start / :online
teslamate_1  | 2022-09-23 10:01:34.406 car_id=1 [info] Connecting ...
teslamate_1  | 2022-09-23 10:02:00.428 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:06:35.167 [info] GET /
teslamate_1  | 2022-09-23 10:06:35.170 [info] Sent 200 in 2ms
teslamate_1  | 2022-09-23 10:08:09.872 [info] GET /
teslamate_1  | 2022-09-23 10:08:09.875 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:12.295 [info] GET /
teslamate_1  | 2022-09-23 10:08:12.298 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:30.128 [info] GET /settings
teslamate_1  | 2022-09-23 10:08:30.135 [info] Sent 200 in 7ms
teslamate_1  | 2022-09-23 10:08:36.941 [info] GET /settings
teslamate_1  | 2022-09-23 10:08:36.946 [info] Sent 200 in 5ms
teslamate_1  | 2022-09-23 10:08:42.059 [info] GET /
teslamate_1  | 2022-09-23 10:08:42.063 [info] Sent 200 in 3ms
teslamate_1  | 2022-09-23 10:08:46.857 car_id=1 [info] Resuming logging
teslamate_1  | 2022-09-23 10:09:13.622 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxx/vehicle_data -> 408 (9881.730 ms)
teslamate_1  | 2022-09-23 10:09:13.622 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:09:33.998 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxx/vehicle_data -> 408 (9246.034 ms)
teslamate_1  | 2022-09-23 10:09:33.998 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:09:33.998 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:03.267 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxxx/vehicle_data -> 408 (9267.594 ms)
teslamate_1  | 2022-09-23 10:10:03.268 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:10:03.268 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:33.243 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9973.944 ms)
teslamate_1  | 2022-09-23 10:10:33.243 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:10:33.243 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-09-23 10:10:55.241 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9245.608 ms)
teslamate_1  | 2022-09-23 10:10:55.241 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:11:04.510 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/xxxxxxxxx/vehicle_data -> 408 (9267.406 ms)
teslamate_1  | 2022-09-23 10:11:04.510 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-09-23 10:11:07.800 car_id=1 [info] Suspending logging [Triggered manually]
teslamate_1  | 2022-09-23 10:11:07.804 car_id=1 [info] Unhandled fetch result: {:error, :unknown}
```

### Screenshots

<img width="529" alt="Bildschirmfoto 2022-09-23 um 09 58 37" src="https://user-images.githubusercontent.com/1732541/191917217-cf27ea2c-cc08-457f-992d-f0fa22946eb7.png">

### Type of installation

Docker

### Version

v1.27.1

**Comment by sultantariq** [comment]
I had kind of the same issue and it got fix in Tesla version 2022.28.1 and iOS app version 4.13.1

https://github.com/adriankumpf/teslamate/discussions/2891#discussioncomment-3740089
