### ISSUE TITLE
Drives missing, drive start points incorrect, and state stuck "online", potentially because of underground garage with no network connectivity.

### ISSUE THREAD

**Issue by AkshayRao27** [teslamate-org/teslamate#2928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. An entire drive is missing. Screenshot of Timeline Dashboard:
![image](https://user-images.githubusercontent.com/44117116/193564898-412f423a-9459-4600-9764-0d8520c0f5db.png)
I was in park for a couple of minutes at Blum on 02/10/2022, 20:17:20 which wasn't recorded properly (TM thinks I was parked for 12 hours), and the following ~65km drive from Blum to Zenn was not recorded at all. This can also been seen in the odometer discrepancy - at Blum, the Odo reads 947 km, but then the next entry is at 1005 km. This is probably because the end point of that drive at Zenn was an underground garage without any network connectivity. 

2. Drive starting points are incorrect - I had a round trip from Zenn to Zenn. However, referring to the screenshot above, you can see that the starting point has been recorded as Maro instead of Zenn. This is because as I drove out of the parking garage at Zenn, the car did not have a network connection. The car managed to connect to LTE only when I was at Maro, and so, I think that's what was recorded as a the starting point. 

3. Teslamate thinks the car is "online" & isn't recording state changes correctly. The car constantly shows up as "online" despite it having no network connection. I highly doubt the car is actually online down there in the garage.
![image](https://user-images.githubusercontent.com/44117116/193565090-170d650f-5d05-4721-8ff9-3c8a1e051304.png)

### Expected Behavior

1. Drives are recorded completely.
> Alternatively
> 1. The user can manually enter a drive that was not recorded at all.
> 2. The user can manually update the starting / ending points of a drive that was not recorded correctly.

2. Teslamate recognizes when the car is offline and sets the status appropriately. 

### Steps To Reproduce

1. Drive from somewhere to a spot with no network connectivity
2. Drive from the spot with no network connectivity to somewhere else
3. Check drive log / timeline in Teslamate.

### Relevant log output

```bash
root@localhost:~# docker compose logs teslamate --since 2022-10-02T18:00 --until 2022-10-02T18:20
root-teslamate-1  | 2022-10-02 20:09:48.545 car_id=1 [info] Start / :online
root-teslamate-1  | 2022-10-02 20:09:48.552 car_id=1 [info] Connecting ...
root-teslamate-1  | 2022-10-02 20:11:50.665 car_id=1 [warning] Received stale stream data: %TeslaApi.Stream.Data{elevation: 173, est_heading: 224, est_lat: 47.8XXXXX, est_lng: 16.4XXXXX, est_range: 107, heading: 224, odometer: 588.6, power: 0, range: 127, shift_state: nil, soc: 39, speed: nil, time: ~U[2022-10-02 18:11:49.157Z]}
root-teslamate-1  | 2022-10-02 20:14:16.954 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 173, est_heading: 224, est_lat: 47.8XXXXX, est_lng: 16.48XXXX, est_range: 107, heading: 224, odometer: 588.6, power: 1, range: 127, shift_state: "R", soc: 39, speed: 0, time: ~U[2022-10-02 18:14:16.792Z]}
root-teslamate-1  | 2022-10-02 20:14:16.954 car_id=1 [info] Driving / Start
root-teslamate-1  | 2022-10-02 20:14:22.596 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1664734461, heading: 224, latitude: 47.8XXXXX, longitude: 16.4XXXXX, native_latitude: 47.8XXXXX, native_location_supported: 1, native_longitude: 16.4XXXXX, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1664734462347}
root-teslamate-1  | 2022-10-02 20:14:22.596 car_id=1 [info] Driving / Ended / 0 km – 0 min
root-teslamate-1  | 2022-10-02 20:14:22.596 car_id=1 [info] Start / :online
root-teslamate-1  | 2022-10-02 20:15:19.971 [info] Start of drive initiated by: %TeslaApi.Stream.Data{elevation: 173, est_heading: 224, est_lat: 47.8XXXXX, est_lng: 16.4XXXXX, est_range: 107, heading: 224, odometer: 588.6, power: 1, range: 127, shift_state: "R", soc: 39, speed: 0, time: ~U[2022-10-02 18:15:19.809Z]}
root-teslamate-1  | 2022-10-02 20:15:19.971 car_id=1 [info] Driving / Start
root-teslamate-1  | 2022-10-02 20:17:39.038 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (13067.058 ms)
root-teslamate-1  | 2022-10-02 20:17:39.038 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
root-teslamate-1  | 2022-10-02 20:17:39.038 car_id=1 [error] Error / :unknown
root-teslamate-1  | 2022-10-02 20:17:58.308 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (9267.575 ms)
root-teslamate-1  | 2022-10-02 20:17:58.308 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
root-teslamate-1  | 2022-10-02 20:17:58.308 car_id=1 [error] Error / :unknown
root-teslamate-1  | 2022-10-02 20:18:17.725 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (9414.723 ms)
root-teslamate-1  | 2022-10-02 20:18:17.725 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
root-teslamate-1  | 2022-10-02 20:18:17.725 car_id=1 [error] Error / :unknown
root-teslamate-1  | 2022-10-02 20:18:29.943 car_id=1 [info] Received stream data: :inactive
root-teslamate-1  | 2022-10-02 20:18:38.170 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (10443.037 ms)
root-teslamate-1  | 2022-10-02 20:18:38.170 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
root-teslamate-1  | 2022-10-02 20:18:38.170 car_id=1 [error] Error / :unknown
root-teslamate-1  | 2022-10-02 20:18:57.558 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (9387.376 ms)
root-teslamate-1  | 2022-10-02 20:18:57.559 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
root-teslamate-1  | 2022-10-02 20:18:57.559 car_id=1 [error] Error / :unknown
root-teslamate-1  | 2022-10-02 20:19:00.925 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
root-teslamate-1  | 2022-10-02 20:19:01.611 [error] Vehicle Error: Vehicle is offline
root-teslamate-1  | 2022-10-02 20:19:07.830 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (270.345 ms)
root-teslamate-1  | 2022-10-02 20:19:08.086 car_id=1 [warning] Vehicle went offline while driving
root-teslamate-1  | 2022-10-02 20:19:13.367 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (278.817 ms)
root-teslamate-1  | 2022-10-02 20:19:18.915 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (264.685 ms)
root-teslamate-1  | 2022-10-02 20:19:24.462 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (272.628 ms)
root-teslamate-1  | 2022-10-02 20:19:31.871 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (267.256 ms)
root-teslamate-1  | 2022-10-02 20:19:32.802 [error] Vehicle Error: Vehicle is offline
root-teslamate-1  | 2022-10-02 20:19:37.868 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (259.254 ms)
root-teslamate-1  | 2022-10-02 20:19:45.046 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (260.084 ms)
root-teslamate-1  | 2022-10-02 20:19:52.098 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (258.291 ms)
root-teslamate-1  | 2022-10-02 20:19:58.806 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/92XXXXXXXXXXXX/vehicle_data -> 408 (261.648 ms)
```
### Type of installation

Docker

### Version
Teslamate 1.27.1
Tesla 2022.28.2

**Comment by AkshayRao27** [comment]
Another drive that I tried today - this time I kept my mobile hotspot on & the car connected to the mobile hotspot. I paused outside the garage and waited for my phone to get reception so that the car could communicate with the internet via my mobile hotspot. The resulting drive is also HELLA wonky:

![image](https://user-images.githubusercontent.com/44117116/194000166-13ea396a-cb34-43f1-ad89-8f4d4786a32e.png)

**Comment by ngardiner** [comment]
Your car can't get 4G connectivity and it can't get a GPS lock. You are probably better off not starting your drive on hotspot because while that fixes the connectivity issue, the GPS issue will remain.

How deep underground is this carpark? Seems to make a great Faraday cage

**Comment by AkshayRao27** [comment]
> Your car can't get 4G connectivity and it can't get a GPS lock. You are probably better off not starting your drive on hotspot because while that fixes the connectivity issue, the GPS issue will remain.

Okay, that's good to know. The only solution then would be to pause outside the garage till the car has cell reception?

> How deep underground is this carpark? Seems to make a great Faraday cage

It's quite deep and is under both a large building plus a garden. There's absolutely zero cell reception in there from the second you're down the ramp. Unfortunately, there are also no usable plug points to set up any kind of WiFi solution (and even if there were, I cannot pull a wire from my flat to the garage).

**Comment by janthurau** [comment]
Same issue here about missing drives:

![image](https://user-images.githubusercontent.com/896179/194288454-a79a3239-bc08-45dc-ad22-f8290afd1a22.png)

There is one drive missing between 11:45AM and 02:46PM (missing: "HOME to Hornsch..."). I'm also parking underground but just one level, there's even cell connectivity, I think just GPS is lost. It was just 10min trip, not sure if that's important to know.

**Comment by AkshayRao27** [comment]
This morning, I drove out of the garage and waited till the car had an LTE connection. After it had establised an LTE connection, I waited a minute more and then started off driving. The tracking is still extremely wonky:

![image](https://user-images.githubusercontent.com/44117116/194527261-690149ab-1320-4297-ac7d-7b26e513e87c.png)
