### ISSUE TITLE
Charge and Drive Details no information in dashboard

### ISSUE THREAD

**Issue by juannicolas** [teslamate-org/teslamate#2971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Charge Details and Drive Details dashboard are not showing end total information such as 

in Drive Details dashboard:
1. Distance is N/A
2. Energy used is N/A
3. Duration is N/A
![drive_details](https://user-images.githubusercontent.com/597411/200345267-5ec5904b-7814-4bde-83d6-1ead07511ab9.png)

in Charge Details dashboard:
1. Added is N/A
2. Cost is N/A
![charge_details](https://user-images.githubusercontent.com/597411/200345325-2f84f86b-665b-405d-bf84-d90ebbe79d87.png)

### Expected Behavior

Show information in N/A result in dashboard

### Steps To Reproduce

1. Go to Internal/Drive Details Dashboard
2. Select Date range

### Relevant log output

```shell
Not so sure what to look in the logs
```

### Screenshots

![charge_details](https://user-images.githubusercontent.com/597411/200345203-01a2764e-ae0b-4ed6-888c-df7a530a8c94.png)
![drive_details](https://user-images.githubusercontent.com/597411/200345211-cfce10c9-b971-470f-b092-725cc2dc08e3.png)

### Type of installation

Docker

### Version

v8.5.6

**Comment by simonpoole** [comment]
IMHO you are supposed to access that via the "Drives" dashboard.

**Comment by cwanja** [comment]
> IMHO you are supposed to access that via the "Drives" dashboard.

This is correct. If you want to see multiple drives or charges, use Trip

**Comment by juannicolas** [comment]
> IMHO you are supposed to access that via the "Drives" dashboard (resp. via "Charges")



> > IMHO you are supposed to access that via the "Drives" dashboard.
> 
> This is correct. If you want to see multiple drives or charges, use Trip

OK, I can confirm that it works when going from ex. Drives Dashboard>Select or click in one history I can see information.
