### ISSUE TITLE
Missing drive info since 2022.40.4 update

### ISSUE THREAD

**Issue by PHMPhotography** [teslamate-org/teslamate#2973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since updating to 2022.40.4 in my Model Y I have had several drives not register the correct start location. As can be seen in the attached screenshot the drive starts recording in the last 3 minutes of the journey. According to my employers (Hardware) tracker the drive should have started at 15:36 and had a distance of 20 miles.

Please not logs have been edited to remove location data and replaced with ***

![Screenshot 2022-11-08 114438](https://user-images.githubusercontent.com/5256442/200555902-a7979af4-7522-42d0-9d49-36b4064ee4a0.jpg)

### Relevant log output

```shell
teslamate_1  | 2022-11-07 15:22:28.326 [info] Refreshing access token ...
teslamate_1  | 2022-11-07 15:22:28.795 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (467.184 ms)
teslamate_1  | 2022-11-07 15:22:28.808 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-11-07 15:31:22.618 car_id=1 [info] Start / :online
teslamate_1  | 2022-11-07 15:31:22.671 car_id=1 [info] Connecting ...
teslamate_1  | 2022-11-07 15:32:02.494 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/929758414622185/vehicle_data -> 408 (9813.879 ms)
teslamate_1  | 2022-11-07 15:32:02.495 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-11-07 15:32:02.496 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-07 15:34:26.833 car_id=1 [info] Suspending logging
teslamate_1  | 2022-11-07 16:04:28.328 car_id=1 [info] Vehicle is still online. Falling asleep for: 33 min
teslamate_1  | 2022-11-07 16:04:28.329 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1667837066, heading: 87, latitude: 56.051375, longitude: -3.413613, native_latitude: 56.051375, native_location_supported: 1, native_longitude: -3.413613, native_type: "wgs", power: 30, shift_state: "D", speed: 28, timestamp: 1667837068203}
teslamate_1  | 2022-11-07 16:04:28.329 car_id=1 [info] Driving / Start
teslamate_1  | 2022-11-07 16:07:06.699 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (249.489 ms)
teslamate_1  | 2022-11-07 16:07:07.204 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (496.048 ms)
teslamate_1  | 2022-11-07 16:07:07.234 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1667837223, heading: 229, latitude: 56.***, longitude: -3.***, native_latitude: 56.***, native_location_supported: 1, native_longitude: -3.***, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1667837224461}
teslamate_1  | 2022-11-07 16:07:07.235 car_id=1 [info] Driving / Ended / 2 km – 3 min
teslamate_1  | 2022-11-07 16:07:07.235 car_id=1 [info] Start / :online
teslamate_1  | 2022-11-07 16:47:16.290 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/929758414622185/vehicle_data -> 408 (9668.399 ms)
teslamate_1  | 2022-11-07 16:47:16.291 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-11-07 16:47:16.292 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-07 17:01:48.215 [warning] Disconnected! Connection Error: Could not resolve domain name. | 2
teslamate_1  | 2022-11-07 17:02:00.222 [warning] Disconnected! Connection Error: Could not resolve domain name. | 3
teslamate_1  | 2022-11-07 17:02:16.228 [warning] Disconnected! Connection Error: Could not resolve domain name. | 4
teslamate_1  | 2022-11-07 17:04:28.935 car_id=1 [info] Suspending logging
teslamate_1  | 2022-11-07 17:34:29.740 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-11-07 17:34:29.753 car_id=1 [info] Disconnecting ...
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by DGhost001** [comment]
Can confirm this issue. Starting with 2022.40.4 not all drives of my M3 are logged as expected.

There should be a drive logged at 15:20-16:00 but nothing is there....
The returning drive beginning at 17:24 was than logged again as expected.

The relevant log section:
```
teslamate_1  | 2022-11-15 11:10:54.035 car_id=1 [info] Start / :asleep
teslamate_1  | 2022-11-15 11:10:54.066 car_id=1 [info] Disconnecting ...
teslamate_1  | 2022-11-15 15:27:03.915 [info] Refreshing access token ...
teslamate_1  | 2022-11-15 15:27:04.833 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (917.501 ms)
teslamate_1  | 2022-11-15 15:27:04.859 [info] Scheduling token refresh in 6 h
teslamate_1  | 2022-11-15 17:24:37.607 car_id=1 [info] Start / :online
teslamate_1  | 2022-11-15 17:24:37.687 car_id=1 [info] Connecting ...
teslamate_1  | 2022-11-15 17:24:37.691 [info] Start of drive initiated by:
```

**Comment by cwanja** [comment]
Had my first instance of this as well - although it has logged multiple drives before. Though I am not sure why TeslaMate stopped logging here - it was not in a geofence to go to sleep, Sentry was enabled, etc. Emphasis is mine.

```
teslamate_1  | 2022-11-15 15:34:33.706 car_id=1 [info] Start / :online
teslamate_1  | 2022-11-15 15:34:33.755 car_id=1 [info] Connecting ...
teslamate_1  | 2022-11-15 15:34:49.049 [info] Start of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: REMOVED, heading: 359, latitude: REMOVED, longitude: -REMOVED, native_latitude: REMOVED, native_location_supported: 1, native_longitude: -REMOVED, native_type: "wgs", power: 1, shift_state: "D", speed: 0, timestamp: 1668548089398}
teslamate_1  | 2022-11-15 15:34:49.050 car_id=1 [info] Driving / Start
teslamate_1  | 2022-11-15 15:37:12.006 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (690.927 ms)
teslamate_1  | 2022-11-15 15:37:12.485 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (475.728 ms)
teslamate_1  | 2022-11-15 15:37:12.556 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: REMOVED, heading: 88, latitude: REMOVED, longitude: -REMOVED, native_latitude: REMOVED, native_location_supported: 1, native_longitude: -REMOVED, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1668548226402}
teslamate_1  | 2022-11-15 15:37:12.556 car_id=1 [info] Driving / Ended / 0 km – 2 min
teslamate_1  | 2022-11-15 15:37:12.556 car_id=1 [info] Start / :online
teslamate_1  | 2022-11-15 15:39:13.498 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (13144.400 ms)
teslamate_1  | 2022-11-15 15:39:13.498 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-11-15 15:39:13.499 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-15 15:39:43.399 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9896.678 ms)
teslamate_1  | 2022-11-15 15:39:43.400 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-11-15 15:39:43.400 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-15 15:40:12.549 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9144.796 ms)
teslamate_1  | 2022-11-15 15:40:12.549 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
teslamate_1  | 2022-11-15 15:40:12.550 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-15 15:40:35.807 [warning] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 540 (3255.007 ms)
teslamate_1  | 2022-11-15 15:40:35.808 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
teslamate_1  | 2022-11-15 15:40:35.808 car_id=1 [error] Error / :unknown
teslamate_1  | 2022-11-15 15:40:58.186 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
teslamate_1  | 2022-11-15 15:40:58.713 [warning] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 540 (2901.383 ms)
teslamate_1  | 2022-11-15 15:40:58.713 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
teslamate_1  | 2022-11-15 15:40:58.714 car_id=1 [error] Error / :unknown
**teslamate_1  | 2022-11-15 15:41:19.181 car_id=1 [info] Suspending logging**
teslamate_1  | 2022-11-15 15:42:22.111 [warning] Too many disconnects from streaming API
teslamate_1  | 2022-11-15 15:42:22.111 car_id=1 [info] Creating new connection … 
teslamate_1  | 2022-11-15 15:42:22.112 car_id=1 [info] Disconnecting ...
```

**Comment by drjjr2** [comment]
I am having the same issue since yesterday. Car goes "offline" and drive isn't logged. And my location automations predictably also don't work.
So far rebooting the car using the scroll wheels brings it back but this *seems* to have started for me with the 2022.40.4.1 update. So my money is on something Tesla did in that update.

**Comment by tonyhaley** [comment]
I too have this issue. The drive table in the database has start and end times but no other data eg temperature, speed, location etc.

**Comment by cwanja** [comment]
> I think I'm in the same group of insomniacs, though my vehicle is  2022.36.20. I sometimes get the red "health check failed" icon in the landing page, though it's not clear if that's the health of the vehicle (oh no!) or the health of the relationship of the vehicle and Teslamate.
> 
> 
> 
> 
> 
> 
> 
> [2022.36.20](https://www.notateslaapp.com/software-updates/version/2022.36.20/release-notes)
> 
> 
> 
> teslamate_1  | 2022-11-30 02:10:43.433 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9200.989 ms)
> 
> teslamate_1  | 2022-11-30 02:10:43.433 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:10:43.434 car_id=1 [error] Error / :unknown
> 
> teslamate_1  | 2022-11-30 02:11:12.580 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9144.422 ms)
> 
> teslamate_1  | 2022-11-30 02:11:12.582 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:11:12.582 car_id=1 [error] Error / :unknown
> 
> teslamate_1  | 2022-11-30 02:11:41.775 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9189.091 ms)
> 
> teslamate_1  | 2022-11-30 02:11:41.775 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:11:41.776 car_id=1 [error] Error / :unknown
> 
> teslamate_1  | 2022-11-30 02:12:10.963 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9184.930 ms)
> 
> teslamate_1  | 2022-11-30 02:12:10.964 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:12:10.964 car_id=1 [error] Error / :unknown
> 
> teslamate_1  | 2022-11-30 02:12:40.121 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (9155.439 ms)
> 
> teslamate_1  | 2022-11-30 02:12:40.122 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:12:40.122 car_id=1 [error] Error / :unknown
> 
> teslamate_1  | 2022-11-30 02:14:16.442 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/REMOVED/vehicle_data -> 408 (10008.458 ms)
> 
> teslamate_1  | 2022-11-30 02:14:16.442 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
> 
> teslamate_1  | 2022-11-30 02:14:16.443 car_id=1 [error] Error / :unknown

The health check is between TeslaMate and Tesla servers. Nothing specific about your car. In fact, I'd be willing to bet if you tried to launch the Tesla app at the same time there's a health check error, the Tesla app would throw an error attempting to connect.

**Comment by natrlhy** [comment]
Agree with @cwanja. Try a double scroll wheel reboot of the infotainment/screens normally fixes the server 504 error that's shown in the app that may be causing the disconnect between TeslaMate, too

**Comment by natrlhy** [comment]
Sorry normally I see the 504 error in the Tesla App not TeslaMate logs. When I do see this in the Tesla app that's when I know there is some sort of Tesla communication problem. This is when I try the double scroll wheel reboot and it sorts it out.

**Comment by drjjr2** [comment]
Anyone know if anything's changed with the 2022.40.4.2 update?

**Comment by M1kep** [comment]
I am also seeing timeouts for at least the last two days, and presumably the last two weeks

**Comment by CrowMash** [comment]
Same here with 2022.40.4.2

**Comment by tangweiji** [comment]
Same here with 2022.40.4.2

**Comment by tangweiji** [comment]
![image](https://user-images.githubusercontent.com/34420702/205882783-dd735145-c908-42cf-9a73-0da25bb6ce84.png)
![image](https://user-images.githubusercontent.com/34420702/205882913-0572102d-ea32-4ccc-ae8f-f3cdb1914e6c.png)
docker need vpn。

**Comment by gulli1986** [comment]
Same here, just updated to 2022.40.4

**Comment by martin0607** [comment]
Is this bug for everyone or random?

**Comment by drjjr2** [comment]
Whenever I've had a problem with the car going offline it also is unreachable via the Tesla app. I set up Home Assistant alerts to alert me when it goes offline or comes back online. I was under the impression that I had to restart the car with the scroll wheels to get it to come back online but the other day on 2022.44.2 it sort of came back on its own.

Is there any chance that the Tesla server/API has a limit or blocking that Teslamate+the app  causes it to hit that makes it "lock itself out" for a period of time? Some sort of security measure?

Just grasping at straws here. When I first got my car I spun up Teslamate AND Tessie and (maybe I'm just having confirmation bias) but it seems like the car was offline so much that none of my drives were getting tracked. Then I uninstalled Tessie and the frequency of offline occurrences dropped dramatically.

**Comment by martin0607** [comment]
I’m currently stay in 2022.36, not sure if the drive data is incomplete after upgrading 2022.40.X.

**Comment by dansantee** [comment]
If it helps, I'm on 2022.44.25.2 with my MY21 3 and drive data is fine. I did have to do a reboot the other day as the screen was fully locked up but other than that nothing interesting to report.

**Comment by drjjr2** [comment]
I still have the issue on 2022.44.25.3. I need to do some more testing but I've recreated it twice (car going offline) by turning on climate using the Home Assistant Tesla custom integration, then checking to see if there was a software update in the car. Both while connected to house wifi. Then I drove away and left the range of Wifi and the car went offline. Reset using the thumb wheels and it was back online.

**Comment by martin0607** [comment]
Does this happening on 2022.44.30.*?

**Comment by jannyg** [comment]
I have this issue (healh check failed and too many disconnects from streaming API) as well with 2018 TMS 75 (MCU2). It seems like it started with 2022.40.4.x and still exists with the 2022.44.25.3 version I have now. 

I also have issues with waking the car from the official Tesla app when sleeping, seems like it could be related. This started with 2022.40.4.x and was working fine before.
