### ISSUE TITLE
Openstreetmap is not available in China. How to modify the map source displayed on the home page?

### ISSUE THREAD

**Issue by QinChBeSt** [teslamate-org/teslamate#2989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Openstreetmap is not available in China. How to modify the map source displayed on the home page?
<img width="492" alt="截屏2022-11-17 16 50 16" src="https://user-images.githubusercontent.com/16349751/202400847-bb476737-e8e9-47da-98ee-415cf3c50586.png">
<img width="244" alt="截屏2022-11-17 16 50 34" src="https://user-images.githubusercontent.com/16349751/202400882-1648311b-2bcd-44d2-99fe-716256146004.png">

### Relevant log output

```shell
。。
```

### Type of installation

Docker

### Version

v.1.24.1

**Comment by QinChBeSt** [comment]
Can you also add a button to select map source in the upper right corner of the home page?Like in  GRAFANA。

**Comment by devilmc8888** [comment]
in china,gov  ban  openstreetmap  ,can add select map source in settings

**Comment by QinChBeSt** [comment]
> in china,gov ban openstreetmap ,can add select map source in settings

This setting was not found..

**Comment by mywind2020** [comment]
You can use teslamate’s chinese version, this problem has been fixed
access http://docs.teslamate.com.cn/

**Comment by DrMichael** [comment]
> You can use teslamate’s chinese version, this problem has been fixed access http://docs.teslamate.com.cn/

Should we refer to that also in the Readme.md?

**Comment by snbdot** [comment]
> http://docs.teslamate.com.cn/

no ARM  support
