### ISSUE TITLE
map cannot display (China user)

### ISSUE THREAD

**Issue by yhq34** [teslamate-org/teslamate#3023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

(China user)All grafana reports map cannot display, cannot find a quick and correct solution, can anyone help fix it?

### Relevant log output

```shell
2022-12-18 14:44:27.664 [info] MQTT connection has been established
2022-12-18 14:44:28.191 car_id=1 [info] Start / :asleep
2022-12-18 14:44:32.658 [info] GET /settings
2022-12-18 14:44:32.668 [info] Sent 200 in 9ms
2022-12-18 14:51:27.866 [info] GET /settings
2022-12-18 14:51:27.872 [info] Sent 200 in 6ms
2022-12-18 14:51:28.196 [info] GET /
2022-12-18 14:51:28.200 [info] Sent 200 in 4ms
2022-12-18 14:52:22.194 [info] GET /settings
2022-12-18 14:52:22.202 [info] Sent 200 in 7ms
```

### Screenshots

![Uploading mapissue.png…]()

### Type of installation

Docker

### Version

v1.27.1

**Comment by yhq34** [comment]
please see the screenshoot;

<img width="1121" alt="mapissue" src="https://user-images.githubusercontent.com/8621200/208285613-861d2d4d-08d2-43b3-95e7-2fb4b1843a37.png">

**Comment by kktoo21** [comment]
https://github.com/adriankumpf/teslamate/issues/2955
openstreetmap在中国被屏蔽，看看是否挂代理吧，如果部署的机器无法挂代理的话，可能就不行了。

**Comment by yhq34** [comment]
> 

你是在部署的机器上面安装翻墙代理？网页可以显示地图？

**Comment by yhq34** [comment]
代理需要装在部署机器和访问的客户端上面才能正常显示

**Comment by gscsnm** [comment]
#2956 
https://github.com/adriankumpf/teslamate/issues/2956#issuecomment-1303582122

You guys can use https://github.com/WayneJz/teslamate-addr-fix

**Comment by jacklp1** [comment]
change bing map

**Comment by mywind2020** [comment]
使用teslamate的中文版本，已经解决了地图和位置无法显示的问题。
https://docs.teslamate.com.cn

**Comment by dhaslkfha** [comment]
If you run teslamate on your own device,use vpn can fix it.

**Comment by bloy123** [comment]
有人把地图改成高德的了， 我想知道怎么改？  他是出售盒子的
