### ISSUE TITLE
charging cost value is too small

### ISSUE THREAD

**Issue by moon-s-june** [teslamate-org/teslamate#3034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Korea, 
Charging cost kwh is 300 ~ 400 won(korean currency), so in normal case total charging cost is over 10000 won.
But charging total cost field is 9999.99 max.

charging total cost field need to over 10k value.

### Relevant log output

```shell
no log
```

### Type of installation

Docker

### Version

1.24.1

**Comment by wonjin214** [comment]
docker-compose exec database psql teslamate teslamate

ALTER TABLE charging_processes ALTER COLUMN cost TYPE numeric(8,2);


typing 2 lines where docker-compose.yml file.
