### ISSUE TITLE
Cannot reach myIP:3000 permission denied

### ISSUE THREAD

**Issue by galosre** [teslamate-org/teslamate#3035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I had tesla mate for a year use to work on debian base with docker, but lately cannot get into the UI the grafana log give me 
=eror msg="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again" err="failed to verify if the 'alert' table exists: unable to open database file: permission denied"
and container Telamate log give me 
(File.Error) could not write to file "/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt": permission denied

no issue with ip :4000
also cannot update image: postgres:13 to image: postgres:14 not compatible?

### Expected Behavior

Before could access the UI but not anymore

### Steps To Reproduce

Start Teslamate as normal using step 3 The Grafana dashboards are available at [http://your-ip-address:3000](http://localhost:3000/)

### Relevant log output

```shell
[error] GenServer :tzdata_release_updater terminating
** (File.Error) could not write to file "/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt": permission denied

logger=migrator t=2022-12-31T21:42:31.39+0000 lvl=eror msg="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again" err="failed to verify if the 'alert' table exists: unable to open database file: permission denied"
logger=settings t=2022-12-31T21:43:31.72+0000 lvl=info msg="Starting Grafana" version=8.5.6 commit=623255cf2d branch=HEAD compiled=2022-06-14T09:25:38Z
logger=settings t=2022-12-31T21:43:31.72+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations"
Client TESLAMATE_302E3936363 closed its connection.
1672521241: mosquitto version 2.0.15 terminating

[42] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.663 UTC [41] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.663 UTC [46] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.663 UTC [43] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.663 UTC [38] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.664 UTC [44] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.664 UTC [45] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.665 UTC [1] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2022-12-31 21:14:01.665 UTC [37] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.667 UTC [40] FATAL:  terminating connection due to administrator command
2022-12-31 21:14:01.667 UTC [39] FATAL:  terminating connection due to administrator command
```

### Additional data

[_teslamate-database-1_logs(1).txt](https://github.com/adriankumpf/teslamate/files/10328005/_teslamate-database-1_logs.1.txt)
[_teslamate-teslamate-1_logs(1).txt](https://github.com/adriankumpf/teslamate/files/10328006/_teslamate-teslamate-1_logs.1.txt)
[_teslamate-grafana-1_logs(2).txt](https://github.com/adriankumpf/teslamate/files/10328007/_teslamate-grafana-1_logs.2.txt)
[_teslamate-mosquitto-1_logs.txt](https://github.com/adriankumpf/teslamate/files/10328008/_teslamate-mosquitto-1_logs.txt)

### Type of installation

Docker

### Version

1.27.1

**Comment by cwanja** [comment]
Do you have space available on the system hosting TeslaMate?

**Comment by galosre** [comment]
Definitely not the issue, the partition where docker folder is got 430Gib free

**Comment by cwanja** [comment]
#3040 - similar errors. No fix, but possible collaboration.

**Comment by dyxyl** [comment]
It looks like the both the teslamate and grafana containers have file permission problems.  Were they upgraded from older versions?

The output of
```
docker exec tm_grafana_1 ls -la /var/lib/grafana
docker exec tm_teslamate_1 ls -la /opt/app/lib/tzdata-1.1.1/priv
```
might be useful (replace `tm_grafana_1` and `tm_teslamate_1` by the names of your containers).

**Comment by galosre** [comment]
Just in case I removed _1 at the end of all my containers's names and relaunched the stack in portainer
`# docker exec teslamate-teslamate ls -la /opt/app/lib/tzdata-1.1.1/priv
total 20
drwxr-xr-x 4 root users 4096 Jul 22 10:35 .
drwxr-xr-x 4 root users 4096 Jul 22 10:35 ..
-rw-r--r-- 1 root users    9 Jul 22 10:35 latest_remote_poll.txt
drwxr-xr-x 2 root users 4096 Jul 22 10:35 release_ets
drwxr-xr-x 2 root users 4096 Jul 22 10:35 tmp_downloads
`
`~# docker exec teslamate-grafana ls -la /var/lib/grafana
Error response from daemon: Container b1a475948dab1774bf8444a25ec1681ce75837921c3c9e06838b0ff3a2d714a3 is restarting, wait until the container is running
`

**Comment by dyxyl** [comment]
In the teslamate container, you somehow have all these files owned by root.  They are owned by nonroot for me with a container created using the instructions at https://docs.teslamate.org/docs/installation/docker on debian 11.  Is that different from what you are doing?

The command for the grafana container failed because the container was restarting.  You could try it again but wait a little longer after starting it to avoid this error.

**Comment by galosre** [comment]
I tried stopping the container and starting it after the other, this is not working because of permission issue
I followed the instructions to the letter, you can see my install in the attached file is also running on a Debian 11 base : OMV.
 So for some reason the user became root, how can I change it back to nonroot without recreate everything and loosing all my data?
[teslamate.txt](https://github.com/adriankumpf/teslamate/files/10397094/teslamate.txt)

**Comment by galosre** [comment]
look like  for docker exec teslamate-teslamate-1 ls -la /opt/app/lib/tzdata-1.1.1/priv
 the files  owner is somehow fixed
`total 28
drwxr-xr-x 1 nonroot nonroot 4096 Jan 13 13:47 .
drwxr-xr-x 1 nonroot nonroot 4096 Jan 13 13:47 ..
-rw-r--r-- 1 nonroot nonroot    9 Jan 13 18:17 latest_remote_poll.txt
drwxr-xr-x 1 nonroot nonroot 4096 Jan 13 18:17 release_ets
drwxr-xr-x 1 nonroot nonroot 4096 Jan 13 18:17 tmp_downloads
`
but beside this basicaly the same result, no fixed.
[_teslamate-teslamate-1_logs(2).txt](https://github.com/adriankumpf/teslamate/files/10416075/_teslamate-teslamate-1_logs.2.txt)
[_teslamate-mosquitto-1_logs(2).txt](https://github.com/adriankumpf/teslamate/files/10416076/_teslamate-mosquitto-1_logs.2.txt)
[_teslamate-grafana-1_logs(4).txt](https://github.com/adriankumpf/teslamate/files/10416077/_teslamate-grafana-1_logs.4.txt)
[_teslamate-database-1_logs(4).txt](https://github.com/adriankumpf/teslamate/files/10416078/_teslamate-database-1_logs.4.txt)
