### ISSUE TITLE
 [error] GenServer :tzdata_release_updater terminating

### ISSUE THREAD

**Issue by martinh2011** [teslamate-org/teslamate#3040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Log repeatedly shows:

2023-01-02 21:42:20.326 [error] GenServer :tzdata_release_updater terminating
 ** (File.Error) could not write to file "/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt": permission denied

This happens every couple of seconds

### Expected Behavior

no such error.

### Steps To Reproduce

1. Setup and run Teslamate as documented
2. View the teslamate log

### Relevant log output

```shell
teslamate-teslamate-1  | ** (File.Error) could not write to file "/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt": permission denied
teslamate-teslamate-1  |     (elixir 1.13.4) lib/file.ex:1054: File.write!/3
teslamate-teslamate-1  |     (tzdata 1.1.1) lib/tzdata/data_loader.ex:43: Tzdata.DataLoader.last_modified_of_latest_available/1
teslamate-teslamate-1  |     (tzdata 1.1.1) lib/tzdata/release_updater.ex:81: Tzdata.ReleaseUpdater.loaded_tzdata_matches_remote_last_modified?/0
teslamate-teslamate-1  |     (tzdata 1.1.1) lib/tzdata/release_updater.ex:42: Tzdata.ReleaseUpdater.poll_for_update/0
teslamate-teslamate-1  |     (tzdata 1.1.1) lib/tzdata/release_updater.ex:19: Tzdata.ReleaseUpdater.handle_info/2
teslamate-teslamate-1  |     (stdlib 3.17.2) gen_server.erl:695: :gen_server.try_dispatch/4
teslamate-teslamate-1  |     (stdlib 3.17.2) gen_server.erl:771: :gen_server.handle_msg/6
teslamate-teslamate-1  |     (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
teslamate-teslamate-1  | Last message: :check_if_time_to_update
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by martinh2011** [comment]
As a temporary workaround I built an own image with this docker file

```
FROM teslamate/teslamate:latest
USER root
RUN chmod ugo+rw /opt/app/lib/tzdata-1.1.1/priv/*
USER nonroot:nonroot
```

and referenced that image in docker-compose.yml. 

However, I don't really know the root cause. The file permissions seem to prevent writing into that folder and the workaround just tweaks them. But I don't really know how this time zone data updater works and when it checks for updates. Maybe it does that not very often. Or maybe it usually has nothing to update and that error only occurs when there's one.

**Comment by cwanja** [comment]
#3035 - similar errors. No fix, but possible collaboration.

**Comment by cwanja** [comment]
Did you update anything on the host system? Or have automatic updates run?

**Comment by martinh2011** [comment]
System runs ArchLinux and gets updates regularly. Docker 20.10.17, updated two weeks ago.

**Comment by fjctp** [comment]
I have the same problem with `podman v4.3.1`. I updated to this version about 3 days ago, and the same problem occurred.

**Comment by dyxyl** [comment]
The output of
```
docker exec teslamate-teslamate-1 ls -la /opt/app/lib/tzdata-1.1.1/priv
```
in the broken image might be useful.  For me, everything is owned by nonroot and writeable by the owner.

**Comment by galosre** [comment]
@martinh2011 martinh2011Can you described in detail your fix?
 https://github.com/adriankumpf/teslamate/issues/3040#issuecomment-1369225342

**Comment by martinh2011** [comment]
@dyxyl if I run the latest image on a system where teslamate never ran, I also see that the files are owned by nonroot, group nonroot. 

On the system where I observed the error the files are owned by user and group with id 972. nonroot has userid 10000 and gid 10001. I don‘t know where the difference came from. Had no time yet to investigate.

@galosre my „fix“ just tweaks the permissions on the files in /opt/app/lib/tzdata-1.1.1/priv so that user nonroot is able to write them which stops the error.

**Comment by martinh2011** [comment]
I just tried to reproduce the problem on a separate system, but I couldn't. On the system where it occurs I tried the following: 

Stopping all container (docker compose down), removing all stopped containers, if any. Removing all docker images (docker image prune --all). Started everything again with "docker compose up -d". Now the files in /opt/app/lib/tzdata-1.1.1/priv have the correct owner, group (nonroot:nonroot) and permissions. Don't know how I ended up in the situation that these files had wrong owner:group.

For me this does not look like a general issue anymore, even if I still don't understand the root cause.

**Comment by rpearson-catdevnull** [comment]
Just resurrecting this thread as I'm also seeing this error on a new install:

```
2023-07-10 22:42:46.419 [error] GenServer :tzdata_release_updater terminating
** (File.Error) could not write to file "/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt": permission denied
    (elixir 1.15.0-rc.1) lib/file.ex:1117: File.write!/3
    (tzdata 1.1.1) lib/tzdata/data_loader.ex:43: Tzdata.DataLoader.last_modified_of_latest_available/1
    (tzdata 1.1.1) lib/tzdata/release_updater.ex:81: Tzdata.ReleaseUpdater.loaded_tzdata_matches_remote_last_modified?/0
    (tzdata 1.1.1) lib/tzdata/release_updater.ex:42: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata 1.1.1) lib/tzdata/release_updater.ex:19: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib 5.0.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

Just spammed constantly in the docker logs, app runs fine otherwise.

The only changes I've made from a standard installation is to add `user: "1003:1007"` to each of the services as I wanted these containers running as as specific user and group. The volumes all have correct permissions setup and the app otherwise functions as expected.

Tried the suggested tear down and recreate and got the same behaviour. I'm guessing its something to do with running as a specific user but I'm not sure what 😄

**Comment by dyxyl** [comment]
What is the ownership of `/opt/app/lib/tzdata-1.1.1/priv/latest_remote_poll.txt` and `/opt/app/lib/tzdata-1.1.1/priv/`? e.g. the output of something like:
```
docker exec tm_teslamate_1 ls -l /opt/app/lib/tzdata-1.1.1/priv
```

**Comment by jwilleke** [comment]
Originally this was working on 
- VM DISTRIB_DESCRIPTION="Ubuntu 23.04"
- Docker Version:   24.0.5


```
docker ps
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                          PORTS                                       NAMES
d68d02d4fcb2   postgres:15                  "docker-entrypoint.s…"   17 minutes ago   Up 17 minutes                   5432/tcp                                    teslamate_database_1
66fd6d6c16f2   teslamate/teslamate:latest   "tini -- /bin/sh /en…"   17 minutes ago   Up 17 minutes                   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   teslamate_teslamate_1
2a3cb193f657   eclipse-mosquitto:2          "/docker-entrypoint.…"   17 minutes ago   Up 17 minutes                   1883/tcp                                    teslamate_mosquitto_1
a1247e29a3a9   teslamate/grafana:latest     "/run.sh"                17 minutes ago   Restarting (1) 53 seconds ago                                               teslamate_grafana_1
aa285b72ff69   apache/jspwiki:latest        "/usr/local/tomcat/b…"   3 weeks ago      Up 2 hours                      0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   jimsWiki
7dfb3f298478   portainer/agent:2.19.0       "./agent"                3 weeks ago      Up 2 hours                      0.0.0.0:9001->9001/tcp, :::9001->9001/tcp   portainer_agent


grafana_1    |0m logger=sqlstore t=2023-09-30T13:30:21.81+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3
grafana_1    |0m logger=migrator t=2023-09-30T13:30:21.81+0000 lvl=eror msg="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again" err="failed to verify if the 'alert' table exists: unable to open database file: permission denied"


docker exec a1247e29a3a9 ls -la /var/lib/grafana
Error response from daemon: Container a1247e29a3a9fcfbed296350cc5ada0c5fd8e5938e33d445547f8831fec5428f is restarting, wait until the container is running

docker exec 66fd6d6c16f2 ls -la /opt/app/lib/tzdata-1.1.1/priv
total 20
drwxr-xr-x 4 nonroot nonroot 4096 Jun 12 09:57 .
drwxr-xr-x 4 nonroot nonroot 4096 Jun 12 09:57 ..
-rw-r--r-- 1 nonroot nonroot    9 Jun 12 09:57 latest_remote_poll.txt
drwxr-xr-x 2 nonroot nonroot 4096 Jun 12 09:57 release_ets
drwxr-xr-x 2 nonroot nonroot 4096 Jun 12 09:57 tmp_downloads
```
DISTRIB_DESCRIPTION="Ubuntu 23.04"

**Comment by dyxyl** [comment]
> ```
> grafana_1    |0m logger=migrator t=2023-09-30T13:30:21.81+0000 lvl=eror msg="failed to determine the status of alerting engine. Enable either legacy or unified alerting explicitly and try again" err="failed to verify if the 'alert' table exists: unable to open database file: permission denied"
> ```

This `unable to open database file: permission denied"` error is a different problem from the tzdata one in the original post.  I suspect it is caused by updating to a newer version of grafana.

The following might fix it (but do a backup of the postgresql database first just in case it does damage):
```
docker stop teslamate_grafana_1
docker rm -f -v teslamate_grafana_1
docker volume rm teslamate_teslamate-grafana-data
docker compose up -d
```

The name `teslamate_teslamate-grafana-data` is a guess -- if `docker volume rm` doesn't work, then find the name of the `teslamate-grafana-data` using `docker volume ls` and use that name instead.

**Comment by dnovischi** [comment]
Still seeing this on a fresh install:

`2024-09-26 11:13:02.605 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.
2024-09-26 11:13:03.770 [error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :error)
    (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update`

Maybe [this dependency](https://github.com/teslamate-org/teslamate/blob/6871ef73d40438abf80df07d9a543c510f79595f/mix.exs#L66) needs updating.

**Comment by brianmay** [comment]
@dnovischi See #4196 - I believe this is fixed in master.

**Comment by dnovischi** [comment]
This is a fresh install, via HA add-on which uses master. But no luck... due to this error some of the data in dashboards is not available.
