### ISSUE TITLE
Odometer value is missing in Charges

### ISSUE THREAD

**Issue by ptar** [teslamate-org/teslamate#3077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Charges dashboard, the odometer value is missing.

### Expected Behavior

The odometer_$length_unit should be part of the panel. Please add it as described below, or alike.

Thank you!

### Steps To Reproduce

Add a second line after
```
        max(c.charger_voltage) as max_charger_voltage,
        p.odometer as odometer
```

And another second line after
```
    convert_km(distance::numeric, '$length_unit') AS distance_$length_unit,
    convert_km(odometer::numeric, '$length_unit') AS odometer_$length_unit
```

Then add an unit override to prevent e.g. '1 Mm' instead of '1000 km':
Add a custom unit 'km ' (with a space at the end) and choose "Custom unit: km "

Do the same for odometer_mi, if necessary

### Relevant log output

```shell
no log needed
```

### Screenshots

![2023-01-18 22_12_59-Ladungen - Grafana – Mozilla Firefox](https://user-images.githubusercontent.com/12029706/213298024-ccdb002a-61a2-41aa-86d8-0e7ee1b9d99e.png)

### Type of installation

Docker

### Version

v1.27.1

**Comment by ptar** [comment]
Thank you for accepting this suggestion for an enhancement as an 'easy-to-fix bug' 😀

**Comment by DrMichael** [comment]
Done in https://github.com/teslamate-org/teslamate/pull/3463

**Comment by ptar** [comment]
Thank you!
