### ISSUE TITLE
Divide by zero in Grafana "Projected Range" dashboards (revisited)

### ISSUE THREAD

**Issue by inigoml** [teslamate-org/teslamate#3092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A "db query error: pq: division by zero" is displayed at two Grafana "Projected Range" dashboads. This bug is related with #2063 bug that was already fixed for "Projected Range" graph. Problem persists at "Battery Level" and "Outdoor Temperature" graphs.

It happens when car battery level is UNDER ZERO. @

### Expected Behavior

Error should not appear and query should be executed properly.

### Steps To Reproduce

1. Drive your car under 0% battery range. You must enter into negative values (buffer zone).
2. Let stats be pushed to Teslamate.
3. Access Projected Range dashboards.

### Relevant log output

```shell
Problematic query for "Battery Level":
SELECT
	floor(extract(epoch from date)/21600)*21600 AS time,
	convert_km(sum(ideal_battery_range_km) / sum(coalesce(usable_battery_level,battery_level)) * 100, 'km') AS "Projected Range (using usable_battery_level) [km]",
	convert_km(sum(ideal_battery_range_km) / sum(battery_level) * 100, 'km') AS "Projected Range (using battery_level)[km]"
FROM
	(
    select battery_level, usable_battery_level, date,
      rated_battery_range_km, ideal_battery_range_km, outside_temp
    from positions
    where
      car_id = '2' and date BETWEEN '2022-07-27T19:55:26.671Z' AND '2023-01-27T20:55:26.671Z' and ideal_battery_range_km is not null
    union all
    select battery_level, coalesce(usable_battery_level,battery_level) as usable_battery_level, date,
      rated_battery_range_km, ideal_battery_range_km, outside_temp
    from charges c
    join
      charging_processes p ON p.id = c.charging_process_id 
    where
      date BETWEEN '2022-07-27T19:55:26.671Z' AND '2023-01-27T20:55:26.671Z' and p.car_id = '2'
    ) as data

GROUP BY
	1
ORDER BY
	1,2  DESC


Problematic query for Outdoor Temp:
SELECT
	floor(extract(epoch from date)/21600)*21600 AS time,
	convert_km(sum(ideal_battery_range_km) / sum(coalesce(usable_battery_level,battery_level)) * 100, 'km') AS "Projected Range (using usable_battery_level) [km]",
	convert_km(sum(ideal_battery_range_km) / sum(battery_level) * 100, 'km') AS "Projected Range (using battery_level) [km]"
FROM
	(
    select battery_level, usable_battery_level, date,
      rated_battery_range_km, ideal_battery_range_km, outside_temp
    from positions
    where
      car_id = '2' and date BETWEEN '2022-07-27T19:55:27.497Z' AND '2023-01-27T20:55:27.497Z' and ideal_battery_range_km is not null
    union all
    select battery_level, coalesce(usable_battery_level,battery_level) as usable_battery_level, date,
      rated_battery_range_km, ideal_battery_range_km, outside_temp
    from charges c
    join
      charging_processes p ON p.id = c.charging_process_id 
    where
      date BETWEEN '2022-07-27T19:55:27.497Z' AND '2023-01-27T20:55:27.497Z' and p.car_id = '2'
    ) as data

GROUP BY
	1
ORDER BY
	1,2  DESC
```

### Screenshots

![image](https://user-images.githubusercontent.com/7486708/215194779-1b937106-7b1d-4d07-8482-488d3a20075b.png)
![image](https://user-images.githubusercontent.com/7486708/215194875-0dfed77f-c043-4dea-a8bf-50ab6e7012ea.png)
![image](https://user-images.githubusercontent.com/7486708/215194920-14ceab17-fa8f-4d85-9211-afd5c757e84e.png)

### Additional data

A mechanism applied to avoid query error as in bug  #2063 should be applied to remaining queries.

### Type of installation

Docker

### Version

v1.27.2

**Comment by SiNaPsEr0x** [comment]
I fixed a similar problem by using a platform-specific version of postgresql of my nas

**Comment by Dulanic** [comment]
Fixed https://github.com/teslamate-org/teslamate/commit/fbfe8e22242f444caec21964cc0a68d242cc9939
