### ISSUE TITLE
about openstreetmap display

### ISSUE THREAD

**Issue by ArthurZangCN** [teslamate-org/teslamate#3097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I build a teslamate services in my nas, the map can not display in pc web browser，but can display in ios web browser.
Whether to consider adding map API suitable for Chinese users in the next version？

I found another phenomenon: homeassent can display maps in pc web browser.

![image](https://user-images.githubusercontent.com/38482604/216912014-34103355-7aef-48d2-b5a6-9f550836108e.png)

### Relevant log output

```shell
...
```

### Type of installation

Docker

### Version

v1.27.2

**Comment by wujian9365** [comment]
I got the same problem 😭

**Comment by yusimtin** [comment]
I have the same problem, I have added a VPN to my router and it shows the map but not the Start and Destination addresses, hope there is a way to fix it

**Comment by ArthurZangCN** [comment]
> I have the same problem, I have added a VPN to my router and it shows the map but not the Start and Destination addresses, hope there is a way to fix it

teslamate-add-fix can solve your problem，but the code must be modify and build by yourself（https://github.com/WayneJz/teslamate-addr-fix/issues/3）

**Comment by yusimtin** [comment]
I also found this project, but I didn't understand it, I'm a novice in this area/(ㄒoㄒ)/~~

**Comment by ArthurZangCN** [comment]
> I also found this project, but I didn't understand it, I'm a novice in this area/(ㄒoㄒ)/~~

**Comment by jiangnan1710** [comment]
I have the same problem. Now the openstreet map has been banned in China mainland.
I think it may cause by the plugin called 'track map' of Grafana. I konw the root cause, but have no way to solve it. 
Hope someone can make a new plugin which change the trackmap plugin's base map.

**Comment by mywind2020** [comment]
You can use teslamate’s chinese version, this problem has been fixed
access http://docs.teslamate.com.cn
