### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by marineboy0122** [teslamate-org/teslamate#3112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I changed the data in the web application setting menu, but it is not saved.

### Relevant log output

```shell
irrelevant
```

### Screenshots

![제목 없음](https://user-images.githubusercontent.com/83511237/217469737-1f48128e-ebf9-426a-b537-deb0abbdbf53.png)

### Type of installation

Docker

### Version

v1.27.2

**Comment by ebretteville** [comment]
Same problem but in the geofence tab.

**Comment by ebretteville** [comment]
Up +1

**Comment by JakobLichterfeld** [comment]
Please use current version, which is 1.28.3
