### ISSUE TITLE
Missing Drives while trips show data.

### ISSUE THREAD

**Issue by Richardrsb** [teslamate-org/teslamate#3127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since 14-02-23 Teslamate does not log drives. In trips i see the trips, but also with missing data.
This *Might* have something to do with the outage of tesla's servers, but those are up and running for a few days.

### Expected Behavior

Logging drives.

### Relevant log output

```shell
I updated Teslamate. It seems the logs are emptied. I only have post update logs.
```

### Additional data

[drives.csv](https://github.com/adriankumpf/teslamate/files/10775230/drives.csv)
[positions.csv](https://github.com/adriankumpf/teslamate/files/10775231/positions.csv)

### Type of installation

Docker

### Version

Latest as per 18-02

**Comment by Richardrsb** [comment]
I attached screnshots. Failed. I'll try again here.
![Screenshot 2023-02-18 at 22 15 09](https://user-images.githubusercontent.com/125134836/219900513-36b6297d-55a8-4293-bb4f-1a1a2c067acf.jpg)
![Screenshot 2023-02-18 at 22 16 50](https://user-images.githubusercontent.com/125134836/219900516-a54b9627-74b9-44d6-ad54-d005848003d7.jpg)

**Comment by cwanja** [comment]
Are there any unclosed drives by chance?

**Comment by Richardrsb** [comment]
What do you mean with unclosed drives?
-- 
Richard Rosenberger

￼

Mobile Techcenter vof
Toepadweg 33 
5301 KA  Zaltbommel
+31-418-511296
http://www.mobiletechcenter.nl
 ***@***.***
 ***@***.***>KvK: 30177799 BTW/VAT: NL8105.84.712.B01 EORI: NL810584712

**Comment by cwanja** [comment]
If there was an outage, it could be that a drive did not close. Thus you have one continuous drive that is actually multiple drives. https://docs.teslamate.org/docs/maintenance/manually_fixing_data

Could try and close the next drive ID from your Drives dashboard. Get the drive ID from the URL.

**Comment by Richardrsb** [comment]
I’ll try tomorrow , and let you know. Thanks. — Mobile Techcenter vofToepadweg 33 5301 KA  ***@***.***: 30177799 BTW/VAT: NL8105.84.712.B01 EORI: NL810584712 Mobile Techcenter is een gecertificeerd reparatiebedrijf, en erkend door Techniek Nederland. On 18 Feb 2023, at 23:12, cwanja ***@***.***> wrote:﻿
If there was an outage, it could be that a drive did not close. Thus you have one continuous drive that is actually multiple drives. https://docs.teslamate.org/docs/maintenance/manually_fixing_data
Could try and close the next drive ID from your Drives dashboard. Get the drive ID from the URL.

**Comment by Richardrsb** [comment]
Hi,

Did not succeed.
“Event not found”

***@***.******@***.***# docker-compose exec teslamate bin/teslamate rpc \
>     "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 2993) |> TeslaMate.Log.close_drive()"
-ash: !: event not found


If you have time, you can log into TM yourself. I opened temporary access to TM on my DS.

You can find it here: 77.174.235.188:3000
Everything is default, normally this is not open to i-net.

I realize you can’t SSH here, but maybe you can see what the problem is.

Regards,


-- 
Richard Rosenberger



Mobile Techcenter vof
Toepadweg 33 
5301 KA  Zaltbommel
+31-418-511296
http://www.mobiletechcenter.nl
 ***@***.***
 ***@***.***>KvK: 30177799 BTW/VAT: NL8105.84.712.B01 EORI: NL810584712

**Comment by Richardrsb** [comment]
Pulling the log with docker-compose logs teslamate gets me this (exerpt):
teslamate_1  | 2023-02-18 20:48:34.129 [error] Could not create schema migrations table. This error usually happens due to the following:
teslamate_1  | 
teslamate_1  |   * The database does not exist
teslamate_1  |   * The "schema_migrations" table, which Ecto uses for managing
teslamate_1  |     migrations, was defined by another library
teslamate_1  |   * There is a deadlock while migrating (such as using concurrent
teslamate_1  | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2590ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
teslamate_1  | 
teslamate_1  |   1. Ensuring your database is available and that you can connect to it
teslamate_1  |   2. Tracking down slow queries and making sure they are running fast enough
teslamate_1  |   3. Increasing the pool_size (although this increases resource consumption)
teslamate_1  |   4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
teslamate_1  | 
teslamate_1  | See DBConnection.start_link/2 for more information
teslamate_1  | 
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     indexes with a migration_lock)
teslamate_1  | 
teslamate_1  | To fix the first issue, run "mix ecto.create".
teslamate_1  | 
teslamate_1  | To address the second, you can run "mix ecto.drop" followed by
teslamate_1  | "mix ecto.create". Alternatively you may configure Ecto to use
teslamate_1  | another table and/or repository for managing migrations:
teslamate_1  | 
teslamate_1  |     config :teslamate, TeslaMate.Repo,
teslamate_1  |       migration_source: "some_other_table_for_schema_migrations",
teslamate_1  |       migration_repo: AnotherRepoForSchemaMigrations
teslamate_1  | 
teslamate_1  | The full error report is shown below.
teslamate_1  | 
teslamate_1  |     (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/release.ex:9: anonymous fn/2 in TeslaMate.Release.migrate/0
teslamate_1  | 2023-02-18 20:49:18.360 [info] == Running 20220123131732 TeslaMate.Repo.Migrations.EncryptApiTokens.change/0 forward
teslamate_1  | 2023-02-18 20:49:18.412 [info] alter table tokens
teslamate_1  | 2023-02-18 20:49:19.472 [warning] 

Maybe it has something to do with home-assistant also running on docker?
Stopped HA, Stopped TM, restarted TM: pull log: same error.

**Comment by myModelY** [comment]
Same by me, drives until 2 weeks missing. charges all ok.

**Comment by Richardrsb** [comment]
After a gap for 10 day's it works again. Drives are logged correctly. <Puzzled>...

**Comment by chowette** [comment]
Same problem here, drive missing since 06 February.
didn't see it before.

Here is a relevant log from Teslamate :

```
teslamate_1  | 2023-02-26 11:37:11.123 [error] Postgrex.Protocol (#PID<0.2388.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2682.0> timed out because it queued and checked out the connection for longer than 60000ms
teslamate_1  | 
teslamate_1  | #PID<0.2682.0> was at location:
teslamate_1  | 
teslamate_1  |     :prim_inet.recv0/3
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:3171: Postgrex.Protocol.msg_recv/4
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:2201: Postgrex.Protocol.recv_bind/3
teslamate_1  |     (postgrex 0.16.5) lib/postgrex/protocol.ex:2093: Postgrex.Protocol.bind_execute/4
teslamate_1  |     (db_connection 2.4.3) lib/db_connection/holder.ex:354: DBConnection.Holder.holder_apply/4
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:1413: DBConnection.run_execute/5
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:1508: DBConnection.run/6
teslamate_1  |     (db_connection 2.4.3) lib/db_connection.ex:644: DBConnection.parsed_prepare_execute/5
teslamate_1  | 
teslamate_1  | 2023-02-26 11:37:12.191 [error] GenStateMachine TeslaMate.Terrain terminating
teslamate_1  | ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
teslamate_1  |     (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
teslamate_1  |     (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/log.ex:177: TeslaMate.Log.get_positions_without_elevation/2
teslamate_1  |     (teslamate 1.27.2) lib/teslamate/terrain.ex:84: TeslaMate.Terrain.handle_event/4
teslamate_1  |     (stdlib 3.17.2.1) gen_statem.erl:1205: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

```

I have tried to increase DATABASE_POOL_SIZE to 10 and 15 (like in #2182 )  , but without success.
 
Database logs show the connection is closed ...

```
database_1   | 2023-02-26 11:36:11.286 UTC [54419] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:36:12.141 UTC [1] LOG:  background worker "parallel worker" (PID 54420) exited with exit code 1
database_1   | 2023-02-26 11:36:12.142 UTC [1] LOG:  background worker "parallel worker" (PID 54419) exited with exit code 1
database_1   | 2023-02-26 11:36:12.168 UTC [54413] LOG:  could not send data to client: Broken pipe
database_1   | 2023-02-26 11:36:12.168 UTC [54413] FATAL:  connection to client lost
database_1   | 2023-02-26 11:37:11.972 UTC [54283] ERROR:  canceling statement due to user request
database_1   | 2023-02-26 11:37:11.972 UTC [54283] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:37:12.301 UTC [54424] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-26 11:37:12.301 UTC [54424] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:37:12.301 UTC [54425] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-26 11:37:12.301 UTC [54425] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:37:13.119 UTC [1] LOG:  background worker "parallel worker" (PID 54425) exited with exit code 1
database_1   | 2023-02-26 11:37:13.120 UTC [1] LOG:  background worker "parallel worker" (PID 54424) exited with exit code 1
database_1   | 2023-02-26 11:38:12.475 UTC [54398] ERROR:  canceling statement due to user request
database_1   | 2023-02-26 11:38:12.475 UTC [54398] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:38:12.476 UTC [54430] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-26 11:38:12.476 UTC [54430] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
database_1   | 2023-02-26 11:38:12.477 UTC [54429] FATAL:  terminating connection due to administrator command
database_1   | 2023-02-26 11:38:12.477 UTC [54429] STATEMENT:  SELECT s0."drive_id" FROM (SELECT sp0."drive_id" AS "drive_id", count(*) FILTER (WHERE NOT (sp0."odometer" IS NULL) AND (sp0."ideal_battery_range_km" IS NULL)) AS "streamed_count" FROM "positions" AS sp0 WHERE (NOT (sp0."drive_id" IS NULL)) GROUP BY sp0."drive_id") AS s0 WHERE (s0."streamed_count" = 0)
```

**Comment by BriCo84** [comment]
Just noticed today missing drives from last couple of days at least...

**Comment by enoch85** [comment]
Hey, I'm also joining the club on this one... Any new findings?

**Comment by jsiegmund** [comment]
I have had this issue for quite a while now, I haven't got a clue why. The trip data seems to be better than the drives dashboard. Drives seems to randomly pick up on some drives whilst leaving out others. Very annoying as I was using the drives dashboard for my trip registration. 

Based on this thread I got myself access into the database and found 286 rows where `end_date` is `NULL`, so there definitely seems to be an issue with ending / closing drives for some reason. I've tried the fix to close one of them, but I'm getting the same "event not found" error as mentioned above.

**Comment by Richardrsb** [comment]
This issue still exists. Randomly drives are missing, especially longer drives. In trips they do exist, also charging at the destination is logged correctly.

**Comment by mligor** [comment]
Unfortunately, I have the same issue (since middle of December 2022). There are many unclosed drivers, and if I try to fix data I get also "Event not found".

**Comment by mligor** [comment]
3 days ago, I upgraded postgres from 13 to 14, and since then, I have no issues any more.  Can you guys check if you are still running on postgres 13? Could this be a problem?

**Comment by enoch85** [comment]
>  3 days ago, I upgraded postgres from 13 to 14, and since then, I have no issues any more. Can you guys check if you are still running on postgres 13? Could this be a problem?


Interesting! 

On that topic, is PostreSQL 15 supported?

**Comment by chowette** [comment]
Thank you @mligor !
I was still running on postgres 13. I updated to 14 and my drives of today (before the update) appeared. 
I also pulled all containers to last version. 
I will drive tomorrow and tell you if it is solved for me.

**Comment by Richardrsb** [comment]
Erm, is there a noob's explanation how to update postgres? I updated TM by Docker-compose down / pull / up -d but postgres is still on 13. I run this on a Synology NAS in docker.

**Comment by mligor** [comment]
Just taking postgres 14 as container will not work, as stored files are incompatible with 13. That was my reason why I didn't do that at the first time. 



Here is the tutorial: https://docs.teslamate.org/docs/maintenance/upgrading_postgres

but be careful, you can lose all your data – and don't skip Step 1 :)

**Comment by chowette** [comment]
My drives are working again!
Updating teslamate to version 1.27.2 require postgres 14.

**Comment by alexeiw123** [comment]
This seems related to an issue I have that appears the same, however in investigating my postgres, it appears I am already on 14.
