### ISSUE TITLE
The start at time in statistics is from 4 or 5 pm?

### ISSUE THREAD

**Issue by yumeng426** [teslamate-org/teslamate#3132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

See the screenshot, my starting at time is always from 4 or 5 pm. Is this a bug? I find it is not intuitive to split a day or a month at this hour. Is there a way to change it to at least midnight? 

### Steps To Reproduce

Go to Statistics tab

### Relevant log output

```shell
n/a
```

### Additional data

<img width="393" alt="Screenshot 2023-02-24 at 10 58 43 PM" src="https://user-images.githubusercontent.com/11802847/221343730-1bf5fc91-00e5-4e04-ab0d-ccc815ac0684.png">

### Type of installation

Docker

### Version

1.27.2

**Comment by DrMichael** [comment]
Try to set your timezone in docker-compose.yml for

teslamate, database, grafana:
`      - TZ=${TM_TZ}
`
I have also for database and grafana (probably only grafana is necessary):
`      - PGTZ=${TM_TZ}
`
And for grafana also (not sure, whether that makes a difference):
`      - LOCALE=${LOCALE}
`

**Comment by yumeng426** [comment]
>  have also for database and grafana (probably only grafana is necessary):
>      - PGTZ=${TM_TZ}

This works. Thanks!

A few more questions tho. 

The timezone seems to be at `utc` to make it split the day at the midnight of my `${TM_TZ}`. Instead of selecting the timezone, it seems to be the relative timezone to my current one. For example, my TM_TZ is Los Angeles, it only splits a day at my midnight if the timezone is selected to `utc`. 

Additionally, although changing the timezone in grafana also changes the day split time, it does not have any impact on the epoch time in `date_to` and `date_from`. As a result, although changing the timezone makes my day split at different time if I chose a `non-utc timezone`, clicking on the date itself leads me to the trip panel from the midnight to next midnight of los Angeles time.

**Comment by DrMichael** [comment]
> > have also for database and grafana (probably only grafana is necessary):
> > - PGTZ=${TM_TZ}
> 
> This works. Thanks!
> The timezone seems to be at `utc` to make it split the day at the midnight of my `${TM_TZ}`. Instead of selecting the timezone, it seems to be the relative timezone to my current one. For example, my TM_TZ is Los Angeles, it only splits a day at my midnight if the timezone is selected to `utc`.

About which timezone are you talking? The setting in Grafana? I have set there my current timezone and TZ and PGTZ set as above. And the splits are at my midnight...

> Additionally, although changing the timezone in grafana also changes the day split time, it does not have any impact on the epoch time in `date_to` and `date_from`. As a result, although changing the timezone makes my day split at different time if I chose a `non-utc timezone`, clicking on the date itself leads me to the trip panel from the midnight to next midnight of los Angeles time.

Right. What is wrong about that? it might be, that events around midnight are not counted correctly, hard to test on my side (only one houur difference to UTC). All times in the database are in UTC.
