### ISSUE TITLE
Install Teslamate in a lxc container

### ISSUE THREAD

**Issue by httpedo13** [teslamate-org/teslamate#3167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, i would like to install teslamate on lxc container and i am having problem with elixir erlang with official tutorial. he always tells me "unable to locate esl-erlang"

### Relevant log output

```shell
nothing
```

### Type of installation

Manual

### Version

v1.27.2

**Comment by balajeek** [comment]
I would like the same help.

**Comment by manuduarte** [comment]
I’m running Teslamate in a LXC container, actually one for Teslamate script, one for the database and one for Grafana.
I had issues installing Elixir but I don’t remenber how I resolve it, maybe following the elixir site instruction.

**Comment by manuelkamp** [comment]
I never got it running in LXC, so any step-by-step would be appreciated from many users who use LXC (and now Docker inside LXC which is bad)

**Comment by jensb** [comment]
This is how I have got it working on a Raspi 4b with Raspbian OS which is based on Debian:

`
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
sudo perl -i -pe 's,bullseye,stretch,g' /etc/apt/sources.list.d/erlang-solutions.list
sudo apt-get update
sudo apt-get install -y elixir esl-erlang
`

Then continue to follow the official manual install instructions.

**Comment by chrta** [comment]
I had no issue getting teslamate (1.27.4 and 1.28.2) running. I also installed everything in a separate lxc (in proxmox). I used the following base container:
- teslamate: alpine 3.18
- grafana: from https://tteck.github.io/Proxmox/
- postgres: alpine 3.18

For teslamate i installed the following prerequisites:
```
apk add elixir npm git jq curl bash
apk add --update musl musl-utils musl-locales tzdata
```

My teslamate init script /etc/init.d/teslamate looks like this:
```
#!/sbin/openrc-run

supervisor=supervise-daemon
command_user=teslamate:teslamate
# command_background=1
# Ask process to terminate within 30 seconds, otherwise kill it
retry="SIGTERM/30/SIGKILL/5"
# pidfile="/var/run/teslamate.pid"
directory=/usr/src/teslamate
healthcheck_delay=60
healthcheck_timer=30
# no_new_privs="yes"
#capabilities=cap_net_bind_service
# CAP_NET_BIND_SERVICE
capabilities="^cap_net_bind_service"

: ${teslamate_port:-4000}

# Needs OpenRC >= 0.42
#respawn_max=0
#respawn_delay=5

export TESLAMATEPATH=/usr/src/teslamate

# put teslamate_console=YES in /etc/conf.d/teslamate if you want to be able to
# connect to telamate via an elixir console
if yesno "${teslamate_console}"; then
        command=elixir
        command_args="--name teslamate@127.0.0.1 --erl '-kernel inet_dist_listen_min 9001 inet_dist_listen_max 9001 inet_dist_use_interface {127,0,0,1}' -S mix phx.server"

        start_post() {
                einfo "You can get a console by using this command as telamate's user:"
                einfo "iex --name console@127.0.0.1 --remsh telamate@127.0.0.1"
        }
else
        command=$TESLAMATEPATH/_build/prod/rel/teslamate/bin/teslamate
        command_args="start"
fi

export ENCRYPTION_KEY="use a random key"
export DATABASE_USER="teslamate"
export DATABASE_PASS="teslamate-passwd"
export DATABASE_HOST="db-ip-address"
export DATABASE_NAME="teslamate"
export MQTT_HOST="mqtt-broker-ip-address"
export MQTT_USERNAME="mqtt-user"
export MQTT_PASSWORD="mqtt-passwd"
export MQTT_TLS="false"
export TZ="Europe/Berlin"

export PORT=80

depend() {
        need net
}

healthcheck() {
        # put teslamate_health=YES in /etc/conf.d/telamate if you want healthchecking
        # and make sure you have curl installed
        yesno "$teslamate_health" || return 0

        curl -q "localhost:${telamate_port}/api/teslamate/healthcheck"
}
```
