### ISSUE TITLE
[Feature Request] Provide ghcr as container registry

### ISSUE THREAD

**Issue by cbirkenbeul** [teslamate-org/teslamate#3188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
it would be very nice, if you provide an alternative to the docker hub container registry. Due to many issues in the last weeks and the rate limit where some users will run into.
Thanks.

### Relevant log output

```shell
...
```

### Type of installation

Docker

### Version

v.1.24.1

**Comment by JakobLichterfeld** [comment]
resolved with #3444, #3445, #3479 and finally #3480
