### ISSUE TITLE
docs: Copy to Clipboard button trims leading space

### ISSUE THREAD

**Issue by helmo** [teslamate-org/teslamate#3219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On the https://docs.teslamate.org site you have yaml code examples with a nice 'Copy to clipboard' button.

Nice, but it turned out that it's trimming the leading whitespace on the first line. Which resulted in errors listed below when restarting homeassistant.

E.g. on the https://docs.teslamate.org/docs/integrations/home_assistant#configurationyaml page.

### Expected Behavior

It would be better to not trim those spaces in this case. 

I'm not sure if Docusaurus has support for to configure that, but atleast someone looking for this error in the issues list cat find the not directly obvious but easy solution.

PS: feel free to quickly close this ;)

### Relevant log output

```shell
[homeassistant.util.yaml.loader] mapping values are not allowed here
in "/home/homeassistant/.homeassistant/mqtt_binary_sensor.yaml", line 2, column 15
```

### Type of installation

Docker

### Version

v1.27.2

**Comment by JakobLichterfeld** [comment]
Home Assistant docu was updated in #2704, issue not present anymore, thanks for your reference.
