### ISSUE TITLE
Something Affecting the Map 

### ISSUE THREAD

**Issue by dxfan227** [teslamate-org/teslamate#3227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Went through a software update on my Model 3 2019 SR+. Upon reboot the car had no data connection and for several min showed itself on GPS as in Palo Alto,CA. This got logged into Tesla mate as a crazy 0 second drive of over 400 miles, throwing off all kinds of data.

I utilized the terminal to remove what I thought was the affected drive, the drive is gone, but it still shows up on my map. Then removed 3 charging sessions on that same day to be safe, still shows up. Not really sure what to do from here. ( note the screen shot below was from before I erased the charges on the date)

![Pasted Graphic 1](https://github.com/adriankumpf/teslamate/assets/18082962/be462797-0b46-4985-a55a-989a72b20e31)
![Pasted Graphic 2](https://github.com/adriankumpf/teslamate/assets/18082962/5a5e5d06-d27d-4b02-8625-e3565c00cb25)

### Expected Behavior

Would love to get this random drive/GPS point out of my Teslamate history

### Relevant log output

```shell
Do not have a log available.
```

### Screenshots

![Pasted Graphic 1](https://github.com/adriankumpf/teslamate/assets/18082962/4fa14ae7-a996-4ece-87d0-dc8f4b84ae52)
![Pasted Graphic 2](https://github.com/adriankumpf/teslamate/assets/18082962/d4247b85-03d4-4bd6-a41c-9b2fad469a41)

### Type of installation

Docker

### Version

2023.7.10

**Comment by cwanja** [comment]
Drop entries from the `positions` table.

**Comment by dxfan227** [comment]
> 

Really appreciate the quick reply. I am not too technical to be honest ( just enough to screw things up). Is there documentation on:

1. How to determine which entires are the correct ones?
2. How to "drop" the entry?

**Comment by cwanja** [comment]
First off, take a backup so you have a restore point. 

Then follow the instructions in either of these items #2719 #3074. Both have instructions for how to drop data manually. Not in front of my computer to fully type out the instructions. If neither of those help, post back.

**Comment by gregmcdougall** [comment]
i'm not sure its 100% covered by the two articles above (I think at the least the guidance pages need an update).

You'll need to run some SQL (the pages above, and [here](https://docs.teslamate.org/docs/maintenance/manually_fixing_data) will help).

1. select * from positions where date::date = '2023-03-27' order by latitude;

the Order By will put the errant position entries at the top - note the 'id' from these rows (there may be more than one)

2. delete from positions where id = [id from the table];

repeat as needed

**Comment by tomS3210** [comment]
Hello, 

I try to remove my false Pao Alto Position from Trip in Teslamate.

I have delete a few position but i have this error message for the last one : 

```
teslamate=# delete from positions where id = 9001000;
ERROR:  update or delete on table "positions" violates foreign key constraint "charging_processes_position_id_fkey" on table "charging_processes"
DETAIL:  Key (id)=(9001000) is still referenced from table "charging_processes".
```

What could i do ?

Thanks :-)

**Comment by tomS3210** [comment]
Finally I looked in a backup of the database what was the ID of the line to delete in charging_processes then I deleted it with the command:

`delete from charging_processes where id = 707;`

I was then able to delete the last position:

`delete from positions where id = 9001000;`
