### ISSUE TITLE
"Visited" map has lost visualization after backup and restore on a different machine

### ISSUE THREAD

**Issue by jamietudor** [teslamate-org/teslamate#3230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I moved my Teslamate install from one Docker container on one server to another on another server using the instructions on the site about how to move.

All the data seems to have moved okay - I can see all my old data in the dashboards.

However, the map visualisation on the "Visited" dashboard which shows locations visited on a map has lost all the history. It's only got locations visited since I moved the data.

### Expected Behavior

The map should show a visualisation of all historic data in the database.

### Steps To Reproduce

View "Visited" dashboard: map shows locations visited since install was moved
View "Locations" dashboard: over a year of drive history is present here.

### Relevant log output

```shell
Last part of logs below - unsure if relevant

teslamate_1  | 2023-06-07 15:15:38.478 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/1492932234725963 -> error: "socket closed" (33.956 ms)
teslamate_1  | 2023-06-07 15:15:38.479 [warning] TeslaApi.Error / socket closed
teslamate_1  | 2023-06-07 15:15:38.482 car_id=1 [error] Error / :unknown
teslamate_1  | 2023-06-07 15:15:50.084 [error] Vehicle Error: Vehicle is offline
teslamate_1  | 2023-06-07 15:16:08.668 car_id=1 [info] Start / :offline
teslamate_1  | 2023-06-07 15:16:08.724 car_id=1 [info] Disconnecting ...
teslamate_1  | 2023-06-07 15:28:42.734 [info] GET /
teslamate_1  | 2023-06-07 15:28:42.844 [info] Sent 200 in 110ms
```

### Screenshots

Visited Map:
![visited](https://github.com/adriankumpf/teslamate/assets/33317626/fed09a3b-58c8-4db2-bb78-c6c23f6a19d3)

Example of a few drives from 6 months ago that aren't visualised:

![drives](https://github.com/adriankumpf/teslamate/assets/33317626/f49369b8-184f-4faf-82cb-0253915e2920)

### Additional data

Export of drives table from 2023-01-01 onwards

[drives.csv](https://github.com/adriankumpf/teslamate/files/11679518/drives.csv)

### Type of installation

Docker

### Version

v1.27.2

**Comment by WengHaHa** [comment]
Hello, although I am unable to provide effective assistance on this issue. But I am still very curious about how you moved a container belonging to one server to another server's container.
I attempted to reinstall the container on another server, but I was unable to transfer the data in the Postgres database.
I tried the method in [https://docs.teslamate.org/docs/maintenance/backup_restore/](url) ,but it cannot succeed either.
Sincerely need your solution, much love.

**Comment by jamietudor** [comment]
I followed the document you linked to. I installed the Teslamate container on a new server in the normal way, stopped both the old and the new container, then ran the scripts on that page to backup the database from the old and restore to the new.

Apart from this visualisation issue which I'm experiencing, it worked first time with no issues.

**Comment by kahobusiness** [comment]
Hey, i think i just fixed out this problem.

The method in [https://docs.teslamate.org/docs/maintenance/backup_restore/](https://github.com/teslamate-org/teslamate/issues/url) can't move the data of table `positions` . So we need to move it ourself.

if your original data still exist, please try:

1. Backup `positions` data by : `docker compose exec -T database pg_dump -U teslamate teslamate -t positions -F c > teslamate-positions.dat`
2. Resotre `positions` data to your new container by : `docker compose exec -T database pg_restore -U teslamate -d teslamate -t positions teslamate-positions.dat` (ps. I used pgAdmin to restore the data, and recommand)

**Comment by jamietudor** [comment]
I actually bought a new Tesla so the old data is now gone. Good fix though, very useful if I need to move containers again.

**Comment by JakobLichterfeld** [comment]
> The method in [https://docs.teslamate.org/docs/maintenance/backup_restore/](https://github.com/teslamate-org/teslamate/issues/url) can't move the data of table `positions` . So we need to move it ourself.
> 
> if your original data still exist, please try:
> 
> 1. Backup `positions` data by : `docker compose exec -T database pg_dump -U teslamate teslamate -t positions -F c > teslamate-positions.dat`
> 2. Resotre `positions` data to your new container by : `docker compose exec -T database pg_restore -U teslamate -d teslamate -t positions teslamate-positions.dat` (ps. I used pgAdmin to restore the data, and recommand)

If it's true that the position table is not backed up, we need to look into it. @brianmay @swiffer

**Comment by brianmay** [comment]
The data I get from the pg_dump command in the docs looks OK to me... But not really sure what I should be looking for.

**Comment by JakobLichterfeld** [comment]
Same for me, but my visited dashboard only shows places I visited since my last restore

**Comment by brianmay** [comment]
I just did a full backup and restore to a test database, and to me it looks like all the data is there in the positions table.

Wondering if somehow the car_id changed and got incremented for new data. But that doesn't make sense either, I would expect grafana to display every car.

**Comment by henryhm0** [comment]
I have done back/restore multiple times without any issues.
