### ISSUE TITLE
Support Self-signed Postgres TLS certificates (v1.27.3 regression)

### ISSUE THREAD

**Issue by jeffutter** [teslamate-org/teslamate#3243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As of `v1.27.3` Teslamate won't start as it can't connect to my Postgres database. My Postgres uses self-signed SSL certificates.

I believe this was introduced in [this commit](https://github.com/adriankumpf/teslamate/commit/556e8d518683b60367ef107b662f5e7fe04b1f16) as it changes elixir versions, introducing OTP-26. OTP-26 changed its behavior: 

> In OTP 26, the default value for the verify option is now verify_peer instead of verify_none. Host verification requires trusted CA certificates to be supplied using one of the options cacerts or cacertsfile.

As such, OTP-26 is more strict about self-signed certificates and ecto needs either:

```
config :teslamate, TeslaMate.Repo,
  ssl: true,
  ssl_opts: [verify: :verify_none]
```

or (I think) the following to use 

```
config :teslamate, TeslaMate.Repo,
  ssl: true,
  ssl_opts: [cacerts: :public_key.cacerts_get()]
```

It seems like a iterative solution might be to make the `DATABASE_SSL` environment variable take a 3rd option: `true`, `false`, or `noverify` which would set the first option above.

### Expected Behavior

I expect teslamate to be able to connect to my postgres database.

### Steps To Reproduce

Setup teslamate to point to a postgres database using self-signed SSL certificates

### Relevant log output

```shell
2023-06-12 15:59:55.060 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (DBConnection.ConnectionError) ssl connect: Options (or their values) can not be combined: [{verify,verify_peer}, {cacerts,undefined}] - {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by adriankumpf** [comment]
Hey @jeffutter, can you try out 56a6aa3? You can either supply a certificate via `DATABASE_SSL_CA_CERT_FILE` or set `DATABASE_SSL` to `noverify`.

**Comment by jeffutter** [comment]
@adriankumpf Thanks for jumping on this so quickly.
I don't have a convenient way to build a certain commit and push a docker container to test `56a6aa3`, but I did try the `edge` image with `DATABASE_SSL` set to `noverify` and that seems to work (assuming that branch has otp-26 in it). If I'm wrong about that assumption let me know and I can try to build an image with `56a6aa3` report back with that commit exactly.

Thanks again.

**Comment by simonsmh** [comment]
Hi, I met a similar issue while using remote database with SSL connection. As the instruction [here](https://neon.tech/docs/guides/elixir-ecto#configure-ecto) it requires a custom `server_name_indication`(SNI) field to establish connection successfully. Could it get supported?

**Comment by Dulanic** [comment]
Closed /w https://github.com/teslamate-org/teslamate/commit/5ee078015c744392b14ffa9a7eda0bcc277764a2
