### ISSUE TITLE
Location not showing in "Charge Details" dashboard

### ISSUE THREAD

**Issue by denzel1994** [teslamate-org/teslamate#3293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Within the Charge Details dashboard the location is shown as N/A.
In the Charges dashboard the location is shown correctly.

### Expected Behavior

Location information should be shown correctly on Charge Details dashboard.

### Steps To Reproduce

1. Go to Charges Dashboard
2. Select a charge and click on the date and time
3. Now you are in Charge Details dashboard

### Relevant log output

```shell
No logs needed. It is a settings issue for the dashboard. See second screenshot.
```

### Screenshots

<img width="1641" alt="Bildschirmfoto 2023-07-23 um 21 14 38" src="https://github.com/adriankumpf/teslamate/assets/36551243/9052482e-a078-4f32-9fe7-2ca4773aa452">

Issue can be fixed by changing these two values, but dashboard can not be saved, because it is provisioned.
<img width="393" alt="Bildschirmfoto 2023-07-23 um 21 13 48" src="https://github.com/adriankumpf/teslamate/assets/36551243/0d174d8e-d026-42c2-93a9-88529c986184">

### Type of installation

Docker

### Version

v1.27.3

**Comment by Dulanic** [comment]
Closed /w https://github.com/teslamate-org/teslamate/pull/3294
