### ISSUE TITLE
Geofence MQTT updates are not as frequent as longitude and latitude

### ISSUE THREAD

**Issue by Shasoosh** [teslamate-org/teslamate#3295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Listening to the relevant MQTT events, I can see that longitude and latitude are updated frequently while Geofence takes 10-20 to update. Is this expected behaviour? 

Is it possible that the GeoFence isn't calculated for each update?

### Expected Behavior

I'd expect that the GeoFence event will update as frequent as longitude and latitude.

### Steps To Reproduce

1. Listen to all MQTT events
2. GeoFence will update 10-20 after entering a geofence.

### Relevant log output

```shell
No relevant logs
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by DjAnu** [comment]
Noticed the same behavior, have you found a solution by any chance yet ?
