### ISSUE TITLE
[Feature Request] data per driver profile

### ISSUE THREAD

**Issue by iksior** [teslamate-org/teslamate#3297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, it would be great to see data per driver profile for example if my wife is driving how is her efficiency vs mine etc.

### Relevant log output

```shell
.
```

### Type of installation

Docker

### Version

latest

**Comment by vzhivkov** [comment]
It would be great if possible.

**Comment by JakobLichterfeld** [comment]
As driver profile is not present via API this could not be implemented

**Comment by vzhivkov** [comment]
vehicleData
Now you know how to wake your car, let's take a look at the full set of car data.

const {
  response: {
    id, // don't use this.
    userId,
    vehicleId, // or this
    vin,
    displayName, // TODO: Is this ever different to `vehicleName`?
    optionCodes,
    color,
    accessType, // e.g. "OWNER"  TODO: find out these values.
    tokens, // array of two small strings
    state, // should be "online",
    inService, // boolean,
    idS, // use this instead of `id`
    calendarEnabled, // boolean
    apiVersion, // e.g. 10 ...


This is from https://github.com/davesag/node-tesla-api/blob/develop/README.md

As far as I can see they get userId and I suppose this is what is needed to identify the driver. Are we sure that "As driver profile is not present via API this could not be implemented" ?

**Comment by JakobLichterfeld** [comment]
You are right, there is userid available via API, but as of my knowledge this is not related to selected driver profile on car, but will double check

**Comment by JakobLichterfeld** [comment]
record vehicle data, change driver profile, record again and compare :-)

As authentication for the API got a bit harder since 2 years, my solution with Tasker for quick test is not working reliable atm, but can look into it.

Happy if someone catch the ball and test it.

**Comment by vzhivkov** [comment]
> Record vehicle data, change driver profile, record again and compare :-)
> 
> As the authentication for the API got a bit harder since 2 years, my solution with Tasker for quick test is not working reliable at ATM, but can look into it.
> 
> I would be happy if someone would catch the ball and test it.

Just tell me how to record the vehicle data. I can change the driver profile of the car so the rest is clear but how do I get to see and record the vehicle data?

**Comment by brianmay** [comment]
I would imagine this `UserId` points to the owner of the car - i.e. the user who was full access to the car.

But would be happy to be proven wrong :-)

**Comment by JakobLichterfeld** [comment]
Yeah, that's my understanding as well.

**Comment by cwanja** [comment]
> > Record vehicle data, change driver profile, record again and compare :-)
> > As the authentication for the API got a bit harder since 2 years, my solution with Tasker for quick test is not working reliable at ATM, but can look into it.
> > I would be happy if someone would catch the ball and test it.
> 
> Just tell me how to record the vehicle data, please! I can change the driver profile of the car so the rest is clear but how do I get to see and record the vehicle data? I have a working instance of Teslamate docker version. Is there a log of the data that Teslamate recieves from the API or I should somehow view it live?

Probably the least efficient way to do it, but: 
1. Start the car, select a profile (and note which one), leave the door ajar and go back a terminal and make a pull request to `vehicle_data` and store data.
2. Go back to said car, change profiles, leave door ajar, re-pull vehicle data and store data.
3. Close car door
4. Compare data.

There is probably a way to do this live. But I am not a software developer 😊

**Comment by vzhivkov** [comment]
> > > Record vehicle data, change driver profile, record again and compare :-)
> > > As the authentication for the API got a bit harder since 2 years, my solution with Tasker for quick test is not working reliable at ATM, but can look into it.
> > > I would be happy if someone would catch the ball and test it.
> > 
> > 
> > Just tell me how to record the vehicle data, please! I can change the driver profile of the car so the rest is clear but how do I get to see and record the vehicle data? I have a working instance of Teslamate docker version. Is there a log of the data that Teslamate recieves from the API or I should somehow view it live?
> 
> Probably the least efficient way to do it, but:
> 
> 1. Start the car, select a profile (and note which one), leave the door ajar and go back a terminal and make a pull request to `vehicle_data` and store data.
> 2. Go back to said car, change profiles, leave door ajar, re-pull vehicle data and store data.
> 3. Compare data.
> 
> Do not forget to close your door 😉 There is probably a way to do this live. But I am not a software developer 😊

My question was how to make that pull of the data. The rest is obvious.

**Comment by vzhivkov** [comment]
OK. I thought that there is some Teslamate log or command to make that API call since it has my tokens anyway. Will try to check this tomorrow.

**Comment by brianmay** [comment]
A teslamate log would be very useful I think. Currently there isn't one. On my todo list, but there are higher priority things.

**Comment by vzhivkov** [comment]
So the bad news is that user_id does indeed shows the owner of the car so it can't be used. However since we all know that most of people use their phones to unlock the car and to drive it and also this is the most common way to chose the driver profile (I don't expect much people to change manually driver profiles) I found this in the response:

"media_info":{"a2dp_source_name":"MYPHONENAME","audio_volume":....

So would it be some kind of solution to have that variable media_info->a2dp_source_name (MYPHONENAME is my phone's bluetooth name) as some additional data to each drive so we can later see statistics. It is not definetly definitive for the current driver but in major cases I think whoever is connected through bluetooth is the one that has unlocked and probably driving the car. If the column is not called "driver profile" but "connected BLE device" I think it will be pretty clear and whoever uses it for statistics will have it in mind based on how he/she/they are using the car.

**Comment by cwanja** [comment]
You _could_ add it, but it's unreliable and not definitively tied to someone. I grab my spouses phone and drive. They grab mine. I lost my phone. Etc. 

If Tesla ever adds the driver profile, I think it could be added. But it would also only be the drives from the date it's implemented in TeslaMate as there's no historical data either.

My opinion - this is closed as not possible (yet).

**Comment by vzhivkov** [comment]
Yes, it's not fully reliable but definetly don't think you would grab your wife's phone very often. And if that happens I might as well not switch the driver profile so even if Tesla provides it might not be any better than this for the same reasons. Anyway it's your call obviously.  However I don't see how a little more data would do any harm to anyone. Besides Tesla won't upgrade this API for sure so I think it's better to have somethinh not fully reliable than nothing. But as I said it's not up to me to decide.

**Comment by brianmay** [comment]
It is my suspicion that field is only going to be populated when the car is playing music from Bluetooth. i.e. if the car is configured to play from Spotify or Tunable, this field may not exist. Verifying this is on my todo list.

In our house hold, it is common for multiple drivers to be in the car as the same time, in which case the Bluetooth connection to the car does not accurately reflect the driver, and the driver profile is likely to be wrong also. Depends on your use case I guess. But remember that value probably comes from the Mobile phone name, which can be set to anything the owner wants.

Having said that, if we could stream the now_playing_stuff_* from Mqtt, that could have some interesting applications. Just not accurately determining the driver.

For some applications it may be better approach to try to track the car from the mobile phone using something like Tasker or Home Assistant. Not done this myself, just heard it is possible.

**Comment by vzhivkov** [comment]
No, it is connected when the driver reaches the car. The car is unlocked through bluetooth of the phone and can be turned to Drive if bluetooth of phone added as key is connected. So it doesn't matter if youbare playing music over bluetooth or not. If 2 drivers reach the car Tesla will connect to the main driver's phone and will turn on his/hers profile. To track the car from Tasler would be useful for 1 driver which doesn't help here. If a car is being drived by 3 or 4 people use Tasker on all of their phones??? And combine the data of those phones how? Just adding a column connectedBLE in the DB won't be any problem I think and anyone will be free to use it or not.

**Comment by wooter** [comment]
Don't leave out the people using keyfobs. I carry my phone, a keyfob and the RFID key as a backup. I have no clue if the keyfob or my phone makes the first connection.

And then you have the scenario of having 2 Tesla's in one household, where both drivers use one Tesla, and it is a bit of a hit or miss on which phone or keyfob connects first.

In the end it seems very unreliable if you have more than one phone, which is kind of the killer of the feature you're looking for: making statistics of multiple driver profiles.
