### ISSUE TITLE
Charges - No Data

### ISSUE THREAD

**Issue by ebretteville** [teslamate-org/teslamate#3306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hye,

I no longer have charges history since 17/02/2023. I checked this last charge and it seems to be stopped pproperly. I also tried the help that I found here: https://docs.teslamate.org/docs/maintenance/manually_fixing_data/#terminate-a-drive-or-charge

And I get this error: `teslamate "docker 'compose' is not a docker command"`

What can I do to solve my issue? The charges can be seen in charges details but not in the charges dashboard, see attached screenshots (same time period):

I opened also a discussion without solution: [https://github.com/adriankumpf/teslamate/discussions/3275](https://github.com/adriankumpf/teslamate/discussions/3275)

### Expected Behavior

All charges are recorded

### Steps To Reproduce

Go to the charges dashboard and see charges

### Relevant log output

```shell
teslamate@TeslaMate:~/teslamate$ docker-compose exec teslamate bin/teslamate rpc \ "TeslaMate.Repo.get(TeslaMate.Log.ChargingProcess, 1220) |> TeslaMate.Log.complete_charging_process()" ** (Postgrex.Error) ERROR 57014 (query_canceled) canceling statement due to user request lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1 lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6 lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4 lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3 lib/ecto/repo/queryable.ex:151: [Ecto.Repo.Queryable.one/3](http://ecto.repo.queryable.one/3) lib/teslamate/log.ex:438: TeslaMate.Log.complete_charging_process/1 nofile:1: (file) teslamate@TeslaMate:~/teslamate$
```

### Screenshots

![250829728-04b3a19c-4dfe-4993-982d-d1df7652f851](https://github.com/adriankumpf/teslamate/assets/3687099/58c29608-f2f3-4192-9f9d-5a8e2123ecd8)
![250831486-1916082c-8a8d-4b58-a7fb-7c8836f18afd](https://github.com/adriankumpf/teslamate/assets/3687099/246e5037-8b6e-4e98-b551-0041169a7477)
![250829735-b5042f46-e11d-44c3-97e2-9ea3d6401673](https://github.com/adriankumpf/teslamate/assets/3687099/6435ad15-1cdf-46b7-9450-11ce9bb97dc1)

### Type of installation

Docker

### Version

v1.27.3

**Comment by JakobLichterfeld** [comment]
Make sure to have mobile data connection. To fix your data follow https://docs.teslamate.org/docs/maintenance/manually_fixing_data for drive and charge. But in your case it seems like there was no mobile connection and therefore no data was streamed by your car
