### ISSUE TITLE
Docker install guidelines

### ISSUE THREAD

**Issue by ststa** [teslamate-org/teslamate#3320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi Adrian, 
thanks for providing a good description how to install teslamate on docker. I have two things to change, what might be helpful for other users:

1) the right command is: docker-compose up -d

2) In the yml says `DATABASE_PASS= #insert your secure database password!`. I considered a problem, when there was a space before the password. In this case teslamate works, but grafana won't log in. So please put a hint about that.

Thanks, Stefan

### Steps To Reproduce

put "DATABASE_PASS= password" instead of "DATABASE_PASS=password" in yml file.

### Relevant log output

```shell
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2023-08-19T09:23:33.99+0000 lvl=eror msg="Query data error" error="failed to query data: invalid option: password" remote_addr=192.168.187.51 traceID=00000000000000000000000000000000
```

### Type of installation

Docker

### Version

latest

**Comment by BluSpanner** [comment]
1. `docker-compose`is the new`docker compose`
See https://docs.docker.com/compose/migrate/ for details on how to upgrade to Compose v2.
