### ISSUE TITLE
TeslaFi mport - filename sensitivity, then when worked around, does not import

### ISSUE THREAD

**Issue by dblacknc** [teslamate-org/teslamate#3337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Fresh docker install on Ubuntu 22.04 updated.  I exported a couple monthly CSV files from TeslaFi and the names pushed/saved were 82023.csv and 92023.csv.   It seemed like Teslamate ignored them (didn't go into import mode).   I noticed examples were prepended with "TeslaFi."  I added that string to the names and then they were recognized in import mode.

When I click to import them, the spinner beside each file runs for perhaps 20 seconds, then disappears.  I see beam.smp process busy for a bit, then it goes back to the way it was - no checkmark, nothing.  The data was not imported, nor have I been able to find any reason/logs yet, even looking inside the teslamate container.  (Hopefully I missed a log.)

### Expected Behavior

1. Import any .csv file, and preferably not have to prepend TeslaFi to it.  If this is necessary to distinguish from another format then this expectation can be disregarded.

2. Have the import work :-)

### Steps To Reproduce

1. Export monthly file(s) from TeslaFi
2. Restart the teslamate container
3. In import mode, set the time zone and click import

-it goes back to the initial state after 20 sec or so-

4. Remove the files from the import subdirectory, start teslamate container again and the data is not there.

### Relevant log output

```shell
Ah ha - now I see how to get the logs.  I'll do that now and update this report.
BTW the command here and in the installation instructions is "docker-compose" not "docker compose"

The only even remotely relevant factor I can think of, is in TeslaFi and initially when I installed Teslamate and attached to my Tesla account, is my car had an emoji at the end of the name - a palm tree.  It appeared as several question marks following the name in Teslamate, and on TeslaFi and the Tesla app looks like the expected palm tree.

Notably, in the exported .csv files the car's name had just the ASCII characters, and without the appended emoji.  (It's "Tessie")
There are no other special characters.   I changed the car's name in the Tesla app to remove the emoji and that's now reflected both in TeslaFi as well as Teslamate, and matches the .csv files.

Even with all this, the import behaves just as it initially did.  Did having that emoji to start with perhaps break something in Teslamate?  It is otherwise normally working.
```

### Type of installation

Docker

### Version

v1.27.1

**Comment by dblacknc** [comment]
Here's pertinent log output:

teslamate_1  | 2023-09-07 15:01:35.256 [info] GET /import
teslamate_1  | 2023-09-07 15:01:35.283 [info] Sent 200 in 26ms
teslamate_1  | 2023-09-07 15:01:46.678 [info] Importing 2 file(s) ...
teslamate_1  | 2023-09-07 15:01:52.672 [error] GenStateMachine TeslaMate.Import terminating
teslamate_1  | ** (RuntimeError) vehicle data is incomplete
teslamate_1  |     (teslamate 1.27.3) lib/teslamate/import.ex:274: TeslaMate.Import.create_car/1
teslamate_1  |     (teslamate 1.27.3) lib/teslamate/import.ex:128: TeslaMate.Import.handle_event/4
teslamate_1  |     (stdlib 5.0.1) gen_statem.erl:1379: :gen_statem.loop_state_callback/11
teslamate_1  |     (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

**Comment by dblacknc** [comment]
The import failure is a dupe of #3158.  I'll leave this open at least for comment on the filename behavior.

**Comment by brad628** [comment]
I'm having this issue as well. Same symptoms. Can't import even after updating file name to append "TeslaFi". The green import button momentarily flashes, but then nothing. No other indicator of any kind.

**Comment by wisdomus** [comment]
The TeslaFi import issues are the one big thing preventing me from moving from one of the other (hosted / SaaS) solutions to Teslamate. I finally got the TeslaFi import to 'work' by doing 3 things: 1- adding a vehicle_id, 2- adding a display_name, 3-  changing the date format to m/d/yyyy hh:mm (instead of h:mm), but after all this and the import "working", it only imported 1 day. Every subsequent import results in no error messages but also no further data import. Other services (like Tessie, for example) import the same data from TeslaFi without any issue whatsoever -- full data set works with TeslaFi data onto Tessie! So strange! Has anyone else noticed this issue? Any suggestions for a fix?
