### ISSUE TITLE
No TelsaMate logs in Docker Desktop, receiving invalid character error

### ISSUE THREAD

**Issue by brad628** [teslamate-org/teslamate#3346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My TeslaMate logs have stopped about 7 days ago, and I have the following error:

`error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value`

Assuming I need to remove the offending characters from the log, but I don't know where they are, can't find them.

### Expected Behavior

Logs are viewable

### Steps To Reproduce

1. Open Docker
2. View TeslaMate-1 Logs

### Relevant log output

```shell
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```

### Type of installation

Docker

### Version

1.27.3

**Comment by John-Bronson** [comment]
I found this because I'm getting the same error in an app I'm working on. I'm pretty sure mongo is logging the character causing this issue. Hope that is of some help to yall
