### ISSUE TITLE
Homeassistant integration does not work with tesla: integration enabled in configuration.yaml

### ISSUE THREAD

**Issue by codedesperate** [teslamate-org/teslamate#3349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When following the home assistant integration guide to the letter, I get the following error upon reloading the yaml files:
```
Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: tesla - Integration 'tesla' not found.
```
The official Tesla integration no longer exists, and I wonder if the instructions are just outdated? When ucommenting out the entire "tesla:" block, it seems to work fine. 

I do use the HACS Tesla Custom integration. 

So, is commenting out the "tesla:" block the right thing to do, and the guide just needs to be updated to not include that? 

### Expected Behavior

Be able to follow the home assistant integration guide, and not get a broken configuration that home assistant won't load. 

https://docs.teslamate.org/docs/integrations/home_assistant/

### Steps To Reproduce

1: Follow the guide: https://docs.teslamate.org/docs/integrations/home_assistant/
2: Reloading config in home assistant will throw the error, and it's won't reload

### Relevant log output

```shell
No error output. 
Error output when reloading home assistant:
Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: tesla - Integration 'tesla' not found.
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by codedesperate** [comment]
To anyone having the same issue as me. What I ended up doing, was to undo everything I did in the guide: "https://docs.teslamate.org/docs/integrations/home_assistant/" and instead you the HACS Tesla Custom integration, and then used there guide to update their values using teslamate: "https://github.com/alandtse/tesla/wiki/Teslamate-MQTT-Integration"

**Comment by pihomeserver** [comment]
@codedesperate seems that documentation has been updated because i've just tried the configuration steps and it works (except few sensors and i have to debug)

**Comment by codedesperate** [comment]
@pihomeserver that's great to hear! But I actually quite enjoy usign the HACS Tesla integrations, and just updating its values from teslamate. Then I don't have multiple sensors showing the same thing. And you need the Tesla integration anyways if you need to send commands to the car from Home Assistant.
