### ISSUE TITLE
efficiency calculation just for charges below 95%

### ISSUE THREAD

**Issue by ulrichc580** [teslamate-org/teslamate#3359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Thanks for the great work with Teslamate!

I am wondering why my efficiency in the "Overview" was not updated (efficiency is still empty in table cars) although I charged the battery of my MYSR  six times. 
Additionally I am wondering why "Efficiency" dashboard in Grafana is not showing any "Derived ideal efficiencies" and "Derived rated efficiencies". 

Then I checked the SQL behind "Derived ideal efficiencies" and assume I found the reason also for the not stored efficiency in cars table: I am always charging to 100% but the SQL is limited to "end_battery_level <= 95".

Why is it this limit? For the new MY with BYD battery they are suggesting to charge up to 100%.

### Expected Behavior

neither in the Grafana SQL nor in any other SQL there should be a limited "end_battery_level".

### Relevant log output

```shell
teslamate-teslamate-1  | 2023-10-05 18:10:29.162 [info] Migrations already up
teslamate-teslamate-1  | 2023-10-05 18:10:34.150 [info] System Info: Erlang/OTP 26 (jit)
teslamate-teslamate-1  | 2023-10-05 18:10:34.150 [info] Version: 1.27.3
teslamate-teslamate-1  | 2023-10-05 18:10:34.864 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (608.028 ms)
teslamate-teslamate-1  | 2023-10-05 18:10:34.864 [info] Refreshed api tokens
teslamate-teslamate-1  | 2023-10-05 18:10:34.878 [info] Scheduling token refresh in 6 h
teslamate-teslamate-1  | 2023-10-05 18:10:34.884 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-teslamate-1  | 2023-10-05 18:10:34.886 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate-teslamate-1  | 2023-10-05 18:10:35.085 [info] Starting logger for 'Warp'
teslamate-teslamate-1  | 2023-10-05 18:10:35.107 [info] MQTT connection has been established
teslamate-teslamate-1  | 2023-10-05 18:10:35.199 car_id=1 [info] Start / :asleep
teslamate-teslamate-1  | 2023-10-05 18:10:37.788 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 28 Mar 2023 20:25:39 GMT.
teslamate-teslamate-1  | 2023-10-05 18:10:40.799 [info] Tzdata has updated the release from 2021e to 2023c
teslamate-teslamate-1  | 2023-10-05 19:07:13.866 [info] GET /
teslamate-teslamate-1  | 2023-10-05 19:07:13.935 [info] Sent 200 in 68ms
teslamate-teslamate-1  | 2023-10-05 19:07:18.828 [info] GET /settings
teslamate-teslamate-1  | 2023-10-05 19:07:18.879 [info] Sent 200 in 50ms
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by JakobLichterfeld** [comment]
Please follow #3524
