### ISSUE TITLE
Unknown Speed

### ISSUE THREAD

**Issue by vaughnlfisher** [teslamate-org/teslamate#3378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My Home assistant instance/mqtt server is not getting through any speed information although everything else is working perfectly.
![Screenshot 2023-10-25 141027](https://github.com/adriankumpf/teslamate/assets/45875201/308b8b4b-8843-4b96-bd6d-503afcbfad77)

### Expected Behavior

I expect the speed to be reported!

### Relevant log output

```shell
No Logs see screen shot
```

### Type of installation

Docker

### Version

v1.27.3

**Comment by Dulanic** [comment]
MQTT only provides the values at the time it is available from API. Since it is charging, there will be no speed.
