### ISSUE TITLE
No updates for over a week after vehicle firmware update (model 3, 2023.38.3)

### ISSUE THREAD

**Issue by Tigwin** [teslamate-org/teslamate#3393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

No updates from the vehicle in over a week. Status page says:

Status | asleep for 1 wk, 2 d

(I drive the car daily).

The charts show last update on 10/26: https://i.imgur.com/Z6KsvGA.png

I ran a teslamate update (v1.27.3), and I also clicked on Settings > Sign out, and generated a new auth key (using tesla_auth.exe) and still no updates are seen. 

Last software update was on 10/26 (the same day updates quit occuring):  [2023.38.4](https://www.notateslaapp.com/software-updates/version/2023.38.4/release-notes).

The Tesla app shows the vehicle is still on 2023.38.4.

### Expected Behavior

Updates to show the system tracking the vehicle

### Relevant log output

```shell
log included below as a screenshot 
(can't cut and paste from my docker container)
```

### Screenshots

![image](https://github.com/adriankumpf/teslamate/assets/8354498/cd88cbb7-fbae-4853-8486-ada35e491362)

### Type of installation

Docker

### Version

1.27.3

**Comment by Tigwin** [comment]
software update was done at 10/26/2023, 05:26:38 PM. Immediately after the software update, no data has since come in about the vehicle:

![image](https://github.com/adriankumpf/teslamate/assets/8354498/7d6c6898-7740-4338-ab68-939f0617db5c)

**Comment by cwanja** [comment]
See #3371, #3370, #3383 and #3386. A "fix" is in #3370 and we are waiting to see if @adriankumpf pushes a formal fix to the TeslaMate.

**Comment by tesla2021a** [comment]
The unofficial fixes didn't work for me either, running Teslamate 1.27.3 on a RaspberryPie with Raspbian GNU/Linux 11 (bullseye).

**Comment by arnault38** [comment]
Same problem on Tesla Model S, the state on main page of teslamate is unavailable. The issue occured on the last Tesla Update on 2023.38.4 and the GPS notification on the main screen...I hope that an update can be proposed soon, as the data that hasn't been recovered is currently being lost!

**Comment by SebastianGode** [comment]
@tesla2021a @nsaunders36 @arnault38 
You all have tried switching your docker image from `teslamate/teslamate:latest` to `jsightler/teslamate:20231029`?
This should work fine.

**Comment by tesla2021a** [comment]
Not on a Raspberry Pi. It's missing their corresponding 32 bits and 64 bits images.

**Comment by cwanja** [comment]
> Not on a **Raspberry Pi**. It's missing their corresponding 32 bits and 64 bits images.

**That** will not bode well for me when I get the .38 branch.

**Comment by Tazmanian79** [comment]
> @tesla2021a @nsaunders36 @arnault38 You all have tried switching your docker image from `teslamate/teslamate:latest` to `jsightler/teslamate:20231029`? This should work fine.

Any guide how to do that?
I have docker on a Synology NAS.  Can use Docker Container or Portainer

**Comment by nsaunders36** [comment]
> @tesla2021a @nsaunders36 @arnault38 You all have tried switching your docker image from `teslamate/teslamate:latest` to `jsightler/teslamate:20231029`? This should work fine.

I have just retried using it and it is now working.

**Comment by heikkis** [comment]
Hello! jsightler/teslamate:20231029 image is seems to be "random" image from internet to install. No Github repository connected to Docker hub etc. Sorry, skip for me.

**Comment by SebastianGode** [comment]
The image is from this PR: https://github.com/adriankumpf/teslamate/pull/3373

**Comment by cbrandlehner** [comment]
Same issue here with Tesla Model S. Updated to 2023.38.4 today in the morning and ran into this problem.

**Comment by jonathanmusto** [comment]
Paging our saviour @adriankumpf.......when do you think we can get an official release, Adrian?

To be honest, I think i'll hold off on updating my car, as I get far more value out of TeslaMate than I do from these software updates that Tesla provide for the car.

**Comment by tesla2021a** [comment]
Good idea to hold off, too late for me though. And I was happy I was early in the update process for once lol. Hopefully this issue in Teslamate will be fixed before the Christmas update lands...

**Comment by cwanja** [comment]
> Good idea to hold off, too late for me though. And I was happy I was early in the update process for once lol. Hopefully this issue in Teslamate will be fixed before the Christmas update lands...

Over in #3381 it seems later branches of 38 are not impacted 🤷🏻‍♂️ so it's not clear if a long term fix is needed. Regardless, it seems the API is transitioning.

**Comment by tesla2021a** [comment]
Which firmware is later than 2023.38.6? That's what I have and no drives or charges were recorded with the official teslamate installation.

**Comment by cwanja** [comment]
> Which firmware is later than 2023.38.6? That's what I have and no drives or charges were recorded with the official teslamate installation.

They are on 38.6 and reporting no issues.

**Comment by tesla2021a** [comment]
Tesla might have reinstated the original API format. I still have my previous Micro SD card with the old teslamate installation. I'll plug it in tomorrow and see if it's functional again.

**Comment by incogizmo** [comment]
I just updated from 2023.32.9 to 2023.38.6 and I immediately stopped receiving data from the car.

**Comment by tesla2021a** [comment]
1281 cars waiting to download 2023.38.6 this morning on Teslafi. First big push of the 2023.38.x firmware. It's about to get busy here lol.

**Comment by Pretagonist** [comment]
This helped with connection issues i were having on my new install with a Model Y as well. I'm not sure if everything is working but at least my logs aren't filling up with errors and I get data in my Grafana Dashboards.

I'm on 2023.38.6

**Comment by xbeaudouin** [comment]
Same issues with 2023.38.6 on Model 3 LR AWD and Model 3 SR+ on my side.

**Comment by fnguy** [comment]
This is working for me.

https://github.com/adriankumpf/teslamate/issues/3371#issuecomment-1805220152

**Comment by PalleRaa** [comment]
Same issue for me. Just updated to 2023.38.6 an car now seems unavailable in TeslaMate

**Comment by bodosom** [comment]
I've also switched to the jsightler fork and it's working with 38.6.

**Comment by SiNaPsEr0x** [comment]
> This is working for me.
> 
> 
> 
> https://github.com/adriankumpf/teslamate/issues/3371#issuecomment-1805220152
> 
> 
> 
> https://github.com/teslamate-fork/teslamate-fork#installation-of-the-fork-with-the-fix-for-tesla-fw-2023381

Thanks working good

**Comment by ykii** [comment]
Same issue here. Jsight fork works though. Thanks!

**Comment by Yonno13** [comment]
> Same issue for me. Just updated to 2023.38.6 an car now seems unavailable in TeslaMate

I'm back up and running after changing the image to teslamate-fork as described in this thread - is this a permanent fix or will I be able to revert to 'latest'?

Running on Docker/Containter on Synology 718+.

**Comment by idjul** [comment]
> Same issue here. Jsight fork works though. Thanks!

Same here! Thanks!

**Comment by graeme-gussey** [comment]
Changed image to teslamate-fork as described in this thread and has fixed the issue described. I do note that the grafana dashboard no longer shows the vehicle temperatures on the overview dashboard. Does still work via mqtt though. Wondering if anyone else seeing this?

**Comment by Dellonb** [comment]
The same issue here with TM3/2021, 2 days ago updated from 2023.32.9 to 2023.38.6  and ran into this problem.
Since the update no more date logged.
Running on docker with latest release 1.27.3. 
As i am running HomeLab migration I have two instances of TeslaMate now running in parallel Proxmox/Debian/Docker/TeslaMate and RP4B Docker/TeslaMate and both experience the same issue after updating to 2023.38.6.

**Comment by Dellonb** [comment]
> This is working for me.
> 
> [#3371 (comment)](https://github.com/teslamate-org/teslamate/issues/3371#issuecomment-1805220152)
> 
> https://github.com/teslamate-fork/teslamate-fork#installation-of-the-fork-with-the-fix-for-tesla-fw-2023381

also worked for me

**Comment by Hofyyy** [comment]
me too

**Comment by MattJeanes** [comment]
Hey everyone, @adriankumpf has released a new version to fix this now so reverting back to `teslamate/teslamate:latest` should solve it.

Note that they have now stopped development on this project which is why it has been moved to a new GitHub organisation @teslamate-org so others can join and maintain it going forward.

See their response here: https://github.com/teslamate-org/teslamate/discussions/3384#discussioncomment-7546999

I just want to give a massive personal thank you to Adrian for all your hard work, this is a fantastic project and a great self-hosted alternative to the paid options out there and your efforts are appreciated by many.

**Comment by Tigwin** [comment]
Is it working for anyone else? I did an update and now I don't see any vehicle stats:

<img width="763" alt="image" src="https://github.com/teslamate-org/teslamate/assets/8354498/54a05a87-ebfb-4254-9ace-ed4852d065d8">

I also tried logging out and obtaining new api key, same result.

**Comment by MattJeanes** [comment]
@Tigwin make sure that if you're using :latest that you actually have the latest image, you can set it explicitly to :1.27.4 or use `docker-compose pull  && docker-compose up -d` to pull the latest image.

**Comment by Tigwin** [comment]
> @Tigwin make sure that if you're using :latest that you actually have the latest image, you can set it explicitly to :1.27.4 or use `docker-compose pull && docker-compose up -d` to pull the latest image.

I use :latest, I just updated again and now it's working. Maybe I did it too early, or maybe it takes a bit to start working again. Thanks!

**Comment by Dulanic** [comment]
Fixed with 1.27.4

**Comment by arnault38** [comment]
> @tesla2021a @nsaunders36 @arnault38 You all have tried switching your docker image from `teslamate/teslamate:latest` to `jsightler/teslamate:20231029`? This should work fine.

Yes it's working on my Synology NAS with docker ! Waiting for the official release ;)

**Comment by Tigwin** [comment]
> @Tigwin make sure that if you're using :latest that you actually have the latest image, you can set it explicitly to :1.27.4 or use `docker-compose pull && docker-compose up -d` to pull the latest image.


It was working and now its back to this:

<img width="798" alt="image" src="https://github.com/teslamate-org/teslamate/assets/8354498/f7729a64-c696-43df-8b19-397b0f6baa6a">

Anyone else seeing this issue?

**Comment by Tigwin** [comment]
...and its back. 

<img width="321" alt="image" src="https://github.com/teslamate-org/teslamate/assets/8354498/3bc3afd6-1f7d-47f3-8151-1fe3d4496d48">

weird...

**Comment by Abcmsaj** [comment]
Hmm... I've still got the issue and I'm on latest. No updates in a week, since I updated. I actually moved my Teslamate instance from my Raspberry Pi to a Mac Mini and restored the DB backup 10 mins ago... All my historical data is there and my car displays on port 4000, but isn't updating.

**Comment by edlevin6612** [comment]
Upgrading postgres to 15 fixed it for me as well. I forgot to update `docker-compose.yaml` to latest when upgrading Teslamate so missed the postgres v14->15 bump. Followed [instructions](https://docs.teslamate.org/docs/maintenance/upgrading_postgres) to upgrade DB.

**Comment by passerby2024** [comment]
> > @Tigwin make sure that if you're using :latest that you actually have the latest image, you can set it explicitly to :1.27.4 or use `docker-compose pull && docker-compose up -d` to pull the latest image.
> 
> It was working and now its back to this:
> 
> <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/8354498/282506511-f7729a64-c696-43df-8b19-397b0f6baa6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTA3NzQsIm5iZiI6MTcwMjQ1MDQ3NCwicGF0aCI6Ii84MzU0NDk4LzI4MjUwNjUxMS1mNzcyOWE2NC1jNjk2LTQzZGYtOGIxOS0zOTdiMGY2YmFhNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDY1NDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjkwYWYxNDgyNjg0NTkyNDE1ZWJiMDc0NTllNzRjNWNmOWZmYTA1NGJlOWM3ODUwYzI3NjQ3ZjU1YzVjM2Q1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lNKy5qahK9K4URSz0CgIdRdd1_Igz8wkpcosS0obLlU">
> Anyone else seeing this issue?

I'm having this issue even after 1.28.2 update.  Have you found a solution to this?

**Comment by chiro79** [comment]
I had the same issue: almost one month without any data gathered. I tried everything, updating, etc... but then I tried to wake the car using the official Tesla app in my mobile device and... Teslamate got working again. Just if this may help anyone.
