### ISSUE TITLE
Is this dead? Pressing issues and PRs remain unapproved or unreviewed for months.

### ISSUE THREAD

**Issue by markusdd** [teslamate-org/teslamate#3399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a list of huge problems that affect a lot of people where the community has spent hours, days and months to debug and work around them, but many of these issues have not seens responses from @adriankumpf for months, even when tagging him and asking specific questions.
The last release is half a year old.

This might seem offensive or rude, but I have to ask the maintainer-question regarding this project.
Is there a second person who could take care about the codebase? Everyone deserves a break or has personal circumstances to deal with, but this project is used by so many people that we cannot just let it rot.

I personally am running on a completely hacked install because of the wakelock issue on MCU2-retrofit cars which has a huge investigation ticket and PR behind it, but nothing is happening.

Now there is the issue with certain cars not getting data at all after a recent update. More than 100 comments, nothing from maintainer.

How do we deal with this? Fork? Has someone a personal contact to Adrian?
We should not let this great project slide, but currently it is rotting away because of foundational issues.

### Relevant log output

```shell
none
```

### Type of installation

Manual

### Version

v1.24.1

**Comment by bmerciergallay** [comment]
you can indeed make a fork
the best maintained fork will be the most used in the end

**Comment by markusdd** [comment]
I certainly cannot make a fork. I investigated the MCU2 retrofit issue and noticed that this codebase is completely unmaintainable for me. I am a hardware negineer and can deal with some C/C++ and Python, but Elixir is beyond my comprehension. I just do not understand the code.

Also, I think forking with the intent to pull users away is a hostile action and I think we should first see if the maintainer base can be extended here. I can certainly try to keep testing and provide input, but I am just not qualified to be a maintainer her due to the choice of language.

**Comment by NickWhitNTES** [comment]
> I certainly cannot make a fork. I investigated the MCU2 retrofit issue and noticed that this codebase is completely unmaintainable for me. I am a hardware engineer and can deal with some C/C++ and Python, but Elixir is beyond my comprehension. I just do not understand the code.
> 
> Also, I think forking with the intent to pull users away is a hostile action and I think we should first see if the maintainer base can be extended here. I can certainly try to keep testing and provide input, but I am just not qualified to be a maintainer her due to the choice of language.

Completely agree with this statement, but something needs to be done soon - one way or the other.

**Comment by cwanja** [comment]
> Also, I think forking with the intent to pull users away is a hostile action

No one is trying to take users away from here. But with the uncertainty of future development from @adriankumpf and individuals willingness to fix a current API issue to get the application working, that is why forks were introduced. If Adrian came back and updated the core repo, the forks could (and should) be shut down.

**Comment by jlestel** [comment]
given the lack of response for several months from adrian, I created the fork: https://github.com/MyTeslaMate/teslamate

I retrieved all the PRs in this repo and the CI works: https://github.com/MyTeslaMate/teslamate/pulls

I integrated the fix of @swiffer

If there are people who want to help me bring the project to life, they are welcome!

**Comment by swiffer** [comment]
@jlestel  - @JakobLichterfeld published teslamatefork - would be great to see joined effort. I'll be happy to support on the Grafana / SQL side of things. no experience working with elixir / phoenix.

@jlestel - #3382 seems to be another great candidate to merge ;)

**Comment by swiffer** [comment]
I've updated my PR (#3398) - @jlestel - merge if wanted ;)

**Comment by markusdd** [comment]
greatly appreciate the effort guys!

Another major thing that needs addressing is this: https://github.com/adriankumpf/teslamate/pull/3262

This essentially fixes (or attempts to fix) the wakelock issue experienced on MCU2 cars, but it also should improve waking behavior in general. if anyone wishes to work with @micves to review this and bring it to mainline that would be great.
The relating ticket is linked in the PR, it has almost a hudnred comments from the investigation we did over months.

**Comment by NickWhitNTES** [comment]
> @jlestel - @JakobLichterfeld published teslamatefork - would be great to see joined effort. I'll be happy to support on the Grafana / SQL side of things. no experience working with elixir / phoenix.
> 
> @jlestel - #3382 seems to be another great candidate to merge ;)

As a user, may I ask which is the one we should use.  I see teslamatefork and also the new myteslamate which has merged in thst fix also.   

So.  As a user, it's confusing to figure out where to point to.  Advice welcome 😁

**Comment by markusdd** [comment]
I think this is all VERY fresh. Give the guys a few days to figure out the way forward,
Maybe also Adrian jumps in and makes a recommendation.

**Comment by cicob** [comment]
Good work there! Thanks!
I don't have the overview, is this PR included in your fork-effort above?
https://github.com/adriankumpf/teslamate/pull/3373

**Comment by DrMichael** [comment]
> @jlestel - @JakobLichterfeld published teslamatefork - would be great to see joined effort. I'll be happy to support on the Grafana / SQL side of things. no experience working with elixir / phoenix.

Please agree on one fork. I am happy to help  with minor Grafana/SQL issues...

**Comment by cicob** [comment]
I think the time is ripe, the momentum is there. Several ppl in this thread alone have offered to start chipping in some work, merging PRs, etc. And as is already stated previously; if @adriankumpf comes back, the fork will fade out, and by then have served its purpose.

@markusdd I think you automatically have the momentum and the lead here, since you started the thread. I too believe everyone here would love ONE fork, here and now. Go for it!

**Comment by markusdd** [comment]
I think @JakobLichterfeld and @jlestel are much better suited for this.

As elobarted above I lack the necessary skills to maintain this project properly.

**Comment by NickWhitNTES** [comment]
Purely from a user perspective.   The name MyTeslamate makes far more sense.  👍

**Comment by jlestel** [comment]
> @jlestel - @JakobLichterfeld published teslamatefork - would be great to see joined effort. I'll be happy to support on the Grafana / SQL side of things. no experience working with elixir / phoenix.
> 
> @jlestel - #3382 seems to be another great candidate to merge ;)

Hi @JakobLichterfeld, I just added you as admin of the myteslamate repo.

While waiting to hear from Adrian, I would be delighted to be able to collaborate with you to help the community move the project forward. With the PRs already integrated, we could have a shorter path with my repo.
Obviously, you should only keep one repo fork while waiting for Adrian's possible return.

In this context, I'm looking for a few other people to have a team that doesn't just rely on one or 2 people.

I guess Tesla's recent changes didn't sit well with Adrian. Even with their new model I believe in a future for TeslaMAte.

For my part, I started working with the new Fleet API and the new data flow process to allow TeslaMate to have a future, even for personal setups.

Finally, as you mentioned, I see plenty of PRs who have asked for their editors' time and who provide value. That's why I wanted to promote them in a fork for some time.

**Comment by cwanja** [comment]
#3384 Adrian has spoken. He will not further development, but is open to forks.

**Comment by IBMRob** [comment]
> #3384 Adrian has spoken. He will not further development, but is open to forks.

Given this IMO it's best to get people moved to using one of the forks. Adding extra admins isn't wise if it's still owed his personal account, best to get it on a new org which can have multiple admins.

**Comment by cwanja** [comment]
> > #3384 Adrian has spoken. He will not further development, but is open to forks.
> 
> 
> 
> Given this IMO it's best to get people moved to using one of the forks. Adding extra admins isn't wise if it's still owed his personal account, best to get it on a new org which can have multiple admins. 

Completely agree. Need to identify what is the 'main' fork going forward and circle around that. Even Adrian could reference in the documentation. 

Anyone could have their own fork of course. But this would be the main fork that is community driven.

**Comment by olsoybakk** [comment]
Nice work, @jlestel. I tried using `myteslamate/teslamate:latest `now, but ran into an issue: `no matching manifest for linux/arm/v7 in the manifest list entries`.
Could you create a build for linux/arm/v7 ? 🙏🏻

**Comment by parkr** [comment]
Adrian moved this to @teslamate-org to support broader maintenance moving forward.

**Comment by natrlhy** [comment]
I'd like to nominate @cwanja as an admin as they have been active in the discussions and other fixes with regards to TeslaMate.

**Comment by adriankumpf** [comment]
> I'd like to nominate @cwanja as an admin as they have been active in the discussions and other fixes with regards to TeslaMate.

Agreed! Welcome aboard @cwanja 😃🎉

**Comment by cwanja** [comment]
> I'd like to nominate @cwanja as an admin as they have been active in the discussions and other fixes with regards to TeslaMate. 

Ah geez, I appreciate it. I am extremely honored. I will take great joy in continuing this project and look forward to collaborating with everyone.

**Comment by nelsongraca** [comment]
I might be late to the party and Elixir is not something I have knowledge of, but I'm available to provide any help wherever I can, can just filter out issues, do code reviews, help with the docker images or help on HomeAssistant integration side. I have been using this for 2 years now and I would love to help keep it further.

**Comment by NickWhitNTES** [comment]
OK, ill be the noob. :)

Does this mean we should point back to the original repository?

**Comment by cwanja** [comment]
> OK, ill be the noob. :)
> 
> 
> 
> Does this mean we should point back to the original repository?
> 
> 

My gut tells me no, pull requests are still merging and not officially released. 

When they are, folks will need to update their YML to the new repo. Instructions to come

**Comment by cwanja** [comment]
> > OK, ill be the noob. :)
> > Does this mean we should point back to the original repository?
> 
> My gut tells me no, pull requests are still merging and not officially released.
> 
> When they are, folks will need to update their YML to the new repo. Instructions to come

Nope, no need to change your YML. It will pickup the new TeslaMate-org repo. I was not impacted by the Tesla API changes, but they are included. Technically, everyone can point back to this repo and continue receiving data. And with the broaden administration, releases could continue to occur.

**Comment by nelsongraca** [comment]
@cwanja thank you

**Comment by tomsteenbakkers** [comment]
> Adrian moved this to @teslamate-org to support broader maintenance moving forward.

Just installed the new version. Works like a charm!

**Comment by NickWhitNTES** [comment]
> > > OK, ill be the noob. :)
> > > Does this mean we should point back to the original repository?
> > 
> > 
> > My gut tells me no, pull requests are still merging and not officially released.
> > When they are, folks will need to update their YML to the new repo. Instructions to come
> 
> Nope, no need to majorly change your YML. Simply point it back to `image: teslamate/teslamate:latest` It will pickup the new TeslaMate-org repo. I was not impacted by the Tesla API changes, but they are included. Technically, everyone can point back to this repo and continue receiving data. And with the broaden administration, releases could continue to occur.

![image](https://github.com/teslamate-org/teslamate/assets/82377682/88203e74-1818-4475-b478-3d683257de96)

**Comment by actraiser** [comment]
> ![image](https://user-images.githubusercontent.com/82377682/282322936-88203e74-1818-4475-b478-3d683257de96.png)

you have a spelling error (**telsa**mate) -  teslamate/teslamate:latest works fine.

Greets
-act

**Comment by NickWhitNTES** [comment]
> > ![image](https://user-images.githubusercontent.com/82377682/282322936-88203e74-1818-4475-b478-3d683257de96.png)
> 
> you have a spelling error (**telsa**mate) - teslamate/teslamate:latest works fine.
> 
> Greets -act

Its been a long day :)  THANK YOU.  Ive been staring at this for 20 min :)

**Comment by Dulanic** [comment]
Thank you all for the discussions and thank you @adriankumpf for your hard work to date. While this is obviously all new, the contributors have been expanded and I am sure at some point a better go forward process will be created. I don't think ANYONE has any idea what this will look like. 

I am going on vacation myself until December soon, but I wanted to help do what I can before I leave. I am going to close up outstanding issues.  I am going to close this out as we know this is no longer the case, but a determination how to handle this repo will be made in the future.

A new discussion will be opened for ideas and what should be done.

**Comment by markusdd** [comment]
Thanks everyone, this went far further in 1 day than I ever could have anticipated.

i also wish to thank @adriankumpf  again, this is one of the greatest open source projects run by just one person I've ever seen.

As stated further above, it might not be technically feasible for me to maintain this, but I always stand by to test and investigate issuesfor MCU2 retrofit vehicles.

**Comment by JakobLichterfeld** [comment]
> Hi @JakobLichterfeld, I just added you as admin of the myteslamate repo.
> 
> While waiting to hear from Adrian, I would be delighted to be able to collaborate with you to help the community move the project forward. With the PRs already integrated, we could have a shorter path with my repo. Obviously, you should only keep one repo fork while waiting for Adrian's possible return.

Hi @jlestel thanks. As things moved fast during me touching grass yesterday, I do see we continue TeslaMate as org and with several contributors. This is what I was looking for in the first place, forking was just my approach to help the people in need, atm 2400 have pulled it :-)

Looking forward to rock TeslaMate as org!

**Comment by jlestel** [comment]
> > Hi @JakobLichterfeld, I just added you as admin of the myteslamate repo.
> > While waiting to hear from Adrian, I would be delighted to be able to collaborate with you to help the community move the project forward. With the PRs already integrated, we could have a shorter path with my repo. Obviously, you should only keep one repo fork while waiting for Adrian's possible return.
> 
> Hi @jlestel thanks. As things moved fast during me touching grass yesterday, I do see we continue TeslaMate as org and with several contributors. This is what I was looking for in the first place, forking was just my approach to help the people in need, atm 2400 have pulled it :-)
> 
> Looking forward to rock TeslaMate as org!

I hope we will have the opportunity to work together on the new org
