### ISSUE TITLE
postgres error

### ISSUE THREAD

**Issue by abc123xxx** [teslamate-org/teslamate#3421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After i update an older version to current Teslamate 1.27.4 and update the docker-compose.yml i have an error in the teslamate-log with:

waiting for postgres at database:5432

Can enyone help me?

Raspberry PI 3 with docker

### Relevant log output

```shell
always:

waiting for postgres at database:5432
waiting for postgres at database:5432
waiting for postgres at database:5432
...
```

### Type of installation

Docker

### Version

v1.27.4

**Comment by swiffer** [comment]
could you include a redacted version of your docker compose file ?

**Comment by abc123xxx** [comment]
![20231113_133540](https://github.com/teslamate-org/teslamate/assets/66249676/7ed42d71-1639-4285-8dda-dcfa88881663)

**Comment by swiffer** [comment]
can you add the following to the telsamate service description

```yml
    depends_on:
      - database
```

**Comment by abc123xxx** [comment]
Thers the same error in the log file:

waiting for postgres at database:5432

**Comment by swiffer** [comment]
ok, and no logs from the database container? have you updated the postgres image tag?

**Comment by swiffer** [comment]
you cannot simply update the version of the postgres tag in a docker container - so please revert that to the previous version.

**Comment by abc123xxx** [comment]
Unfortunately, I don't remember which version (postgres) was the old one.
I installed Teslamte in June 2022 and haven't updated it since.

**Comment by DrMichael** [comment]
Probably 13 or 14. Try those. And then we have nice documentation, how to upgrade postgresql: https://docs.teslamate.org/docs/maintenance/upgrading_postgres

**Comment by abc123xxx** [comment]
Ok 14 was the right one.

Now Teslamate with postgres is running.

But now i connect connect to mosquitto with a MQTT-Client.

In the current Teslamate documentation the port 1883 ist not projected, why?
i have use port 1883 so far.

![image](https://github.com/teslamate-org/teslamate/assets/66249676/783aa6af-c565-41c9-8d3a-6db01043a624)

**Comment by DrMichael** [comment]
Probably you need to expose the port on the host. Uncomment the two lines...

**Comment by abc123xxx** [comment]
ok thanks, not it works fine

**Comment by abc123xxx** [comment]
But there is now an other problem:

If I call TeslaMate within my network everything works.
But if I call it from the Internet via my dyndns URL, then there is an origin error and no data.
Can this be related to a cross-origin problem? Do I have to set something in the new TeslaMate version?

**Comment by brianmay** [comment]
For what it is worth, recently I saw this `waiting for postgres at  ...` message and nothing was wrong with the database, or the network connection to the database. I restarted it, and it come good. So am a bit puzzled what happened, but haven't been able to diagnose yet.
