### ISSUE TITLE
MQTT published battery_level reverts to old value.

### ISSUE THREAD

**Issue by weljajoh** [teslamate-org/teslamate#3436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since updating to 2023.38.6 and Teslamate 1.27.4 this week, the value of battery_level (and related values) published through MQTT reverts to an old value (the value seems to be the value at the time of updating). Restarting the teslamate container corrects the issue and the correct value is published via MQTT again. The battery level as shown by the Grafana dashboards is always correct, so this seems to be an MQTT publishing issue only.

Wrong value after a drive:
````
pi@teslamate:~ $ mosquitto_sub -v -t teslamate/#
teslamate/cars/2/ideal_battery_range_km 243.85
teslamate/cars/2/version 2023.38.6
teslamate/cars/2/exterior_color DeepBlue
teslamate/cars/2/trim_badging 74D
teslamate/cars/2/geofence Thuis
teslamate/cars/2/battery_level 49           <<=== incorrect value
teslamate/cars/2/since 2023-11-14T09:07:15.089271Z
teslamate/cars/2/usable_battery_level 48     <<=== incorrect value
teslamate/cars/2/est_battery_range_km 225.57
teslamate/cars/2/model Y
teslamate/cars/2/rated_battery_range_km 243.85
teslamate/cars/2/healthy true
````

Restart Teslamate container and the correct value is published again:

````pi@teslamate:~ $ mosquitto_sub -v -t teslamate/#
teslamate/cars/2/ideal_battery_range_km 371.26
teslamate/cars/2/version 2023.38.6
teslamate/cars/2/exterior_color DeepBlue
teslamate/cars/2/trim_badging 74D
teslamate/cars/2/geofence Thuis
teslamate/cars/2/battery_level 74     <<=== incorrect value
teslamate/cars/2/since 2023-11-14T09:07:15.089271Z
teslamate/cars/2/usable_battery_level 74      <<=== correct value
teslamate/cars/2/est_battery_range_km 341.97
teslamate/cars/2/model Y
teslamate/cars/2/rated_battery_range_km 371.26
teslamate/cars/2/healthy true
````

### Expected Behavior

Correct values published via MQTT.

### Relevant log output

```shell
Lots of these stale fetch result messages during the drive
pi-teslamate-1  | 2023-11-14 08:04:52.068 car_id=2 [warning] Discarded stale fetch result: [
pi-teslamate-1  |   now: %TeslaApi.Vehicle.State.Drive{
pi-teslamate-1  |     gps_as_of: 1699949086,
pi-teslamate-1  |     heading: 24,
pi-teslamate-1  |     latitude: xxxxxxx,
pi-teslamate-1  |     longitude: xxxxxxx,
pi-teslamate-1  |     native_latitude: xxxxxxx,
pi-teslamate-1  |     native_location_supported: 1,
pi-teslamate-1  |     native_longitude: xxxxxxx,
pi-teslamate-1  |     native_type: "wgs",
pi-teslamate-1  |     power: -20,
pi-teslamate-1  |     shift_state: "D",
pi-teslamate-1  |     speed: 52,
pi-teslamate-1  |     timestamp: 1699949091808
pi-teslamate-1  |   },
pi-teslamate-1  |   last: %TeslaApi.Vehicle.State.Drive{
pi-teslamate-1  |     gps_as_of: 1699949072,
pi-teslamate-1  |     heading: 24,
pi-teslamate-1  |     latitude: xxxxxxx,
pi-teslamate-1  |     longitude: xxxxxxx,
pi-teslamate-1  |     native_latitude: xxxxxxx,
pi-teslamate-1  |     native_location_supported: 1,
pi-teslamate-1  |     native_longitude: xxxxxxx,
pi-teslamate-1  |     native_type: "wgs",
pi-teslamate-1  |     power: -14,
pi-teslamate-1  |     shift_state: "D",
pi-teslamate-1  |     speed: 52,
pi-teslamate-1  |     timestamp: 1699949091853
pi-teslamate-1  |   }
pi-teslamate-1  | ]
pi-teslamate-1  | 2023-11-14 08:09:38.288 [error] GET https://nominatim.openstreetmap.org/reverse -> error: "timeout" (5007.694 ms)
pi-teslamate-1  | 2023-11-14 08:09:38.289 [warning] Address not found: "timeout"
pi-teslamate-1  | 2023-11-14 08:09:43.300 [error] GET https://nominatim.openstreetmap.org/reverse -> error: "timeout" (5008.617 ms)
pi-teslamate-1  | 2023-11-14 08:09:43.300 [warning] Address not found: "timeout"
pi-teslamate-1  | 2023-11-14 08:09:43.337 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1699949371, heading: 187, latitude: xxxxxxx, longitude: xxxxxxx, native_latitude: xxxxxxx, native_location_supported: 1, native_longitude: xxxxxxx, native_type: "wgs", power: 1, shift_state: "P", speed: 0, timestamp: 1699949372947}
pi-teslamate-1  | 2023-11-14 08:09:43.337 car_id=2 [info] Driving / Ended / 12 km – 13 min
pi-teslamate-1  | 2023-11-14 08:09:43.338 car_id=2 [info] Start / :online
pi-teslamate-1  | 2023-11-14 08:12:59.883 car_id=2 [info] Suspending logging
pi-teslamate-1  | 2023-11-14 08:20:13.208 [info] Start of drive initiated by: %TeslaApi.Stream.Data{time: ~U[2023-11-14 08:20:12.966Z], speed: 0, odometer: 21435.8, soc: 77, elevation: -3, est_heading: 187, est_lat: xxxxxxx, est_lng: xxxxxxx, power: 2, shift_state: "R", range: 240, est_range: 228, heading: 189}
pi-teslamate-1  | 2023-11-14 08:20:13.209 car_id=2 [info] Driving / Start
pi-teslamate-1  | 2023-11-14 08:34:04.667 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (372.894 ms)
pi-teslamate-1  | 2023-11-14 08:34:05.056 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (376.115 ms)
pi-teslamate-1  | 2023-11-14 08:34:05.096 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{gps_as_of: 1699950842, heading: 322, latitude: xxxxxxx, longitude: xxxxxxx, native_latitude: xxxxxxx, native_location_supported: 1, native_longitude: xxxxxxx, native_type: "wgs", power: 2, shift_state: "P", speed: 0, timestamp: 1699950844145}
pi-teslamate-1  | 2023-11-14 08:34:05.096 car_id=2 [info] Driving / Ended / 12 km – 14 min
pi-teslamate-1  | 2023-11-14 08:34:05.096 car_id=2 [info] Start / :online
pi-teslamate-1  | 2023-11-14 08:37:37.764 car_id=2 [info] Suspending logging
pi-teslamate-1  | 2023-11-14 08:54:45.558 [info] Repairing drive #2757 ...
pi-teslamate-1  | 2023-11-14 08:54:47.280 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (218.331 ms)
pi-teslamate-1  | 2023-11-14 08:54:48.993 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (206.106 ms)
pi-teslamate-1  | 2023-11-14 08:54:49.003 [info] OK
pi-teslamate-1  | 2023-11-14 09:07:14.826 car_id=2 [info] Fetching vehicle state ...
pi-teslamate-1  | 2023-11-14 09:07:15.089 car_id=2 [info] Start / :asleep
pi-teslamate-1  | 2023-11-14 09:07:15.098 car_id=2 [info] Disconnecting ...
pi-teslamate-1  | 2023-11-14 09:27:14.241 [notice] SIGTERM received - shutting down
```

### Type of installation

Docker

### Version

v1.27.4

**Comment by weljajoh** [comment]
I did some more testing and it is not triggered by a drive per se, but it happens sometime after the car moves from the 'suspended' state to the 'asleep' state. 

To reproduce:
- let the car fall asleep
- restart the teslamate container to get an initial correct value for battery_level
- wake up the car by opening the app
- the value is still correct (checked with 'mosquitto_sub -v -t teslamate/cars/2/battery_level -C 1')
- wait until teslamate/cars/2/state moves to 'suspended'
- the value is still correct (checked with 'mosquitto_sub -v -t teslamate/cars/2/battery_level -C 1')
- wait until teslamate/cars/2/state moves to 'asleep'
- there is a fluyrry of MQTT messages at that time and the battery_level value is now incorrect.

The attached file contains a trace of all MQTT messages issued by teslamate with timestamps.
The sequence of events was:
13:32 start MQTT message trace (car was asleep at that time, battery_level was incorrect)
13:36 wake up car
14:03 restart container, value corect
14:15 wake up car via app, value is correct
14:18 car is suspended, value still correct
14:28 car asleep, value now incorrect
14:30 restart container, value correct
14:32 wake up car via app, value is correct
14:40 car falls asleep, value is incorrect again.

[trace.txt](https://github.com/teslamate-org/teslamate/files/13378493/trace.txt)

**Comment by drlauridsen** [comment]
I have a related or maybe even the same issue..

I am using Homeassistant,  and get the values for SoC, position etc from teslamate via mqtt. For 4 days these data have not been correct whenever the car is asleep, but  updated whenever the car is awoken, and when asleep it has been the same outdated values every time. Eg SoC will revert to 23% and position home, every time I leave the car/tesla app alone for some  time, but update  to correct SoC and position when I open the Tesla app.

It turns out to be teslamate that has  stopped getting data 4 days ago, so last data is SoC 23% and position home. 
I tried restarting teslamate containers, and logged out and in again with new tokens, but data were still not updated.
I now opened the tesla app, restarted teslamate,  and now data are updated,  but not sure if it will keep updating and in that case, what solved it..

**Comment by brianmay** [comment]
To the best of my knowledge, teslamate always sets "retain=true" when publishing outgoing data. But from above reports it is sounding exactly like this may not be the case.

Example. In one window I run:

```
$ mosquitto_sub -t 'test'`:
```

 in the other window I run:

```
$ mosquitto_pub -t test -m message
```

In the first window, the message appears, If I restart the command, it does not reappear. This is expected, I did not instruct the server to retain the message.

```
$ mosquitto_sub -t 'test'
message
^C%
$  mosquitto_sub -t 'test'
<nothing>
```

Now I repeat the test, but in the second window I type the following commands:

```
$ mosquitto_pub -t test -m retained -r
$ mosquitto_pub -t test -m not_retained
```

The first window is showing what I would expect to see:

```
$ mosquitto_sub -t 'test'
retained
not_retained
```

But if I exit and restart this:

```
$ mosquitto_sub -t 'test'
retained
```

I now get the old data, because the new data was not retained by the server. Because I didn't ask it to do so. But this is only seen in new sessions, old sessions are OK.

So question is: If you leave a mosquitto_sub open, does it show the old data? Or is it only when you create a new connection?

Having said that, I thought I understood this code, and I believe it always uses "retain: true". Maybe MQTT server doing something weird?

But it does seem more likely something is going wrong with the retain, then Teslamate somehow getting old data. I might be wrong though.

**Comment by weljajoh** [comment]
The trace file was generated by the following script which is equivalent to leaving mosquitto_sub open but with timestamps.

```
#!/usr/bin/env python

from __future__ import print_function

import paho.mqtt.client as mqttClient
import time
import sys

broker = '192.168.1.248'
port = 1883


def on_message(client, userdata, message):
    print(time.strftime("%Y-%m-%d %H:%M:%S"), message.topic, message.payload)


def on_connect(client, userdata, flags):
    print(time.strftime("%Y-%m-%d %H:%M:%S"), "Connected")
    client.subscribe("teslamate/#")


client = mqttClient.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect(broker, port=port)

client.loop_start()


try:
    while True:
        time.sleep(0.1)

except KeyboardInterrupt:
    client.disconnect()
    client.loop_stop()
    sys.exit(0)
```

**Comment by brianmay** [comment]
OK, I think that rules out my theory about retain being wrong. Good. But kind of confusing all the same.

**Comment by brianmay** [comment]
I suspect the next step might be to prove or disprove the possibility that the Tesla API is giving you bad data. Which might mean an appropriate call to `IO.inspect(...)` right after we receive the data.

I think battery data is not retrieved by streaming, we have to poll the API to get this data.

**Comment by brianmay** [comment]
It probably would be good actually if there was some built in way of selectively logging the raw data we receive from Tesla. Maybe to a distinct file. And one option for polled data, and another option for streamed data. This isn't the first time have access to such logs - although maybe really verbose - would be really useful.

**Comment by parnic** [comment]
Both of my cars are seeing this issue as well. I'm happy to help debug if I can. For what it's worth, at first only one of the cars was giving stale data, then a few days/week later, the other car started giving stale data. I'm using this in conjunction with https://github.com/denverquane/MMM-Teslamate

**Comment by weljajoh** [comment]
It's not Tesla that is passing us the incorrect value, the script below prints the charge state part of the vehicle data we get from Tesla every minute and what Teslamate sends us over MQTT. 

````
$ ./api-trace.py 
2023-11-17 08:59:52 teslamate/cars/2/state b'asleep'
2023-11-17 08:59:52 teslamate/cars/2/battery_level b'66'
2023-11-17 08:59:52 Vehicle is asleep
2023-11-17 08:59:52 charge_state {
    "battery_heater_on": false,
    "battery_level": 66,
    "battery_range": 205.55,
    "charge_amps": 16,
    "charge_current_request": 16,
    "charge_current_request_max": 16,
    "charge_enable_request": true,
    "charge_energy_added": 23.71,
    "charge_limit_soc": 80,
    "charge_limit_soc_max": 100,
    "charge_limit_soc_min": 50,
    "charge_limit_soc_std": 80,
    "charge_miles_added_ideal": 99.0,
    "charge_miles_added_rated": 99.0,
    "charge_port_cold_weather_mode": false,
    "charge_port_color": "<invalid>",
    "charge_port_door_open": false,
    "charge_port_latch": "Engaged",
    "charge_rate": 0.0,
    "charger_actual_current": 0,
    "charger_phases": null,
    "charger_pilot_current": 16,
    "charger_power": 0,
    "charger_voltage": 2,
    "charging_state": "Disconnected",
    "conn_charge_cable": "<invalid>",
    "est_battery_range": 179.85,
    "fast_charger_brand": "<invalid>",
    "fast_charger_present": false,
    "fast_charger_type": "<invalid>",
    "ideal_battery_range": 205.55,
    "max_range_charge_counter": 0,
    "minutes_to_full_charge": 0,
    "not_enough_power_to_heat": null,
    "off_peak_charging_enabled": false,
    "off_peak_charging_times": "all_week",
    "off_peak_hours_end_time": 420,
    "preconditioning_enabled": false,
    "preconditioning_times": "all_week",
    "scheduled_charging_mode": "Off",
    "scheduled_charging_pending": false,
    "scheduled_charging_start_time": null,
    "scheduled_charging_start_time_app": 0,
    "scheduled_departure_time": 1699261200,
    "scheduled_departure_time_minutes": 600,
    "supercharger_session_trip_planner": false,
    "time_to_full_charge": 0.0,
    "timestamp": 1700141881676,
    "trip_charging": false,
    "usable_battery_level": 66,
    "user_charge_enable_request": null
}
<snipped multiple charge_state dumps>
<woke up car with app at 09:01>
2023-11-17 09:01:38 teslamate/cars/2/state b'online'
2023-11-17 09:01:48 teslamate/cars/2/state b'unavailable'
<snipped multiple charge_state dumps with correct battery_level values>
2023-11-17 09:04:39 teslamate/cars/2/state b'suspended'
<snipped multiple charge_state dumps with correct battery_level values>
2023-11-17 09:13:56 charge_state {
    "battery_heater_on": false,
    "battery_level": 66,
    "battery_range": 203.89,
    "charge_amps": 16,
    "charge_current_request": 16,
    "charge_current_request_max": 16,
    "charge_enable_request": true,
    "charge_energy_added": 23.71,
    "charge_limit_soc": 80,
    "charge_limit_soc_max": 100,
    "charge_limit_soc_min": 50,
    "charge_limit_soc_std": 80,
    "charge_miles_added_ideal": 99.0,
    "charge_miles_added_rated": 99.0,
    "charge_port_cold_weather_mode": false,
    "charge_port_color": "<invalid>",
    "charge_port_door_open": false,
    "charge_port_latch": "Engaged",
    "charge_rate": 0.0,
    "charger_actual_current": 0,
    "charger_phases": null,
    "charger_pilot_current": 16,
    "charger_power": 0,
    "charger_voltage": 2,
    "charging_state": "Disconnected",
    "conn_charge_cable": "<invalid>",
    "est_battery_range": 178.4,
    "fast_charger_brand": "<invalid>",
    "fast_charger_present": false,
    "fast_charger_type": "<invalid>",
    "ideal_battery_range": 203.89,
    "max_range_charge_counter": 0,
    "minutes_to_full_charge": 0,
    "not_enough_power_to_heat": null,
    "off_peak_charging_enabled": false,
    "off_peak_charging_times": "all_week",
    "off_peak_hours_end_time": 420,
    "preconditioning_enabled": false,
    "preconditioning_times": "all_week",
    "scheduled_charging_mode": "Off",
    "scheduled_charging_pending": false,
    "scheduled_charging_start_time": null,
    "scheduled_charging_start_time_app": 0,
    "scheduled_departure_time": 1699261200,
    "scheduled_departure_time_minutes": 600,
    "supercharger_session_trip_planner": false,
    "time_to_full_charge": 0.0,
    "timestamp": 1700208836544,
    "trip_charging": false,
    "usable_battery_level": 65,
    "user_charge_enable_request": null
}
2023-11-17 09:14:27 teslamate/cars/2/battery_level b'49'       <<=== wrong value 
2023-11-17 09:14:27 teslamate/cars/2/state b'asleep'
2023-11-17 09:14:56 charge_state {
    "battery_heater_on": false,
    "battery_level": 66,         <<=== Tesla still sends us the correct value
    "battery_range": 203.89,
    "charge_amps": 16,
    "charge_current_request": 16,
    "charge_current_request_max": 16,
    "charge_enable_request": true,
    "charge_energy_added": 23.71,
    "charge_limit_soc": 80,
    "charge_limit_soc_max": 100,
    "charge_limit_soc_min": 50,
    "charge_limit_soc_std": 80,
    "charge_miles_added_ideal": 99.0,
    "charge_miles_added_rated": 99.0,
    "charge_port_cold_weather_mode": false,
    "charge_port_color": "<invalid>",
    "charge_port_door_open": false,
    "charge_port_latch": "Engaged",
    "charge_rate": 0.0,
    "charger_actual_current": 0,
    "charger_phases": null,
    "charger_pilot_current": 16,
    "charger_power": 0,
    "charger_voltage": 2,
    "charging_state": "Disconnected",
    "conn_charge_cable": "<invalid>",
    "est_battery_range": 178.4,
    "fast_charger_brand": "<invalid>",
    "fast_charger_present": false,
    "fast_charger_type": "<invalid>",
    "ideal_battery_range": 203.89,
    "max_range_charge_counter": 0,
    "minutes_to_full_charge": 0,
    "not_enough_power_to_heat": null,
    "off_peak_charging_enabled": false,
    "off_peak_charging_times": "all_week",
    "off_peak_hours_end_time": 420,
    "preconditioning_enabled": false,
    "preconditioning_times": "all_week",
    "scheduled_charging_mode": "Off",
    "scheduled_charging_pending": false,
    "scheduled_charging_start_time": null,
    "scheduled_charging_start_time_app": 0,
    "scheduled_departure_time": 1699261200,
    "scheduled_departure_time_minutes": 600,
    "supercharger_session_trip_planner": false,
    "time_to_full_charge": 0.0,
    "timestamp": 1700208836544,
    "trip_charging": false,
    "usable_battery_level": 65,
    "user_charge_enable_request": null
}
````

````
#!/usr/bin/env python3

import paho.mqtt.client as mqtt
import sys
import time
from datetime import datetime
import teslapy
from config import mqtt_broker_host, mqtt_broker_port, tesla_user

def on_message(client, userdata, msg):
    dprint(msg.topic, msg.payload)

def mqtt_init():
    client = mqtt.Client("trace-mqtt")
    client.on_message = on_message
    client.connect(mqtt_broker_host, mqtt_broker_port)
    client.subscribe("teslamate/cars/2/state")
    client.subscribe("teslamate/cars/2/battery_level")
    client.loop_start()


def dprint(*objects, **argv):
    ts = datetime.now().strftime("%04Y-%02m-%02d %H:%M:%S")
    print(ts, *objects, **argv)


mqtt_init()

with teslapy.Tesla(tesla_user) as tesla:
    while True:
        try:
            tesla.fetch_token()
            vehicles = tesla.vehicle_list()

        except teslapy.HTTPError as e:
            dprint(f"vehicle_list() {type(e).__name__}: {str(e)}")
            time.sleep(10)
            continue

        dprint(f"Vehicle is {vehicles[0]['state']}")
        break

    while True:
        try:
            vehicle_data = vehicles[0].get_vehicle_data()
            dprint("charge_state", vehicle_data.get("charge_state"))
        except teslapy.HTTPError as e:
            dprint(f"get_vehicle_data() {e.response.status_code} {e.response.text}")
       
        time.sleep(60)

**Comment by brianmay** [comment]
Starting to understand the code. Not sure that is a good thing :-)

I believe this is the relevant code, when we detect the call has fallen asleep.

```
  def handle_event(:internal, {:update, {:asleep, vehicle}}, :start, data) do
    Logger.info("Start / :asleep", car_id: data.car.id)

    {:ok, %Log.State{start_date: last_state_change}} =
      call(data.deps.log, :start_state, [data.car, :asleep, date_opts(vehicle)])

    :ok = disconnect_stream(data)

    {:next_state, {:asleep, @asleep_interval},
     %Data{data | last_state_change: last_state_change, stream_pid: nil},
     [broadcast_summary(), schedule_fetch(data)]}
  end
```

So we do some key things (simplified):

* We record in database that the car is asleep.
* We disconnect the streaming API. I guess the streaming API doesn't work when the car is asleep??
* We schedule an immediate `:broadcast_summary` event to publish the current state to MQTT.
* We schedule in 10 seconds time to call `fetch()` which will notice the vehicle is asleep and this attempts to retrieve data from `/api/1/vehicles/id/vehicle_data`. Considering the car is asleep, I believe this means the Tesla API may return cached data. At least that is what the docs say: https://developer.tesla.com/docs/fleet-api#vehicle_data

> Makes a live call to the vehicle. This may return cached data if the vehicle is offline. For vehicles running firmware versions 2023.38+, location_data is required to fetch vehicle location. This will result in a location sharing icon to show on the vehicle UI."

Still not 100% convinced that the Tesla API is not returning the bad data, it could be it is giving Teslamate one value, and your Python script another value for example. Scalable caches, such as presumably in use by Tesla, can act in ways that look weird to the outsider.

Teslamate itself I believe has only one authoritative source of data for the battery level. It is part of the Vehicle process. There is no evidence this process is killed and getting restarted (and that shouldn't matter in any case).

If somehow Teslamate was getting confused with your 2 cars, and starting two Vehicle processes for one car, that might explain some confusion. But there is only one set of logs getting produced, so I don't think so. And the code has an explicit unique constraint on the car id, to stop this happening.

I think this is all I can think of right now.

I might try to log my MQTT data, see if I notice anything weird.

**Comment by brianmay** [comment]
Not sure I 100% understand this code, but appears if we get incoming data from Tesla, and the car is asleep, then we just use values from our database instead (`restore_last_known_values`). We don't use the data from Tesla. If correct, this renders my theory about bad data from Tesla invalid.

```elxiir
      {:ok, %Vehicle{state: state} = vehicle} when state in ["offline", "asleep"] ->
        data =
          with %Data{last_response: nil} <- data do
            {last_response, geofence} = restore_last_known_values(vehicle, data)
            %Data{data | last_response: last_response, geofence: geofence}
          end

        {:keep_state, data,
         [
           broadcast_fetch(false),
           {:next_event, :internal, {:update, {String.to_existing_atom(state), vehicle}}}
         ]}
```

Where that function is:

```elixir
  defp restore_last_known_values(vehicle, data) do
    with %Vehicle{drive_state: nil, charge_state: nil, climate_state: nil} <- vehicle,
         %Log.Position{} = position <- call(data.deps.log, :get_latest_position, [data.car]) do
      drive = %Drive{
        latitude: position.latitude,
        longitude: position.longitude,
        shift_state: :unknown
      }

      to_miles = fn km ->
        with km when not is_nil(km) <- km do
          km |> Convert.km_to_miles(2) |> Decimal.to_float()
        end
      end

      charge = %Charge{
        ideal_battery_range: to_miles.(position.ideal_battery_range_km),
        est_battery_range: to_miles.(position.est_battery_range_km),
        battery_range: to_miles.(position.rated_battery_range_km),
        battery_level: position.battery_level,
        usable_battery_level: position.usable_battery_level,
        charge_energy_added: :unknown,
        charger_actual_current: :unknown,
        charger_phases: :unknown,
        charger_power: :unknown,
        charger_voltage: :unknown,
        charge_port_door_open: :unknown,
        scheduled_charging_start_time: :unknown,
        time_to_full_charge: :unknown
      }

      climate = %Climate{
        outside_temp: position.outside_temp,
        inside_temp: position.inside_temp
      }

      vehicle_state = %VehicleState{
        odometer: position.odometer |> Convert.km_to_miles(6),
        car_version:
          case call(data.deps.log, :get_latest_update, [data.car]) do
            %Log.Update{version: version} -> version
            _ -> nil
          end
      }

      vehicle = %Vehicle{
        vehicle
        | drive_state: drive,
          charge_state: charge,
          climate_state: climate,
          vehicle_state: vehicle_state
      }

      geofence = call(data.deps.locations, :find_geofence, [position])

      {vehicle, geofence}
    else
      _ -> {vehicle, nil}
    end
  end
```

Where `call(data.deps.log, :get_latest_position, [data.car])` is:

```elixir
  def get_latest_position(%Car{id: id}) do
    Position
    |> where(car_id: ^id)
    |> order_by(desc: :date)
    |> limit(1)
    |> Repo.one()
  end
```

i.e. it gets the latest entry in the Position table for that car. Which despite the name includes stuff like battery level.

So if your database has old values, that might explain it. But I would have expected grafana to display the old values too.

**Comment by brianmay** [comment]
My previous response was rubbish, just deleted it. Reasoning only applies if we get data from Tesla and the car is asleep and we have no previous data.

But if car is asleep and we do get new data, I don't think we use the data from Tesla either.

Still trying to understand the code however:

```elixir
        data =
          with %Data{last_response: nil} <- data do
            {last_response, geofence} = restore_last_known_values(vehicle, data)
            %Data{data | last_response: last_response, geofence: geofence}
          end
```

As in not sure what happens if last_response != nil, to the data value.

**Comment by JakobLichterfeld** [comment]
This is not related to 1.27.4. During the update, if the vehicle is asleep at the time of the TeslaMate update, no new values will be populated.

**Comment by weljajoh** [comment]
To clarify: I don't have two cars, I just have two cars in my Teslamate instance. My current car (car_id 2) and my previous car (car_id 1) which I sold before I got car 2.

**Comment by drlauridsen** [comment]
I solved my issues by logout-login, restarting all teslamate containers, and disabling streaming and enabling it again.
Have no idea what solved it, but it works now.

**Comment by JakobLichterfeld** [comment]
> I solved my issues by logout-login, restarting all teslamate containers, and disabling streaming and enabling it again. Have no idea what solved it, but it works now.

Awesome, closed.

**Comment by drlauridsen** [comment]
No dont close it, I am not the original poster 🙂
I just had the same or similar issue and wanted to tell how I solved it.
But it might not be the exact same issue..

**Comment by JakobLichterfeld** [comment]
MY bad, was confused due to the same default avatar.

**Comment by weljajoh** [comment]
Logging out, restarting all containers and toggling streaming didn't help (as expected).

One thing I did notice in the MQTT data was a timestamp 5 days in the past. The surronding data seems to match that date e.g. the odometer is also in the past (should be 35650)

````
2023-11-26 11:41:12 teslamate/cars/2/inside_temp 5.6
2023-11-26 11:41:12 teslamate/cars/2/rated_battery_range_km 399.31
2023-11-26 11:42:13 teslamate/cars/2/ideal_battery_range_km 399.17
2023-11-26 11:42:13 teslamate/cars/2/est_battery_range_km 277.21
2023-11-26 11:42:13 teslamate/cars/2/charge_energy_added 28.25
2023-11-26 11:42:13 teslamate/cars/2/rated_battery_range_km 399.17
2023-11-26 11:42:43 teslamate/cars/2/ideal_battery_range_km 399.31
2023-11-26 11:42:43 teslamate/cars/2/est_battery_range_km 277.31
2023-11-26 11:42:43 teslamate/cars/2/charge_energy_added 28.27
2023-11-26 11:42:43 teslamate/cars/2/rated_battery_range_km 399.31
2023-11-26 11:42:43 teslamate/cars/2/state suspended
2023-11-26 11:42:43 teslamate/cars/2/since 2023-11-26T10:42:43.253491Z
2023-11-26 11:45:28 teslamate/cars/2/healthy false
2023-11-26 11:46:15 teslamate/cars/2/healthy true
2023-11-26 11:48:12 teslamate/cars/2/healthy false
2023-11-26 11:52:49 teslamate/cars/2/version 2023.38.6
2023-11-26 11:52:49 teslamate/cars/2/odometer 34485.13    <<=== value from the past
2023-11-26 11:52:49 teslamate/cars/2/outside_temp 10.0
2023-11-26 11:52:49 teslamate/cars/2/since 2023-11-21T19:14:37.279986Z  <<=== 5 days ago
2023-11-26 11:52:49 teslamate/cars/2/latitude x.xxxxx
2023-11-26 11:52:49 teslamate/cars/2/battery_level 49
2023-11-26 11:52:49 teslamate/cars/2/usable_battery_level 48
2023-11-26 11:52:49 teslamate/cars/2/ideal_battery_range_km 243.85
2023-11-26 11:52:49 teslamate/cars/2/geofence Thuis
2023-11-26 11:52:49 teslamate/cars/2/display_name Y
2023-11-26 11:52:49 teslamate/cars/2/rated_battery_range_km 243.85
2023-11-26 11:52:49 teslamate/cars/2/longitude x.xxxxxxx
2023-11-26 11:52:49 teslamate/cars/2/est_battery_range_km 225.57
2023-11-26 11:52:49 teslamate/cars/2/inside_temp 19.1
2023-11-26 11:52:49 teslamate/cars/2/state asleep
2023-11-26 11:53:19 teslamate/cars/2/state asleep
2023-11-26 11:53:19 teslamate/cars/2/since 2023-11-26T10:53:19.174060Z
````
I ran my python API trace script at the same and there all data looks fine and up to date. I'd be happy to run a Teslamate version that logs all data received through the API to help confirm or deny API data problems if someone can provide such a version (or point me to steps to create one myself).

**Comment by weljajoh** [comment]
Looking through the drives, that odometer value is the end-of-drive value from a drive on 2023-11-12, the last drive before the upgrade to 2023.38.6 and Teslamate 1.27.4.

**Comment by JakobLichterfeld** [comment]
So you have unfinished drives, as there was a time TeslaMate was not logging your drives. Follow https://docs.teslamate.org/docs/maintenance/manually_fixing_data

**Comment by weljajoh** [comment]
> So you have unfinished drives, as there was a time TeslaMate was not logging your drives. Follow https://docs.teslamate.org/docs/maintenance/manually_fixing_data

Bingo! 

Manually terminiating the drive after the update (i.e. the one that started with incorrect odometer and battery_level) fixes this problem.

**Comment by parnic** [comment]
So how do we track this down ourselves when it happens? Dig into the mqtt data and attempt to correlate that to an old drive? Is there no way for the software to detect and either fix or prompt to fix this?

**Comment by brianmay** [comment]
Does this problem still happen? Might already be fixed...

Perhaps first thing, ideally there should be a way of listing all unclosed drives and charges. I would imagine this shouldn't be too hard to do from grafana...

**Comment by JakobLichterfeld** [comment]
> Perhaps first thing, ideally there should be a way of listing all unclosed drives and charges. I would imagine this shouldn't be too hard to do from grafana...

There is a custom dashboard for this https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards#incomplete-data

**Comment by weljajoh** [comment]
To check for unclosed drives from the commandline:
````
$ CAR=2
$ docker compose exec database psql -c "select id, start_date, end_date from drives where car_id=${CAR} and end_date is null;" teslamate teslamate
````

**Comment by parnic** [comment]
> > Perhaps first thing, ideally there should be a way of listing all unclosed drives and charges. I would imagine this shouldn't be too hard to do from grafana...
> 
> There is a custom dashboard for this https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards#incomplete-data

This is very helpful, thanks! Any suggestions on bulk-closing something like this?

<img width="1032" alt="image" src="https://github.com/teslamate-org/teslamate/assets/888126/234a3541-cc53-42e6-9837-a9f5d4f5c9c5">

**Comment by JakobLichterfeld** [comment]
> Any suggestions on bulk-closing something like this?

3 drives and charges, would close manually, see Docu linke above
Always backup, always

**Comment by parnic** [comment]
> > Any suggestions on bulk-closing something like this?
> 
> 3 drives and charges, would close manually, see Docu linke above Always backup, always

Note the "1-3 of 210/194 rows". That's a lot of unclosed drives. I closed the first three before realizing.

**Comment by JakobLichterfeld** [comment]
> Note the "1-3 of 210/194 rows". That's a lot of unclosed drives. I closed the first three before realizing.

Sorry, only on mobile right now. To bulk close see command above, or write a loop over your ids on your own.
