### ISSUE TITLE
feat: use variables in grafana dashboards for battery type

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are different types of batteries, e.g. LFP is normally charged to 100%. Dashboards should reflect this depending on the battery type: see #3311 

### Expected Behavior

Battery type handled with variables to avoid multiple dashboards for each variant

### Relevant log output

```shell
n.a.
```

### Type of installation

Docker

### Version

v1.27.4

**Comment by swiffer** [comment]
Battery type can be derived from VIN - https://teslawissen.ch/tesla-vin-decoder-so-kannst-du-die-vin-entschluesseln/#ziffer-7-ladetyp-2012-2013-akkutyp-seit-2014

happy to open a PR once current grafana PR are merged.

**Comment by swiffer** [comment]
This is what we need for it

https://grafana.com/docs/grafana/next/panels-visualizations/query-transform-data/transform-data/#config-from-query-results

**Comment by swiffer** [comment]
@eden881 - do you have a list of Changes done to the LFP Variants of the Dashboards?

**Comment by eden881** [comment]
> @eden881 - do you have a list of Changes done to the LFP Variants of the Dashboards?
> 
> Is that all that has been Changed?
> 
> Overview - LFP: The battery level gauge has red and yellow zones only on the lower end. The maximum value of the charging kW gauge has been lowered to 170, as this is the maximum DC charging potential for Tesla's LFP batteries. Charging Stats - LFP: The charge stats table remains green even for entries higher than 80% and 95%. Battery Health - LFP: The current SOC bar has a red zone only on the lower end

That is correct.

**Comment by swiffer** [comment]
Tried editing the Overview Dashboard, works fine for "Charging kw" - however for modifying the Thresholds we do need support for setting multiple values via config I guess

https://github.com/grafana/grafana/issues/77491
https://github.com/grafana/grafana/issues/45803

**Comment by swiffer** [comment]
It can be derived from vin, will modify Dashboards and remove LFP ones as soon as we can Set multiple thresholds via Config from query transformation

**Comment by NirKli** [comment]
I've reviewed the potential solution for retrieving information from VIN, but it appears to be inaccurate. 
I've begun developing the solution, implementing a flag on the settings page. However, it seems that Grafana does not support conditional thresholds.

**Comment by swiffer** [comment]
> I've reviewed the potential solution for retrieving information from VIN, but it appears to be inaccurate. I've begun developing the solution, implementing a flag on the settings page. However, it seems that Grafana does not support conditional thresholds.

flag on settings page is not working if there are multiple cars monitored via one teslamate instance.

see my proposal here: https://github.com/teslamate-org/teslamate/issues/3524#issuecomment-1850452981
