### ISSUE TITLE
ci: failed test since pr 3087

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Elixir Mix test failed since #3087 

@brianmaand @DrMichael please either revert or fix the test

I thought it was a caching issue at first, but after deleting all caches the problem persists.

### Expected Behavior

CI Test success

### Steps To Reproduce

see runner output

### Relevant log output

First fail on master is this PR, see this runner output: https://github.com/teslamate-org/teslamate/actions/runs/6892784984
Last success was this runner https://github.com/teslamate-org/teslamate/actions/runs/6887784700 for PR #2840

### Screenshots

n.a.

### Additional data

n.a.

### Type of installation

Docker

### Version

v1.24.4

**Comment by JakobLichterfeld** [comment]
cc @jlestel

**Comment by JakobLichterfeld** [comment]
Hm, the behavior is strange, because the runner reported success before, even if it failed: https://github.com/teslamate-org/teslamate/actions/runs/6887784700/job/18735559815#step:11:10 but that was not in the test, but in the coverage step, which does not make sense here.

**Comment by jlestel** [comment]
I've seen the coverage error: `(ExCoveralls.ReportUploadError) Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, body = {"message":"Couldn't find a repository matching this job.","error":true}).`

It seems that the repository no longer exists in coveralls.io and that's why it fails every time he wants to update it.

Could it be related to organizational change?

**Comment by JakobLichterfeld** [comment]
Yeah oberserved that as well, but is not related to failed elixir test cases

**Comment by jlestel** [comment]
> cc @jlestel

Il me semble que c'est plutôt le repository qui a été supprimé sur coveralls ?

**Comment by jlestel** [comment]
> Yeah oberserved that as well, but is not related to failed elixir test cases

I think that if, at the end of the Elixir check, the coverage is updated.

Until CI can't update it, it returns exit 1.

**Comment by jlestel** [comment]
To simply test, you can deactivate coverage.

**Comment by JakobLichterfeld** [comment]
As `continue-on-error: true`for the coverage the tests with failed coverage still report as success. 
It is strange sometimes the failed elixir test cases are only shown in coverage, so will test it.

**Comment by jlestel** [comment]
Hmmm... Failures seem linked with this PR? It's really related to the piece of code that was modified https://github.com/teslamate-org/teslamate/pull/3087

**Comment by JakobLichterfeld** [comment]
Yeah, so introducing new things to vehicle summary without updating test cases

**Comment by JakobLichterfeld** [comment]
Disabling Coverage did not solve it, as expected, see https://github.com/teslamate-org/teslamate/actions/runs/6933555983/job/18859928226?pr=3467

**Comment by JakobLichterfeld** [comment]
Rerunning the failed job solved it as well. So probably should avoid caching the test dependencies for the moment.

**Comment by JakobLichterfeld** [comment]
I reverted #3087 and restored ci.

Please open new PR for vehiclesummary @brianmay
