### ISSUE TITLE
grafana can't run up after upgrading to the latest version

### ISSUE THREAD

**Issue by henryxqy** [teslamate-org/teslamate#3496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After updating the grafana to the latest version, the container is always rebooting. The log shows "mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied".

### Relevant log output

```shell
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
mkdir: can't create directory '/var/lib/grafana-plugins': Permission denied
```

### Type of installation

Docker

### Version

v1.28.1

**Comment by JakobLichterfeld** [comment]
Please share your full docker-compose.yaml

**Comment by henryxqy** [comment]
The yml is just copied from docs.teslamate.org only with change of the input of password. I tried to completely reinstall with the compose yaml, it shows " ⠿ Volume "_teslamate-grafana-data"  Error                                                                                                                                          0.0s
Error response from daemon: create _teslamate-grafana-data: "_teslamate-grafana-data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path".

**Comment by JakobLichterfeld** [comment]
Please copy the docker.compose.yaml as raw, it seems like you have unallowed caracters in there.

**Comment by swiffer** [comment]
it might be that there is an existing volume from a previous grafana container that needs to be dropped. we simplyfied the grafana image.

**Comment by henryxqy** [comment]
Try to rebuild the container with yaml and it successed.

**Comment by JakobLichterfeld** [comment]
Thanks @swiffer for quick assistance!
