### ISSUE TITLE
bug on load grafana dashboard

### ISSUE THREAD

**Issue by SiNaPsEr0x** [teslamate-org/teslamate#3499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

more problem on new grafana with load submenu and other:

on clic menu dont open:
<img width="439" alt="image" src="https://github.com/teslamate-org/teslamate/assets/5438823/15a19b26-9048-4b0b-9c7c-8b21e3950ef1">

and on open battery health:

<img width="867" alt="image" src="https://github.com/teslamate-org/teslamate/assets/5438823/1be1297a-38fe-40c1-9d68-1c702afc4b4c">

but the log of grafana is all ok than this:

`teslamate-grafana-1  | logger=local.finder t=2023-11-26T10:05:45.619478931Z level=warn msg="Skipping finding plugins as directory does not exist" path=/usr/share/grafana/plugins-bundled`

### Relevant log output

```shell
ubuntu@vps:~/teslamate$ docker compose logs teslamate
teslamate-teslamate-1  | 2023-11-26 10:50:15.846 [info] Migrations already up
teslamate-teslamate-1  | 2023-11-26 10:50:28.031 [info] System Info: Erlang/OTP 26 (jit)
teslamate-teslamate-1  | 2023-11-26 10:50:28.031 [info] Version: 1.28.1
teslamate-teslamate-1  | 2023-11-26 10:50:29.027 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (591.981 ms)
teslamate-teslamate-1  | 2023-11-26 10:50:29.027 [info] Refreshed api tokens
teslamate-teslamate-1  | 2023-11-26 10:50:29.034 [info] Scheduling token refresh in 6 h
teslamate-teslamate-1  | 2023-11-26 10:50:29.037 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-teslamate-1  | 2023-11-26 10:50:29.039 [info] Access TeslaMateWeb.Endpoint at http://************
teslamate-teslamate-1  | 2023-11-26 10:50:29.417 [info] Starting logger for 'Vimana'
teslamate-teslamate-1  | 2023-11-26 10:50:29.678 [info] MQTT connection has been established
teslamate-teslamate-1  | 2023-11-26 10:50:30.338 car_id=1 [info] Start / :asleep
teslamate-teslamate-1  | 2023-11-26 10:50:32.633 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Tue, 28 Mar 2023 20:25:39 GMT.
```

### Type of installation

Docker

### Version

1.28.1

**Comment by JakobLichterfeld** [comment]
@oivindoh and @swiffer can you please double check?

**Comment by swiffer** [comment]
@SiNaPsEr0x can you remove the Grafana Container + volumes and recreate ? Take Care to drop Volume of grafana Container only, Not PostgreSQL!

**Comment by SiNaPsEr0x** [comment]
> @SiNaPsEr0x can you remove the Grafana Container + volumes and recreate ? Take Care to drop Volume of grafana Container only, Not PostgreSQL!

Yes...

`ubuntu@vps:~/teslamate$ ./clean.sh 
Deleted Images:
untagged: teslamate/grafana:latest
untagged: teslamate/grafana@sha256:501b75bd9c943a2061fae2a5f095ab0d9fea91dc7f4f3372e61940a2c972c876
deleted: sha256:aba6ad4dc432a5a2d106135fd35d0a89a282c490bdb4dbd5e8287480b90201d9
deleted: sha256:f4b45cf85d7aa433f022f2d5421e0f966847bee794e33ed94bc71eb3c38d2af8
deleted: sha256:022143942276b4517f0c92381c25733c4bcc9f190aa8de9a379e8204146bff41
deleted: sha256:6a8f2b0f8db5596aa991c05ac682d8919dc113a38201733d6acaf2ce44d78a9e
deleted: sha256:32bd111bb0a8bd11ce76f514cddca33304b2800cfdab3fce817fc36a424390c4
deleted: sha256:02dea88e23a2543b4f4836f634a0c5a6db109`

![image](https://github.com/teslamate-org/teslamate/assets/5438823/1e4d70c4-3ece-4efc-8a6f-131eaaba6dc3)

**Comment by swiffer** [comment]
You need to:

`docker compose down`
`docker volume ls`
`docker volume rm teslamate_grafana` <- volume name can be different
`docker compose up -d`

**Comment by oivindoh** [comment]
A bit of a strange issue since the official container builds in provisioning yaml to pull fresh dashboards from paths outside /var/lib/grafana (that are added as part of build)

**Comment by oivindoh** [comment]
You're running [1.28.1](https://hub.docker.com/layers/teslamate/grafana/1.28.1/images/sha256-3de987d9fba659f63bce082cf3df07a472c13adfd79cdee793e0d3b152044042?context=explore) this image right @SiNaPsEr0x ?

**Comment by SiNaPsEr0x** [comment]
> You need to:
> 
> `docker compose down` `docker volume ls` `docker volume rm teslamate_grafana` <- volume name can be different `docker compose up -d`

After executing these commands the remaining error is as follows:
`teslamate-grafana-1  | logger=local.finder t=2023-11-26T10:28:40.10457943Z level=warn msg="Skipping finding plugins as directory does not exist" path=/usr/share/grafana/plugins-bundled`

**Comment by oivindoh** [comment]
We need to get the :latest tag out of the example docker compose on the website. It's going to give us all kinds of grief when people end up running "whatever was the last to be pushed when they originally fired up the rig"

**Comment by swiffer** [comment]
Instead: we could change `docker compose up -d` to `docker compose up -d --pull always --renew-anon-volumes`

**Comment by oivindoh** [comment]
Yes, we probably don’t need a volume for teslamate grafana anyway, since it’s dedicated to these dashboards/the datasource. Advanced users likely run their own grafana instance anyway.

**Comment by manikoutai** [comment]
I haven`t find a way to mention that I am facing the same problem with version 1.28.1.  I have subscribed to the discussion if my attention is required, otherwise I will wait for the fix to be part of an official version since I have low knowledge about grafana.

**Comment by JakobLichterfeld** [comment]
> otherwise I will wait for the fix to be part of an official version since I have low knowledge about grafana.

There is no solution in official version. Official version is fine, you just need to update correct way. If you're facing this issue, it means you messed up beforehand.

**Comment by SiNaPsEr0x** [comment]
@JakobLichterfeld Anyone who has updated has this problem ... we have been using these systems for like 5 years and we know how they work .. if you write this it is because you have not updated because we all have the exact same problem ..

**Comment by SiNaPsEr0x** [comment]
@swiffer I have now done all the commands except changing the docker repo ... in all sincerity changing latest with the current version would be a waste of time since it is the same .. But the thing that leaves me a little perplexed is that you developers release the update without having tested it first!

**Comment by manikoutai** [comment]
> > otherwise I will wait for the fix to be part of an official version since I have low knowledge about grafana.
> 
> There is no solution in official version. Official version is fine, you just need to update correct way. If you're facing this issue, it means you messed up beforehand.

I am facing the problem. I installed 1.28.0 and then the problem occured when I upgrade to 1.28.1.

I am no expert so I only follow the documented way to upgrade both versions.  Here are the 2 commands that I have executed:

sudo docker-compose pull
sudo docker-compose up -d

Are you saying that an alternative approach should have been used to install those versions?

**Comment by SiNaPsEr0x** [comment]
> The reason being specific about tags was requested is if you're getting a message about natel-plotly-panel not found on battery health dashboard, you are **clearly** not running the 1.28.1 image as that is not referenced by the 1.28.1 image dashboard in any way. `latest` tag does not necessarily mean you're running the latest. 
> 
> 
> 
> I can replicate the Dashboards dropdown not working on a fresh docker-compose setup though. I can see grafana makes a call to `http://localhost:3000/api/search?tag=tesla&limit=100` and gets the full list of tesla-tagged dashboards, but no indication as to what makes grafana not display them in the browser. Downgrading my other non-teslamate grafana instance to 10.1.2 and importing dashboards from master, and the dropdown works fine. Not sure what's the issue for the container.
> 
> 
> 
> Unselecting the show as dropdown option for the link shows all the tagged dashboards, but as separate buttons.
> 
> 
> 
> I would note that indignant comments about errors in software isn't very helpful to debugging the issue.

I have already entered at the top what appears in the battery Health tab... this one of the submenu that does not load is another bug related to the grafana update... we run updates since the dawn of time and being told that the problem is how we update is really funny ... I would like to see your updated versions working!

**Comment by SiNaPsEr0x** [comment]
I repeat for the umpteenth time... the worrying thing is that at every update there is no one who performs a test to see if everything works!

**Comment by manikoutai** [comment]
@oivindoh You are right, I might have "highjacked" this conversation, please redirect me to another bug/situation if needed be.

My 2 problems:

1) When I call directly the main entry ("http://192.168.1.2:3000/") I receive nothing.  The port :4000 will load to tell me where is my car.
2) When I load directly a saved board, for instance the "overview" board I face 2 situations:
2.1: The "Dashboards" buttons is not responding, i.e. it is not giving me the possibility to call the other dashboard
2.2: In the Overview, the "Driver Temp", "Outside Temp" and "Inside Temp" are not showing any data anymore. This start to occurs in 1.28.0 and this 3rd problem is not related to this thread (I haven't attempt to investigate it yet).

I "assumed" that points 1 and 2.1 are related to this thread but if not I would appreciate if someone could help me identify what thread I should be following/comment.


thanks.

**Comment by swiffer** [comment]
Will look into it tomorrow. Those who are affected - could you Clean your Browser Cache / force reload via Ctrl+F5? Just to make Sure that is not the issue

**Comment by JakobLichterfeld** [comment]
> I repeat for the umpteenth time... the worrying thing is that at every update there is no one who performs a test to see if everything works!

Thanks for your feedback. We have automated testing for 321 test cases for each commit. 

For a few days now, new features are tested with dedicated docker images just for that new feature.

Obviously, there are two instances where this error occurs and on the other thousands of installs without it. You get plenty of attention on this for a bug in a fancy dashboard.

**Comment by JakobLichterfeld** [comment]
> I am no expert so I only follow the documented way to upgrade both versions. Here are the 2 commands that I have executed:
> 
> ```
> sudo docker-compose pull
> sudo docker-compose up -d
> ```
> 
> Are you saying that an alternative approach should have been used to install those versions?

Documented way is to use docker compose and not docker-compose which is deprecated.

**Comment by manikoutai** [comment]
> Will look into it tomorrow. Those who are affected - could you Clean your Browser Cache / force reload via Ctrl+F5? Just to make Sure that is not the issue

@swiffer  I did a full browser cache cleanup + the suggested CTRL-F5 on the main :3000 entry page and on a dashboard page and the problem remained as-is for me.

Thanks for looking into this.

**Comment by manikoutai** [comment]
> > I am no expert so I only follow the documented way to upgrade both versions. Here are the 2 commands that I have executed:
> > ```
> > sudo docker-compose pull
> > sudo docker-compose up -d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are you saying that an alternative approach should have been used to install those versions?
> 
> Documented way is to use docker compose and not docker-compose which is deprecated.

Thanks @JakobLichterfeld.  I will update my personal notes accordingly.  I hope I haven't broke something in my environment.

I will double check the documentation page before each updates for now on: https://docs.teslamate.org/docs/upgrading/?fbclid=IwAR1hj20GepB_tmwidaVQeJZT0LJMPPeTJJ3T9HC_OZuamjW6jhdP7C_a9iw

**Comment by JakobLichterfeld** [comment]
> **UPDATE** The **docker compose** is not available on my old Raspberry pi:

We do have a hint about it in documentation, but it did not populate on website due to some deployment issues with the website. So it could be updated, and there is a small chance your issue is related to it. 
Anyway, swiffer has offered to look at the issue by tomorrow.

**Comment by oivindoh** [comment]
[Note the lack of reference to the plugin from original issue screenshot in the battery health dashboard contained within the 1.28.1 container](https://github.com/teslamate-org/teslamate/blob/v1.28.1/grafana/dashboards/battery-health.json)

> @oivindoh You are right, I might have "highjacked" this conversation, please redirect me to another bug/situation if needed be.
> 
> My 2 problems:
> 
> 1. When I call directly the main entry ("http://192.168.1.2:3000/") I receive nothing.  Meanwhile the port :4000 works and will load to tell me where is my car.
> 2. When I load directly a saved board, for instance the "overview" board I face 2 situations:
>    2.1: The "Dashboards" buttons is not responding, i.e. it is not giving me the possibility to call the other dashboard
>    2.2: In the Overview, the "Driver Temp", "Outside Temp" and "Inside Temp" are not showing any data anymore. This start to occurs in 1.28.0 and this 3rd problem is not related to this thread (I haven't attempt to investigate it yet).
> 
> I "assumed" that points 1 and 2.1 are related to this thread but if not I would appreciate if someone could help me identify what thread I should be following/comment.
> 
> thanks.

2.2 Temperature not showing probably just means your car has been sleeping for a while. The dashboard query only looks 60m back to make the numbers relevant. This has been the case for a couple of years now.

1 is not related to this issue and could be any number of issues. Is grafana actually running on that address and is the port available? Sounds like it isn't.
2.1 Yes, this seems to be an issue. I just tracked it down to the `GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false` environment variable set in the 1.28.1 container. Looks like we need it enabled for dashboard dropdown links to work - this is worthy of a bug report to grafana if you would like to do the honours.

**Comment by manikoutai** [comment]
> [Note the lack of reference to the plugin from original issue screenshot in the battery health dashboard contained within the 1.28.1 container](https://github.com/teslamate-org/teslamate/blob/v1.28.1/grafana/dashboards/battery-health.json)
> 
> > @oivindoh You are right, I might have "highjacked" this conversation, please redirect me to another bug/situation if needed be.
> > My 2 problems:
> > 
> > 1. When I call directly the main entry ("http://192.168.1.2:3000/") I receive nothing.  Meanwhile the port :4000 works and will load to tell me where is my car.
> > 2. When I load directly a saved board, for instance the "overview" board I face 2 situations:
> >    2.1: The "Dashboards" buttons is not responding, i.e. it is not giving me the possibility to call the other dashboard
> >    2.2: In the Overview, the "Driver Temp", "Outside Temp" and "Inside Temp" are not showing any data anymore. This start to occurs in 1.28.0 and this 3rd problem is not related to this thread (I haven't attempt to investigate it yet).
> > 
> > I "assumed" that points 1 and 2.1 are related to this thread but if not I would appreciate if someone could help me identify what thread I should be following/comment.
> > thanks.
> 
> 2.2 Temperature not showing probably just means your car has been sleeping for a while. The dashboard query only looks 60m back to make the numbers relevant. This has been the case for a couple of years now.
> 
> 1 is not related to this issue and could be any number of issues. Is grafana actually running on that address and is the port available? Sounds like it isn't. 2.1 Yes, this seems to be an issue. I just tracked it down to the `GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false` environment variable set in the 1.28.1 container. Looks like we need it enabled for dashboard dropdown links to work - this is worthy of a bug report to grafana if you would like to do the honours.

@oivindoh I admit that my description of point 1 was misleading around the "I receive nothing" part.  I meant to say that I received nothing from Teslamate.  Grafana responded but teslamate didn't load in it.

![image](https://github.com/teslamate-org/teslamate/assets/103542406/92698cf3-6ad1-4bab-a8f2-195962c07ca5)

Regarding the bug report to grafana, I am not familiar about the environment to report bugs in grafana and wouldn't be able to describe it.  Any way for me to enable the variable or is this part of a fix that seems to be worked on?

**Comment by JakobLichterfeld** [comment]
If you want to test with the fix @oivindoh suggested: 

image: ghcr.io/teslamate-org/teslamate:master

and image: ghcr.io/teslamate-org/teslamate/grafana:master

**Comment by DrMichael** [comment]
> Documented way is to use docker compose and not docker-compose which is deprecated.

Deprecated is a hard word. V2 is not available in Ubuntu 22.04.3 LTS or bullseye on the RPi3.

**Comment by JakobLichterfeld** [comment]
> Deprecated is a hard word. V2 is not available in Ubuntu 22.04.3 LTS or bullseye on the RPi3

It's officially deprecated since June. And yes it is available on all platforms, using armv7 here with docker compose v2

**Comment by cwanja** [comment]
> > Documented way is to use docker compose and not docker-compose which is deprecated.
> 
> Deprecated is a hard word. V2 is not available in Ubuntu 22.04.3 LTS or bullseye on the RPi3.

Not a Raspberry Pi expert, but I have Docker Compose v2 running a bullseye Raspberry Pi 3b+. No clue how many "v3" Pis are out there.

**Comment by DrMichael** [comment]
> Not a Raspberry Pi expert, but I have Docker Compose v2 running a bullseye Raspberry Pi 3b+. No clue how many "v3" Pis are out there.

What did you install? I have docker/stable,now 1.5-2 all  [installiert]... Should it be docker-clean?

**Comment by cwanja** [comment]
> What did you install?

I assume I installed Docker Compose V2. I followed the guide here https://docs.docker.com/compose/migrate/. I still have Docker Compose v1 (believe it is 1.5.X)

**Comment by manikoutai** [comment]
Thanks to everyone involved in this investigation and fix.  I have installed version 1.28.2 and now the "Dashboards" button is working properly once again, and I was able to see for the first time the different "LFP" dashboards that have been added as part of 1.28.0.

**Comment by JakobLichterfeld** [comment]
> and I was able to see for the first time the different "LFP" dashboards that have been added as part of 1.28.0.

You could have seen than before, just open teslamate webapp (port 4000) and click on Dashboards.

**Comment by manikoutai** [comment]
> > and I was able to see for the first time the different "LFP" dashboards that have been added as part of 1.28.0.
> 
> You could have seen than before, just open teslamate webapp (port 4000) and click on Dashboards.

Although not related to the whole topic discussed here, the webapp at port 4000 doesn`t have any dashboards access to me.

![image](https://github.com/teslamate-org/teslamate/assets/103542406/13c67af8-2aca-451a-b7d3-1c234ec27060)

**Comment by cwanja** [comment]
> > > and I was able to see for the first time the different "LFP" dashboards that have been added as part of 1.28.0.
> 
> > 
> 
> > You could have seen than before, just open teslamate webapp (port 4000) and click on Dashboards.
> 
> 
> 
> Although not related to the whole topic discussed here, the webapp at port 4000 doesn`t have any dashboards access to me.
> 
> 
> 
> ![image](https://github.com/teslamate-org/teslamate/assets/103542406/13c67af8-2aca-451a-b7d3-1c234ec27060)
> 
> 

You need to set a grafana URL in the settings page.
