### ISSUE TITLE
Battery Health - LFP "Usable (new)" calculation not realistic

### ISSUE THREAD

**Issue by denzel1994** [teslamate-org/teslamate#3509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The new Battery Health - LFP dashboard shows me 83.7 kWh for a new battery. I have a late 2021 SR+ Model 3 with the 60/62 kWh LFP battery. 
<img width="852" alt="Bildschirmfoto 2023-11-27 um 23 47 57" src="https://github.com/teslamate-org/teslamate/assets/36551243/12c8a2f8-9fcb-482e-8a61-44dbcf24092e">

### Expected Behavior

The normal Battery Health Dashboard shows correct values:
<img width="861" alt="Bildschirmfoto 2023-11-27 um 23 48 21" src="https://github.com/teslamate-org/teslamate/assets/36551243/77a67405-9219-4e13-83e5-c3b378ea7630">

### Relevant log output

```shell
-
```

### Type of installation

Docker

### Version

v1.28.2

**Comment by manikoutai** [comment]
I have a 2022 SR+ Model 3 which was the first official 2022 cars delivered in North-America (Canada) with LFP batteries as I received it in January (In the USA few SR+ LFP cars have been shipped in Autumn 2021 as part of a testing effort if I recall it).  I don`t have the problem reported here.  Would it be possible that the late 2021 cars had a different LFP batterie?  (I am not searching for an answer, just mentioning it in case it could help resolve the situation, although we don`t know from which part of the world the owner is reporting this situation).

The only difference that I am observing is about the expected results that show an "Usable (new)" value of 60.8, while I receive a 60.4 value.

**Comment by denzel1994** [comment]
Reporting from Germany. :)

I am just wondering because in (https://github.com/teslamate-org/teslamate/pull/3311) it states: 
"Battery Health - LFP: The current SOC bar has a red zone only on the lower end."

Meaning the Battery Capacity calculation should not have changed compared to the "Not LFP - Battery Health".
As mentioned the "Non LFP" Battery Health Dashboard shows realistic values that can be backed up by Scan My Tesla BMS Data.

**Comment by denzel1994** [comment]
The issue still remains for me with 1.28.5.
