### ISSUE TITLE
Website Autobuild stopped working

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3512]
The automatic deployment to https://docs.teslamate.org/ stopped working since renaming to teslamate-org.

#2845 and #3472 are not visible on Website.

Org name change is reflected correctly in docusaurus config:
https://github.com/teslamate-org/teslamate/blob/008955ab18c07be2a88218ff77423444e07aa5bd/website/docusaurus.config.js#L7

**Comment by JakobLichterfeld** [comment]
Deployment config seems to be incorrect. I do not have edit rights there. @cwanja can you adjust it?

**Comment by cwanja** [comment]
I do not have any elevated access beyond what is in the GitHub repo. When you say "deployment config", where are you referring to @JakobLichterfeld? 

Is there a server side config located at docs.teslamate.org? @adriankumpf

**Comment by JakobLichterfeld** [comment]
> I do not have any elevated access beyond what is in the GitHub repo. When you say "deployment config", where are you referring to @JakobLichterfeld?
Sorry, this one: https://github.com/teslamate-org/teslamate/deployments

**Comment by cwanja** [comment]
> > I do not have any elevated access beyond what is in the GitHub repo. When you say "deployment config", where are you referring to @JakobLichterfeld?
> Sorry, this one: https://github.com/teslamate-org/teslamate/deployments
> ![image](https://private-user-images.githubusercontent.com/16510328/286311910-6dadc3cc-23cf-41b9-9aa7-ccc486cbd16b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODYxNTAsIm5iZiI6MTcwMTE4NTg1MCwicGF0aCI6Ii8xNjUxMDMyOC8yODYzMTE5MTAtNmRhZGMzY2MtMjNjZi00MWI5LTlhYTctY2NjNDg2Y2JkMTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTZlMTE5YWVhMmZkMmZmMzExMmQ0YTMyZDkzNzdkYWFlZmQxMDU0NzU0NDRhYWQ4YTJjNjNhMTc3ODhhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfR4n3jI7o7SRrrOUeBWQHR1QojAOFVX1_MlOEtlFns)

I can get to the Deployment page, but I cannot get into the the github.io link from your image. There is a "Manage Environments" link, but not seeing where to configure it. Happy to jump on a Teams call to screenshare. Though I believe our permissions are the same for the GitHub repo.

**Comment by JakobLichterfeld** [comment]
> Though I believe our permissions are the same for the GitHub repo.

No, I do not have the "Manage Environments", as I'm a Member and you are configured as owner in the teslamate-org, see https://github.com/orgs/teslamate-org/people

**Comment by cwanja** [comment]
> No, I do not have the "Manage Environments", as I'm a Member and you are configured as owner in the teslamate-org, see https://github.com/orgs/teslamate-org/people

Yikes. News to me. We probably need a second, as I know Adrian step away. I do not want to be a single bottle neck.

Clicking through the Manage Environments, I cannot see anything "wrong". But will keep diving into it.

**Comment by cwanja** [comment]
That "environment settings" looks like GitHub pages - which is the adrian link in your image that is a 404. Is your assumption that GitHub pages deploys to Docusaurus? 

Also, assuming Adrian's owns docs.teslamate.org (@adriankumpf) and not sure if something has to be updated there.

**Comment by DrMichael** [comment]
> Yikes. News to me. We probably need a second, as I know Adrian step away. I do not want to be a single bottle neck.

Perhaps you can promote @JakobLichterfeld to owner?

**Comment by cwanja** [comment]
> > Yikes. News to me. We probably need a second, as I know Adrian step away. I do not want to be a single bottle neck.
> 
> Perhaps you can promote @JakobLichterfeld to owner?

Done. Welcome to the club @JakobLichterfeld 😄

**Comment by JakobLichterfeld** [comment]
> s your assumption that GitHub pages deploys to Docusaurus?

In the readme it is stated that: 
https://github.com/teslamate-org/teslamate/blob/008955ab18c07be2a88218ff77423444e07aa5bd/website/README.md?plain=1#L3

**Comment by JakobLichterfeld** [comment]
And our new org does not have the the teslamate docu website as verified domain, thus we can't deploy there, see: https://github.com/organizations/teslamate-org/settings/pages

**Comment by cwanja** [comment]
@adriankumpf - we will need you to add the necessary DNS entries. I just added http://docs.teslamate.org as a domain. My guess is the TXT records for the domain from when TeslaMate was under Adrian's account will not work.

**Comment by adriankumpf** [comment]
@cwanja @JakobLichterfeld The docs are actually hosted on Netlify, not GitHub pages. I've updated the site configuration and it should work again. Unfortunately, the non-pro plan does not allow adding more members to the team on Netlify, so I cannot invite you. 
The config usually does not need to be changed, though, since every commit gets deployed automatically. If you ever want to make changes, I'll be around.

**Comment by brianmay** [comment]
I think, like it or not, we really need control over the `teslamate.org` domain. That way we still have options if Netlify stops meeting our needs and we cannot contact Adrian.

Disregard if we already do have control, e.g. via Netlify.

The website has `<title>Import from tesla-apiscraper (BETA) | TeslaMate</title>` - perhaps this could be changed?

And would also be good if the website has some sort of date stamp - at least I can't see any - so we can easily tell if it is up-to-date or not.

**Comment by parkr** [comment]
I'd recommend some setup with octodns and a repo for this like http://GitHub.com/jekyll/dns. DNS is declaratively defined, synced with GitHub actions, and is version controlled. This democratizes access to the domain without requiring handing out credentials or managing more things outside GitHub.

**Comment by cwanja** [comment]
Resolved based upon Adrian's comment. 

Open to suggestions in a discussion for management of the domain from Brian and Parker.

**Comment by JakobLichterfeld** [comment]
Deployment works as expected, checks are running and even a nice preview is build before the merge, see https://github.com/teslamate-org/teslamate/pull/3344
