### ISSUE TITLE
Mention grafana-vs-code-extension in Contribution Docs

### ISSUE THREAD

**Issue by swiffer** [teslamate-org/teslamate#3517]
There is a super great extension for VS Code created by the Grafana Team that eases editing bundled Dashboards. We should make use of it and mention it in the Contribution Docs.

-> https://github.com/grafana/grafana-vs-code-extension

We can hash out some further improvements down the line regarding ease of maintaining these dashboards. I'll definately give the extension @swiffer mentioned a whirl, and I think we probably ned to consider making the datasource we provision in grafana for the post gres database have a static uid.

_Originally posted by @oivindoh in https://github.com/teslamate-org/teslamate/issues/3439#issuecomment-1817956980_

**Comment by DrMichael** [comment]
I followed the instructions, created service account, created token, put the token into VS code settings. But still getting an error

`grafana_1    | logger=authn.service t=2023-11-29T16:10:47.58157139+01:00 level=warn msg="Failed to authenticate request" client=auth.client.api-key error="[api-key.invalid] API key is invalid"`

What did I miss?

**Comment by DrMichael** [comment]
Hmmm, don't think so. I did c&p. I also typed it in manually. Still `Authentication error`

**Comment by swiffer** [comment]
And the service Account has been created with Admin rights?

**Comment by DrMichael** [comment]
Yes. Sigh
