### ISSUE TITLE
Docker Install Instructions - Needs improvement

### ISSUE THREAD

**Issue by defconxt** [teslamate-org/teslamate#3528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Source:** https://docs.teslamate.org/docs/installation/docker

Deployed TeslaMate using 4000:4000 for the WebApp, 3002:3002 for the Grafana dashboard. 
**Reason:** I have several dozen of containers using various ports that I'm unwilling to move around.

Grafana was not reachable.

### Expected Behavior

Expected Result: Grafana reachable at IP:3002

Remediation: Map HOST 3002 to DOCKER 3000 (3002:3000). Result: Grafana reachable. I would expect the docker container to match my needs as many other containers I use do this dynamically.

### Steps To Reproduce

Deploy the container on a different port than the documentation.

### Relevant log output

```shell
no logs.
```

### Type of installation

Docker

### Version

latest as of 11/30/23

**Comment by Dulanic** [comment]
Closing, this is invalid. This is a personal issue with changes you made to your ports that you didn't do properly.
