### ISSUE TITLE
Bogus line in visited dashboard

### ISSUE THREAD

**Issue by ilkkao** [teslamate-org/teslamate#353]
**Describe the bug**

Teslamate works perfectly for me. The only minor UI glitch is in the visited dashboard:

![image](https://user-images.githubusercontent.com/474587/72163350-62135300-33cc-11ea-97ce-ef10c38ba89c.png)

The extra line is from a day where teslamate has recorded two drives. One ending where the erroneous line starts and a second one which starts where the erroneous line ends. Which means there's one leg that is missing from the drives.

Does this happen because visited dashboard draws one contiguous line? If that's the case, could it not join the lines if there's a big enough gap. This would cover the cases the car is transported to a new location by train for example.

**Comment by ilkkao** [comment]
This seems to be related: https://github.com/pR0Ps/grafana-trackmap-panel/issues/21

**Comment by lux4rd0** [comment]
I just had the same thing happen to me where two drives had data missing from the start of the drive. I deleted the drives with the "Manually fixing data" of DELETE FROM drives WHERE id = ?; - but it doesn't seem to delete the data from panel - just from the drives. Is there a way to fix this?

**Comment by bekriebel** [comment]
I have the same unfortunate line from the point when I canceled my teslafi subscription and started using teslamate. Unfortunately my sub lapsed while I was ~100m from home, so I have a big cut across the map. It does look like we may be out of luck until that pROPs feature can be added, though.

**Comment by ilkkao** [comment]
I've been checking this a little, grafana trackmap extension in the end gets an array of coordinates and draws lines that connect them. It should be relatively straightforward to add option "do not draw this line if the line start and end coordinates are more than X meters apart" Might be able to propose a patch there at some point.

**Comment by cash69** [comment]
<img width="410" height="504" alt="Image" src="https://github.com/user-attachments/assets/bcd6ae9f-088d-4f7a-a71a-70d1087ddc26" />

I still have this bug (I have another one in my visited map in Teslamate).
This PR seems to be outdated since grafana-trackmap-panel has changed a lot : https://github.com/pR0Ps/grafana-trackmap-panel/pull/39

Do you have any clue on how to fix it ? 
Thanks
