### ISSUE TITLE
Dog Mode not longer recognized

### ISSUE THREAD

**Issue by Shadesh** [teslamate-org/teslamate#3535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When Dog Mode is active, Teslamate shows nothing and is going to sleep after a while. So for me it looks like the Dog Mode is not longer recognized. There are no relevant logs, only after a while:

car_id=1 [info] Suspending logging

### Expected Behavior

Detect Dog Mode and show A/C symbol and dont go to sleep on the Teslamate Interface.

### Steps To Reproduce

Enable Dog Mode for more then 15 Minutes and look at the Teslamate Interface

### Relevant log output

```shell
car_id=1 [info] Suspending logging
```

### Type of installation

Docker

### Version

1.28.2

**Comment by NirKli** [comment]
@Shadesh 
Could you clarify if this issue with Dog Mode not being recognized by Teslamate started occurring specifically after updating to version 1.28.2? Or have you been experiencing this problem since you first started using the program?

**Comment by Shadesh** [comment]
Afaik i had the A/C symbol and Teslamate wasn't going to sleep while Dog mode was active. This seems not longer the case. Don't know exactly if it changed with 1.28.2 or earlier. I saw it today the first time because the car was in Dog mode for around 30 minutes.

**Comment by JakobLichterfeld** [comment]
TeslaApi didn't report dedicated dog mode in the past, as they change their API we need to adopt

**Comment by JakobLichterfeld** [comment]
closed by #3538
