### ISSUE TITLE
Where did cost_per_kw in Charges Dashbard go?

### ISSUE THREAD

**Issue by PalleRaa** [teslamate-org/teslamate#3553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the 1.27.x versions there were a column in the "charges" dashboard that showed the price pr kWh for each charge. This is no longer available in 1.28.x :(

### Expected Behavior

I hope the value could still be calculated in the dashboard in the futire.

### Relevant log output

```shell
Not relevant
```

### Screenshots

Comparing 1.27.4. to 1.2.8.0 (grafana/dashboards/charges.json)
![image](https://github.com/teslamate-org/teslamate/assets/95851907/ce291b66-ec90-4c4e-8962-26634909bf93)

### Type of installation

Docker

### Version

1.28.2

**Comment by DrMichael** [comment]
Already comitted in https://github.com/teslamate-org/teslamate/commit/fdfdd63d6f5f47598890d9fc3a67d9e5c5dfbd40. Will be back in the next version.
