### ISSUE TITLE
[Feature Requets] Group Charges in Dashboard by distance driven since last charge

### ISSUE THREAD

**Issue by drBeam** [teslamate-org/teslamate#3575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At my company we have chargers that are switching cars every 5-15 Minutes if more than one car is connected to one string. In this case my car got power for five minutes and then none for another five minutes and so on:
![image](https://github.com/teslamate-org/teslamate/assets/29180766/aff6386c-1a82-4753-9d54-5650d3303963)
This messes up my charges for obvious reasons, sadly i'm an absolute noob on grafana. Is it possible to group all charges with the same odometer and distance driven equals 0m together? Or would this make sense for everyone?

### Steps To Reproduce

-

### Relevant log output

```shell
-
```

### Type of installation

Docker

### Version

v1.28.2

**Comment by JakobLichterfeld** [comment]
Technically, these are separate charges, so I see no issue with TeslaMate recording them as separate charges.

Can you elaborate on your request further?

**Comment by drBeam** [comment]
Sure, technically that is correct. However my dashboard looks pretty messy and logically i started a charge that got disrupted every 15 Minutes. 
![image](https://github.com/teslamate-org/teslamate/assets/29180766/70e75e74-0579-4211-86bc-1e5d4c83e565)
This screenshot are just the charges from two days. I plugged the car in in the morning so from the logical (or end-user) perspective i just charged the car two times. 

I see that the data recorded by Teslamate is correct and shouldn't be changed but the dashboard view would be much nicer if these charges get grouped imo.

**Comment by JakobLichterfeld** [comment]
> I see that the data recorded by Teslamate is correct and shouldn't be changed but the dashboard view would be much nicer if these charges get grouped imo.

Agree on the one hand, on the other, the battery cooles down in the 15 minutes interruption and so on, so the calculation must start with new values.

I do have the use case when my car charges, is charged till the threshold, fall asleep. When I wake it up it had rebalanced it, so new charge state is below threshold and it starts a new charge as well.
