### ISSUE TITLE
Some location can't be resolved in China

### ISSUE THREAD

**Issue by hipudding** [teslamate-org/teslamate#3591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I found some location in China can't be resolved, these locations have no names, which bring problems:
1.  charging state will add them together, Location in map is also not correct.
2. Visited will not show these locations.

This problem also exists in drives, charges and other pages which contains a location.

I know it's about the map API, but can I add this location names manually, just like I can set charging fee.

### Relevant log output

Nothing about teslamate itself, I think it's about map apis.

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/3837401/156a965e-7c04-44d4-b1b3-545242442abf)
![image](https://github.com/teslamate-org/teslamate/assets/3837401/7939191e-b341-49a1-865d-ff382c799d01)

### Type of installation

Docker

### Version

v1.28.2

**Comment by hipudding** [comment]
BTW, I already use a proxy.

**Comment by hipudding** [comment]
I found a solution in #2956, close this issue.

**Comment by bloy123** [comment]
你知道怎么更改为高德或者百度地图吗？ 有人已经改了 但是在出售。。

**Comment by hipudding** [comment]
这个没研究过，前端不太懂。麻烦问下哪里能看到修改版本？
