### ISSUE TITLE
Failing to export teslamate.bck on macOS Docker Desktop

### ISSUE THREAD

**Issue by danielraffel** [teslamate-org/teslamate#3609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to move my teslamate install from macOS running Docker Desktop to a cloud VM. When I attempt to backup the database on macOS I cannot.

Looks like my db is >8mb

```
docker compose exec database psql -U teslamate -d teslamate -c "SELECT pg_size_pretty(pg_database_size('teslamate'));"
 pg_size_pretty 
----------------
 8569 kB
```

But, when I export the data teslamate.bck is just 545 bytes.
`docker compose exec -T database pg_dump -U teslamate teslamate > teslamate.bck`

### Expected Behavior

I am expecting when I run this command it will export a file called teslamate.bck that's many mb. Instead it's creating one that is hundreds of bytes.

> `docker compose exec -T database pg_dump -U teslamate teslamate > teslamate.bck`

### Steps To Reproduce

1. in a terminal, navigate to the folder with docker-compose.yml 
2. run this command `docker compose exec -T database pg_dump -U teslamate teslamate > teslamate.bck `
3. Notice that teslamate.bck is just 545 bytes

### Relevant log output

```shell
when I run in the terminal: docker compose logs teslamate
I see no output
```

### Additional data

docker 4.26.1

### Type of installation

Docker

### Version

macOS is running 1.27.1 (server is newer running 1.28.2)

**Comment by DrMichael** [comment]
Have a look at teslamate.bck. Probably there is an error message in it.

**Comment by danielraffel** [comment]
Good point, sorry for not sharing. Here's the contents of `teslamate.bck` any suggestions?

```
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.10 (Debian 14.10-1.pgdg120+1)
-- Dumped by pg_dump version 14.10 (Debian 14.10-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--


```

**Comment by JakobLichterfeld** [comment]
Please give it a try without the `-T`. As docker compose (which is docker compose v2) omit the -T automatically if not called from a TTY.
