### ISSUE TITLE
the same UID is used more than once in Grafana

### ISSUE THREAD

**Issue by vaminakov** [teslamate-org/teslamate#3616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On fresh manual install of TeslaMate, Grafana's logs have a lot of warnings about UID's.

### Steps To Reproduce

1. Install latest Grafana (10.2.3) and TeslaMate (1.28.2) on Archlinux
2. Set up TeslaMate and Grafana with default settings
3. Check Grafana logs

### Relevant log output

```shell
19:44.166997602+03:00 level=warn msg="the same UID is used more than once" orgId=1 uid=BHhxFeZRz times=2 providers="[teslamate teslamate_internal]"
19:44.167043838+03:00 level=warn msg="the same UID is used more than once" orgId=1 uid=lBIoQIggk times=2 providers="[teslamate teslamate_reports]"
19:44.167060111+03:00 level=warn msg="the same UID is used more than once" orgId=1 uid=zm7wN6Zgz times=2 providers="[teslamate teslamate_internal]"
19:44.167075825+03:00 level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=teslamate orgId=1
19:44.167088187+03:00 level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=teslamate_internal orgId=1
19:44.167100549+03:00 level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=teslamate_reports orgId=1
```
```


### Screenshots

_No response_

### Additional data

_No response_

### Type of installation

Manual

### Version

1.28.2

**Comment by JakobLichterfeld** [comment]
TeslaMate is pinned to Grafana 10.1.2

**Comment by dyxyl** [comment]
The warning is about provisioning, so I suspect you have created the duplicates yourself by copying files into more than one provisioning directory.  Names like `teslamate_internal` and `teslamate_reports` come from the provisioning files used by the Docker install.

I have a manual install, but I use `grafana/dashboards.sh restore` to import the dashboards as described in the TeslaMate documentation rather than using provisioning.

**Comment by vaminakov** [comment]
@dyxyl you're right, problem was in provisioning: 3 sources in .yml
Deleted 2 of them and all working fine.
