### ISSUE TITLE
Teslamate not starting

### ISSUE THREAD

**Issue by BDThug** [teslamate-org/teslamate#3620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I updated my teslamate to the latest version with docker compose pull. 

When trying to start teslamate again everything starts (db, grafana etc) but teslamate is failing:

teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
tesla_teslamate_1 exited with code 134
tesla_teslamate_1 exited with code 0
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
tesla_teslamate_1 exited with code 134

I can run 1.25.0 without a problem for instance, but 1.28.2 is not working. What is error 134 about?

### Expected Behavior

Teslamate running without any problem

### Relevant log output

```shell
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
teslamate_1  | Aborted (core dumped)
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
tesla_teslamate_1 exited with code 134
tesla_teslamate_1 exited with code 0
teslamate_1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate_1  | Aborted (core dumped)
tesla_teslamate_1 exited with code 134
```

### Type of installation

Docker

### Version

v.1.28.2

**Comment by JakobLichterfeld** [comment]
Please restore your old setup from your backup, follow https://docs.teslamate.org/docs/maintenance/upgrading_postgres and check the relase notes as stated in https://docs.teslamate.org/docs/upgrading
