### ISSUE TITLE
Missing v1.28.2 ghcr.io build?

### ISSUE THREAD

**Issue by szinn** [teslamate-org/teslamate#3632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a 1.28.2 release, but no binary on ghcr.io

### Relevant log output

```shell
n/a
```

### Type of installation

Docker

### Version

v1.28.1

**Comment by szinn** [comment]
Could do a new release to pick up the change in the tesla api as well perhaps?

**Comment by JakobLichterfeld** [comment]
ghcr build are only for testing.

Regarding tesla api change, follow https://github.com/teslamate-org/teslamate/pull/3630, where test images are available since the change happpend.
