### ISSUE TITLE
Can't get the carId .  already logging by the tesla token!

### ISSUE THREAD

**Issue by wangkang0726** [teslamate-org/teslamate#3641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

no data 
![4961706682757_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/ceb2cdf6-4824-4668-9925-2f9e93299d22)
![4971706682785_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/5bf95258-6ebe-4376-8032-3b1583c73da0)
![4981706682851_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/46bc4016-2334-4994-b47c-76b4fc6372c2)

### Relevant log output

```shell
SELECT
  sum(GREATEST(start_rated_range_km - end_rated_range_km, 0) * car.efficiency * 1000) / 
  convert_km(sum(distance)::numeric, 'km') as "consumption_km"
FROM drives
JOIN cars car ON car.id = car_id
WHERE start_date BETWEEN '2024-01-30T16:00:00Z' AND '2024-01-31T06:29:14.495Z' AND car_id = 



No request and response collected yet. Hit refresh button
```

### Screenshots

![4961706682757_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/5e00241c-9a99-47ac-bd70-ee3d45e5dc7c)
![4971706682785_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/7be958ea-e996-472d-ac26-3563c6316451)
![4981706682851_ pic](https://github.com/teslamate-org/teslamate/assets/16094960/4710ba05-c0bc-490b-a72a-cc50b456d8f6)

### Type of installation

Docker

### Version

v1.28.2

**Comment by wooter** [comment]
Possibly same issue as https://github.com/teslamate-org/teslamate/issues/3629. 
A fix for the API endpoint change in the works, https://github.com/teslamate-org/teslamate/pull/3630.

**Comment by wangkang0726** [comment]
ty
