### ISSUE TITLE
WebView crashes while charging, if time_zone_not_found

### ISSUE THREAD

**Issue by maxhac03** [teslamate-org/teslamate#3651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When charging the car, the web interface report "Internal Server Error".

Stopping the charge cause Teslamate to return to normal.

### Steps To Reproduce

Opened the Tesla app, started a charging session, Teslamate crash.

### Relevant log output

```shell
Server: teslamate.DOMAIN.COM:80 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) time_zone_not_found
        (timex 3.7.11) lib/format/datetime/formatter.ex:55: Timex.Format.DateTime.Formatter.lformat!/4
        (teslamate 1.28.3) lib/teslamate_web/live/car_live/summary.html.heex:157: anonymous fn/2 in TeslaMateWeb.CarLive.Summary.render/1
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:138: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/static.ex:244: Phoenix.LiveView.Static.to_rendered_content_tag/4
2024-02-03 05:13:27.857 [info] GET /
2024-02-03 05:13:27.864 [info] Sent 500 in 7ms
2024-02-03 05:13:27.867 [error] #PID<0.23142.0> running TeslaMateWeb.Endpoint (connection #PID<0.23141.0>, stream id 1) terminated
```

### Screenshots

![screenshot 16](https://github.com/teslamate-org/teslamate/assets/64552097/dcec40d8-0cb7-437b-95ee-70aca902de16)

### Type of installation

Docker

### Version

1.28.3

**Comment by JakobLichterfeld** [comment]
`time_zone_not_found` -> please set TZ environment variable, see https://docs.teslamate.org/docs/configuration/environment_variables

**Comment by maxhac03** [comment]
**TM_TZ=Atlantic/Halifax** replaced with **TM_TZ=America/Moncton**.

No longer crashing. 

Thanks.

**Comment by TSJasonH** [comment]
I ran into this issue on the latest upgrade. I saw the release notes and confirmed that I have TZ= defined properly in my docker-compose file. Adding a TM_TZ line fixed the issue as noted, but what I'm not seeing is where "TM_TZ" is written in the linked documentation: https://docs.teslamate.org/docs/configuration/environment_variables/

**Comment by JakobLichterfeld** [comment]
> I ran into this issue on the latest upgrade. I saw the release notes and confirmed that I have TZ= defined properly in my docker-compose file. Adding a TM_TZ line fixed the issue as noted, but what I'm not seeing is where "TM_TZ" is written in the linked documentation: https://docs.teslamate.org/docs/configuration/environment_variables/

The Name of the environment variable is TZ.

**Comment by TSJasonH** [comment]
I don't know why or how your reply explains my confusion. The fact is using "TZ=" was not enough but instead a line with "TM_TZ=" works yet is not in the documentation written as "TM_TZ=". Am I just missing something that should be "obvious"?

**Comment by brianmay** [comment]
There is currently no code in TeslaMate that I am aware of that reads the `TM_TZ` environment variable. If it really is the case that setting `TM_TZ` in addition to `TZ` fixes problems, we would need to be able to understand how and why this is happening before we could fix it. That may not be easy, would require somebody who knows their way around the code being able to reproduce the issue.

I see references in the docs to setting `TZ=${TM_TZ}` in the docker-compose. I suspect that is not happening here.

In any case, I think if it really is the case that something is looking at `TM_TZ` not `TZ`, this requires another bug report, clearly defined and scoped at that issue.

**Comment by brianmay** [comment]
My bad, I just realised that was already mentioned in #3678.
