### ISSUE TITLE
No connection to Tesla API / non-existing domain *done*

### ISSUE THREAD

**Issue by WZBFL** [teslamate-org/teslamate#3655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since 04.02.2024 Connection between Car and Teslamate is down
- install v1.28.3
- no changes
- install v1.28.2 
- no changes
- logoff
- want to login again
- install v1.28.2 again
- its already logged on but stil no connection -> see on the second error message

no login possible since logoff
->  Message on Screen: "Tokens are invalid"

### Relevant log output

```shell
2024-02-05 10:56:19.335 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (8004.405 ms)

2024-02-05 17:28:16.540 [error] GET https://owner-api.teslamotors.com/api/1/vehicles/XXXXXXXXXXXXX-> error: "non-existing domain" (8003.685 ms)
2024-02-05 17:28:16.540 [warning] TeslaApi.Error / non-existing domain
2024-02-05 17:28:16.540 car_id=1 [error] Error / :unknown

```

### Screenshots

<img width="932" alt="2024-02-05 18_33_16-Home · TeslaMate und 1 weitere Seite - Profil 1 – Microsoft​ Edge" src="https://github.com/teslamate-org/teslamate/assets/102554708/ddf35cbf-b59d-42de-9455-2e908b1734ab">

### Type of installation

Docker

### Version

v1.28.2

**Comment by JakobLichterfeld** [comment]
Please check your network connection

**Comment by WZBFL** [comment]
ok, ein reboot vom Qnap System hat alles geheilt.... seltsam.

<img width="935" alt="2024-02-05 20_00_01-Home · TeslaMate und 1 weitere Seite - Profil 1 – Microsoft​ Edge" src="https://github.com/teslamate-org/teslamate/assets/102554708/1176446d-19ee-4057-a409-b69b95053b42">
