### ISSUE TITLE
Wrong time zone for estimated charge end, TZ environment variable set correctly

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3665]
> > I’m getting the wrong time zone too, and I have the TZ line set correctly. Is there something else to change to get the correct time zone for estimated charge completion?
> 
> Please double-check your value is valid (see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If the error still persists afterward, please open an issue and share your TZ settings.

I believe I double checked and it seems to be correct, and even after restarting Docker/whole Mac, I can't seem to get this to work.

<img width="600" alt="Screenshot 2024-02-08 at 12 12 38 PM" src="https://github.com/teslamate-org/teslamate/assets/39997942/273821c7-81ba-46fc-aa1e-2b940a2db774">

_Originally posted by @PoppyS33d in https://github.com/teslamate-org/teslamate/issues/3646#issuecomment-1934859109_

**Comment by PoppyS33d** [comment]
I'm not really sure what's going on. I'm getting help over on TMC as well, and it's a very bizarre thing. Still not any closer to figuring out why it's being finicky for me!

**Comment by JakobLichterfeld** [comment]
Just to double-check: Your system time is correct?

**Comment by PoppyS33d** [comment]
Yes, it's correct. All car trips etc are correct times, too.

**Comment by JakobLichterfeld** [comment]
> All car trips etc are correct times, too.

That's a different story as grafana uses your browser's timezone.

**Comment by PoppyS33d** [comment]
I see. Well, either way, correct system time. One thing that's peculiar that I can't figure out. I renamed the yml file and rebooted Docker, and TeslaMate still works. That would indicate that the yml I'm using is not the "right" one, yes? Well, 

NAME STATUS CONFIG FILES
teslamate running(4) /Users/username/Documents/TeslaMate/docker-compose.yml

That's the only one I have, so.. I just don't get it. :(

**Comment by JakobLichterfeld** [comment]
> I renamed the yml file and rebooted Docker, and TeslaMate still works. That would indicate that the yml I'm using is not the \"right\" one, yes? 

No, as soon as you deployed the docker compose stack you can potentially delete the yml file. Only when you want to change something, restart the containers etc. you need your compose specification.

**Comment by PoppyS33d** [comment]
> > I renamed the yml file and rebooted Docker, and TeslaMate still works. That would indicate that the yml I'm using is not the "right" one, yes?
> 
> No, as soon as you deployed the docker compose stack you can potentially delete the yml file. Only when you want to change something, restart the containers etc. you need your compose specification.

I see. So is that why the TZ line change isn't doing anything? I added the line and restarted Docker, but that's apparently not enough.

**Comment by PoppyS33d** [comment]
Yep that was it. I didn't know I had to run:

`docker compose up -d`

Thanks for all the help. Solved now!
