### ISSUE TITLE
Has edge been updated?

### ISSUE THREAD

**Issue by DrMichael** [teslamate-org/teslamate#3677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running _edge_ image gives the "Endpoint is only available on fleetapi." error. _latest_ image does not.
@JakobLichterfeld are you sure, _egde_ has been updated? It shows version 1.28.2...

### Expected Behavior

Don't show that error.

### Relevant log output

```shell
teslamate-1  | 2024-02-15 12:19:18.695 [info] GET https://owner-api.teslamotors.com/api/1/vehicles -> 412 (178.227 ms)
teslamate-1  | 2024-02-15 12:19:18.695 [warning] TeslaApi.Error / %{"error" => "Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info", "error_description" => "", "response" => nil}
teslamate-1  | 2024-02-15 12:19:18.695 [warning] Could not get vehicles: :unknown
```

### Type of installation

Docker

### Version

1.28.2

**Comment by JakobLichterfeld** [comment]
Good catch, seems like our new CI introduced with #3559 prevent the docker build for edge version, will look into it

**Comment by JakobLichterfeld** [comment]
Resolved, edge version will be build every night from now on

**Comment by JakobLichterfeld** [comment]
Edge has been updated: https://github.com/teslamate-org/teslamate/actions/runs/7925453010
