### ISSUE TITLE
Battery Health not showing on new cars?

### ISSUE THREAD

**Issue by NickWhitNTES** [teslamate-org/teslamate#3686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi all,

Is this expected behaviour?  We have two new M3 2024 units added to the company account, but they (unlike the others) show no data?

![image](https://github.com/teslamate-org/teslamate/assets/82377682/e1fdbcba-fb64-4d7c-8ab9-b898fd0f2a61)

### Expected Behavior

Data, or a warning that more data is required

### Steps To Reproduce

Open page, expect data.

### Relevant log output

```shell
.
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/82377682/8013e6fa-cd46-445a-97ed-5a9627a3d5c4)

### Additional data

.

### Type of installation

Docker

### Version

Latest

**Comment by JakobLichterfeld** [comment]
> Is this expected behaviour

Hi, yes this is the expected bahavior, see the info in the grafana dashboard: 
![image](https://github.com/teslamate-org/teslamate/assets/16510328/74718b0f-8f83-4da1-b2b3-d8c089e572de)
