### ISSUE TITLE
build: bump app base image to fix 'GLIBC_2.34' not found error

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3691]
> I mess around and went back a version of your PR which didn't result in an improvement in my sleep behavior (you're probably right that I need a new 12v). Now trying to pull and run the latest of your PR results in the follow error. The latest from the repo does successfully run, so something specific with the PR. Any ideas?
```/opt/app/erts-14.2.2/bin/erlexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/app/erts-14.2.2/bin/erlexec)```

_Originally posted by @Dhtjf in https://github.com/teslamate-org/teslamate/issues/3084#issuecomment-1960471561_

> My suspicion is now on the github action that builds the image. 
I haven't look that much into it, but there is a new version, which might have changed something:

> ![image](https://github.com/teslamate-org/teslamate/assets/36691199/54d4d3ff-88e7-47d4-a154-687f7dd6ef51)

> The right one works.
> The left one fails with: ```/opt/app/erts-14.2.2/bin/erlexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/app/erts-14.2.2/bin/erlexec```

_Originally posted by @micves in https://github.com/teslamate-org/teslamate/issues/3084#issuecomment-1960942327_
          
>  Edge appears to also have the GLIBC_2.34 error.

_Originally posted by @DrMichael in https://github.com/teslamate-org/teslamate/issues/3084#issuecomment-1963714201_
            

> I can take a look into the ghcr builds next week

_Originally posted by @JakobLichterfeld in https://github.com/teslamate-org/teslamate/issues/3084#issuecomment-1962870110_
            
### Relevant log output

```shell
/opt/app/erts-14.2.2/bin/erlexec: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/app/erts-14.2.2/bin/erlexec)
```

### Type of installation

Docker

### Version

`ghcr.io/teslamate-org/teslamate:pr-3262`

**Comment by JakobLichterfeld** [comment]
Has been an issue in the past, see https://github.com/teslamate-org/teslamate/blob/8e7d514bfd0f6bf5aa487bbe485123239fd3d19e/CHANGELOG.md?plain=1#L384

**Comment by micves** [comment]
Nice find, would it make sense to use debian:latest to avoid similar things in the future? Or could that just cause other issues that we never now when it will change?

And we might have new problems with the build due to the new bookworm image:
https://github.com/teslamate-org/teslamate/actions/runs/8054386860

**Comment by JakobLichterfeld** [comment]
> Nice find, would it make sense to use debian:latest to avoid similar things in the future? Or could that just cause other issues that we never now when it will change?
> 
> And we might have new problems with the build due to the new bookworm image:
> https://github.com/teslamate-org/teslamate/actions/runs/8054386860
> 
> 

No, best practice is to pin all versions. Best would be to build the docker file with nix as it would be really reproducible and declarative.

The new issue is related to #3692

**Comment by JakobLichterfeld** [comment]
Closed by https://github.com/teslamate-org/teslamate/commit/776e7a2739c068d991e9f66b16a4486f8ebcb9b7 (Typo in referenced issue)
