### ISSUE TITLE
Drive state appears as online state while driving.

### ISSUE THREAD

**Issue by refrain** [teslamate-org/teslamate#3698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Model 3 will be driving ("drive" state), but Teslamate only reports the state as "online" state.  Teslamate will correct this at the end of the drive, but during the drive it will only show "online".

### Expected Behavior

State is reported as "drive" state when driving.

### Steps To Reproduce

Look at overview dashboard or states dashboard or trips dashboard during drives.

### Relevant log output

```shell
I pasted the last 150kb of the logs to pastebin:

https://paste.debian.net/hidden/8f0a7eac/
```

### Screenshots

You can see in the screenshot the charge state goes down while online because the car is driving.  My wife is driving home so I know for a fact she's driving.  After she arrives home, it corrects the states.

![Screenshot from 2024-02-27 18-27-36](https://github.com/teslamate-org/teslamate/assets/1521711/ae54bfe2-61e3-41ac-8a86-ef0c59daff15)

![Screenshot from 2024-02-27 18-30-26](https://github.com/teslamate-org/teslamate/assets/1521711/11d4215c-96b7-470f-a773-536077408a28)

### Type of installation

Docker

### Version

v1.28.3

**Comment by JakobLichterfeld** [comment]
TeslaMate web ui shows current state, grafana shows stored values after trip is completed.

**Comment by refrain** [comment]
How come sometimes it shows as "driving" while driving, but other times it shows as "online" while driving?  I'm only bringing this up because it seems inconsistent?

![Screenshot from 2024-03-06 12-53-06](https://github.com/teslamate-org/teslamate/assets/1521711/ca10e068-961c-48c4-a5cb-acd74e2a3a7f)
