### ISSUE TITLE
Internal server error due to "time_zone_not_found"

### ISSUE THREAD

**Issue by Kacper2Kaczmarek** [teslamate-org/teslamate#3700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've updated Teslamate to 1.28.3 a few days ago. Everything's been working fine but today I noticed that it's not possible to load the website as it only shows an "Internal server error" message.

### Relevant log output

```shell
2024-02-28 19:29:45.647 [info] GET /
2024-02-28 19:29:45.654 [info] Sent 500 in 6ms
2024-02-28 19:29:45.655 [error] #PID<0.3027.0> running TeslaMateWeb.Endpoint (connection #PID<0.3007.0>, stream id 2) terminated
Server: 192.168.1.13:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) time_zone_not_found
        (timex 3.7.11) lib/format/datetime/formatter.ex:55: Timex.Format.DateTime.Formatter.lformat!/4
        (teslamate 1.28.3) lib/teslamate_web/live/car_live/summary.html.heex:157: anonymous fn/2 in TeslaMateWeb.CarLive.Summary.render/1
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.14) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
```

### Type of installation

Docker

### Version

v1.28.3

**Comment by cwanja** [comment]
Are you charging at the time of the internal server error? 

Does your Docker file contain the TZ environment variable? 
https://docs.teslamate.org/docs/configuration/environment_variables

[Release 1.28.3](https://github.com/teslamate-org/teslamate/releases/tag/v1.28.3) introduced estimated completion time for charging and we are seeing errors while charging.

**Comment by Kacper2Kaczmarek** [comment]
> Are you charging at the time of the internal server error?

I checked both while charging and not, it didn't change anything.
> Does your Docker file contain the TZ environment variable? https://docs.teslamate.org/docs/configuration/environment_variables

Yes, it does. `TZ=PL`

**Comment by cwanja** [comment]
Try adding TM_TZ and restart the container. Reference #3678

**Comment by Kacper2Kaczmarek** [comment]
Well, it turns out I was wrong. I actually have 2 cars connected to Teslamate and by checking Grafana I've just found out that the one that my father drives was being charged when I was getting this error. 

Now that both cars are not being charged, the website loads fine, so it seems that this is indeed related to the estimated completion time feature.

**Comment by brianmay** [comment]
Adding `TM_TZ` will not help here. There is no code inside TeslaMate that looks at `TM_TZ`. If you remove `TZ` and replace it with `TM_TZ` then you haven't actually set the timezone.

The key problem here is that `PL` is not a valid TZ identifier.

Look at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones I think the correct value is "Poland".

```
iex(4)> Timex.Timezone.get("PL")
{:error, :time_zone_not_found}
iex(5)> Timex.Timezone.get("Poland")
#<TimezoneInfo(Poland - CET (+01:00:00))>
```

**Comment by cwanja** [comment]
Great catch @brianmay, thank you.

**Comment by Kacper2Kaczmarek** [comment]
> The key problem here is that `PL` is not a valid TZ identifier.
> 
> Look at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones I think the correct value is "Poland".

It seems like this is the solution, I'll test it soon. I think the most appropriate value would be "Europe/Warsaw" but both should work.

**Comment by Kacper2Kaczmarek** [comment]
I can confirm that the invalid identifier was the problem. I've changed it to Europe/Warsaw and everything works now :)

**Comment by rhapgood** [comment]
Please note that when setting your TZ env you can't have it in quotes.
eg. In a Docker compose
      - TZ="Australia/Brisbane"
Fails, but
      - TZ=Australia/Brisbane
Works.

**Comment by juergen852** [comment]
Cool, but hard to know...
Got a [info] Tzdata has updated the release from 2024b to 2025b when using -TZ= without the ", so seems OK.

Proposal:
Add time zone entry to the example docker compose in the documentation.
https://docs.teslamate.org/docs/installation/docker/
This might also help many others.

**Comment by juergen852** [comment]
Using just - TZ=Europe/Berlin **without apostrophe** solves the problem.

Proposal:
Add TZ-entry  to the  docker compose example file at https://docs.teslamate.org/docs/installation/docker/
Might also help others.
