### ISSUE TITLE
Dynamically varying the polling frequency

### ISSUE THREAD

**Issue by TesLocker** [teslamate-org/teslamate#3722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Thank you to all contributors of this incredible project! My understanding is that (when not waiting for the car to sleep) the polling mechanism is used every 15 seconds, regardless of whether the streaming API is connected or not.  I am not able to change the 15 second frequency, such as via Home Assistant using the Home Assistant TeslaMate Integration.

### Expected Behavior

I would like to reduce the polling frequency (e.g., to every 30 seconds) when the vehicle is not within .5 miles of my home, as the accuracy of logged data is not critical in those instances.  However, when the vehicle is within .5 miles of my home, I would like to increase the frequency (e.g., to every 7 seconds) to get more reliable location data, as the streaming API frequently does not work.  Any way to do this?

### Relevant log output

```shell
N/A
```

### Screenshots

Here is an example of when the streaming API does not work after the vehicle has stopped for 10minutes (between 21:10 and 21:20) and the polling mechanism is used for at least the next 10 minutes (between 21:20 and 21:30).
![Screenshot 2024-03-04 at 9 49 32 PM](https://github.com/teslamate-org/teslamate/assets/111825925/19997bd1-24eb-4968-8ed1-ec271a9c867b)

### Type of installation

Docker

### Version

v1.28.3

**Comment by JakobLichterfeld** [comment]
Increasing polling will result in too many requests to Tesla Servers and no data will be available.

**Comment by TesLocker** [comment]
Thanks for the feedback.  Sounds like this is something that has been considered in the past and intentionally not implemented.  I will close this out.
