### ISSUE TITLE
switch netcat-traditional to netcat-openbsd for IP v6 support

### ISSUE THREAD

**Issue by czras** [teslamate-org/teslamate#3731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When updating the base image to bookworm, the `netcat-traditional` package installed does not support IPv6 networking. This results in the enrypoint script stuck at waiting for the database to come up, as netcat tries to resolve the database host on IP v4, where it does not listen.

### Expected Behavior

use a netcat which supports IPv6: `netcat-openbsd`

### Relevant log output

```shell
loads of:

`echo waiting for postgres at czras-postgres.internal:5432`
```

### Type of installation

Manual

### Version

master

**Comment by JakobLichterfeld** [comment]
Thanks for reporting, good catch!
