### ISSUE TITLE
Battery health issue

### ISSUE THREAD

**Issue by MarcFinns** [teslamate-org/teslamate#3735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have two tesla cars (Model 3 and Model Y) on the same account, for years.
Recently I noticed that the battery health for the Model 3 shows "No data" and the Battery capacity by mileage shows "Cannot read properties of undefined (reading 'x')".
The Model Y still displays correctly.
In the discussion I found a comment stating that this happens when data is not yet collected. However, the car is over 4 years old and has driven about 100k Km. The function always worked in the past.

 

### Expected Behavior

Health stats should be displayed...

### Steps To Reproduce

Go to battery health dashboard.
Select the car of interest.
One works, the other gives the error above.

### Relevant log output

```shell
Nothing relevant appears in the log when invoking the dashboard.
I am willing to provide any info that might be useful.
```

### Screenshots

![2024-03-11_15-20-21](https://github.com/teslamate-org/teslamate/assets/24367661/51c8b03b-637b-47a1-bf06-7053dcbf64b5)

### Type of installation

Docker

### Version

1.28.3

**Comment by cwanja** [comment]
Can you click on one of the 'No data' tiles and tell me what the error says? Wondering if the dashboard is having issues with the second vehicle.

**Comment by cwanja** [comment]
@jheredianet any thoughts on this? Looks like the 3 is causing issues, but was the original car. As such, the ID 2 would not be an issue.

**Comment by MarcFinns** [comment]
Breaking news: today battery health stats came back. I did not change anything, apart from charging. There might be a data dependent bug somewhere...

**Comment by jheredianet** [comment]
Sorry for my late reply. I was very busy these days.
I'm glad it's working again. Actually, the Battery Health dashboard depends on charges to show data and make the maths. 
So, I guess you had a charge session without closing it. It usually happens when the car loses Internet connection.
You may browse your data and find for that info without closing (both drives and charges), that's why TM has a way to fix them as explained here https://docs.teslamate.org/docs/maintenance/manually_fixing_data

**Comment by MarcFinns** [comment]
Thanks all for your comments and suggestions

**Comment by cwanja** [comment]
Thanks @jheredianet! Let's proceed to close if resolved @MarcFinns. Thanks.
