### ISSUE TITLE
efficiency field of table cars is empty

### ISSUE THREAD

**Issue by gslshbs** [teslamate-org/teslamate#3788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've been using teslamate for about a month, with 1000+ km logged distance, and number of charges is 6.
Consumption and Efficiency is empty in some Dashboards.

efficiency dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/1252252/993e9274-40ec-4b08-ae7a-92e630f0d405)

drives dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/1252252/d9142b23-168c-4953-9d02-b0d13985e1a9)

trip dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/1252252/82fe40bb-ac3d-4aef-8a5d-d1ce69053d31)

battery-health-lfp dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/1252252/46c9dbe7-faf1-4832-9294-e1fc049b8b18)

I dived into and found that the problem is, the efficiency filed of table cars is empty.
![image](https://github.com/teslamate-org/teslamate/assets/1252252/18e6b718-a301-45b0-b46b-befc65eb2850)

I found the FAQ page has some explanation about this: https://docs.teslamate.org/docs/faq/#why-are-no-consumption-values-displayed-in-grafana

But I already have 6 charging sessions and the charging sessions have been longer than 10 minutes and less than 95% state-of-charge (SoC).

Sorry but I don't have experience about  Elixir so can't figure out the problem.

### Expected Behavior

efficiency filed of table cars is not to be empty.

### Relevant log output

```shell
None
```

### Screenshots

list of charges records:
![image](https://github.com/teslamate-org/teslamate/assets/1252252/e32c8339-c237-4fbe-b4ee-f97fbd1ba17e)

### Type of installation

Docker

### Version

1.28.5

**Comment by cwanja** [comment]
> Charging sessions have to be longer than 10 minutes and less than 95% state-of-charge (SoC).

All of your charges go to 100%. Perform two charge sessions to 95% and report back.

**Comment by gslshbs** [comment]
> > Charging sessions have to be longer than 10 minutes and less than 95% state-of-charge (SoC).
> 
> All of your charges go to 100%. Perform two charge sessions to 95% and report back.

I have solved the problem following the method you suggested. Thx~ @cwanja
