### ISSUE TITLE
how to update to 1.28.5 from 1.28.3

### ISSUE THREAD

**Issue by beramodes** [teslamate-org/teslamate#3796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

teslamate:latest container tag of Digest is different which i downloaded it(1.28.5).
RIghtnow,  downloaded teslamate:latest container ID is "3eb006e9b7836210d4f2bdf993b2dbafc9fa81ccac4f33ae1ef4f5f58ad2a380".

Update is not working.
Just staying in 1.28.3 version.

### Relevant log output

```shell
nolog.
```

### Type of installation

Docker

### Version

1.28.3

**Comment by beramodes** [comment]
![2024-04-01 163819](https://github.com/teslamate-org/teslamate/assets/47095492/7d29193c-772a-41e1-9b44-35c6ed9be5b9)

**Comment by brianmay** [comment]
Not sure I understand? Why is this a problem?

**Comment by brianmay** [comment]
Also note that the digest and image id are two very different values:

```
docker image ls --digests  docker.io/teslamate/teslamate
REPOSITORY                     TAG         DIGEST                                                                   IMAGE ID      CREATED     SIZE
docker.io/teslamate/teslamate  latest      sha256:aa3f37ecccc7ea77fa1e259391c8f2a05533e208228a42ebb4dbe560828db057  3eb006e9b783  7 days ago  187 MB
```

**Comment by beramodes** [comment]
I'm sorry. I just said “no” without any prior explanation.
I tried to receive new “teslamate images” that updated the existing 1.28.3 to 1.28.5 using the “docker compose pull” command. However, after the pull, the image I downloaded thinking it was 1.28.5 was not the "sha256:aa3f3" I wanted.

**Comment by brianmay** [comment]
Like I said above, I think you are getting the image ID confused with the digest.

The digest is aa3f37ecccc7ea77fa1e259391c8f2a05533e208228a42ebb4dbe560828db057

The image id is 3eb006e9b783*

This is the same image.

**Comment by JakobLichterfeld** [comment]
> However, a message still appeared on my web-UI telling me to update, so I thought it was an image problem.

You need to run `docker compose up -d` after the `docker compose pull`, see https://docs.teslamate.org/docs/upgrading

**Comment by beramodes** [comment]
haha.  Of course, I implemented it according to the manual, and thankfully I have been using Tesla Mate for over 3 years.  I asked GitHub, but I didn't expect you to respond like this.  Please just close the issue.
