### ISSUE TITLE
Health report , wrong calculation

### ISSUE THREAD

**Issue by merlinfive** [teslamate-org/teslamate#3815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In previous dashboards the Max Range (new) was correct ( S Plaid 21" , new 560Km), 
in the actual Version Max range (new) is now 616Km (which is correct for 19")
max range (now) is correct for my car with 21" (540Km) , so the Max range (new) seems wrong 

![image](https://github.com/teslamate-org/teslamate/assets/101570702/47db0e3b-f435-4fff-9d97-21bfc37f4e23)

### Expected Behavior

Max range (new) seems wrong 

### Relevant log output

```shell
see screenshot
```

### Type of installation

Docker

### Version

v1.27.5

**Comment by cwanja** [comment]
@jheredianet is this similar to #3787 resolved in PR #3795 ?

**Comment by cwanja** [comment]
Will be resolved in a future TeslaMate release. Thanks Juan.
