### ISSUE TITLE
Data while driving is updated much less frequently than before

### ISSUE THREAD

**Issue by roughwood** [teslamate-org/teslamate#3817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've noticed recently that when looking at drive data, the data points (particularly on the map) are updated much less frequently than before. It appears that my car location is only updated every 10-15 seconds, resulting in jagged lines across the map instead of lines that follow the true path of the vehicle. When I go back to older drives, the more precise data points are there. Has something changed with the API?

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

1.28.5

**Comment by roughwood** [comment]
![image](https://github.com/teslamate-org/teslamate/assets/7537179/aadbcb3c-d891-41cf-9a33-1577334e2dcc)

**Comment by cwanja** [comment]
Are all of your **new** drives like this or a subset of drives? 

> Has something changed with the API?

No, but I have seen even back to back drives have different polling rates. There was a discussion or issue where we were chatting about the intermittent nature of this and not sure if it is TeslaMate or Tesla's API doing the limiting. But nothing fundamental has changed from TeslaMate.

**Comment by roughwood** [comment]
It does appear to be a subset. Some drives appear normally. I would say about 75% of my recent drives display this behavior though.

**Comment by cwanja** [comment]
> It does appear to be a subset. Some drives appear normally. I would say about 75% of my recent drives display this behavior though.

What does the TeslaMate logs say during the drives where they show jagged position data?

**Comment by JakobLichterfeld** [comment]
I assume this is the Tesla API rate limit

**Comment by brianmay** [comment]
Everything here would seem to suggest that streaming was not working for some reason.

Another possibility that I have seen myself is that the car is an an areas with poor mobile coverage.

**Comment by mikec-design** [comment]
I'm also seeing this recently. My visited map is much more "jagged" than it used to be. This is in 1.28.2.

**Comment by woyteck1** [comment]
Hi, I investigated such behaviour before. 

In my case, this was rate limiting by Tesla prior to launch of Giga Berlin.
I think they do it on some occasions, with timing significant to Tesla, as to limit the API access, so their servers are not overwhelmed by potential malicious traffic.

**Comment by JakobLichterfeld** [comment]
closed as Tesla API side not TeslaMate
