### ISSUE TITLE
warning about ipv6 address

### ISSUE THREAD

**Issue by bear0328** [teslamate-org/teslamate#3818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I used Docker of Unraid ,install the teslamate, there are some warnings in the log , I just want to know how to fix it.

### Relevant log output

```shell
Apr  4 10:58:06 Tower kernel: device veth958e6e2 entered promiscuous mode
Apr  4 10:58:07 Tower kernel: eth0: renamed from veth11de857
Apr  4 10:58:07 Tower kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth958e6e2: link becomes ready
Apr  4 10:58:07 Tower kernel: br-47bcf8b68ce6: port 3(veth958e6e2) entered blocking state
Apr  4 10:58:07 Tower kernel: br-47bcf8b68ce6: port 3(veth958e6e2) entered forwarding state
Apr  4 10:58:08 Tower kernel: veth11de857: renamed from eth0
Apr  4 10:58:08 Tower kernel: br-47bcf8b68ce6: port 3(veth958e6e2) entered disabled state
Apr  4 10:58:09 Tower kernel: br-47bcf8b68ce6: port 3(veth958e6e2) entered disabled state
Apr  4 10:58:09 Tower kernel: device veth958e6e2 left promiscuous mode
Apr  4 10:58:09 Tower kernel: br-47bcf8b68ce6: port 3(veth958e6e2) entered disabled state
Apr  4 10:59:08 Tower kernel: br-47bcf8b68ce6: port 3(veth88c90ec) entered blocking state
Apr  4 10:59:08 Tower kernel: br-47bcf8b68ce6: port 3(veth88c90ec) entered disabled state
```

### Type of installation

Docker

### Version

v1.24.1

**Comment by JakobLichterfeld** [comment]
Hi bear0328,

thanks for reporting. I do not see any teslamate log. I assume you will find support for unraid in their support forum.

Current TeslaMate version is 1.28.5 and is supporting ipv6.

**Comment by brianmay** [comment]
I think those messages are just normal informational kernel messages that happen when starting/stoping docker containers causes changes to the network configuration. No warnings or errors here.
