### ISSUE TITLE
Unable to start teslamate normally

### ISSUE THREAD

**Issue by zhoubingyi** [teslamate-org/teslamate#3825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

teslamate will keep restarting

### Relevant log output

```shell
Crash dump is being written to: erl_crash.dump...done
=CRASH REPORT==== 9-Apr-2024::03:45:44.798262 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.84.0>
    registered_name: []
    exception exit: {bad_return,
                     {{elixir,start,[normal,[]]},
                      {'EXIT',
                       {undef,
                        [{erlang,nif_error,
                          [undef],
                          [{error_info,#{module => erl_erts_errors}}]},
                         {prim_tty,isatty,1,
                          [{file,"prim_tty.erl"},{line,1261}]},
                         {elixir,start,2,[{file,"src/elixir.erl"},{line,62}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,293}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 142)
    ancestors: [<0.83.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.85.0>,normal}]
    links: [<0.83.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 28
    reductions: 220
  neighbours:

Runtime terminating during boot ({{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{undef,[{erlang,nif_error,[undef],[{error_info,#{module=>erl_erts_errors}}]},{prim_tty,isatty,1,[{file,"prim_tty.erl"},{line,1261}]},{elixir,start,2,[{file,"src/elixir.erl"},{line,62}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}}}},[{'Elixir.Config.Provider',boot,1,[{file,"lib/config/provider.ex"},{line,207}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

### Type of installation

Mac M2
Docker

### Version

v1.28.5

**Comment by JakobLichterfeld** [comment]
Hi zhoubingyi,
thanks for reporting.

May you elaborate on your Docker installation on your Mac M2 a bit? Are you using docker desktop? Which docker compose do you use? May you share your docker-compose.yml (without your secrets).

**Comment by zhoubingyi** [comment]
I using OrbStack.
The issue arose after I upgraded Teslamate. It was running normally before this.


docker-compose.yml ：

`
version: "3"

services:
  teslamate:
    image: dhuar/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=tesla
      - DATABASE_USER=teslamate
      - DATABASE_PASS=tesla
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all
      
  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=tesla
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: dhuar/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=tesla
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
`

**Comment by JakobLichterfeld** [comment]
> image: dhuar/teslamate:latest

First catch: you are not using teslamate image

**Comment by JakobLichterfeld** [comment]
> This is the Chinese version of Teslamate

**It is NOT.**

As TeslaMate has native translation for Chinese this is not correct nor does this correlate to the official teslamate.
