### ISSUE TITLE
No car information after successful login.

### ISSUE THREAD

**Issue by parmeetdx** [teslamate-org/teslamate#3829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Did a fresh setup on Synology. Everything looks up and running. Upon entering the refresh and API token, I found a successful login, but it doesn't seem to show any information.

<img width="1005" alt="image" src="https://github.com/teslamate-org/teslamate/assets/16869639/eb507c94-7d45-4cdc-ade5-0f23c630f753">

### Relevant log output

```shell
NA
```

### Type of installation

Docker

### Version

1.28.1

**Comment by cwanja** [comment]
What do the logs say? Is there a reason you are not running the latest version?
