### ISSUE TITLE
Tesla Tokens (Android) is no longer available.

### ISSUE THREAD

**Issue by mywind2020** [teslamate-org/teslamate#3830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Tesla Tokens (Android) is no longer available. After logging in, it prompts "login failed". This problem has been going on since January 2024.
[Tesla Tokens (Android)](https://play.google.com/store/apps/details?id=net.leveugle.teslatokens)

### Relevant log output

```shell
teslamate_1  | 2024-04-10 03:08:04.813 car_id=1 [info] Creating new connection … 
teslamate_1  | 2024-04-10 03:08:04.813 car_id=1 [info] Disconnecting ...
teslamate_1  | 2024-04-10 03:08:04.818 car_id=1 [info] Connecting ...
teslamate_1  | 2024-04-10 03:13:02.464 car_id=1 [info] Fetching vehicle state ...
teslamate_1  | 2024-04-10 03:13:02.902 car_id=1 [info] Start / :asleep
teslamate_1  | 2024-04-10 03:13:02.920 car_id=1 [info] Disconnecting ...
teslamate_1  | 2024-04-10 05:59:15.587 [info] Refreshing access token ...
teslamate_1  | 2024-04-10 05:59:15.866 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (278.471 ms)
teslamate_1  | 2024-04-10 05:59:15.898 [info] Scheduling token refresh in 6 h
```

### Screenshots

![20240410-152932](https://github.com/teslamate-org/teslamate/assets/64183208/bf156d10-6f37-40f6-869e-49cbba8371bd)

### Type of installation

Docker

### Version

v1.28.5

**Comment by mywind2020** [comment]
Use this open-source app instead.

https://github.com/mywind2020/TeslaAuth

**Comment by brianmay** [comment]
Or this one: https://github.com/adriankumpf/tesla_auth

**Comment by JakobLichterfeld** [comment]
I'm a bit on my toes on this one. The Android app Tesla Tokens has been removed from the Play Store. The user reports that it doesn't work and then suggests using another open source app created by himself without disclosing this.
