### ISSUE TITLE
Statistics and Trip display are inconsistent

### ISSUE THREAD

**Issue by Fred3343** [teslamate-org/teslamate#3832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the statistics display, the Distance displayed on April 9, 2024 is 2km, but when I clicked on the date to enter the interface of that day, my actual Distance was 77.9 km. I had this problem recently
![image](https://github.com/teslamate-org/teslamate/assets/130917630/cd897498-8105-4d34-b160-d797a8d08dec)
![image](https://github.com/teslamate-org/teslamate/assets/130917630/42d154df-375e-4905-8d45-c69182a7ffe5)

### Expected Behavior

I think they're a match. I was fine

### Relevant log output

```shell
teslamate_1  | waiting for postgres at database:5432
teslamate_1  | 2024-04-10 09:40:29.886 [info] Migrations already up
teslamate_1  | 2024-04-10 09:40:34.112 [info] System Info: Erlang/OTP 26 (jit)
teslamate_1  | 2024-04-10 09:40:34.112 [info] Version: 1.28.3
teslamate_1  | 2024-04-10 09:40:34.685 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (492.022 ms)
teslamate_1  | 2024-04-10 09:40:34.685 [info] Refreshed api tokens
teslamate_1  | 2024-04-10 09:40:34.690 [info] Scheduling token refresh in 6?h
teslamate_1  | 2024-04-10 09:40:34.696 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate_1  | 2024-04-10 09:40:34.699 [info] Access TeslaMateWeb.Endpoint at http://localhost
teslamate_1  | 2024-04-10 09:40:34.978 [info] GET /settings
teslamate_1  | 2024-04-10 09:40:35.007 [info] Sent 200 in 27ms
teslamate_1  | 2024-04-10 09:40:35.098 [info] Starting logger for '换新版 Model 3'
teslamate_1  | 2024-04-10 09:40:35.117 [info] MQTT connection has been established
teslamate_1  | 2024-04-10 09:40:35.305 car_id=1 [info] Start / :asleep
teslamate_1  | 2024-04-10 09:40:38.760 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 01 Feb 2024 18:40:48 GMT.
teslamate_1  | 2024-04-10 09:40:41.038 [info] Tzdata has updated the release from 2021e to 2024a
teslamate_1  | 2024-04-10 09:45:35.349 [info] Update available: 1.28.3 -> 1.28.5
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/130917630/2ecd17d7-72bb-49bf-96a6-210eb8a24c01)

![image](https://github.com/teslamate-org/teslamate/assets/130917630/bce4852b-3214-4552-a98b-a2da145b4132)

### Type of installation

Docker

### Version

1.28.3

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. Please use latest version, which is as of now 1.28.5

**Comment by JakobLichterfeld** [comment]
Additional your second screenshot shows timeframe from 2024-04-09 till 2024-04-10

**Comment by JakobLichterfeld** [comment]
I'm not able to reproduce on 1.28.5

**Comment by DrMichael** [comment]
Hmmm, interesting. In the first screenshot of drives, there is an entry as of 2024/09/04 01:... of 35km.  Although the range does not include that time. Difficult to track that down, when not in Shangai timezone...

**Comment by Fred3343** [comment]
> Hmmm, interesting. In the first screenshot of drives, there is an entry as of 2024/09/04 01:... of 35km. Although the range does not include that time. Difficult to track that down, when not in Shangai timezone... If the system/browser timezone is also Asia/Shanghai, the daily stats should start at 00:00, not 08:00. @Fred3343 can you please check the timezone setting in `Home->Administration->General->Default preferences`

Thank you for your answer. My default time zone is Shanghai, which has been shown as 8:00 when I first deployed it

**Comment by Fred3343** [comment]
> Additional your second screenshot shows timeframe from 2024-04-09 till 2024-04-10

Thank you. Yes, the content shown in the second picture is correct.

**Comment by Fred3343** [comment]
Please note that I also found a problem, this problem may not be important, my server time zone is Shanghai, but the data stored in my database is not saved according to the time of Shanghai, my browser time zone is also Shanghai. I don't know if this is normal.

**Comment by DrMichael** [comment]
I am a bit confused, why Grafana says CST as timezone...
![image](https://github.com/teslamate-org/teslamate/assets/8087682/bb271177-ab6d-4b9c-8bd8-55499778d536)

**Comment by Fred3343** [comment]
> I am a bit confused, why Grafana says CST as timezone... ![image](https://private-user-images.githubusercontent.com/8087682/321572280-bb271177-ab6d-4b9c-8bd8-55499778d536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjcyMDUsIm5iZiI6MTcxMjgyNjkwNSwicGF0aCI6Ii84MDg3NjgyLzMyMTU3MjI4MC1iYjI3MTE3Ny1hYjZkLTRiOWMtOGJkOC01NTQ5OTc3OGQ1MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDkxNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2VkNDA5ZDQ2N2M3MTQwYjFhZjlhNzYxMjY0ZGI2NjQzYWM4ZmQ1MWY1ZmQ5YjY0YTAzOGVkZWEwMWQyZjU1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1zTnKVjxybZ6Pu1fGGsi4vsDhgmgxwCtQoHaKaZV7tw)
> 
> (Ah, date and times in the database are stored in UTC, I think to remember.)

In Grafana's time bar, the CST is always displayed

**Comment by DrMichael** [comment]
When you click on the range, you should get information about the timezone used:
![image](https://github.com/teslamate-org/teslamate/assets/8087682/7b368eb4-76e8-4030-a7e5-cc6d164755ed)

**Comment by DrMichael** [comment]
PR created https://github.com/teslamate-org/teslamate/pull/3862. Please test and discuss there.

**Comment by DrMichael** [comment]
@Fred3343 could you test latest version https://github.com/DrMichael/teslamate/blob/master/grafana/dashboards/statistics.json?

**Comment by Fred3343** [comment]
> @Fred3343 could you test latest version https://github.com/DrMichael/teslamate/blob/master/grafana/dashboards/statistics.json?

I tested the statistics.json and I'm sure it works, thanks
