### ISSUE TITLE
feat request: velocity histogram in drive dashboard

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#3835]
In the Drive Dashboard a velocity histogram would be nice.

Screenshots see: https://tff-forum.de/t/einsteiger-teslamate-oder-teslalogger/140361/413?u=ghostreader

### Type of installation

Docker

### Version

v1.28.5

**Comment by swiffer** [comment]
https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards?tab=readme-ov-file#speed-rates

similar to this, right?

**Comment by JakobLichterfeld** [comment]
> similar to this, right?

Yeah, this even looks better imo

**Comment by jheredianet** [comment]
> @swiffer, @jheredianet, @tobiasehlert What do you think about a velocity histogram in drive dashboard?

Hi, sure. Sometime ago, I found myself in the need to know the maximum and minimum speed of a trip in which I was doing some consumption tests and that is why I was inspired and developed this dashboard https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards?tab=readme-ov-file#speed-rates which you just mentioned @swiffer 

So, I guess you're are suggesting to incluide it in TM as I did with the Battery Health, right? ;-)

**Comment by cwanja** [comment]
PS this should have been a discussion and not an issue 😜

**Comment by jheredianet** [comment]
> PS this should have been a discussion and not an issue 😜

I second that ;-)

**Comment by cwanja** [comment]
Not to hijack this thread entirely, but is there a chance to discuss merging parts of your visuals @jheredianet into our native dashboards? Think our dashboards use too many line charts and there are better visuals out there.

**Comment by JakobLichterfeld** [comment]
> So, I guess you're are suggesting to incluide it in TM as I did with the Battery Health, right? ;-)
> 
> Or are you just asking for something like this? (only speeds of one a trip)

The original idea from the german TFF (tesla "drivers" and "firends" forum) was to have the histogram directly in the drive dashboard. 
Your seperate dashboard would be a second step imo.

**Comment by jheredianet** [comment]
> > So, I guess you're are suggesting to incluide it in TM as I did with the Battery Health, right? ;-)
> > Or are you just asking for something like this? (only speeds of one a trip)
> 
> The original idea from the German TFF (tesla “drivers” and “friends” forum) was to have the histogram directly in the drive dashboard. Your separate dashboard would be a second step, imo.

Sure, this is it https://github.com/teslamate-org/teslamate/pull/3836

**Comment by jheredianet** [comment]
> Not to hijack this thread entirely, but is there a chance to discuss merging parts of your visuals @jheredianet into our native dashboards? Think our dashboards use too many line charts and there are better visuals out there.

Yes, sure. From the beginning my idea was that, to enrich the native panels, but when Adrian was very busy a while ago and accepted the PR after many months of waiting, in the meantime, I decided to create my own repository and host all the ideas I had there.

**Comment by jheredianet** [comment]
> Not to hijack this thread entirely, but is there a chance to discuss merging parts of your visuals @jheredianet into our native dashboards? Think our dashboards use too many line charts and there are better visuals out there.

@cwanja  I've just started to merge some dashboards, take a look of this: https://github.com/teslamate-org/teslamate/pull/4031
