### ISSUE TITLE
Timeline kWh is incorrect for miles

### ISSUE THREAD

**Issue by sdwalker** [teslamate-org/teslamate#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Timeline kWh is incorrect for miles due to the missing 1.60934 multiplication for driving and parking

### Relevant log output

```shell
N/A
```

### Screenshots

Most recent drive
![image](https://github.com/teslamate-org/teslamate/assets/904020/62f3b5a9-2d69-4e03-96d0-d7a0ca11a33a)

Without multiplication
![image](https://github.com/teslamate-org/teslamate/assets/904020/2e2fd2c5-816a-47eb-a563-dfcddfa48fc4)

With multiplication
![image](https://github.com/teslamate-org/teslamate/assets/904020/a2607be8-ff32-4981-80dc-6755598abd6b)

### Type of installation

Manual

### Version

v1.28.6-dev

**Comment by JakobLichterfeld** [comment]
related PR #3847
