### ISSUE TITLE
Statistics temperature color missing for Fahrenheit

### ISSUE THREAD

**Issue by sdwalker** [teslamate-org/teslamate#3853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The statistics temperature colors are missing when Fahrenheit units are used

### Relevant log output

```shell
N/A
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/904020/17269f68-8496-4643-b1cf-07cc231ec4e6)

### Type of installation

Manual

### Version

v1.28.6-dev

**Comment by cwanja** [comment]
I will pull my comment from the PR here for broader discussion. 

My only concern with this is the 'colors' vary by region. Red at 70° in South Texas is wrong. Should be green. Not sure an ideal fix.

**Comment by DrMichael** [comment]
:-) Well, indeed some temperatures are warm in Norther Europe, which are regarded as very cold in Southern Europe.
Perhaps we should set the threshold according to the Celsius thresholds?

- Celsius 20 - Fahrenheit 68
- Celsius 10 - Fahrenheit 50
- Celsius 0 - Fahrenheit 32

?
