### ISSUE TITLE
Statistics dashboard link via other dashboards does not pass TZ into URL 

### ISSUE THREAD

**Issue by cwanja** [teslamate-org/teslamate#3858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Related to #3857, the Statistics dashboard link in the dropdown of dashboards within other Grafana dashboards does not pass the TZ variable into the URL. As such, the Statistics dashboard loads with the default Berlin timezone if accessed from another dashboard within Grafana.

### Expected Behavior

Link respects the TZ variable the user has configured, similar to the link off of TeslaMate homepage. 

**TeslaMate home page code**
https://github.com/teslamate-org/teslamate/blob/c833a30323f6d014f56e4b9a86e0be9ca8d7f8b1/assets/js/main.js#L22

### Steps To Reproduce

1. Go to TeslaMate and launch the Statistics dashboard and note your timezone. **Should** match your TZ variable in docker-compose.yml
2. Load another dashboard
3. Using the dropdown in the right corner, select Statistics and note that the dashboard loads **without** your TZ variable and defaults to Berlin.

### Relevant log output

```shell
N/A
```

### Screenshots

From Grafana dashboard:
![image](https://github.com/teslamate-org/teslamate/assets/54645561/e554d278-8ff2-492d-95b6-eb3cb0bad172)

From TeslaMate home page:
![image](https://github.com/teslamate-org/teslamate/assets/54645561/2779423c-c479-48c7-9eda-6852c34ea0d3)

### Type of installation

Docker

### Version

1.28.5

**Comment by cwanja** [comment]
@DrMichael or @jheredianet can either of you take a look at this?

**Comment by jheredianet** [comment]
> @DrMichael or @jheredianet can either of you take a look at this?

Yes, I've reproduced that behaviour. I don't know why "statics" dashboard is the only one having the Time zone selector. I think it's not necessary and should be removed. No dashboard needs the time zone selector since Grafana itself has that feature and by default the browser's time zone is activated:

![image](https://github.com/teslamate-org/teslamate/assets/45735191/1b79fa0b-914f-45d2-8139-faecc3bf83be)

**Comment by DrMichael** [comment]
Ah, I wrote the dashboard some four years ago. I remember, that I had a heavy struggle with the timezones... I think, (To get days started at 00:00 local time.) Grafana did not take the browser timezone then. So, could well be, that it is not necessary anymore.
I will have a look into it in the coming days.

**Comment by cwanja** [comment]
Thanks @DrMichael

**Comment by cwanja** [comment]
> > @DrMichael or @jheredianet can either of you take a look at this?
> 
> 
> 
> Yes, I've reproduced that behaviour. I don't know why "statics" dashboard is the only one having the Time zone selector. I think it's not necessary and should be removed. No dashboard needs the time zone selector since Grafana itself has that feature and by default the browser's time zone is activated:
> 
> 
> 
> ![image](https://github.com/teslamate-org/teslamate/assets/45735191/1b79fa0b-914f-45d2-8139-faecc3bf83be)
> 
> 

Thanks @jheredianet sounds like an easy removal of the time zone selector is in order from the dashboard and in the code if I found the right line.

**Comment by DrMichael** [comment]
Apparently, handing over the timezone in the URL is not yet possible, perhaps in Grafana v11 https://github.com/grafana/grafana/issues/81538

**Comment by cwanja** [comment]
Closing as we have resolved via #3862

**Comment by DrMichael** [comment]
Apparently the Statistics dashboard appears to be the only one, where the uid is hardcoded, in https://github.com/teslamate-org/teslamate/blob/master/assets/js/main.js (I have no idea, how the other hrefs are constructed). The reason for that might have been, that the timezone should be handed over to the dashboard.
Since that is neither possible nor needed, I suggest to remove that code in https://github.com/teslamate-org/teslamate/blob/master/assets/js/main.js
@cwanja @jheredianet Any thoughts?

**Comment by cwanja** [comment]
The others are built in the HTML using the settings and UIDs

lib/teslamate_web/templates/layout/root.html.heex

Although I am not sure where the UIDs are stored or passed. On holiday, but can check in a few days when I get back.

**Comment by DrMichael** [comment]
Ah, I see, title an duid are read from` grafana/dashboards/*.json` in ./lib/teslamate_web/views/layout_view.ex. Should be safe to change the uid then in the dashboard.

**Comment by DrMichael** [comment]
I would have preferred to have the statistics dashboard specific part in https://github.com/teslamate-org/teslamate/blob/master/assets/js/main.js removed. That dealing with timezones is not working.
