### ISSUE TITLE
Error when restoring Teslamate backup

### ISSUE THREAD

**Issue by Trunkzeh** [teslamate-org/teslamate#3861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

postgres reports an error when creating / replacing function public.ll_to_earth(float8, float8):

Error in query: ERROR: syntax error at or near "\"
LINE 1: ...ublic.cube(public.cube(public.earth()*cos(radians(\$1))*cos(...
QUERY: SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth

### Expected Behavior

Restore instructions specify:

docker compose exec -T database psql -U teslamate teslamate << .
drop schema public cascade;
create schema public;
create extension cube;
create extension earthdistance;
CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
    RETURNS public.earth
    LANGUAGE SQL
    IMMUTABLE STRICT
    PARALLEL SAFE
    AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
.

### Relevant log output

```shell
Error in query: ERROR: syntax error at or near "\"
LINE 1: ...ublic.cube(public.cube(public.earth()*cos(radians(\$1))*cos(...
QUERY: SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth
```

### Screenshots

<img width="1449" alt="Screenshot 2024-04-19 at 14 46 10" src="https://github.com/teslamate-org/teslamate/assets/52528608/9c332410-ed91-4a64-9d71-18da7112487b">

### Type of installation

Docker

### Version

v1.28.5

**Comment by Trunkzeh** [comment]
Hey @JakobLichterfeld 

I actually thought something was amiss with psql so have run the entire command in adminer (screenshot above) for good measure and the same issue. To confirm I took the entire SQL command directly from the backup & restore instructions you have linked to above:

```
drop schema public cascade;
create schema public;
create extension cube;
create extension earthdistance;
CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
    RETURNS public.earth
    LANGUAGE SQL
    IMMUTABLE STRICT
    PARALLEL SAFE
    AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
```

**Comment by Trunkzeh** [comment]
See attached SQL query in adminer:
<img width="1266" alt="image" src="https://github.com/teslamate-org/teslamate/assets/52528608/0accdcd4-dcea-40c8-a2f1-6a8e3787f895">

**Comment by JakobLichterfeld** [comment]
> o confirm I took the entire SQL command directly from the backup & restore instructions you have linked to above:

You don't :-) You missed the `.`

**Comment by JakobLichterfeld** [comment]
> Teslamate installed via portainer

This is not a supported installation, as Portainer arise issues like this for no reason.
