### ISSUE TITLE
Distance traveled on drive graph doesn't update is the time range is changed

### ISSUE THREAD

**Issue by Nakatomi2010** [teslamate-org/teslamate#3882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening up the Drives graphs, you can change the timeframe and get a different map, and a different energy use graph, but the four data tips in the upper right remain tied to the drive ID you opened, before you started messing with the time ranges.

When looking at the "distance traveled" box, for example, it uses this:

select convert_km(distance::numeric, '$length_unit') as "$length_unit" from drives where id = $drive_id;

Which I would expect to be tied to the range of the graph, not the drive ID in question.

### Expected Behavior

I would expect all data views on the Drives graph to be able to be changed based on the time ranges being used, not just the drive ID.

### Steps To Reproduce

Go to Drive, pick a drive, change the time ranges.

### Relevant log output

```shell
.
```

### Type of installation

Docker

### Version

12.8.5

**Comment by DrMichael** [comment]
Hmmm, sorry, which dashboard are you talking of? The only "Distance traveled" I can see is in the "Visited" dashboard. And changes in the time range are correctly reflected.

**Comment by Nakatomi2010** [comment]
The Drives dashboard.

When you click on a drive to get the details.

I'm referring to the boxes that are above the map.

**Comment by DrMichael** [comment]
Sorry, can you post a screenshot?

**Comment by Nakatomi2010** [comment]
See attached.

Those four boxes above the map on "Drive details", after you click a drive,
they're not tied to the timeframe chosen for the drive, they're based on
the drive ID

**Comment by DrMichael** [comment]
Sorry, no attachment.
