### ISSUE TITLE
API: non-existing domain (auth.tesla.com and owner-api.teslamotors.com)

### ISSUE THREAD

**Issue by aklira** [teslamate-org/teslamate#3896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Error fetching car data

### Relevant log output

```shell
2024-05-19 08:49:06.025 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "non-existing domain" (5124.268 ms)
2024-05-19 08:49:06.039 [warning] Token refresh failed: %TeslaApi.Error{
  reason: :token_refresh,
  message: "non-existing domain",
  env: nil
}
```

### Type of installation

Docker

### Version

v1.28.5

**Comment by JakobLichterfeld** [comment]
same for https://owner-api.teslamotors.com/

**Comment by JakobLichterfeld** [comment]
> Works in EU

The webserver itself, yes, the API endpoints seem down.

**Comment by JakobLichterfeld** [comment]
Token generation with tesla_auth is possible, but TeslaMate complain tokens not valid, logs show 

> -> error: "non-existing domain"

**Comment by aklira** [comment]
I've made a test to query the tesla auth api with the following query from the same host I am running teslamate:
`curl -sX POST -H "Content-Type: application/json" https://auth.tesla.com/oauth2/v3/token -d @auth.json -w "%{http_code}\n"`

And it works fine, I am getting the correct response content with http code 200

**Comment by JakobLichterfeld** [comment]
For me a flush dns and reboot solved the issue

**Comment by aklira** [comment]
Same thing here for me, a reboot fixed the problem. Issue can ben closed.
