### ISSUE TITLE
Statistics dashboard not working from menu in v1.29.1

### ISSUE THREAD

**Issue by djpalmis** [teslamate-org/teslamate#3899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I select "statistics" from homepage I get this page
![Screenshot_20240520_221217_Samsung Internet](https://github.com/teslamate-org/teslamate/assets/402122/b86ca9ea-4741-4358-889c-007e1a05c44b)
It works if I navigate in graphana

### Steps To Reproduce

1. Click on menu the "Statistics" menu item

### Relevant log output

```shell
nothing is logged when it happens
```

### Type of installation

Docker

### Version

v1.29.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. @DrMichael seems like the statistic dashboard issue was not caused by dangling images in my test case but is a real bug

**Comment by DrMichael** [comment]
Hmmm, I don't know, how the URL in the teslamate page is constructed. It works fine for me.
I change the uid in https://github.com/teslamate-org/teslamate/pull/3862 because Grafana was complaining. I reverted that back in https://github.com/teslamate-org/teslamate/pull/3907. Not sure, whether that is the right way to fix it...

**Comment by woyteck1** [comment]
I am also experiencing this bug.

**Comment by JakobLichterfeld** [comment]
Fix in #3907

**Comment by fischerphilipp** [comment]
FYI as a workaround:
If I select another dashboard and then use the Dashboard selector in the upper righthand corner in the Grafana dashboard (for example if I opened up "States" before) then I can select the Statistics dashboard from there. As mentioned by @JakobLichterfeld in #3907 , the link from the main screen seems to be broken.
![Screenshot 2024-05-24 at 14 43 51](https://github.com/teslamate-org/teslamate/assets/68103956/0bc557d9-4f35-4633-860d-1a837fb50e82)

**Comment by JakobLichterfeld** [comment]
Solved by V1.29.2
