### ISSUE TITLE
URL_PATH not working on breadcrumbs HOME link

### ISSUE THREAD

**Issue by odinms** [teslamate-org/teslamate#3905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/teslamate-org/teslamate/assets/10906256/5e1d8a52-bb98-4f22-863a-bd4f41579118)
1.URL_PATH not showing on Breadcrumbs as pic shows when in settings page. 
2.a JS erro showing in web console in home page.
ENV:
VIRTUAL_HOST=te.xxxx.cn
URL_PATH=/test

### Expected Behavior

click on HOME go to https://te.xxxx.cn/test . 

### Steps To Reproduce

1.go to Settings page.
2.click/hover on home instead of Teslamate logo on Navi 

### Relevant log output

```shell
teslamate-1  | 2024-05-22 13:47:08.481 [info] Migrations already up
teslamate-1  | 2024-05-22 13:47:10.423 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
teslamate-1  | 2024-05-22 13:47:10.524 [info] System Info: Erlang/OTP 26 (jit)
teslamate-1  | 2024-05-22 13:47:10.524 [info] Version: 1.29.1
teslamate-1  | 2024-05-22 13:47:10.810 [info] POST https://auth.tesla.cn/oauth2/v3/token -> 200 (263.530 ms)
teslamate-1  | 2024-05-22 13:47:10.810 [info] Refreshed api tokens
teslamate-1  | 2024-05-22 13:47:10.814 [info] Scheduling token refresh in 6 h
teslamate-1  | 2024-05-22 13:47:10.818 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-1  | 2024-05-22 13:47:10.819 [info] Access TeslaMateWeb.Endpoint at http://te.xxxx.cn
teslamate-1  | 2024-05-22 13:47:11.327 [info] Starting logger for 'xxxx'
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/10906256/5e990ac1-c167-4200-8307-0e28671863d3)
![image](https://github.com/teslamate-org/teslamate/assets/10906256/9e675d91-23dd-45e3-9cb3-e6ed9d7a32d6)

### Type of installation

Docker

### Version

v1.29.1

**Comment by cwanja** [comment]
Do your URL settings match your environment configuration?

**Comment by odinms** [comment]
> Do your URL settings match your environment configuration?

YES.
![image](https://github.com/teslamate-org/teslamate/assets/10906256/ade64e21-a621-4e80-b85c-ea2f7f298214)

**Comment by cwanja** [comment]
Does this also happen on the Geofence page?

**Comment by odinms** [comment]
> Does this also happen on the Geofence page?
yes.
![image](https://github.com/teslamate-org/teslamate/assets/10906256/bfb47735-d197-42fc-88d8-02b4c5236053)


and as mentioned before, a javascript erro showed in web console but no erro showed in geofence or settings page.

**Comment by cwanja** [comment]
@brianmay @jlestel - are either of you proficient in Elixir by chance? I believe the following lines for both `settings` and `geo fences` is the root of the issue. 

**Settings** https://github.com/teslamate-org/teslamate/blob/31cdaac395aa0ad0d59f764d34fb01899c838ce8/lib/teslamate_web/live/settings_live/index.html.heex#L3


**Geo-fences**
https://github.com/teslamate-org/teslamate/blob/31cdaac395aa0ad0d59f764d34fb01899c838ce8/lib/teslamate_web/live/geofence_live/index.html.heex#L3

Both codes reference `/` to go home. But that does not respect if the user has a subfolder configured. Or maybe it should be handled in the users Docker configure since it is in the environment. 

Speculating here, but seeking further guidance. Thanks.

**Comment by brianmay** [comment]
I am a bit vague here apologies if I got this wrong:

I think the problem is `live_redirect` just uses the URL we supply it "as is". We give it a URL of "/", so that is what gets used.

Rather you need to pass it the full path returned by the appropriate helper function, e.g. here is an example I copied from some range page:

```heex
<%= live_redirect String.capitalize("#{city}") , to: Routes.energy_raters_path(@socket, :show, city) %>
```

Obviously you need to use the appropriate helper function.

In addition, recent versions of Pheonix support compile time checking of routes - called verified routes. I don't think TeslaMate uses these at present, but I think they are probably worth it. See links such as https://elixircasts.io/phoenix-verified-routes and https://hexdocs.pm/phoenix/routing.html#verified-routes

I am assuming this should also expand to the correct thing (not checked).

**Comment by cwanja** [comment]
> I am a bit vague here apologies if I got this wrong:
> 
> I think the problem is `live_redirect` just uses the URL we supply it "as is". We give it a URL of "/", so that is what gets used.
> 
> Rather you need to pass it the full path returned by the appropriate helper function, e.g. here is an example I copied from some range page:
> 
> ```
> <%= live_redirect String.capitalize("#{city}") , to: Routes.energy_raters_path(@socket, :show, city) %>
> ```
> 
> Obviously you need to use the appropriate helper function.
> 
> In addition, recent versions of Pheonix support compile time checking of routes - called verified routes. I don't think TeslaMate uses these at present, but I think they are probably worth it. See links such as https://elixircasts.io/phoenix-verified-routes and https://hexdocs.pm/phoenix/routing.html#verified-routes
> 
> I am assuming this should also expand to the correct thing (not checked).

I do believe you are spot on @brianmay, but I do not know Elixir or Phoenix well enough to know a resolution. @swiffer is this an area you are aware of and or can propose a fix?

**Comment by JakobLichterfeld** [comment]
@b1c1l1 Can you please take a look into this, as it is related to your PR #3771. Ty.

**Comment by JakobLichterfeld** [comment]
> In addition, recent versions of Pheonix support compile time checking of routes - called verified routes. I don't think TeslaMate uses these at present

I do think we already use it: https://github.com/teslamate-org/teslamate/blob/63b76779e6d2b59e7e839e550017b8004e9acf29/lib/teslamate_web.ex#L106

**Comment by brianmay** [comment]
I don't have a lot of time right now, but I imagine something like this should work:

```diff
diff --git a/lib/teslamate_web/live/charge_live/cost.html.heex b/lib/teslamate_web/live/charge_live/cost.html.heex
index f40b23e7..0c15e8b4 100644
--- a/lib/teslamate_web/live/charge_live/cost.html.heex
+++ b/lib/teslamate_web/live/charge_live/cost.html.heex
@@ -1,6 +1,6 @@
 <nav class="breadcrumb" aria-label="breadcrumbs">
   <ul>
-    <li><%= live_redirect(gettext("Home"), to: "/") %></li>
+    <li><%= live_redirect(gettext("Home"), to: ~p"/") %></li>
     <li class="is-active"><%= live_redirect(gettext("Charge Cost"), to: "") %></li>
   </ul>
 </nav>
diff --git a/lib/teslamate_web/live/geofence_live/form.html.heex b/lib/teslamate_web/live/geofence_live/form.html.heex
index 17baeddd..245c84c8 100644
--- a/lib/teslamate_web/live/geofence_live/form.html.heex
+++ b/lib/teslamate_web/live/geofence_live/form.html.heex
@@ -1,7 +1,7 @@
 <nav class="breadcrumb" aria-label="breadcrumbs">
   <ul>
-    <li><%= live_redirect(gettext("Home"), to: "/") %></li>
-    <li><%= live_redirect(gettext("Geo-Fences"), to: "/geo-fences") %></li>
+    <li><%= live_redirect(gettext("Home"), to: ~p"/") %></li>
+    <li><%= live_redirect(gettext("Geo-Fences"), to: ~p"/geo-fences") %></li>
     <li class="is-active">
       <a href="#">
         <%= case @action do
diff --git a/lib/teslamate_web/live/geofence_live/index.html.heex b/lib/teslamate_web/live/geofence_live/index.html.heex
index 8bad39d5..0e7e026b 100644
--- a/lib/teslamate_web/live/geofence_live/index.html.heex
+++ b/lib/teslamate_web/live/geofence_live/index.html.heex
@@ -1,7 +1,7 @@
 <nav class="breadcrumb" aria-label="breadcrumbs">
   <ul>
-    <li><%= live_redirect(gettext("Home"), to: "/") %></li>
-    <li class="is-active"><%= live_redirect(gettext("Geo-Fences"), to: "/geo-fences") %></li>
+    <li><%= live_redirect(gettext("Home"), to: ~p"/") %></li>
+    <li class="is-active"><%= live_redirect(gettext("Geo-Fences"), to: ~p"/geo-fences") %></li>
   </ul>
 </nav>

diff --git a/lib/teslamate_web/live/import_live/index.html.heex b/lib/teslamate_web/live/import_live/index.html.heex
index f1becf81..2e398dc8 100644
--- a/lib/teslamate_web/live/import_live/index.html.heex
+++ b/lib/teslamate_web/live/import_live/index.html.heex
@@ -1,6 +1,6 @@
 <nav class="breadcrumb" aria-label="breadcrumbs">
   <ul>
-    <li><%= live_redirect(gettext("Home"), to: "/") %></li>
+    <li><%= live_redirect(gettext("Home"), to: ~p"/") %></li>
     <li class="is-active"><%= live_redirect(gettext("TeslaFi Import"), to: "") %></li>
   </ul>
 </nav>
diff --git a/lib/teslamate_web/live/settings_live/index.html.heex b/lib/teslamate_web/live/settings_live/index.html.heex
index 41715530..30d97a27 100644
--- a/lib/teslamate_web/live/settings_live/index.html.heex
+++ b/lib/teslamate_web/live/settings_live/index.html.heex
@@ -1,7 +1,7 @@
 <nav class="breadcrumb" aria-label="breadcrumbs">
   <ul>
-    <li><%= live_redirect(gettext("Home"), to: "/") %></li>
-    <li class="is-active"><%= live_redirect(gettext("Settings"), to: "/settings") %></li>
+    <li><%= live_redirect(gettext("Home"), to: ~p"/") %></li>
+    <li class="is-active"><%= live_redirect(gettext("Settings"), to: ~p"/settings") %></li>
   </ul>
 </nav>
```

Did I miss anything?

Ideally old links that look like `Routes.live_path(@conn, TeslaMateWeb.SettingsLive.Index)` would be replaced by something like `~p"/settings"` but that isn't important as far as this bug is concerned.

**Comment by JakobLichterfeld** [comment]
> Did I miss anything?

I have not found any other places either. I opened #4052
