### ISSUE TITLE
Please add Baidu Map 

### ISSUE THREAD

**Issue by belugaming** [teslamate-org/teslamate#3915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Please add Baidu Maps API. Chinese users cannot use the default map source. I found Baidu Maps API. Please add it in the next version. We really need it.
https://github.com/badafans/BaiduMap-Tiles-Download

### Relevant log output

```shell
0
```

### Type of installation

Docker

### Version

V1.29.1

**Comment by cwanja** [comment]
Closing as this is not an 'issue' with TeslaMate. See your discussion as an idea.

**Comment by hipudding** [comment]
这个可以做，我这里有一个高德地图的[demo](https://github.com/hipudding/teslamate_fix_addrs/issues/7)，看是否能满足需求？
希望可以一起讨论下，工作量不算大
