### ISSUE TITLE
Battery Health Dashboard Wrong Capacity - LFP

### ISSUE THREAD

**Issue by yigitgungor** [teslamate-org/teslamate#3920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I realized that the battery health dashboards (Battery Health - LFP or Battery Health) do not represent the actual capacity of the Model 3 RWD LFP. The car has a 60.5 kWh gross, 57.5 kWh usable battery. However, both dashboards claim the usable was over 60 kWh when it was new. 

![image](https://github.com/teslamate-org/teslamate/assets/65617039/89077618-04fa-4826-92e8-a364bff6841b)
![image](https://github.com/teslamate-org/teslamate/assets/65617039/0cd61f24-8d99-48d4-87c8-abf5b06f5762)

Source (https://insideevs.com/news/563125/tesla-model3-60kwh-winter-range/)
The car has [about a 60.5 kWh battery], out of which - according to the updated reading by the ScanMyTesla app - 57.5 kWh is usable. That's over 9% more than previously.

Capacity of the full pack (when new): 60.5 kWh (kind of initial/theoretical value)

Nominal full pack capacity: 60.4 kWh (total; net + buffer) vs 55.3 kWh (+9.2%)

Energy buffer: 2.7 kWh or 4.5% vs 2.5 kWh or 4.5% previously (between the current nominal value and usable value)

Usable full pack capacity: 57.5 kWh (net) vs 52.6 kWh previously * at "101% SOC" the ScanMyTesla app shown 58.4 kWh usable, out of 61.1 kWh nominal remaining (the values happens to fluctuate depending on various factors, and should be treated like a good estimate, rather than a perfect value).

### Relevant log output

```shell
N/A
```

### Type of installation

Docker

### Version

v1.29.1

**Comment by JakobLichterfeld** [comment]
LFP Dashboards are outdated, #3438
