### ISSUE TITLE
2024.14.8 - Shows "offline" instead of "asleep"

### ISSUE THREAD

**Issue by wolf39us** [teslamate-org/teslamate#3936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before upgrading to 2024.14.x, Teslamate would correctly identify the vehicle as "asleep" when asleep.  It appears after upgrading that anytime the vehicle is in a sleep state it is reported as "Offline"

I will point out that I have two vehicles that are in the same location.  One is running 2024.3.25 and the other 2024.14.8.  The car on the older version reports everything correctly.

I have also noticed that the Tesla app itself also uses a different term when displaying the vehicle in a sleep state.  It appears to show "asleep for" instead of "last seen"

### Expected Behavior

"Asleep" state should be reported as such

### Steps To Reproduce

Upgrade to 2024.14.x

Wait for vehicle to fall asleep
Check status

### Relevant log output

```shell
2024-06-03 07:13:31.622 [info] Streaming API: Vehicle offline
2024-06-03 07:13:31.622 car_id=1 [warning] Stream reports vehicle as offline, fetching vehicle state ...
2024-06-03 07:13:31.910 car_id=1 [info] Start / :offline
2024-06-03 07:13:31.929 car_id=1 [info] Disconnecting ...
```

### Screenshots

![image](https://github.com/teslamate-org/teslamate/assets/43860704/d0bd40e2-52b9-4a32-bd40-cae54244a899)

### Type of installation

Docker

### Version

v1.29.1

**Comment by wolf39us** [comment]
Here it is in the offline state
![image](https://github.com/teslamate-org/teslamate/assets/43860704/05836b0d-b0b5-4f62-a17b-aa1d7bcd27ea)

**Comment by cwanja** [comment]
This is not entirely an 'issue', and we have a healthy discussion going here #3753. As a product, there is not a decision to start marking 'offline' as sleep. Historically, it was two different states.

**Comment by JongSun84** [comment]
The same problem appears when entering Asleep after the update.

2024.8.9 Asleep / 2024.14.8 Offline

Teslamate 1.29.1
2022 Model 3 (Ryzen)

**Comment by JakobLichterfeld** [comment]
This is not a TeslaMate issue. Tesla API reports "offline" for intel MCUs since 2024.8.3 and for all MCUs (expect MCU2 upgraded) since spring update, 2024.14.x
There are rare cases the Tesla API still report sleep state, if you car falls asleep while charger plugged in in some cases.
