### ISSUE TITLE
grafana maps under drives and charges dashboards are not visible

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#3939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updated dashboards in my grafana custom instance to version in latest master.

The graphs appear completely black on black. However mouse hover shows the correct values are there.

Tried changing to from dark theme to light theme, now graphs appear white on white.

### Expected Behavior

Graphs should appear as before.

### Steps To Reproduce

Go to trip dashboard, and click on drive to go to drive dashboard.

Or go to charges dashboard, and click on charge to go to charge dashboard.

### Relevant log output

```shell
N/A
```

### Screenshots

![screen](https://github.com/teslamate-org/teslamate/assets/112729/a4f690a3-fd11-454e-9442-e2f1af2fb8a9)

### Additional data

Out of time to debug this is more detail right now. Apologies in advance if I have somehow messed up :-)

### Type of installation

Manual

### Version

master

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. Could not reproduce with 1.29.1
![image](https://github.com/teslamate-org/teslamate/assets/16510328/1d5e695d-cdc9-4a8d-8b26-ac722051a7dc)

**Comment by brianmay** [comment]
Firefox 126.0.1
Grafana 10.4.3

WTF? Today it is fine...

I had to reboot my computer for unrelated reasons, maybe restarting Firefox fixed it.

Anyway, nothing wrong with Teslamate, closing.
