### ISSUE TITLE
Tesla restricting api request frequency, leading to multiple malfunctions in Teslamate

### ISSUE THREAD

**Issue by realJustinLee** [teslamate-org/teslamate#3965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Teslamate cannot fetch vital data from Tesla servers due to Tesla has restricted its api query frequency.

### Expected Behavior

Teslamate should fetch data normally from Tesla servers

### Steps To Reproduce

Just simply boot the teslamate services

### Relevant log output

```shell
teslamate-1  | 2024-06-16 07:14:36.061 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/XXXXXXXXXXXXXXX/vehicle_data -> 429 (263.169 ms)
teslamate-1  | 2024-06-16 07:14:36.061 [warning] TeslaApi.Error / :too_many_request 2725
teslamate-1  | 2024-06-16 07:14:36.062 car_id=2 [error] Too many request / Retry after 2725 seconds
```

### Screenshots

N/A

### Additional data

N/A

### Type of installation

Docker

### Version

1.29.2-dev

**Comment by brianmay** [comment]
See #3957
