### ISSUE TITLE
Gafana errors after importing teslamate postgres database

### ISSUE THREAD

**Issue by SemoTech** [teslamate-org/teslamate#3976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**SOLVED!  - SEE HERE:**  https://github.com/teslamate-org/teslamate/issues/3976#issuecomment-2181302937

**Failed attempt to "move" (backup and restore) a full teslamate database between two different hosts (servers)!**  

* The Source host was using CentOS 7 and an older postgres:12 database and was configured for separate FQDN's:
  `teslamate.example.com` & `garfana.example.com`

* The Target host was setup with Ubuntu Server 22.04 and the newest postgres:16 database, as well as one FQDN with a subpath:  
  `tm.example.com` & `tm.example.com/grafana`
  
* Both hosts confirmed running latest Docker (v26.0.0 / v26.1.4) and Docker Compose (vv2.25.0 / v2.27.1) versions.

These are the steps taken with great care and with no errors occurred in the import process, [only in Grafana](https://pastebin.com/H8s8ikLm) when accessing the imported data:

A - Ensured teslamate on Source host was running properly and was recording data from the Tesla API.
B - Upgraded Source host teslamate from v1.29.1 to latest _current_ version of v1.29.2
C - Exported Source host teslamate postgres:12 database into a file without any errors using:
`docker compose exec -T database pg_dump -U teslamate teslamate > teslamate.bck`
D - Deployed a fresh teslamate v1.29.2 environment on the Target host, using postgres:16 and single FQDN for Grafana as `tm.example.com/grafana`
E - Prepared Target host for database import, as follows:
     E1 - Stopped the new `teslamate` container
     E2 - Accessed new postgres:16 DB and issued cleanup commands as per [HERE](https://docs.teslamate.org/docs/maintenance/backup_restore) (with no errors) using:
`docker exec -i teslamate-postgres /bin/bash -c "PGPASSWORD=<TM_DB_PASS> psql --username teslamate teslamate" << .`
Result was:
```
> drop schema public cascade;
> create schema public;
> create extension cube;
> create extension earthdistance;
> CREATE OR REPLACE FUNCTION public.ll_to_earth(float8, float8)
> RETURNS public.earth
> LANGUAGE SQL
> IMMUTABLE STRICT
> PARALLEL SAFE
> AS 'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(\$1))*cos(radians(\$2))),public.earth()*cos(radians(\$1))*sin(radians(\$2))),public.earth()*sin(radians(\$1)))::public.earth';
> .
NOTICE:  drop cascades to 25 other objects
DETAIL:  drop cascades to extension cube
drop cascades to extension earthdistance
drop cascades to type billing_type
drop cascades to type range
drop cascades to type states_status
drop cascades to type unit_of_length
drop cascades to type unit_of_pressure
drop cascades to type unit_of_temperature
drop cascades to function convert_celsius(numeric,text)
drop cascades to function convert_km(numeric,text)
drop cascades to function convert_m(double precision,text)
drop cascades to function convert_tire_pressure(numeric,character varying)
drop cascades to table addresses
drop cascades to table car_settings
drop cascades to table cars
drop cascades to table charges
drop cascades to table charging_processes
drop cascades to table drives
drop cascades to table geofences
drop cascades to table positions
drop cascades to table schema_migrations
drop cascades to table settings
drop cascades to table states
drop cascades to table tokens
drop cascades to table updates
DROP SCHEMA
CREATE SCHEMA
CREATE EXTENSION
CREATE EXTENSION
CREATE FUNCTION
```
F - Imported database backup file copied to Target host (no errors) using:
`docker exec -i teslamate-postgres /bin/bash -c "PGPASSWORD=<TM_DB_PASS> psql --username teslamate teslamate" < teslamate.bck`
Results can be seen [HERE](https://pastebin.com/5U3rMiVJ)
G - Started new `teslamate` container successfully
H - Accessed `tm.example.com` with no Tesla token prompt shown, so it means the original token imported correctly!
I - Manually changed the access paths under teslamate's Settings Page for the cars
From:
![image](https://github.com/teslamate-org/teslamate/assets/1452100/7cc8b471-c6d0-4ea4-bc9c-4c33fc460c08)

To:
![image](https://github.com/teslamate-org/teslamate/assets/1452100/1b3e4f50-86e2-45bb-a0d0-8e645ad60576)

J - Attempted to access the Dashboards which opened up Grafana correctly and using the new path of `tm.example.com/grafana`, but there is no actual data shown only errors like this:

![image](https://github.com/teslamate-org/teslamate/assets/1452100/43179f39-e319-448f-9fc4-f785b3907517)

Followed moments later by a Grafana "Failed to Fetch" Error notice:
![image](https://github.com/teslamate-org/teslamate/assets/1452100/fac07be4-a604-4dc5-8e2f-34c2dfa72316)

K - Checked all containers log files and **_only errors were in the grafana container logs_**, see [HERE](https://pastebin.com/H8s8ikLm) 

L - As a last resort used the pgAdmin manager tool to access the teslamate postgres:16 database, and confirmed the data imported correctly (cars were there, and so was old data), yet something is still broken!

![image](https://github.com/teslamate-org/teslamate/assets/1452100/8048b399-e11c-4c68-9844-645c58ad6748)

**QUESTIONS:**

1 - Since the Target host had a fresh / newly deployed postgres:16 database, are the specific cleanup restore instructions outlined [HERE](https://docs.teslamate.org/docs/maintenance/backup_restore) to "Drop existing data and reinitialize" as per previous step "E2" still needed on a fresh setup before a backup file import is performed?

2 - Any other adjustments needed on the backup data file **_prior_** to importing, due to differences in the postgres:12 to postgres:16 versions?

3 - Before and After the database import, are there any other changes or database commands needed to properly display the historical data in Grafana without errors?

**ANY IDEAS HOW TO FIX?**

Thank you.

### Expected Behavior

Grafana should render the imported data

### Steps To Reproduce

See steps in description 

### Relevant log output

```shell
See logs links in description
```

### Screenshots

see screenshots inline in description

### Type of installation

Docker

### Version

v1.29.2

**Comment by JakobLichterfeld** [comment]
> 1 - Since the Target host had a fresh / newly deployed postgres:16 database, are the specific cleanup restore instructions outlined [HERE](https://docs.teslamate.org/docs/maintenance/backup_restore) to "Drop existing data and reinitialize" as per previous step "E2" still needed on a fresh setup before a backup file import is performed?

Yes, thats why they are stated in the docs.

> 2 - Any other adjustments needed on the backup data file **_prior_** to importing, due to differences in the postgres:12 to postgres:16 versions?

As Postgres12 is outdated since years, we can not support such bug version jumps, but there had been succesful migrations in the past from other users, so it should be possible. Best ist to do the migration on old system, then import to new system.

> 3 - Before and After the database import, are there any other changes or database commands needed to properly display the historical data in Grafana without errors?

https://docs.teslamate.org/docs/maintenance/upgrading_postgres

**Comment by SemoTech** [comment]
Thank you for the prompt reply @JakobLichterfeld.  

If it's not too much trouble, could you please be so kind as to keep this ticket Open until there is some resolution?  _I spent a lot of hours troubleshooting and putting this ticket together, with all the details and logs, and it is very disconcerting to see it closed in a minute and without any resolution._  

Since teslamate is about 5 years old, other users here may have run into this or similar issues with DB upgrades & migrations, therefore someone may have solutions or ideas they can share, this is why I provide so much detail. This in turn will help the teslamate community, provided the ticket is not closed before an actual resolution... 

Now, just to recap:  

1 - You said that the "Drop existing data and reinitialize" process is STILL needed _even with importing a backup into a fresh/newly spun-up database_, which is what I did, but it is good to know since that was not clear in the docs. 

2 - You had a great idea of me trying to 1st do an in-place upgrade directly on the Source/old host from postgres:12 to postgres:16 which I will do, and will report back here if it worked.  

3 - If the Source upgrade-in-place is successful, I'll export/backup the upgraded Source teslamate postgres:16 database, and again import it into another freshly rebuilt Target host with postgres:16, after re-doing the "Drop existing data and reinitialize" process.

Thank you.

**Comment by SemoTech** [comment]
OK, @JakobLichterfeld and @DrMichael  I have partial good news, we are closer to a solution:

1 - I managed to do an in-place postgres:12 to postgres:16 database upgrade on the Source host!
Grafana was then accessible (on it's own FQDN of `grafana.example.com`) and all data seems to have survived the postgres upgrade process.
All steps are detailed [HERE](https://pastebin.com/Xa9qwhTk) with all outputs.

2 - I re-exported the now upgraded postgres:16 teslamate database data from the Source host and imported it into a fresh build of the Target host after it's own postgres:16 database first received the "Drop existing data and reinitialize" process. 
See all steps and detailed output [HERE](https://pastebin.com/4ExzkPE2)

Sadly, while the Source upgrade was successful and that host and is now running postgres:16, the imported data on the Target host is again NOT being rendered correctly by Grafana!

This is what I get in Grafana on the Target host `tm.example.com/grafana` after the import of postgres:16 data:

![image](https://github.com/teslamate-org/teslamate/assets/1452100/0469acfe-f9a5-4a5e-8e36-f1295cd7ce19)

As this is no longer a postgres old version issue, it is clearly something else, maybe related to the paths, so I am hoping there is more I can try to get this fixed given we are so close...

Maybe something/a path I can check and change in the backup file _before_ importing it?

Your patience and any additional help would be appreciated...

Thank you.

**Comment by JakobLichterfeld** [comment]
> Grafana was then accessible (on it's own FQDN of `grafana.example.com`) and all data seems to have survived the postgres upgrade process.

As expected it is not an issue with TeslaMate but with your new "target" system. Please provide docker-compose.yml without credentials and make sure to delete your postgres docker volume completly before the restore to get a clear starting state (as you messed around with it).

**Comment by SemoTech** [comment]
Hello @JakobLichterfeld,

Actually all this proves is that an in-place teslamate postgres:12 to postgres:16 version upgrade worked, which is great news for anyone with an older setup.

However, as described from the start, the Target system uses one FQDN instead of two for the Source, so it is different.  Adjusting teslamate to migrate from one configuration to the other _should_ be trivial, especially since the manual describes setups for both instances.

Also, as described in detail above and per provided logs, the postgres:16 docker volume on the Target was deleted in full followed by being re-created and having the "Drop existing data and reinitialize" process applied, BEFORE the DB restore.

[HERE](https://pastebin.com/bYJgQJ5H) is the _Source_ docker-compose.yml 
[HERE](https://pastebin.com/LFrm2Zay) is the _Target_ docker-compose.yml 

If ay other details are needed, please just ask.

I am hoping someone has a suggestion on how to fix this and allow the data imported into the Target from the Source to be made accessible by Grafana on the Target...

Thank you.

P.S.  If I start the Target host with a fresh postgres:16 so not to loose new tesla API events, and once this issue is resolved I attempt to import the old/original data from the Source server (with same postgres:16 version DB), can I do so without loosing the new/previous up-to-date data in the database? Basically can one add teslamate backup data into a system rather than replace everything with the older backup?

**Comment by SemoTech** [comment]
### ***** SOLVED, GOT IT WORKING!!!! *****

Based on the Grafana logs error that stated `dial tcp: lookup **database** on 127.0.0.11:53: server misbehaving` I initially thought this was a DNS resolution problem or lack of access to Internet, which I proved it was not. Then the keyword `database` made me think something was hardcoded in the postgres DB so I did a search but alas found no entries matching it.

Finally, I recalled that in the Source host docker-compose.yml file the references for both the **teslamate:** service and **grafana:** service called onto the postgres `database` using: `DATABASE_HOST=database`, however in my Target setup docker-config.yml I had changed the name just for the **teslamate:** service to `teslamate-postgres` while the **grafana:** service entry still had the name `database`, and therefore they did not match causing Grafana to error out.

Recommend everyone using a variable in the .env file not just for entries that are security related, but also any that are referenced by more than one service, to ensure no typos or mismatching!

P.S. - I'd still like to know if one can add teslamate backup data "on top" of existing data, rather than replace everything with the older backup?

P.P.S. - I continue to get a Grafana `Failed to fetch` popup error about 10-15 seconds after Garfana dashboard data is loaded, but this is also happening on the Source host (and there is nothing relevant in the Grafana logs) so maybe it is a side-effect of the postgres:12 to postgres:16 upgrade, or possibly an issue with polling the Tesla API?
![image](https://github.com/teslamate-org/teslamate/assets/1452100/f864b077-33a6-4036-a4f9-ae8c5c6b5f95)

**Comment by cwanja** [comment]
> P.S. - I'd still like to know if one can add teslamate backup data "on top" of existing data, rather than replace everything with the older backup?

No. Would suggest you take your source system (which is hopefully complete) and load it to your target system and then shut down source. 

> P.P.S. - I continue to get a Grafana Failed to fetch popup error about 10-15 seconds after Garfana dashboard data is loaded, but this is also happening on the Source host (and there is nothing relevant in the Grafana logs) so maybe it is a side-effect of the postgres:12 to postgres:16 upgrade, or possibly an issue with polling the Tesla API?

See #3982

**Comment by SemoTech** [comment]
Thanks @cwanja !

So based on the link you referenced, the last issue I am seeing, the Grafana `Failed to fetch` message is unrelated to the DB upgrade or the Tesla API and is internal to the current Grafana version which makes an extra call that gets blocked and devs are working on a fix for next Grafana version.

**Comment by cwanja** [comment]
> Thanks @cwanja !
> 
> 
> 
> So based on the link you referenced, the last issue me and others are seeing, the Grafana `Failed to fetch` message, is unrelated to the DB upgrade or the Tesla API and is internal to the current Grafana version which makes an extra call that gets blocked and devs are working on a fix for next Grafana version.

There is a lot of assumptions in that block of text. Anything Grafana focused is outside my purview. 

Can confirm TeslaMate with non-uBlock ad blockers running is not facing Grafana pop-ups.

**Comment by SemoTech** [comment]
> > 
> Can confirm TeslaMate with non-uBlock ad blockers running is not facing Grafana pop-ups.

Correct @cwanja I further tested using a Private Safari window, and no Grafana error.

Though I did notice discrepancies from the Source teslamate host to the Target host as can be seen below.  

Any idea why would the `plugged-in` and `locked` as well as the `Charge Limit` info not be displayed for the same vehicle on the Target host?  Both hosts run the same version teslamate/postgres and the same data, since the Source was just exported and imported to Target host! 

![image](https://github.com/teslamate-org/teslamate/assets/1452100/28485641-aa0e-4f93-bbbb-014150b04202)

**Comment by cwanja** [comment]
Wake the car up.

**Comment by SemoTech** [comment]
> Wake the car up.

Good call @cwanja Thank you.

**Comment by JakobLichterfeld** [comment]
> however in my Target setup docker-config.yml I had changed the name just for the teslamate: service to teslamate-postgres while the grafana: service entry still had the name database, and therefore they did not match causing Grafana to error out.

Glad you found the error in your docker-compose on your own. As assumed correctly, no TeslaMate issue at all

**Comment by SemoTech** [comment]
Indeed @JakobLichterfeld, thank you for pointing me in the right direction and very glad this was just an internal configuration mismatch. 

Recommend having the `database` entry/name for the `teslamarte:` and `postgres:` services made a ${} variable in the standard configuration, in order to avoid this.  Hopefully this ticket helps others as well.

My thanks again for everyone's help.
