### ISSUE TITLE
v1.29.2:  Bad Certificate when using http proxy (self signed cert)

### ISSUE THREAD

**Issue by zlymeda** [teslamate-org/teslamate#3979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home Assistant addon is using http proxy without an issue. Using TESLA_API_HOST in teslamate fails with `Bad Certificate`.

I believe it is due to a self-signed certificate. 
I see there is already `TESLA_WSS_TLS_ACCEPT_INVALID_CERTS` for WebSockets. Can we have the same for the HTTP?

Thank you

### Expected Behavior

to be able to use self-signed cert on HTTP proxy

### Steps To Reproduce

Use HTTP proxy with self-signed cert

### Relevant log output

```shell
2024-06-19 07:30:59.483 [notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2123 generated CLIENT ALERT: Fatal - Bad Certificate
2024-06-19 07:30:59.483 [error] GET https://pi.home:8443/api/1/vehicles/XYZ -> error: "TLS client: In state wait_cert_cr at ssl_handshake.erl:2123 generated CLIENT ALERT: Fatal - Bad Certificate\n" (78.470 ms)
```

### Type of installation

Docker

### Version

v1.29.2

**Comment by jlestel** [comment]
It would seem logical to me to add it to allow http proxy installations without SSL to work.

**Comment by XxTopKillerzZ** [comment]
Just to add up to this discussion, I also have http proxy running with self signed certificate

I having an hard time following the docs at https://docs.teslamate.org/docs/guides/api/#tesla-fleet-api
What I understand is I need to have http proxy running and then change TESLA_AUTH_HOST to my proxy domain?
I already have a developer account with public key hosted and tesla proxy working for HomeAssistant

**Comment by zlymeda** [comment]
Ultimately, I modified the HTTP proxy to run both HTTPS and HTTP. HA integration hits the HTTPS and teslamate hits the HTTP

**Comment by XxTopKillerzZ** [comment]
Can you share your setup? How are you hosting the proxy?

**Comment by Mewks** [comment]
> sorry did not see the comment...
> 
> I have my own repo, where vehicle command repo is a dependency. and I run the proxy in my main module running this function:
> 
> ```go
> func runProxy() error {
> 	fmt.Println(os.Args[0], version.Version, version.BuildTime)
> 	host := "0.0.0.0"
> 	port := 8443
> 
> 	privateKey, err := protocol.LoadPrivateKey(keyFile)
> 	if err != nil {
> 		return err
> 	}
> 
> 	ctx, cancel := CreateMainCtx()
> 	defer cancel()
> 
> 	log.Println("Starting HTTP and HTTPS...")
> 	p, err := myproxy.New(ctx, privateKey, cacheSize)
> 	p.Timeout = 60 * time.Second
> 
> 	go func() {
> 		addrHttp := fmt.Sprintf("%s:%d", host, port + 1)
> 		log.Println("Starting HTTP server on " + addrHttp)
> 		if err := http.ListenAndServe(addrHttp, p); err != nil {
> 			log.Fatalf("HTTP server error: %v", err)
> 		}
> 	}()
> 
> 	addr := fmt.Sprintf("%s:%d", host, port)
> 	log.Println("Starting HTTPs server on " + addr)
> }	
> ```

Thanks for this @zlymeda . I'm looking to implement this as well and run HTTP on my HA Proxy addon as you have but not really familiar with customising addons.

If its not too much trouble would you mind writing a quick step by step on what you did?

In short, I understand it like this: 
You created a copy of the Teslamate github into your own repository.
You then amended the code - and the code that you amended is what you mention here in your post? Where did you put that? which file?
You then added your github repo to the addon store in HA and installed the app and then just went through the same process as you would the official repo?

Thanks for your help
