### ISSUE TITLE
Unable to delete, edit or add geofencing

### ISSUE THREAD

**Issue by natrimed** [teslamate-org/teslamate#4011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When logged in to Teslamate, I am unable to edit, create or delete a geofence. The interface allows for the editing, deleting or creation of a geofence but does not save it. It defaults back to the original geofences.

### Expected Behavior

Deleting, editing or creating new geofences are saved after saving.

### Relevant log output

```shell
No logs
```

### Type of installation

Docker

### Version

v1.29.2

**Comment by cwanja** [comment]
> Relevant log output
> No logs

There are always logs. Please provide them.
