### ISSUE TITLE
Grafana maps not fitting data; zoomed out to world view

### ISSUE THREAD

**Issue by kktoo21** [teslamate-org/teslamate#4055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue that occurred after upgrading to the latest v1.30.0 version was normal before.

### Expected Behavior

I hope that as before, the parts related to map display can be customized for display size, instead of manually zooming in to the appropriate size range by displaying them globally

### Steps To Reproduce

Stable reproduction after upgrading to v1.30.0 version

### Relevant log output

```shell
null
```

### Screenshots

<img width="1473" alt="image" src="https://github.com/teslamate-org/teslamate/assets/44777290/9fba79a1-f2dc-4bb0-8ba8-1b6b36ec963e">
<img width="1485" alt="image" src="https://github.com/teslamate-org/teslamate/assets/44777290/a5e8a879-db54-4e71-89ec-23699e40f981">

### Type of installation

Docker

### Version

v1.30.0

**Comment by DrMichael** [comment]
It appers to be a bug in Grafana. Will be fixed in one of the next releases, see https://github.com/teslamate-org/teslamate/discussions/4029

**Comment by cwanja** [comment]
Reopening to track / reference the map issue with Grafana. This issue will be the source for pointing future discussions and issues to as a reference. Once we release a PR that merges the Grafana update, that will close this issue.

**Comment by cwanja** [comment]
Reopening based upon discussion in #4019

**Comment by cwanja** [comment]
bug in Grafana Geomap. Will be fixed in one of the next releases: https://github.com/grafana/grafana/pull/89248

**Comment by JakobLichterfeld** [comment]
Solved via v1.30.1
