### ISSUE TITLE
Grafana map automatic zoom not working

### ISSUE THREAD

**Issue by mandreasen** [teslamate-org/teslamate#4070]
### What happened?

After upgrading to v1.30.0, all openstreetmap maps aren't automatically zooming in to show only the part of the map, where I have been driving. No matter where I look at the map, it shows the whole world and I have to manually zoom in.

![image](https://github.com/teslamate-org/teslamate/assets/7643734/dec8b596-793a-45e5-b00e-579ace9b0103)

### Expected Behavior

Automatically zooming in to show only the part of the map, where I have been driving.

![image](https://github.com/teslamate-org/teslamate/assets/7643734/71669560-eeab-4f99-bb9c-cc4484143541)

### Steps To Reproduce

Open Teslamate Grafana views with openstreetmap windows, like Grafana -> Dashboards -> TeslaMate -> Trip.

### Relevant log output

```shell
logger=context userId=1 orgId=1 uname=grafana t=2024-07-09T18:28:00.136387792Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.100 time_ms=1 duration=1.176964ms size=0 referer= handler=/api/live/ws status_source=server
```

### Type of installation

Docker

### Version

v1.30.0

**Comment by cwanja** [comment]
Please see #4029. Grafana bug. Will be resolved with a future Grafana update.

**Comment by cwanja** [comment]
#4055
