### ISSUE TITLE
1.30.1 - Localized Grafana doesn't work as per claim in #4064

### ISSUE THREAD

**Issue by stauffenberg2020** [teslamate-org/teslamate#4077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The claim from #4064 says that Grafana will use Date formats as per browser locale. But I can never see the date formats as per my broser locale which is DD MMM YYYY in any of the dashboards

### Expected Behavior

Date formats are not to be hard coded as per North American locale and should be as per user's preferences

### Relevant log output

```shell
Just open any dashboard and you understand the point I am trying to say
```

### Type of installation

Docker

### Version

1.30.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. Can you please double-check the Drives Dashboard and the Drives Details Dashboard?

**Comment by DrMichael** [comment]
But that is not US date format...

**Comment by JakobLichterfeld** [comment]
> Hi @JakobLichterfeld, I did clearly check and I can never find a date with DD MMM YYYY format in any of the dashboards.

Interesting. Does this show local browser time for you as well?

![image](https://github.com/user-attachments/assets/b85b1edb-90cf-43e0-a88f-529e095223c8)

**Comment by JakobLichterfeld** [comment]
Your screenshot shows CEST instead of "Local browser time". Did you played with dashboards? If so, please do a backup of teslamate, stop your instance, delete your grafana volume and restart.

**Comment by DrMichael** [comment]
> > But that is not US date format...
> 
> So?

> ### Expected Behavior
> Date formats are not to be hard coded as per North American locale and should be as per user's preferences

**Comment by DrMichael** [comment]
Hmmm, what is set in Chrome's settings?
https://support.cascade.app/hc/en-us/articles/22433396194963-How-to-Change-Date-Format-in-your-Browser#:~:text=At%20the%20top%2Dright%20of,dd%2Fmm%2Fyyyy%20format.

**Comment by JakobLichterfeld** [comment]
> I did this, Now I can see that the CEST part is gone, 

Perfect.

> But the date format are still not as per my system Date.

But your browser time...

**Comment by JakobLichterfeld** [comment]
> But I can never see the date formats as per my broser locale which is DD MMM YYYY in any of the dashboards

Your screenshot clearly show date format DD/MM//YYYY and am and pm, so where is exactly your issue?

**Comment by JakobLichterfeld** [comment]
As stated above, your dashbopard shows your Brower time, not your system time. The screenshots your provied shows your system time is in dd-MMM-YYYY format but your browser is in DD/MM/YYYY format. Not a TeslaMate issue your screenshot show TeslaMate works perfectly fine
