### ISSUE TITLE
Teslamate is failing to run after update

### ISSUE THREAD

**Issue by jweichel** [teslamate-org/teslamate#4080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I could not get teslamate to run properly (eg port 4000 was not responding) after updating using this docker-compose.yml file:
[docker-compose.pdf](https://github.com/user-attachments/files/16184209/docker-compose.pdf)

After pulling the new versions and starting it up, I did a docker compose ps and the teslamate process kept restarting.  There were many problems in the docker compose logs below.

I have been trying various things for days to no avail.  I even tried to remove the entire installation before doing the above, but the results were similar.  I used this sequence by jibinc to remove everything:
https://github.com/teslamate-org/teslamate/discussions/1125

### Expected Behavior

I expected port 4000 to be accessible, but it is not so I cannot connect it to my Tesla account.

### Relevant log output

```shell
[TeslamateLogs.txt](https://github.com/user-attachments/files/16184223/TeslamateLogs.txt)
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by brianmay** [comment]
```
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
teslamate-1  | clock_gettime(CLOCK_MONOTONIC, _) failed: Operation not permitted (1)
teslamate-1  | Aborted (core dumped)
```

We have seen this before (e.g. #2302), you might have to upgrade your libseccomp2.

**Comment by jweichel** [comment]
I finally started over by re-imaging the Raspberry Pi and installing Docker & Teslamate.  It all works now.
