### ISSUE TITLE
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized on Statistics dashboard

### ISSUE THREAD

**Issue by ivanovd** [teslamate-org/teslamate#4090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading to v. 1.30.1 I no longer see the statistics. I get the following errors on the dashboard:

```
A
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
B
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
C
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
```

The dashboards were restored after the update:

```
/usr/local/src/teslamate]# ./grafana/dashboards.sh restore

URL:                  http://localhost:3000
LOGIN:                xxxxxxxxxxxxxxxxxxxx
DASHBOARDS_DIRECTORY: ./grafana/dashboards
  
RESTORED updates.json
RESTORED statistics.json
RESTORED vampire-drain.json
RESTORED charge-level.json
RESTORED states.json
RESTORED mileage.json
RESTORED drive-stats.json
RESTORED drive-details.json
RESTORED charge-details.json
RESTORED trip.json
RESTORED timeline.json
RESTORED locations.json
RESTORED projected-range.json
RESTORED charges.json
RESTORED battery-health.json
RESTORED drives.json
RESTORED charging-stats.json
RESTORED efficiency.json
RESTORED visited.json
RESTORED dutch-tax.json
RESTORED overview.json
[root@teslamate /usr/local/src/teslamate]#
```

### Expected Behavior

Expecting to see the stats as per the aggregation selected

### Steps To Reproduce

1. Go to Grafana
2. Select the Statistics dashboard

### Relevant log output

```shell
A
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
B
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
C
Status: 500. Message: db query error: pq: time zone "$__timezone" not recognized
```

### Screenshots

![image](https://github.com/user-attachments/assets/143c67e0-879f-4fb9-afcc-ef60ab8bf3ca)

### Type of installation

Manual

### Version

v1.30.1

**Comment by DrMichael** [comment]
Ok, $__timezone was introduced in Grafana 10.1.0. I assume, you are running that?
Then, what is the timezone your browser is set to?

**Comment by ivanovd** [comment]
It seems that I was running Grafana v9.5.7. I upgraded to v10.4.1 and the issue was resolved. Thanks a lot @DrMichael
