### ISSUE TITLE
Timeout/alarm in logs when submitting jwt tokens

### ISSUE THREAD

**Issue by zax123** [teslamate-org/teslamate#4107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am setting up new jwt auth tokens because for some reason they randomly stopped working on June 27th. I'm hoping this isn't related to Tesla's new API access rules. When I submit my tokens, my teslamate container log shows:

`2024-07-28 20:09:31.453 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
2024-07-28 20:09:36.522 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "timeout" (60865.639 ms)
2024-07-28 20:13:35.657 [warning] Cannot refresh access token: :not_signed_in
2024-07-28 20:19:22.324 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "timeout" (60857.266 ms)`

And the front end shows "Error: The tokens are invalid". I've tried generating tokens several times and they are fresh and should be valid for 8 hours.

Not sure if I'm doing something wrong or if this is related to the new API changes.

### Expected Behavior

I expected the tokens to be accepted and for Teslamate to continue tracking activity on my cars without generating the invalid tokens error.

### Steps To Reproduce

Visit teslamate site port 4000, click on Settings, then Home.

Teslamate asks for the tokens.

Enter access and refresh tokens as generated by a Tesla auth desktop app.

Wait 60s, get "Error: The tokens are invalid" message. Check docker container logs, see above log messages.

### Relevant log output

```shell
2024-07-28 20:09:31.453 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
2024-07-28 20:09:36.522 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "timeout" (60865.639 ms)
2024-07-28 20:13:35.657 [warning] Cannot refresh access token: :not_signed_in
2024-07-28 20:19:22.324 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: "timeout" (60857.266 ms)
```

### Screenshots

![invalid token](https://github.com/user-attachments/assets/0f7c2f7a-9770-4895-92f8-74014c1be74e)

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. Not possible to reproduce here. As you get a timeout: does your docker have internet access? Do you use a proxy, adblocker or similar? Does you have DNS issues? Did you restart your container, your system?

**Comment by zax123** [comment]
Turns out the auth.tesla.com servers don't like requests coming from privateinternetaccess.com VPNs... :( So this is all my fault, and nothing to do with Teslamate. Sorry for the trouble!

**Comment by JakobLichterfeld** [comment]
> Turns out the auth.tesla.com servers don't like requests coming from privateinternetaccess.com VPNs... :( So this is all my fault, and nothing to do with Teslamate. Sorry for the trouble!

Glad you solved it. Yeah, IPs from AWS, GCP, and some more are blocked
