### ISSUE TITLE
Drive Stats dashboard has an area with a confusing title 

### ISSUE THREAD

**Issue by munkee** [teslamate-org/teslamate#4119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Drive Stats dashboard there is a panel with the title "kWh used" but after having the car for not too long, the contents of the panel will have the unit "MWh". Perhaps the title should be "energy used"?

### Expected Behavior

Units match or the title isn't as confusing.

### Steps To Reproduce

Go to the Drive Stats dashboard in Grafana on any car with more than 1000 kWh of energy used.

### Relevant log output

```shell
Grafana UI issue only
```

### Screenshots

<img width="1617" alt="Screenshot 2024-08-02 at 8 56 53 AM" src="https://github.com/user-attachments/assets/6173e4fd-3b30-4e97-8f52-e1c6616784da">

### Type of installation

Manual

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting, nice find!
@jheredianet May I ask you to look into it? Thank you!

**Comment by jheredianet** [comment]
> Thanks for reporting, nice find! @jheredianet May I ask you to look into it? Thank you!

It's fixed in this PR https://github.com/teslamate-org/teslamate/pull/4148
