### ISSUE TITLE
Trailer mode

### ISSUE THREAD

**Issue by macbar** [teslamate-org/teslamate#4132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I have been searching through the data teslamate gathers from the API to find out if there is a way to see if a drive was performed in trailer mode or not.

Given that towing a trailer/caravan/... has a huge impact on consumption and range, it would be nice to be able to filter for these drives.

Is this technically feasible?

Thanks

### Relevant log output

```shell
none
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by brianmay** [comment]
Does the car even know when I trailer is attached?

I have no idea, my car doesn't support trailers.

**Comment by macbar** [comment]
It does, see https://www.tesla.com/ownersmanual/modely/en_eu/GUID-A6D6CF75-C9CA-4140-97FA-341E27E3B4D8.html

**Comment by JakobLichterfeld** [comment]
> API to find out if there is a way to see if a drive was performed in trailer mode or not.

The API does not provide any corresponding values, so unfortunately this problem cannot be solved via the API.

> Does the car even know when I trailer is attached?

ABS/ESP needs to be aware of for example
