### ISSUE TITLE
Less data points after parking with sentry mode on

### ISSUE THREAD

**Issue by Imaginous** [teslamate-org/teslamate#4155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sometimes I noticed that the route plotted on the map is less detailed, but never knew why.

Now I found out when it is happening.
When my car is parked and sentry mode is off, the next trip will be captured in detail.
But when the car was parked with sentry mode on, the next trip will have way less data points.

See screenshot for the difference.

### Expected Behavior

Same detail / amount of data points.

### Steps To Reproduce

1. Park car without sentry mode.
2. Lock the car and leave it until it falls asleep.
3. Drive a bit.
4. Everything is normal.

1. Park the car with sentry mode.
2. Lock the car and leave it for a while (30 minutes or so)
3. Drive a bit.
4. A low amount of data points is registered.

### Relevant log output

```shell
-
```

### Screenshots

Correct amount of data points (sentry mode off):
![Without_Sentry](https://github.com/user-attachments/assets/f7330a60-6585-49f5-90ea-736c97e351aa)

Incorrect amount of data points (sentry mode on):
![With_Sentry](https://github.com/user-attachments/assets/23a3b25c-f153-4da1-9910-9f4ef9d8c615)

### Additional data

-

### Type of installation

Docker

### Version

v1.30.1

**Comment by cwanja** [comment]
I do not believe this is true. I have multiple drives after Sentry Mode was enabled that capture every second or every other second.

**Comment by Imaginous** [comment]
I can repeat it on every drive.

Model 3 2024 (Highland), European model.

**Comment by jakobfriis** [comment]
I have  Model 3 2024 SR (Highland), European, and I do not have that issue.
I'm on 2024.26.6 just for comparison

**Comment by Imaginous** [comment]
Do you have premium connectivity?
I have not, maybe it's related. 

I'm still on 2024.20.9, but all previous versions, showed this behavior.

It seems like rate limiting or a connectivity issue.

**Comment by jakobfriis** [comment]
i have premium connectivity, yes

**Comment by cwanja** [comment]
I have premium connectivity as well, US based.

**Comment by cwanja** [comment]
>It seems like rate limiting or a connectivity issue.

I would tend to agree with that. Which is beyond the scope of TeslaMate.

**Comment by Imaginous** [comment]
Maybe I will try a month premium connectivity.
