### ISSUE TITLE
Error trying to import TeslaFi data

### ISSUE THREAD

**Issue by emilecantin** [teslamate-org/teslamate#4163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've followed the steps outlined in the documentation to export my data from TeslaFi, and import it in TeslaMate. However when I click the "import" button and I get the attached logs.

I've dug a little into the code but I'm not a Python guy and I don't really know this codebase.

I don't want to post the TeslaFi dump publicly as it contains personal data, so I don't know how you can go about reproducing this. If you need some more detailed logging I'd be happy to provide it.

### Relevant log output

```shell
server-teslamate-1  | 2024-08-28 01:30:12.905 [info] GET /
server-teslamate-1  | 2024-08-28 01:30:12.915 [info] Sent 302 in 9ms
server-teslamate-1  | 2024-08-28 01:30:12.929 [info] GET /import
server-teslamate-1  | 2024-08-28 01:30:12.943 [info] Sent 200 in 14ms
server-teslamate-1  | 2024-08-28 01:30:20.247 [info] Importing 1 file(s) ...
server-teslamate-1  | 2024-08-28 01:30:20.274 [error] GenStateMachine TeslaMate.Import terminating
server-teslamate-1  | ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :update, changes: %{eid: 58337}, errors: [vid: {"is invalid", [type: :integer, validation: :cast]}], data: #TeslaMate.Log.Car<>, valid?: false>}
server-teslamate-1  |     (teslamate 1.30.1) lib/teslamate/vehicles.ex:113: TeslaMate.Vehicles.create_or_update!/1
server-teslamate-1  |     (teslamate 1.30.1) lib/teslamate/import.ex:289: TeslaMate.Import.create_car/1
server-teslamate-1  |     (teslamate 1.30.1) lib/teslamate/import.ex:128: TeslaMate.Import.handle_event/4
server-teslamate-1  |     (stdlib 5.2.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
server-teslamate-1  |     (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

### Type of installation

Docker

### Version

1.30.1

**Comment by cwanja** [comment]
Looks like it is erroring out on `vid`. What is that value in your TeslaFi export? Do you have more than one car for TeslaMate? If not, you could try putting a 1 in that field.

**Comment by emilecantin** [comment]
Is there supposed to be a "vid" column in the data? I see a "vehicle_id" and a "vin" column, but no "vid".

"vehicle_id" is full of weird values like "1 1 0 0 0 0 0" (with the quotes) that increase on each row.

**Comment by cwanja** [comment]
Sorry, was basing it off the error and assumed there was one. Replace `vehicle_id` with 1 or which ever ID  this cars data would be for in TeslaMate. If you have no other cars in TeslaMate, it is 1.

**Comment by emilecantin** [comment]
I'm making progress after replacing the vehicle_id as suggested, but I'm still getting errors. They're different, though, so there's that!

Side-note: what are you using to edit these CSV files? They're pretty unwieldy to use with a text editor so I tried CSVKit (has a csvsql command that's pretty handy), but I'm pretty sure it messes with the formatting and that's the source of these errors.

**Comment by emilecantin** [comment]
Just managed to make it work: the secret was the `--no-inference` option on CSVkit so it didn't try to interpret the data types and just treat as text.

For future reference, here's the command I used to fix the `vehicle_id` in the CSV:

```
csvsql --query "UPDATE TeslaFi82024 SET vehicle_id=1; SELECT * FROM TeslaFi82024;" --no-inference TeslaFi82024.csv > TeslaFi82024-fixed.csv
```

Thanks!

**Comment by emilecantin** [comment]
Also, if you've got some weird locations in the Atlantic off the coast of Africa (they show up in TeslaFi too, not a TeslaMate issue), I've solved it with the "explore" feature in Grafana, where I've run some variations of `DELETE FROM positions WHERE latitude=0` (always run SELECT first to see what you're deleting).

**Comment by ampersandru** [comment]
> Just managed to make it work: the secret was the `--no-inference` option on CSVkit so it didn't try to interpret the data types and just treat as text.
> 
> For future reference, here's the command I used to fix the `vehicle_id` in the CSV:
> 
> ```
> csvsql --query "UPDATE TeslaFi82024 SET vehicle_id=1; SELECT * FROM TeslaFi82024;" --no-inference TeslaFi82024.csv > TeslaFi82024-fixed.csv
> ```
> 
> Thanks!

Thanks for the command, I did similar to the months that would not import, but now I get this error:

```
2024-09-10 21:20:07.276 [error] GenStateMachine TeslaMate.Import terminating

** (RuntimeError) vehicle data is incomplete

    (teslamate 1.30.1) lib/teslamate/import.ex:277: TeslaMate.Import.create_car/1

    (teslamate 1.30.1) lib/teslamate/import.ex:128: TeslaMate.Import.handle_event/4

    (stdlib 5.2.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11

    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

I do have 2 cars in my account, but teslafi only should be recording data for one of the cars. How would I go about fixing this?
