### ISSUE TITLE
Backup not working and drives are not recorded

### ISSUE THREAD

**Issue by bdreifuss** [teslamate-org/teslamate#4183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Backup does not work. Error: could not read block 1104 in file "base/16384/17129"
Furthermore, drives are not recorded since a couple of weeks

### Expected Behavior

Backup works and drives are recoreded

### Steps To Reproduce

Backup is setup according to the official instructions.

### Relevant log output

```shell
pg_dump: error: Dumping the contents of table "positions" failed: PQgetResult() failed.
pg_dump: error: Error message from server: ERROR:  could not read block 1104 in file "base/16384/17129": Input/output error
pg_dump: error: The command was: COPY public.positions (id, date, latitude, longitude, speed, power, odometer, ideal_battery_range_km, battery_level, outside_temp, elevation, fan_status, driver_temp_setting, passenger_temp_setting, is_climate_on, is_rear_defroster_on, is_front_defroster_on, car_id, drive_id, inside_temp, battery_heater, battery_heater_on, battery_heater_no_power, est_battery_range_km, rated_battery_range_km, usable_battery_level, tpms_pressure_fl, tpms_pressure_fr, tpms_pressure_rl, tpms_pressure_rr) TO stdout;
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by dyxyl** [comment]
"Input/output error" suggests that you have disk problems.  Check the syslog for messages.

**Comment by JakobLichterfeld** [comment]
> ```shell
> Input/output error
> ```

Echoing dyxyl, this indicates a disk issue, so your disk is corrupted, db can not be read nor write.
