### ISSUE TITLE
battery level gauge shows red value if battery is 100% and LFP is selected

### ISSUE THREAD

**Issue by neothematrix** [teslamate-org/teslamate#4184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In case of LFP Tesla, that is, lfp option is flagged in teslamate config, the battery level gauge correctly shows different alert thresholds, however, the edge case where the battery is actually 100% charged still shows as red.
It's probably enough to change the limit config query to use "101" as max level in case of LFP. See screenshot for proposed solution.

### Expected Behavior

See screenshot

### Relevant log output

```shell
See screenshot
```

### Screenshots

![issue with 100 percent](https://github.com/user-attachments/assets/38560f95-e0c0-409e-a6d5-d6cca03854f2)

![proposed change](https://github.com/user-attachments/assets/9e43c1c8-223d-4667-b0ac-fdf755e75456)

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Nice find. 
@jheredianet May I ask you to look into this?
