### ISSUE TITLE
following an unofficial guide resulted in installing a test version and issues with switch to latest release

### ISSUE THREAD

**Issue by jaswals** [teslamate-org/teslamate#4190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have started to see these errors lately, anyone know why? I don't have LFP battery. Teslamate is installed in docker on Synology NAS

### Relevant log output

```shell
n/a
```

### Screenshots

![Screenshot 2024-09-09 at 12 30 05 AM](https://github.com/user-attachments/assets/d072e72b-0479-4748-8c9f-dbbe196f8654)
![Screenshot 2024-09-09 at 12 30 26 AM](https://github.com/user-attachments/assets/23d192bf-8851-4500-ad0e-59cbc83f82dc)
![Screenshot 2024-09-09 at 12 30 37 AM](https://github.com/user-attachments/assets/be91d54d-e415-49e3-8713-b29e349355af)

### Type of installation

Docker

### Version

v1.28.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

Please update TeslaMate to latest version (1.30.1 as of writing). It seems like you only updated the grafana docker and not the TeslaMate. See https://docs.teslamate.org/docs/upgrading

**Comment by jaswals** [comment]
I have tried many ways to update it on Sinology NAS but not successful.

I hav tried from Container Manager, I hav tried from Poratiner, system just says I have latest update.

any tips?

**Comment by JakobLichterfeld** [comment]
Use a supported installation method (portainer is not). 

Post your docker-compose.yml (without secrets)

**Comment by jaswals** [comment]
> Use a supported installation method (portainer is not).
> 
> Post your docker-compose.yml (without secrets)

version: "3.9"

services:
  teslamate:
    image: ghcr.io/teslamate-org/teslamate:pr-3630
    container_name: TeslaMate
    restart: on-failure:5
    environment:
      - ENCRYPTION_KEY=xxxxxxxx
      - DATABASE_USER=xxxxxx
      - DATABASE_PASS=xxxxxxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 20002:4000
    cap_drop:
      - all

  database:
    image: postgres:14
    container_name: TeslaMate-DB
    restart: on-failure:5
    environment:
      - POSTGRES_USER=xxxxxxx
      - POSTGRES_PASSWORD=xxxxxx
      - POSTGRES_DB=teslamate
    volumes:
      - /volume1/docker/teslamate/db:/var/lib/postgresql/data:rw

  grafana:
    image: teslamate/grafana:latest
    container_name: TeslaMate-GRAFANA
    restart: on-failure:5
    environment:
      - DATABASE_USER=xxxxxxx
      - DATABASE_PASS=xxxxxx
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 20003:3000
    volumes:
      - /volume1/docker/teslamate/datagrafana:/var/lib/grafana:rw

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: TeslaMate-MOSQUITTO
    restart: on-failure:5
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - /volume1/docker/teslamate/mosqconf:/mosquitto/config:rw
      - /volume1/docker/teslamate/mosqdata:/mosquitto/data:rw
      - /volume1/docker/teslamate/mosqlogs:/mosquitto/log:rw

**Comment by cwanja** [comment]
Is there a reason you are running a specific PR? Instead of a released version?

**Comment by JakobLichterfeld** [comment]
> ```yaml
> image: ghcr.io/teslamate-org/teslamate:pr-3630
> ```

As @cwanja already pointed out, you are not using TeslaMate:latest (1.30.1 as of writing) but a testing version from February 2024. 

Please see instructions here: https://docs.teslamate.org/docs/installation/docker/

**Comment by jaswals** [comment]
> Is there a reason you are running a specific PR? Instead of a released version?

I don’t know why/ how I downloaded a specific version (maybe was following instructions to download it on NAS)

now I am trying to follow proper instructions and running this command from the folder where docker-compose.yml us and it’s saying the image is up to date. If I have the latest version then how do I switch to using that in grafana and keep my data (then delete this old version)

sudo docker pull teslamate/teslamate
Using default tag: latest
latest: Pulling from teslamate/teslamate
Digest: sha256:21b53b2490f88805a48c03998a1a307edfc908dec6323f5221097639bcb846bf
Status: Image is up to date for teslamate/teslamate:latest
docker.io/teslamate/teslamate:latest

**Comment by JakobLichterfeld** [comment]
YOu must change your docker-compose.yml file, 

At minimum you must change `image: ghcr.io/teslamate-org/teslamate:pr-3630` to `image: teslamate/teslamate:latest`. Save it. 
Run ´docker compose pull` and `docker compose up -d`

**Comment by jaswals** [comment]
> You must change your `docker-compose.yml` file,
> 
> At minimum, you must
> 
> 1. change `image: ghcr.io/teslamate-org/teslamate:pr-3630` to `image: teslamate/teslamate:latest`. Save it.
> 2. Run `docker compose pull`
> 3. `docker compose up -d`
> 
> But it is advised to review your docker-compose file in whole

I am just getting to many issues trying to upgrade Testalate on Synology NAS.

$ sudo docker-compose up
[+] Running 0/0
 ⠋ Container TeslaMate            Creating                                 0.0s
 ⠋ Container TeslaMate-DB         Creating                                 0.0s
 ⠋ Container TeslaMate-GRAFANA    Creatin...                               0.0s
 ⠋ Container TeslaMate-MOSQUITTO  Creat...                                 0.0s
Error response from daemon: Conflict. The container name "/TeslaMate-GRAFANA" is already in use by container "b6a46ecc6be1a2ebf088f0de073590e5544ccb04a8c5e60233732b044708dc33". You have to remove (or rename) that container to be able to reuse that name.

I followed and online guide that involved installing portioner to get teslamate to work on Synology NAS, is that really needed?

What do I need to backup by data (gathered from the car) and restore it? I like to start from scratch.

**Comment by JakobLichterfeld** [comment]
> was the only purpose of portainer to create the docker-compose.yml file?

Portainer adds another level of abstraction above it which results in more complexity and is therefor not supported.

You are running an outdated, unsupported docker version (`docker-compose` is deprecated, `docker compose` is right.

> I exported container TestamateDB from the UI, is that all I need to restore vehicle date after?

Nope, just follow https://docs.teslamate.org/docs/maintenance/backup_restore

**Comment by jaswals** [comment]
issue resolved

backed up DB

deleted all images/containers

pulled them from YML folder and restored DB, all is working now including historical data.

Deleted portainer and not using the test image of test version anymore.

Thank you @JakobLichterfeld for helping out a noob (Now have a saved, backup and restore scripts and the backup file of the db.

**Comment by JakobLichterfeld** [comment]
> issue resolved
> 
> backed up DB
> 
> deleted all images/containers
> 
> pulled them from YML folder and restored DB, all is working now including historical data.
> 
> Deleted portainer and not using the test image of test version anymore.
> 
> Thank you @JakobLichterfeld for helping out a noob (Now have a saved, backup and restore scripts and the backup file of the db.

Great, I'm glad to hear that. I hope you continue to enjoy TeslaMate.
