### ISSUE TITLE
km-driven in drive-stats only updates once a day

### ISSUE THREAD

**Issue by roely15mol** [teslamate-org/teslamate#4193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

km-driven in drive-stats only updates once a day at 2am, is this as designed or is this a bug. 

### Relevant log output

```shell
06/09/2024, 02:00:00 55.8 km
07/09/2024, 02:00:00 74.7 km
08/09/2024, 02:00:00 115 km
09/09/2024, 02:00:00 100.0 km
10/09/2024, 02:00:000 0km
```

### Type of installation

Docker

### Version

v1.30.1

**Comment by swiffer** [comment]
@roely15mol - could you test the PR opened here and see if this is fixed with the changes made to the drive dashboard ?

#4258

**Comment by roely15mol** [comment]
I will have a look in the evening! Thanks!

**Comment by roely15mol** [comment]
![image](https://github.com/user-attachments/assets/a0dc5033-c1ce-4ebb-8513-ca88707125e3)

Looks like it's something in the database maybe? That it only calculated it at 2am?

**Comment by roely15mol** [comment]
Looks like it's something in the database maybe? That it only calculated it at 2am?
![image](https://github.com/user-attachments/assets/e92746ee-15e3-49f9-bf1d-41454dbd6ec8)

**Comment by swiffer** [comment]
are you using the dashboard / image provided in PR? data should look like this:

![grafik](https://github.com/user-attachments/assets/f4c4641b-f062-47c6-9369-c515fb9ace92)

-> the data is bucketed per day, therefore you only see a daily total. however this is calculated on demand, so no delays should occure. after a ride you should see the km driven increasing on the same day.

**Comment by roely15mol** [comment]
Just tested and it works with this new image thanks for the work!

**Comment by swiffer** [comment]
great to hear, merged and released soon i guess.
