### ISSUE TITLE
not a tuple

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#4196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Seeing a `not a tuple` error periodically in my logs. Seems to be associated with TzData. Was happening once an hour, and last occurrance was 2024-09-13 03:20:06UTC.

Possibly a bug from tzdata, maybe there was some sort of error condition with its update.

### Expected Behavior

Error should not appear.

### Steps To Reproduce

Run teslamate for a while and look at the logs.

### Relevant log output

```shell
Sep 11 11:19:55 iot2 teslamate[24319]:   * 2nd argument: not a tuple
Sep 11 11:19:55 iot2 teslamate[24319]:     :erlang.element(1, :error)
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
Sep 11 11:19:55 iot2 teslamate[24319]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
```

### Type of installation

Manual

### Version

57acace3582dabadfe3f6756a0d362d078e12fd0

**Comment by sdwalker** [comment]
https://diff.hex.pm/diff/tzdata/1.1.1..1.1.2

Looks like the tzdata dep needs bumped to 1.1.2 to get the updated timezone database

**Comment by sdwalker** [comment]
Full error

```
Sep 14 23:53:37 TeslaMate teslamate[26264]: 2024-09-14 23:53:37.115 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.
Sep 14 23:53:37 TeslaMate teslamate[26264]: 2024-09-14 23:53:37.376 [error] GenServer :tzdata_release_updater terminating
Sep 14 23:53:37 TeslaMate teslamate[26264]: ** (ArgumentError) errors were found at the given arguments:
Sep 14 23:53:37 TeslaMate teslamate[26264]:   * 2nd argument: not a tuple
Sep 14 23:53:37 TeslaMate teslamate[26264]:     :erlang.element(1, :error)
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
Sep 14 23:53:37 TeslaMate teslamate[26264]:     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Sep 14 23:53:37 TeslaMate teslamate[26264]: Last message: :check_if_time_to_update
```

**Comment by JakobLichterfeld** [comment]
Nice find, although my logs don't show this behavior, presumably due to different time zones.

**Comment by sdwalker** [comment]
> > can handle months being spelled out instead of abbreveated to 3 letters as happened in one place in 2024b. (Moxley Stratton)

Yep, https://github.com/lau/tzdata/pull/147

Local tzdata update and then rebuild
```
mix deps.update tzdata --only prod
```

**Comment by sdwalker** [comment]
> Next release will have tzdata 1.1.2 automatically

Will the other ~1/2 of the dependencies get updated?

$ mix deps.update --only prod --all
Resolving Hex dependencies...
Resolution completed in 0.403s
Unchanged:
  certifi 2.12.0
  combine 0.10.0
  cowboy_telemetry 0.4.0
  decimal 2.1.1
  ex_cldr 2.37.5
  fuse 2.5.0
  gen_state_machine 3.0.0
  hackney 1.20.1
  idna 6.1.1
  metrics 1.0.1
  mimerl 1.3.0
  nimble_csv 1.2.0
  parse_trans 3.4.1
  phoenix_live_view 0.18.18
  phoenix_pubsub 2.1.3
  phoenix_template 1.0.4
  ranch 2.1.0
  srtm 0.8.0
  ssl_verify_fun 1.1.7
  timex 3.7.11
  tzdata 1.1.2
  unicode_util_compat 0.7.0
  websock 0.5.3
  websockex 0.4.3
Upgraded:
  castore 1.0.5 => 1.0.8
  cldr_utils 2.24.2 => 2.28.2
  cloak 1.1.2 => 1.1.4
  cloak_ecto 1.2.0 => 1.3.0
  cowboy 2.10.0 => 2.12.0
  cowlib 2.12.1 => 2.13.0
  db_connection 2.6.0 => 2.7.0
  ecto 3.10.3 => 3.12.3
  ecto_sql 3.10.2 => 3.12.0
  ex_cldr_plugs 1.3.1 => 1.3.3
  expo 0.4.1 => 1.1.0 (major)
  finch 0.16.0 => 0.19.0 (minor)
  floki 0.35.2 => 0.36.2 (minor)
  gettext 0.23.1 => 0.26.1 (minor)
  hpax 0.1.2 => 1.0.0 (major)
  jason 1.4.1 => 1.4.4
  mime 2.0.5 => 2.0.6
  mint 1.5.1 => 1.6.2
  nimble_options 1.0.2 => 1.1.1
  nimble_pool 1.0.0 => 1.1.0
  phoenix 1.7.10 => 1.7.14
  phoenix_ecto 4.4.3 => 4.6.2
  phoenix_html 3.3.3 => 3.3.4
  phoenix_view 2.0.3 => 2.0.4
  plug 1.15.2 => 1.16.1
  plug_cowboy 2.6.1 => 2.7.2
  plug_crypto 2.0.0 => 2.1.0
  postgrex 0.17.3 => 0.19.1 (minor)
  telemetry 1.2.1 => 1.3.0
  tesla 1.8.0 => 1.12.1
  tortoise311 0.11.7 => 0.12.0 (minor)
  websock_adapter 0.5.5 => 0.5.7
* Updating castore (Hex package)
* Updating ecto_sql (Hex package)
* Updating ex_cldr_plugs (Hex package)
* Updating finch (Hex package)
* Updating floki (Hex package)
* Updating gettext (Hex package)
* Updating jason (Hex package)
* Updating phoenix (Hex package)
* Updating phoenix_view (Hex package)
* Updating phoenix_ecto (Hex package)
* Updating phoenix_html (Hex package)
* Updating plug_cowboy (Hex package)
* Updating postgrex (Hex package)
* Updating tesla (Hex package)
* Updating tortoise311 (Hex package)
* Updating cloak_ecto (Hex package)
* Updating cloak (Hex package)
* Updating ecto (Hex package)
* Updating telemetry (Hex package)
* Updating mime (Hex package)
* Updating db_connection (Hex package)
* Updating cowboy (Hex package)
* Updating plug (Hex package)
* Updating plug_crypto (Hex package)
* Updating cowlib (Hex package)
* Updating websock_adapter (Hex package)
* Updating expo (Hex package)
* Updating mint (Hex package)
* Updating nimble_options (Hex package)
* Updating nimble_pool (Hex package)
* Updating hpax (Hex package)
* Updating cldr_utils (Hex package)

**Comment by JakobLichterfeld** [comment]
> Will the other ~1/2 of the dependencies get updated?

I wonder since a while why Dependabot not saying anything. Seems like Adrian disabled it for mix 2 years ago:
https://github.com/teslamate-org/teslamate/commit/6e876d76852c34b48b3ca664ac0cd5df1d97ff56

**Comment by brianmay** [comment]
Shame Adrian didn't say why he disabled it. But I imagine it was because he couldn't keep up with the updates. Which is a problem that I regularly face with my projects.

**Comment by JakobLichterfeld** [comment]
> But I imagine it was because he couldn't keep up with the updates. Which is a problem that I regularly face with my projects.

Yes, I assume the same, but anyway, will start with updating tzdata and then one step at a time.

**Comment by a1exus** [comment]
i'm still getting same error w/ 1.3.1

```
# docker compose logs teslamate
teslamate-1  | 2024-09-17 14:08:24.574 [info] Migrations already up
teslamate-1  | 2024-09-17 14:08:25.561 [info] No tzdata release files found in custom data dir. Copying release file from tzdata priv dir.
teslamate-1  | 2024-09-17 14:08:25.619 [info] System Info: Erlang/OTP 26 (jit)
teslamate-1  | 2024-09-17 14:08:25.619 [info] Version: 1.30.1
teslamate-1  | 2024-09-17 14:08:25.646 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
teslamate-1  | 2024-09-17 14:08:25.647 [info] Access TeslaMateWeb.Endpoint at http://teslamate.X.X
teslamate-1  | 2024-09-17 14:08:25.650 [info] MQTT connection has been established
teslamate-1  | 2024-09-17 14:08:28.750 [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.
teslamate-1  | 2024-09-17 14:08:28.896 [error] GenServer :tzdata_release_updater terminating
teslamate-1  | ** (ArgumentError) errors were found at the given arguments:
teslamate-1  |
teslamate-1  |   * 2nd argument: not a tuple
teslamate-1  |
teslamate-1  |     :erlang.element(1, :error)
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
teslamate-1  |     (tzdata 1.1.1) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
teslamate-1  | Last message: :check_if_time_to_update
#
```

**Comment by sdwalker** [comment]
> > But I imagine it was because he couldn't keep up with the updates. Which is a problem that I regularly face with my projects.
> 
> Yes, I assume the same, but anyway, will start with updating tzdata and then one step at a time.

The WIP changes needed to bump to Phoenix HTML 4.1 are at https://gist.github.com/sdwalker/a057d9f8f3425efb746f6805ce087beb

**Comment by JakobLichterfeld** [comment]
> I wonder since a while why Dependabot not saying anything. Seems like Adrian disabled it for mix 2 years ago:
> [6e876d7](https://github.com/teslamate-org/teslamate/commit/6e876d76852c34b48b3ca664ac0cd5df1d97ff56)



> Yes, I assume the same, but anyway, will start with updating tzdata and then one step at a time.

---> #4207

**Comment by a1exus** [comment]
> > i _STILL_ get the same error even w/ latest 1.3.1
> 
> It is not fixed in TeslaMate 1.30.1, so this is expected behavior till a new version is released.

ok, is there ETA for new version? or is there another known version that works? i tried to rollback few version behind, however still couldn't get it to work due to same error.

**Comment by JakobLichterfeld** [comment]
> ok, is there ETA for new version? or is there another known version that works? i tried to rollback few version behind, however still couldn't get it to work due to same error.

This issue described by OP is cosmetic nature. As the dependency always had the issue a rollback does not result in different behavior.

**Comment by a1exus** [comment]
> > ok, is there ETA for new version? or is there another known version that works? i tried to rollback few version behind, however still couldn't get it to work due to same error.
> 
> This issue described by OP is cosmetic nature. As the dependency always had the issue a rollback does not result in different behavior.

it's not cosmetic nature, as i can't start Teslamate inside of the docker container because of that issue though..

**Comment by JakobLichterfeld** [comment]
> it's not cosmetic nature, as i can't start Teslamate inside of the docker container because of that issue though..

The issue described by OP is cosmetic.

If your instance is not starting, please check your tz config in your `docker-compose.yml` and open a separate issue if still present after comparing to https://docs.teslamate.org/docs/installation/docker

**Comment by JakobLichterfeld** [comment]
> The WIP changes needed to bump to Phoenix HTML 4.1 are at https://gist.github.com/sdwalker/a057d9f8f3425efb746f6805ce087beb

-> #4277
