### ISSUE TITLE
perf: drive stat - km driven slow

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#4199]
the query for km driven in drive stats dashboard is slow on slow host hw.

### Expected Behavior

improved query

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Backlog @swiffer  😄

**Comment by swiffer** [comment]
will have a look ;) could you add an explain analyze please ? :)

```sql
explain analyze SELECT 
    DATE(start_date)  AS "time",
    SUM(convert_km((end_km - start_km)::numeric, 'km')) AS "distance_km"
FROM drives 
WHERE car_id = 2
    AND start_date BETWEEN '2023-09-15T10:19:50.176Z' AND '2024-09-15T10:19:50.176Z'
GROUP BY DATE(start_date)
ORDER BY DATE(start_date);
```

**Comment by JakobLichterfeld** [comment]
> will have a look ;) 

Awesome, ty!

> could you add an explain analyze please ? :)

```bash
                                                                                         QUERY PLAN
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=107.43..115.60 rows=297 width=36) (actual time=4.425..7.340 rows=122 loops=1)
   Group Key: (date(start_date))
   ->  Sort  (cost=107.43..108.17 rows=297 width=20) (actual time=4.364..4.521 rows=358 loops=1)
         Sort Key: (date(start_date))
         Sort Method: quicksort  Memory: 33kB
         ->  Seq Scan on drives  (cost=0.00..95.23 rows=297 width=20) (actual time=2.575..3.805 rows=358 loops=1)
               Filter: ((start_date >= '2023-09-15 10:19:50.176'::timestamp without time zone) AND (start_date <= '2024-09-15 10:19:50.176'::timestamp without time zone) AND (car_id = 1))
               Rows Removed by Filter: 1727
 Planning Time: 3.623 ms
 Execution Time: 7.562 ms
(10 rows)
```

**Comment by swiffer** [comment]
7ms is to slow ? 🤔

**Comment by JakobLichterfeld** [comment]
> 7ms is to slow ? 🤔

There must be an error, it is around 26 seconds when I open the dashboard till the km driven is visible

**Comment by swiffer** [comment]
No, copied from the dashboard. Was another panel not loaded that maybe blocked this one?

**Comment by JakobLichterfeld** [comment]
> Was another panel not loaded that maybe blocked this one?

No. Tried to capture it via screenrecord

https://github.com/user-attachments/assets/84f7e73b-023a-42e0-88eb-8f47f9a1ed0f

**Comment by swiffer** [comment]
strange - no explanation, that query is really simple (as you can see from the explain analyze)...

**Comment by JakobLichterfeld** [comment]
Indeed. Can reproduce on Chrome, Safari and Brave Browser.

**Comment by DrMichael** [comment]
Strange. I get 15 seconds on the raspi, but it is loading really fast.

**Comment by JakobLichterfeld** [comment]
> Strange. I get 15 seconds on the raspi, but it is loading really fast.

That sounds like similar behavior to mine, yesterday I got 26s, today it is worse.

**Comment by swiffer** [comment]
@JakobLichterfeld / @DrMichael - could you please both try running the dashboard provided in 

https://github.com/teslamate-org/teslamate/pull/4258

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld / @DrMichael - could you please both try running the dashboard provided in #4258

for sure, see comment in PR
