### ISSUE TITLE
battery health issues

### ISSUE THREAD

**Issue by fay000fay** [teslamate-org/teslamate#4220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

as you can see, there are lots of warnings in this dashboard, my battery is LFP. I can't figure it out. teslamate version is 1.30.1.

### Relevant log output

```shell
024-09-21 00:14:56.549 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (1738.051 ms)
2024-09-21 00:14:57.047 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (486.569 ms)
2024-09-21 00:14:57.204 [info] End of drive initiated by: %TeslaApi.Vehicle.State.Drive{active_route_destination: nil, active_route_energy_at_arrival: nil, active_route_latitude: 3**.56**53, active_route_longitude: 11**.582*73, active_route_miles_to_arrival: nil, active_route_minutes_to_arrival: nil, active_route_traffic_minutes_delay: 0.0, gps_as_of: 172648***693, heading: 41, latitude: 3***.7**859, longitude: 12**.71**15, native_latitude: 35.70052, native_location_supported: 1, native_longitude: 1***.720**49, native_type: "gcj", power: 1, shift_state: "P", speed: 0, timestamp: 172368***94549}
2024-09-21 00:14:57.204 car_id=1 [info] Driving / Ended / 27 km – 44 min
2024-09-21 00:14:57.205 car_id=1 [info] Start / :online
2024-09-21 00:17:09.177 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 408 (9109.339 ms)
2024-09-21 00:17:09.184 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2024-09-21 00:17:09.187 car_id=1 [error] Error / :unknown
2024-09-21 00:17:38.329 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 408 (9140.801 ms)
2024-09-21 00:17:38.330 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2024-09-21 00:17:38.331 car_id=1 [error] Error / :unknown
2024-09-21 00:18:07.462 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 408 (9129.501 ms)
2024-09-21 00:18:07.463 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2024-09-21 00:18:07.463 car_id=1 [error] Error / :unknown
2024-09-21 00:18:29.927 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 540 (2462.326 ms)
2024-09-21 00:18:29.927 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
2024-09-21 00:18:29.928 car_id=1 [error] Error / :unknown
2024-09-21 00:18:52.397 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 540 (2467.491 ms)
2024-09-21 00:18:52.398 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
2024-09-21 00:18:52.398 car_id=1 [error] Error / :unknown
2024-09-21 00:18:59.236 [notice]     :alarm_handler: {:set, {TeslaMate.Vehicles.Vehicle_1_api_error, :fuse_blown}}
2024-09-21 00:19:12.670 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 540 (257.119 ms)
2024-09-21 00:19:12.671 [warning] TeslaApi.Error / {"error": "Get \"http://localhost:7654/vehicle_data?vault_uuid=ff23#####54-c9a7e3102355&app_type=unverified_3p_app&endpoints=charge_state%3Bclimate_state%3Bclosures_state%3Bdrive_state%3Bgui_settings%3Blocation_data%3Bvehicle_config%3Bvehicle_state%3Bvehicle_data_combo&slow_query_time=15&headers%5BX-Request-Timeout%5D=5&let_sleep=true&user_command=true\": EOF"}
2024-09-21 00:19:12.671 car_id=1 [error] Error / :unknown
2024-09-21 00:19:35.090 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 540 (2417.261 ms)
2024-09-21 00:19:35.091 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
2024-09-21 00:19:35.091 car_id=1 [error] Error / :unknown
2024-09-21 00:19:57.610 [warning] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 540 (2516.974 ms)
2024-09-21 00:19:57.610 [warning] TeslaApi.Error / vehicle error: it is online but not responsive
2024-09-21 00:19:57.611 car_id=1 [error] Error / :unknown
2024-09-21 00:20:16.235 [warning] Too many disconnects from streaming API
2024-09-21 00:20:16.236 car_id=1 [info] Creating new connection … 
2024-09-21 00:20:16.236 car_id=1 [info] Disconnecting ...
2024-09-21 00:20:16.266 car_id=1 [info] Connecting ...
2024-09-21 00:20:17.869 car_id=1 [warning] User present ...
2024-09-21 00:25:59.245 [notice]     :alarm_handler: {:clear, TeslaMate.Vehicles.Vehicle_1_api_error}
2024-09-21 00:26:42.422 [info] GET https://owner-api.vn.cloud.tesla.cn/api/1/vehicles/362674****8942/vehicle_data -> 408 (94.873 ms)
2024-09-21 00:26:43.122 [warning] Too many disconnects from streaming API
2024-09-21 00:26:43.122 car_id=1 [info] Creating new connection … 
2024-09-21 00:26:43.122 car_id=1 [info] Disconnecting ...
2024-09-21 00:26:43.137 car_id=1 [info] Connecting ...
2024-09-21 00:26:43.505 [info] Streaming API: Vehicle offline
2024-09-21 00:26:43.505 car_id=1 [warning] Stream reports vehicle as offline, fetching vehicle state ...
2024-09-21 00:26:43.595 car_id=1 [info] Start / :offline
2024-09-21 00:26:43.633 car_id=1 [info] Disconnecting ...
```

### Screenshots

![QQ截图20240921153950](https://github.com/user-attachments/assets/f77a9c82-e6ee-407f-bb8e-bea787b97457)

### Type of installation

Docker

### Version

v1.30.1

**Comment by swiffer** [comment]
Can you show log output of the database container?

**Comment by fay000fay** [comment]
> Can you show log output of the database container?



> Can you show log output of the database container?

![QQ截图20240923120912](https://github.com/user-attachments/assets/82aaff28-1440-47aa-875f-3c97800ac616)
[postgres.zip](https://github.com/user-attachments/files/17092683/postgres.zip)
as you can see, lots errors

**Comment by swiffer** [comment]
Ok, what version of postgres are you running?

**Comment by fay000fay** [comment]
> Ok, what version of postgres are you running?

![QQ截图20240923132827](https://github.com/user-attachments/assets/4cb10cba-7897-4a85-9b69-d75a6f19ee02)
pls see the attachment, thank you.

**Comment by swiffer** [comment]
guess there is an issue with the aux variable query in dashboard settings. can you run the query below:

```sql
WITH Aux AS

(

		SELECT 

    car_id,

		COALESCE(efficiency, 

		(SELECT efficiency

			FROM cars WHERE id = 2) * 100) AS efficiency

	FROM (

		SELECT ROUND((charge_energy_added / NULLIF(end_rated_range_km - start_rated_range_km, 0))::numeric, 3) * 100 as efficiency,

			COUNT(*) as count, 2 AS car_id 

		FROM charging_processes

		WHERE car_id = 2

			AND duration_min > 10

			AND end_battery_level <= 95

			AND start_rated_range_km IS NOT NULL

			AND end_rated_range_km IS NOT NULL

			AND charge_energy_added > 0

		GROUP BY 1

		ORDER BY 2 DESC

		LIMIT 1

	) AS DerivatedEfficiency

),

CurrentCapacity	 AS

(

	SELECT AVG(Capacity) AS Capacity

FROM (

SELECT 

	c.rated_battery_range_km * aux.efficiency / c.usable_battery_level AS Capacity

	FROM charging_processes cp

		INNER JOIN charges c

		ON c.charging_process_id = cp.id 

                INNER JOIN aux ON cp.car_id = aux.car_id

	WHERE cp.car_id = 2

		AND cp.end_date IS NOT NULL

		AND cp.charge_energy_added >= aux.efficiency

		AND c.usable_battery_level > 0

	 ORDER BY cp.end_date DESC LIMIT 10) AS lastCharges

), 

MaxCapacity AS

(

	SELECT 

		MAX(c.rated_battery_range_km * aux.efficiency / c.usable_battery_level) AS Capacity

	FROM charging_processes cp

		INNER JOIN (

			SELECT charging_process_id, MAX(date) as date FROM charges WHERE usable_battery_level > 0 GROUP BY charging_process_id) AS gcharges	

			ON cp.id = gcharges.charging_process_id

		INNER JOIN charges c

		ON c.charging_process_id = cp.id AND c.date = gcharges.date

		INNER JOIN aux ON cp.car_id = aux.car_id

	WHERE cp.car_id = 2

		AND cp.end_date IS NOT NULL

		AND cp.charge_energy_added >= aux.efficiency

), 

CurrentRange AS

(

    SELECT (range * 100.0 / usable_battery_level) AS range

	FROM (

		(SELECT date, rated_battery_range_km AS range, usable_battery_level AS usable_battery_level

			FROM positions	WHERE car_id = 2 AND rated_battery_range_km IS NOT NULL AND usable_battery_level > 0  ORDER BY date DESC LIMIT 1)

		UNION ALL

		(SELECT date, rated_battery_range_km AS range, usable_battery_level as usable_battery_level

			FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id

			WHERE p.car_id = 2 AND usable_battery_level > 0 ORDER BY date DESC LIMIT 1)

	) AS data

	ORDER BY date DESC

	LIMIT 1

), 

MaxRange AS

(

    SELECT

		floor(extract(epoch from date)/86400)*86400 AS time,

	    CASE WHEN sum(usable_battery_level) = 0 THEN sum(rated_battery_range_km) * 100

		     ELSE sum(rated_battery_range_km) / sum(usable_battery_level) * 100

	END AS range

    FROM (

		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 

		JOIN charging_processes p ON p.id = c.charging_process_id 

		WHERE p.car_id = 2 AND usable_battery_level IS NOT NULL) AS data

	GROUP BY 1

	ORDER BY 2 DESC

	LIMIT 1

) 

SELECT  CONCAT('{"MaxRange": ', convert_km(MaxRange.range,'km'),

  ', "CurrentRange": ',convert_km(CurrentRange.range,'km'),

  ', "MaxCapacity": ', MaxCapacity.Capacity,

  ', "CurrentCapacity": ', CASE WHEN CurrentCapacity.Capacity IS NULL THEN 1 ELSE CurrentCapacity.Capacity END,

  ', "RatedEfficiency": ', aux.efficiency, '}') 

FROM MaxRange, CurrentRange, Aux, MaxCapacity, CurrentCapacity
```

**Comment by fay000fay** [comment]
> guess there is an issue with the aux variable query in dashboard settings. can you run the query below:
> 
> ```sql
> WITH Aux AS
> 
> (
> 
> 		SELECT 
> 
>     car_id,
> 
> 		COALESCE(efficiency, 
> 
> 		(SELECT efficiency
> 
> 			FROM cars WHERE id = 2) * 100) AS efficiency
> 
> 	FROM (
> 
> 		SELECT ROUND((charge_energy_added / NULLIF(end_rated_range_km - start_rated_range_km, 0))::numeric, 3) * 100 as efficiency,
> 
> 			COUNT(*) as count, 2 AS car_id 
> 
> 		FROM charging_processes
> 
> 		WHERE car_id = 2
> 
> 			AND duration_min > 10
> 
> 			AND end_battery_level <= 95
> 
> 			AND start_rated_range_km IS NOT NULL
> 
> 			AND end_rated_range_km IS NOT NULL
> 
> 			AND charge_energy_added > 0
> 
> 		GROUP BY 1
> 
> 		ORDER BY 2 DESC
> 
> 		LIMIT 1
> 
> 	) AS DerivatedEfficiency
> 
> ),
> 
> CurrentCapacity	 AS
> 
> (
> 
> 	SELECT AVG(Capacity) AS Capacity
> 
> FROM (
> 
> SELECT 
> 
> 	c.rated_battery_range_km * aux.efficiency / c.usable_battery_level AS Capacity
> 
> 	FROM charging_processes cp
> 
> 		INNER JOIN charges c
> 
> 		ON c.charging_process_id = cp.id 
> 
>                 INNER JOIN aux ON cp.car_id = aux.car_id
> 
> 	WHERE cp.car_id = 2
> 
> 		AND cp.end_date IS NOT NULL
> 
> 		AND cp.charge_energy_added >= aux.efficiency
> 
> 		AND c.usable_battery_level > 0
> 
> 	 ORDER BY cp.end_date DESC LIMIT 10) AS lastCharges
> 
> ), 
> 
> MaxCapacity AS
> 
> (
> 
> 	SELECT 
> 
> 		MAX(c.rated_battery_range_km * aux.efficiency / c.usable_battery_level) AS Capacity
> 
> 	FROM charging_processes cp
> 
> 		INNER JOIN (
> 
> 			SELECT charging_process_id, MAX(date) as date FROM charges WHERE usable_battery_level > 0 GROUP BY charging_process_id) AS gcharges	
> 
> 			ON cp.id = gcharges.charging_process_id
> 
> 		INNER JOIN charges c
> 
> 		ON c.charging_process_id = cp.id AND c.date = gcharges.date
> 
> 		INNER JOIN aux ON cp.car_id = aux.car_id
> 
> 	WHERE cp.car_id = 2
> 
> 		AND cp.end_date IS NOT NULL
> 
> 		AND cp.charge_energy_added >= aux.efficiency
> 
> ), 
> 
> CurrentRange AS
> 
> (
> 
>     SELECT (range * 100.0 / usable_battery_level) AS range
> 
> 	FROM (
> 
> 		(SELECT date, rated_battery_range_km AS range, usable_battery_level AS usable_battery_level
> 
> 			FROM positions	WHERE car_id = 2 AND rated_battery_range_km IS NOT NULL AND usable_battery_level > 0  ORDER BY date DESC LIMIT 1)
> 
> 		UNION ALL
> 
> 		(SELECT date, rated_battery_range_km AS range, usable_battery_level as usable_battery_level
> 
> 			FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id
> 
> 			WHERE p.car_id = 2 AND usable_battery_level > 0 ORDER BY date DESC LIMIT 1)
> 
> 	) AS data
> 
> 	ORDER BY date DESC
> 
> 	LIMIT 1
> 
> ), 
> 
> MaxRange AS
> 
> (
> 
>     SELECT
> 
> 		floor(extract(epoch from date)/86400)*86400 AS time,
> 
> 	    CASE WHEN sum(usable_battery_level) = 0 THEN sum(rated_battery_range_km) * 100
> 
> 		     ELSE sum(rated_battery_range_km) / sum(usable_battery_level) * 100
> 
> 	END AS range
> 
>     FROM (
> 
> 		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 
> 
> 		JOIN charging_processes p ON p.id = c.charging_process_id 
> 
> 		WHERE p.car_id = 2 AND usable_battery_level IS NOT NULL) AS data
> 
> 	GROUP BY 1
> 
> 	ORDER BY 2 DESC
> 
> 	LIMIT 1
> 
> ) 
> 
> SELECT  CONCAT('{"MaxRange": ', convert_km(MaxRange.range,'km'),
> 
>   ', "CurrentRange": ',convert_km(CurrentRange.range,'km'),
> 
>   ', "MaxCapacity": ', MaxCapacity.Capacity,
> 
>   ', "CurrentCapacity": ', CASE WHEN CurrentCapacity.Capacity IS NULL THEN 1 ELSE CurrentCapacity.Capacity END,
> 
>   ', "RatedEfficiency": ', aux.efficiency, '}') 
> 
> FROM MaxRange, CurrentRange, Aux, MaxCapacity, CurrentCapacity
> ```

![QQ截图20240923144714](https://github.com/user-attachments/assets/c91a9bc0-6827-4ff8-a871-62383fae856d)

it shows nothing. something wrong?

**Comment by fay000fay** [comment]
> > guess there is an issue with the aux variable query in dashboard settings. can you run the query below:
> > ```sql
> > WITH Aux AS
> > 
> > (
> > 
> > 		SELECT 
> > 
> >     car_id,
> > 
> > 		COALESCE(efficiency, 
> > 
> > 		(SELECT efficiency
> > 
> > 			FROM cars WHERE id = 2) * 100) AS efficiency
> > 
> > 	FROM (
> > 
> > 		SELECT ROUND((charge_energy_added / NULLIF(end_rated_range_km - start_rated_range_km, 0))::numeric, 3) * 100 as efficiency,
> > 
> > 			COUNT(*) as count, 2 AS car_id 
> > 
> > 		FROM charging_processes
> > 
> > 		WHERE car_id = 2
> > 
> > 			AND duration_min > 10
> > 
> > 			AND end_battery_level <= 95
> > 
> > 			AND start_rated_range_km IS NOT NULL
> > 
> > 			AND end_rated_range_km IS NOT NULL
> > 
> > 			AND charge_energy_added > 0
> > 
> > 		GROUP BY 1
> > 
> > 		ORDER BY 2 DESC
> > 
> > 		LIMIT 1
> > 
> > 	) AS DerivatedEfficiency
> > 
> > ),
> > 
> > CurrentCapacity	 AS
> > 
> > (
> > 
> > 	SELECT AVG(Capacity) AS Capacity
> > 
> > FROM (
> > 
> > SELECT 
> > 
> > 	c.rated_battery_range_km * aux.efficiency / c.usable_battery_level AS Capacity
> > 
> > 	FROM charging_processes cp
> > 
> > 		INNER JOIN charges c
> > 
> > 		ON c.charging_process_id = cp.id 
> > 
> >                 INNER JOIN aux ON cp.car_id = aux.car_id
> > 
> > 	WHERE cp.car_id = 2
> > 
> > 		AND cp.end_date IS NOT NULL
> > 
> > 		AND cp.charge_energy_added >= aux.efficiency
> > 
> > 		AND c.usable_battery_level > 0
> > 
> > 	 ORDER BY cp.end_date DESC LIMIT 10) AS lastCharges
> > 
> > ), 
> > 
> > MaxCapacity AS
> > 
> > (
> > 
> > 	SELECT 
> > 
> > 		MAX(c.rated_battery_range_km * aux.efficiency / c.usable_battery_level) AS Capacity
> > 
> > 	FROM charging_processes cp
> > 
> > 		INNER JOIN (
> > 
> > 			SELECT charging_process_id, MAX(date) as date FROM charges WHERE usable_battery_level > 0 GROUP BY charging_process_id) AS gcharges	
> > 
> > 			ON cp.id = gcharges.charging_process_id
> > 
> > 		INNER JOIN charges c
> > 
> > 		ON c.charging_process_id = cp.id AND c.date = gcharges.date
> > 
> > 		INNER JOIN aux ON cp.car_id = aux.car_id
> > 
> > 	WHERE cp.car_id = 2
> > 
> > 		AND cp.end_date IS NOT NULL
> > 
> > 		AND cp.charge_energy_added >= aux.efficiency
> > 
> > ), 
> > 
> > CurrentRange AS
> > 
> > (
> > 
> >     SELECT (range * 100.0 / usable_battery_level) AS range
> > 
> > 	FROM (
> > 
> > 		(SELECT date, rated_battery_range_km AS range, usable_battery_level AS usable_battery_level
> > 
> > 			FROM positions	WHERE car_id = 2 AND rated_battery_range_km IS NOT NULL AND usable_battery_level > 0  ORDER BY date DESC LIMIT 1)
> > 
> > 		UNION ALL
> > 
> > 		(SELECT date, rated_battery_range_km AS range, usable_battery_level as usable_battery_level
> > 
> > 			FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id
> > 
> > 			WHERE p.car_id = 2 AND usable_battery_level > 0 ORDER BY date DESC LIMIT 1)
> > 
> > 	) AS data
> > 
> > 	ORDER BY date DESC
> > 
> > 	LIMIT 1
> > 
> > ), 
> > 
> > MaxRange AS
> > 
> > (
> > 
> >     SELECT
> > 
> > 		floor(extract(epoch from date)/86400)*86400 AS time,
> > 
> > 	    CASE WHEN sum(usable_battery_level) = 0 THEN sum(rated_battery_range_km) * 100
> > 
> > 		     ELSE sum(rated_battery_range_km) / sum(usable_battery_level) * 100
> > 
> > 	END AS range
> > 
> >     FROM (
> > 
> > 		SELECT battery_level, usable_battery_level, date,  rated_battery_range_km from charges c 
> > 
> > 		JOIN charging_processes p ON p.id = c.charging_process_id 
> > 
> > 		WHERE p.car_id = 2 AND usable_battery_level IS NOT NULL) AS data
> > 
> > 	GROUP BY 1
> > 
> > 	ORDER BY 2 DESC
> > 
> > 	LIMIT 1
> > 
> > ) 
> > 
> > SELECT  CONCAT('{"MaxRange": ', convert_km(MaxRange.range,'km'),
> > 
> >   ', "CurrentRange": ',convert_km(CurrentRange.range,'km'),
> > 
> >   ', "MaxCapacity": ', MaxCapacity.Capacity,
> > 
> >   ', "CurrentCapacity": ', CASE WHEN CurrentCapacity.Capacity IS NULL THEN 1 ELSE CurrentCapacity.Capacity END,
> > 
> >   ', "RatedEfficiency": ', aux.efficiency, '}') 
> > 
> > FROM MaxRange, CurrentRange, Aux, MaxCapacity, CurrentCapacity
> > ```
> 
> ![QQ截图20240923144714](https://private-user-images.githubusercontent.com/10692621/369773358-c91a9bc0-6827-4ff8-a871-62383fae856d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzQ0OTUsIm5iZiI6MTcyNzA3NDE5NSwicGF0aCI6Ii8xMDY5MjYyMS8zNjk3NzMzNTgtYzkxYTliYzAtNjgyNy00ZmY4LWE4NzEtNjIzODNmYWU4NTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA2NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjA2MDM1ZGVjMDMzMDk0ZjJjMWUxNTc5OGFlNGQ3Y2ZjMDljMjc1ZjgzOTZlYTRjZDg4ZTVjMTM4OThmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6fxYJnE_DU0CDL6wlD4oSE9hQ9KHdBMJqCTa98XgkRE)
> 
> it shows nothing. something wrong?

my car_id is 1, and I replace all, still nothing data output.

**Comment by swiffer** [comment]
ok, that's the problem - no output means invalid json and therefore most queries on the dashboard fail.

could you run the ctes individually to see what they are returning (and yes, car_id = 1 in your case).

**Comment by fay000fay** [comment]
> ok, that's the problem - no output means invalid json and therefore most queries on the dashboard fail.
> 
> could you run the ctes individually to see what they are returning (and yes, car_id = 1 in your case).

yes, sure, pls see the pngs.
![Aux CTE](https://github.com/user-attachments/assets/d5701c97-8109-4047-bf06-0d7ef506cc79)
![CurrentRange CTE](https://github.com/user-attachments/assets/2ee90e59-9807-475c-84f1-04e91c29895f)
![MaxCapacity CTE](https://github.com/user-attachments/assets/25cfe4e9-239e-40b6-9df8-1faede2c670a)
![MaxRange CTE](https://github.com/user-attachments/assets/ffdb744d-9d65-4ec0-b9f3-603496eb27c8)
![CurrentCapacity CTE](https://github.com/user-attachments/assets/537ae2c9-badc-42d6-b822-bd69ef4618c4)

**Comment by JakobLichterfeld** [comment]
> as you can see, there are lots of warnings in this dashboard, my battery is LFP. I can't figure it out. teslamate version is 1.30.1.

Thanks for reporting.

From the log you posted, we can see your car is not logging anything.

The dashboard can only display data if there has been any recorded data (Which need to match certain criteria for this dashboard to function as well).

If you have recorded data and all other dashboards works as expected:

Have you installed any custom dashboards or messed with the grafana config in any other style?

**Comment by swiffer** [comment]
@JakobLichterfeld - thanks, i was to focused on the dashboard - if no data has been collected sure we can't show anything. if it's lfp and data has been collected it might be a sql problem (excluding charges over 95%. i would still like to fix the query in case no data is returned. will have a look ;)

**Comment by MatthewFYD** [comment]
If 'end_dattery_level' is set to 100, data will only appear on my dashboard
How do I set it to 100
