### ISSUE TITLE
New insallation docker-compose - Teslamate continuously reboot

### ISSUE THREAD

**Issue by reydecopas** [teslamate-org/teslamate#4233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

after locate a code to avoid the "earth" issue...
the next one issue is "function gc_to_sec"  problem...

### Expected Behavior

from clean installation to up and running with a completely new database

### Steps To Reproduce

1. clean enviroment
2. docker-compose up -d
3. docker logs teslamate

### Relevant log output

```shell
2024-09-29 17:41:19.390 [info] execute "CREATE EXTENSION IF NOT EXISTS cube"
2024-09-29 17:41:19.394 [info] execute "CREATE EXTENSION IF NOT EXISTS earthdistance"
2024-09-29 17:41:19.395 [info] create index geofences__earth_box_ll_to_earth_latitude__longitude___radius_index
** (Postgrex.Error) ERROR 42704 (undefined_object) type "earth" does not exist
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
2024-09-29 17:41:21.216 [info] == Running 20190925152807 TeslaMate.Repo.Migrations.CreateGeoExtensions.change/0 forward
2024-09-29 17:41:21.217 [info] execute "CREATE EXTENSION IF NOT EXISTS cube"
2024-09-29 17:41:21.222 [info] execute "CREATE EXTENSION IF NOT EXISTS earthdistance"
2024-09-29 17:41:21.223 [info] create index geofences__earth_box_ll_to_earth_latitude__longitude___radius_index
```

### Type of installation

Docker

### Version

latest

**Comment by reydecopas** [comment]
after running in psql:
CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;
ALTER FUNCTION public.ll_to_earth SET search_path = public;


docker logs teslamate:
2024-09-29 17:56:32.884 [info] == Running 20190925152807 TeslaMate.Repo.Migrations.CreateGeoExtensions.change/0 forward
2024-09-29 17:56:32.886 [info] execute "CREATE EXTENSION IF NOT EXISTS cube"
2024-09-29 17:56:32.886 [info] extension "cube" already exists, skipping
2024-09-29 17:56:32.886 [info] execute "CREATE EXTENSION IF NOT EXISTS earthdistance"
2024-09-29 17:56:32.886 [info] extension "earthdistance" already exists, skipping
2024-09-29 17:56:32.886 [info] create index geofences__earth_box_ll_to_earth_latitude__longitude___radius_index
** (Postgrex.Error) ERROR 42883 (undefined_function) function gc_to_sec(double precision) does not exist

    hint: No function matches the given name and argument types. You might need to add explicit type casts.
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1047: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/adapters/sql.ex:1154: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.2) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3

**Comment by swiffer** [comment]
Please use Postgrs 16 for now, Postgres 17 support is added in next release.

Otherwise:

See here for second function you need to alter

https://github.com/teslamate-org/teslamate/blob/master/priv/repo/migrations/20190925152807_create_geo_extensions.exs

**Comment by pk825** [comment]
If I modify the yaml forcing the 16 postegree version I have an error with the directory path that is not compatible with the version of postgree/debian

**Comment by swiffer** [comment]
yes, in that case you need to drop the teslamate volume that has been created in v17.

`docker volume rm "$(basename "$PWD")_teslamate-db"`

as v17 works (despite initial migration) you could also stick with v17 and just run the queries shown in my link above before starting teslamate.

**Comment by pk825** [comment]
> yes, in that case you need to drop the teslamate volume that has been created in v17.
> 
> `docker volume rm "$(basename "$PWD")_teslamate-db"`
> 
> as v17 works (despite initial migration) you could also stick with v17 and just run the queries shown in my link above before starting teslamate.

thank you, it works now :)

**Comment by reydecopas** [comment]
solved changing docker-compose to postgress:16
