### ISSUE TITLE
perf: cost per 100 km in charging stats is slow

### ISSUE THREAD

**Issue by JakobLichterfeld** [teslamate-org/teslamate#4251]
The query for cost per 100 km in charging stats dashboard is slow on slow host hw.

### Expected Behavior

improved query

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Backlog @swiffer  😄

**Comment by swiffer** [comment]
Yes - positions table involved in the query... TimescaleDB continous aggregates to the rescue...

Let me see if we can make use of the newly created index to skip streamed data. Not needed in this query...
