### ISSUE TITLE
DateTime.from_iso8601 returns unexpected tuple

### ISSUE THREAD

**Issue by brianmay** [teslamate-org/teslamate#4260]
https://github.com/teslamate-org/teslamate/blob/ad341310893fdb14ebd3cb72e1cc23e467c3e6a2/lib/teslamate/log.ex#L176-L185

If you look at the logs, there was is scary looking error that isn't generating a test failure:

```
** (FunctionClauseError) no function clause matching in DateTime.to_naive/1
    (elixir 1.16.2) lib/calendar/datetime.ex:925: DateTime.to_naive({:ok, ~U[2003-07-01 00:00:00Z], 0})
    (teslamate 1.30.2-dev) lib/teslamate/log.ex:185: TeslaMate.Log.get_positions_without_elevation/2
    (teslamate 1.30.2-dev) lib/teslamate/terrain.ex:77: TeslaMate.Terrain.handle_event/4
    (stdlib 5.2.3.2) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

Problem is DateTime.from_iso8601 returns a tuple, and could in theory fail. Sigh. Wish Elixir had strong type checking...

In actual practice, this function call probably I think can't fail, the value is constant.

**Comment by swiffer** [comment]
sorry for introducing this issue, not enough elixir experience

**Comment by swiffer** [comment]
@JakobLichterfeld - error has already been logged in this run, but test completed successfully

https://github.com/teslamate-org/teslamate/actions/runs/11443404821/job/31836224603

**Comment by JakobLichterfeld** [comment]
> error has already been logged in this run, but test completed successfully

Yeah, assume the same as Brian:

> I suspect (but haven't checked) the reason this didn't cause the tests to fail is because the errors occurred in another process, not the test process.
