### ISSUE TITLE
ci: ghcr_build workflow_call fail when running from a fork

### ISSUE THREAD

**Issue by scottbot95** [teslamate-org/teslamate#4266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When submitting a pull request from a fork the various `ghcr_build` workflows will fail with 403 errors (presumably because the workflow is trying to push to the main repository from the PR fork)

([example](https://github.com/teslamate-org/teslamate/actions/runs/11335144167/job/31525967720?pr=4265))

### Expected Behavior

We either just build, but don't publish the various images, or we push images to the fork the PR originates from.

### Steps To Reproduce

1. Create fork
2. Submit PR

### Relevant log output

```shell
N/A
```

### Type of installation

Manual

### Version

N/A

**Comment by scottbot95** [comment]
According to [this post](https://github.com/orgs/community/discussions/25217#discussioncomment-3246901) it sounds like we could probably use `github.event.pull_request.head.repo.full_name` instead of `github.repository`

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. I'm aware of it, didn't find the time yet to fix it. This was something untestable locally.
ghcr build needs to be suppressed on push from fork, `pull_request` target runs fines as we use teslamate-org credentials there.

**Comment by JakobLichterfeld** [comment]
> According to [this post](https://github.com/orgs/community/discussions/25217#discussioncomment-3246901) it sounds like we could probably use `github.event.pull_request.head.repo.full_name` instead of `github.repository`

We already do that: https://github.com/teslamate-org/teslamate/blob/773a58e023dd189dcda15118b4bf256d1a7cadc7/.github/workflows/devops.yml#L58

Anyways, will solve it.
