### ISSUE TITLE
Drive Stats: Top 10 Destinations query issue with postgres <16

### ISSUE THREAD

**Issue by xxxarmitagexxx** [teslamate-org/teslamate#4295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After importing the pulling the latest Grafana dashboards from GitHub, the Top 10 Destinations panel in the Drive stats is no longer loading data. 

The error is very explicit: 
`db query error: pq: subquery in FROM must have an alias`

If the query is run as is in pgAdmin, the same error is reached and can easily be fixed by adding an alias at the end of the subquery: 
eg: 
```
SELECT * FROM (
SELECT
	COALESCE(g.name, COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), ''))) as name,
	count(*) AS visited
FROM drives t
INNER JOIN addresses a ON end_address_id = a.id
LEFT JOIN geofences g ON end_geofence_id = g.id
WHERE t.car_id = $car_id AND $__timeFilter(t.start_date) and $__timeFilter(t.end_date) 
GROUP BY 1
ORDER BY visited DESC) as foo
WHERE name NOT ILIKE ALL ${exclude_formatted_string:raw}
LIMIT 10;
```

### Expected Behavior

The query should run normally

### Steps To Reproduce

Go to Grafana, Drive Stats, Top 10 Destinations should fail to load.

### Relevant log output

```shell
`db query error: pq: subquery in FROM must have an alias`
```

### Screenshots

![Screenshot 2024-10-22 at 09-48-39 Drive Stats - TeslaMate - Dashboards - Grafana](https://github.com/user-attachments/assets/adc4d4fc-6a8e-4166-850b-474571d8249b)

### Type of installation

Docker

### Version

v1.30.1

**Comment by JakobLichterfeld** [comment]
Not reproducible with v1.30.1

**Comment by xxxarmitagexxx** [comment]
My guess is that it is a different behavior in more recent Grafana versions as I am running Grafana v11.2.2.

**Comment by JakobLichterfeld** [comment]
> My guess is that it is a different behavior in more recent Grafana versions as I am running Grafana v11.2.2.

Thats why Teslamate uses Grafana 11.0.x atm. See: #4162 where we log the issues regarding Grafana 11.2.x

**Comment by davull** [comment]
I see the same error with the current version 1.31.0 with grafana 11.0.6+security-01  (from /api/health) and Postgres:15 docker image.

Regards and thank you :)

**Comment by JakobLichterfeld** [comment]
Not reproducible with v1.31.0

**Comment by davull** [comment]
Thank you; I found that alias was made optional for subqueries with Postgres 16.

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=bcedd8f5fce0b69970cf0cee7bca560833d05869

I will update my postgres at some time

**Comment by JakobLichterfeld** [comment]
> I found that alias was made optional for subqueries with Postgres 16.

A nice catch. Ty.

@swiffer: davull found a query with is not backwards compatible, see above.

**Comment by swiffer** [comment]
thanks, added a commit fixing this issue to latest PR - but: upgrade postgres, it's worth it 💯
