### ISSUE TITLE
Missing PR #4124 in 1.31

### ISSUE THREAD

**Issue by stauffenberg2020** [teslamate-org/teslamate#4306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

PR #4124 is expected to be part of  release 1.31.0, But it seems to be missing.

### Expected Behavior

Expected different colours for different type of charges

### Steps To Reproduce

NA

### Relevant log output

```shell
NA
```

### Type of installation

Docker

### Version

v1.31.0

**Comment by swiffer** [comment]
that seems to have been overwritten by the rewrite done in #4144 - preparing a fix. also some overwrites are currently looking a bit strange - fixing these as well.
