### ISSUE TITLE
Drive Stats show high Max Speeds that are incorrect, as conversion to mph is missing

### ISSUE THREAD

**Issue by laneyweb** [teslamate-org/teslamate#4343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When viewing the Drive Stats page, my Max Speed values are unusually high. They are definitely incorrect. I have not exceeded 90MPH ever and they are showing as 146, 126 and 111. 
I have looked in the Drives section and no drives go above 88.
Is there any way I can check or fix this issue?

### Expected Behavior

Accurate MAx mileage in Drive Stats page.

### Steps To Reproduce

1. Open Drive Stats Dashboard.
2. View Max Speeds (higher than expected).
3. Open Drives and sort by Max speed column. Max values do not match.

### Relevant log output

```shell
No logs seem relevant.
```

### Screenshots

![brave_5PtiyqJepj](https://github.com/user-attachments/assets/e40737e5-8dbd-40f7-9c0b-c239707b4823)
![brave_eCQ3rlB26N](https://github.com/user-attachments/assets/fe2d5d8f-e2dd-4bb3-80d2-46308dbe1a78)

### Type of installation

Docker

### Version

Version	1.31.1

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. The conversion from km to miles is missing in the new introduced max speed, which is already fixed in #4338 and will be included in next release.

**Comment by laneyweb** [comment]
Thank you.
