### ISSUE TITLE
RFE: MQTT data formatted as JSON

### ISSUE THREAD

**Issue by billygr** [teslamate-org/teslamate#4346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All of my "home" devices (meaning sensors/lights/switches etc) are connected to a mosquitto instance (our broker) where a telegraf instance is subscribed to the # topic (meaning ALL) parse the JSON data and keep them to an influxdb for long term storage (regardless of the HomeAssistant)

While trying to figure out why i don't see any data written in the influxdb (over the last months) becide the 
teslamate/cars/$car_id/location
teslamate/cars/$car_id/active_route

While the MQTT from teslamate are being send correctly, i noticed that it works as expected :) since i am waiting for JSON and only two of them are json formatted from teslamate :)

Technically the MQTT message can be in any format (including txt, XML or JSON) 

Ask:
Is it possible to have one entry formatted as json in the MQTT message ?

I have checked the [teslamate](https://github.com/teslamate-org/teslamate/tree/master)/[lib](https://github.com/teslamate-org/teslamate/tree/master/lib)/[teslamate](https://github.com/teslamate-org/teslamate/tree/master/lib/teslamate)/[mqtt](https://github.com/teslamate-org/teslamate/tree/master/lib/teslamate/mqtt)

But i have absolutely no idea about elixir...

 

### Relevant log output

```shell
.
```

### Type of installation

Docker

### Version

v.1.31.1

**Comment by JakobLichterfeld** [comment]
> While the MQTT from teslamate are being send correctly, i noticed that it works as expected :)

Glad that there is no issue with TeslaMate.

> Is it possible to have one entry formatted as json in the MQTT message ?

Sending all the data in one JSON blob is not the spirit of MQTT, nor performant on either side, nor easy to handle. We decided to send related values like `teslamate/cars/$car_id/location` as json, as a latitude makes no sense without a longitude. You can see the format here: https://docs.teslamate.org/docs/integrations/mqtt/

Combining all values into one JSON is possible on the user side if you choose to do so on your instance.
