### ISSUE TITLE
Show full VIN in dashboards when no car-name set at all

### ISSUE THREAD

**Issue by swiffer** [teslamate-org/teslamate#4353]
Hi everyone, 

I had previously opened this pull request, for cases of unnamed vehicles
* https://github.com/teslamate-org/teslamate/pull/4198

Looks like the behavior changed in this pull request 

### From:

<img src="https://github.com/user-attachments/assets/a3acdf05-4a63-48d3-9741-056d8e1d8e05" width="450px" />

### To:

<img src="https://github.com/user-attachments/assets/ff6207f9-5dbc-4c7f-900f-775cb17f44ac" width="400px"/>

In my opinion, displaying a bunch of numbers with no context isn't too great. 

Would you be opposed if I opened a new pull request to change back the case of unnamed vehicles to `VIN $full_vin`?

In summary:
* Uniquely named vehicles: `$Name`
* Duplicate named vehicles: `$Name - $Last_six_of_vin`
* Unnamed vehicles: `VIN $Full_vin`

c.c. @swiffer , @JakobLichterfeld , @edgararroyo

_Originally posted by @arcastro in https://github.com/teslamate-org/teslamate/issues/4230#issuecomment-2453862453_

**Comment by arcastro** [comment]
Thank you both @swiffer  and @JakobLichterfeld 👍👍
