### ISSUE TITLE
Model S long range miss labeled as a 100D

### ISSUE THREAD

**Issue by VintageWillis** [teslamate-org/teslamate#4368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Very minor issue, the teslamate dashboard labels by Model S long range plus as a 100D. I know they are basically the same but it just doesn't line up with the Tesla naming from the car info and app.

 
![image](https://github.com/user-attachments/assets/8b404061-c1d9-4c15-bb26-7735624a38f6)

![image](https://github.com/user-attachments/assets/98d91d41-be47-4e4f-8b7a-2bfbde588647)

I'm guessing this might also be the same with other raven Model Ss (long Range, Long Range Plus, Performance) 

### Relevant log output

```shell
NA
```

### Type of installation

Docker

### Version

1.31.1

**Comment by cwanja** [comment]
Can you please query the Tesla API and get your [`'vehicle_config' -> 'car_type'`](https://tesla-api.timdorr.com/vehicle/state/data#response)? 

Follows #2193, #2454. Mimic PR #2455

**Comment by VintageWillis** [comment]
"car_type":"models2"

**Comment by cwanja** [comment]
Thank you! Can you get your `trim_badging` as well? Assume 100D, but want to confirm.

**Comment by VintageWillis** [comment]
You're correct ;)!
`"trim_badging":"100d"`

**Comment by cwanja** [comment]
Can you deploy #4370 and verify it is reporting correctly?

**Comment by VintageWillis** [comment]
> Can you deploy #4370 and verify it is reporting correctly?

I might need some help on how to, I'm using a Pi5 do I modify the compose.yml file to point to this new build?

**Comment by cwanja** [comment]
> > Can you deploy #4370 and verify it is reporting correctly?
> 
> 
> 
> I might need some help on how to, I'm using a Pi5 do I modify the compose.yml file to point to this new build?

https://docs.teslamate.org/docs/development#testing-with-our-ci-which-builds-the-docker-images-automatically-per-pr

To test the changes introduce by a PR you can edit your docker-compose.yml file as follows (replace pr-3836 with the PR number)

```
teslamate:
  # image: teslamate/teslamate:latest
  image: ghcr.io/teslamate-org/teslamate:pr-3836
```

**Comment by VintageWillis** [comment]
Thanks , that works although the tooltip shows 100D when hovering over the model. But that might be expected?

![image](https://github.com/user-attachments/assets/5b78d5c4-8fd4-428b-a83b-a7465fc1d122)

**Comment by cwanja** [comment]
That is intended, as it is reporting the `trim_badging` from the Tesla API. For the "marketing name", we string together various variables and concatenate them for the display.

https://github.com/cwanja/teslamate/blob/3a5dfb8aca4a74a4f3f472bbd390a3d8e0ab9a71/lib/teslamate_web/live/car_live/summary.html.heex#

**Comment by VintageWillis** [comment]
Super happy with that great work
