### ISSUE TITLE
Error: :nxdomain

### ISSUE THREAD

**Issue by a1exus** [teslamate-org/teslamate#4383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i used [tesla_auth](https://github.com/adriankumpf/tesla_auth) as Tesla API tokens generator, then copy and paste access & refresh token into teslamate app, yet getting this error

> Error: :nxdomain

### Expected Behavior

sign into teslamate ui

### Steps To Reproduce

1. download/run tesla_auth
2. open teslamate over web and copy/paste respective tokens

### Relevant log output

```shell
teslamate-1  | 2024-11-14 22:49:31.878 [error] POST https://auth.tesla.com/oauth2/v3/token -> error: :nxdomain (8001.790 ms)
```

### Type of installation

Docker

### Version

teslamate/teslamate:1.31.1

**Comment by cwanja** [comment]
Is the hosting device able to access the internet? Have you restarted the containers?

**Comment by a1exus** [comment]
> Is the hosting device able to access the internet? Have you restarted the containers?

i actually just restarted host and was able to login just now! so i guess the issue wasn't teslamate, but rather somewhere else..
