### ISSUE TITLE
Drive Stats report showing high Max Speed

### ISSUE THREAD

**Issue by vincep5** [teslamate-org/teslamate#4385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Drive Stats report is showing the 3 sections of Max Speed, Max Speed (last 30d), and Max Speed (last 7d) likely in kilometers per hour instead of miles per hour for those in the United States.

### Expected Behavior

SQL should be converted into mph

### Relevant log output

```shell
none
```

### Screenshots

![image](https://github.com/user-attachments/assets/877679e6-85e7-44f8-a04c-e71c76f7bdda)

### Type of installation

Docker

### Version

1.31.1

**Comment by cwanja** [comment]
Please see #4343. Duplicate.
