### ISSUE TITLE
Enabling teslaMate in Sentry Mode increases battery consumption

### ISSUE THREAD

**Issue by ahzdhfzd** [teslamate-org/teslamate#4396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sentinel mode case with teslaMate on increases battery consumption. It consumes 3% more power than in I don't have teslaMate turned on.

### Expected Behavior

First of all, I'm sorry for the delay, because of my lack of English and programming skills, I may not have seen the relevant documents. The following description is translated by translation software, it may be a bit strange, sorry.
Sentinel mode case with teslaMate on increases battery consumption. It consumes 3% more power than in I don't have teslaMate turned on.
Is it because with Sentinel Mode on, the vehicle will not be in sleep mode, causing the teslaMate to poll the query more often, which leads to an increase in power consumption.
I see that the database is now updating data once every 5 seconds, is it because the vehicle is in online mode that the polling frequency is so high.
Additionally, these data requests need to go to the vehicle location, whether this raises the power consumption.

### Relevant log output

```shell
null
```

### Type of installation

Docker

### Version

latest

**Comment by JakobLichterfeld** [comment]
Sentry mode results in the car not going to sleep, independent of TeslaMate

**Comment by ahzdhfzd** [comment]
> Sentry mode results in the car not going to sleep, independent of TeslaMate哨兵模式导致汽车无法进入睡眠状态，与 TeslaMate 无关

So using the TeslaMate without going into sleep mode consumes the same amount of power as using the TeslaMate in sleep mode right?

**Comment by JakobLichterfeld** [comment]
In SentryMode the car is always awake, cameras are on, MCU is on (tesla tries currently to reduce the power consumption in Sentry Mode, in Cybertruck this has been succesfull).
The car will use ~300W/h in Sentry Mode, independend of TeslaMate

**Comment by ahzdhfzd** [comment]
> In SentryMode the car is always awake, cameras are on, MCU is on (tesla tries currently to reduce the power consumption in Sentry Mode, in Cybertruck this has been succesfull). The car will use ~300W/h in Sentry Mode, independend of TeslaMate

Thanks I got it. Perhaps the TeslaMate has statistics on the sentry mode state, with some sleep mode-like special handling for that state?

**Comment by JakobLichterfeld** [comment]
TeslaMate detects SentryMode, you can see an corresponding icon on the webpage.
