### ISSUE TITLE
login mode, refreshing webview again after a long period of inactivity, reports an "Internal Server Error" error

### ISSUE THREAD

**Issue by leeyxq** [teslamate-org/teslamate#4435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Dashboard homepage, in login mode, refreshing again after a long period of inactivity reports an "Internal Server Error" error

### Steps To Reproduce

1.Open the dashboard homepage；
2.enter your username and password, log in；
3.then hold the page for 1 day, refresh again, and then an error message appears

### Relevant log output

```shell
teslamate-teslamate-1  | 2024-12-10 11:22:43.998 [info] GET /
teslamate-teslamate-1  | 2024-12-10 11:22:44.004 [info] Sent 500 in 5ms
teslamate-teslamate-1  | 2024-12-10 11:22:44.005 [error] #PID<0.440495.0> running TeslaMateWeb.Endpoint (connection #PID<0.440486.0>, stream id 1) terminated
teslamate-teslamate-1  | Server: teslamate.waidiche.top:80 (http)
teslamate-teslamate-1  | Request: GET /
teslamate-teslamate-1  | ** (exit) an exception was raised:
teslamate-teslamate-1  |     ** (ArgumentError) time_zone_not_found
teslamate-teslamate-1  |         (timex 3.7.11) lib/format/datetime/formatter.ex:55: Timex.Format.DateTime.Formatter.lformat!/4
teslamate-teslamate-1  |         (teslamate 1.32.0) lib/teslamate_web/live/car_live/summary.html.heex:228: anonymous fn/2 in TeslaMateWeb.CarLive.Summary.render/1
teslamate-teslamate-1  |         (phoenix_live_view 0.20.17) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
teslamate-teslamate-1  |         (phoenix_live_view 0.20.17) lib/phoenix_live_view/diff.ex:532: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
teslamate-teslamate-1  |         (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
teslamate-teslamate-1  |         (phoenix_live_view 0.20.17) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
teslamate-teslamate-1  |         (phoenix_live_view 0.20.17) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
teslamate-teslamate-1  |         (phoenix_live_view 0.20.17) lib/phoenix_live_view/static.ex:249: Phoenix.LiveView.Static.to_rendered_content_tag/4
```

### Screenshots

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/4f3de0d6-5181-49de-b720-a598fc71ccf6">
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/81a7b8d5-2842-4155-8b10-b65889801354">

### Type of installation

Docker

### Version

v1.32.0

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

Can you please share your docker compose (without your secrets)?

**Comment by leeyxq** [comment]
> Thanks for reporting.
> 
> Can you please share your docker compose (without your secrets)?

docker-compose.yml

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=${TM_ENCRYPTION_KEY}
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=${FQDN_TM}
      - CHECK_ORIGIN=true
      - TZ=${TM_TZ}
    volumes:
      - ./import:/opt/app/import
    labels:
      traefik.enable: "true"
      traefik.port: "4000"
      traefik.http.middlewares.redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.teslamate-auth.basicauth.realm: "teslamate"
      traefik.http.middlewares.teslamate-auth.basicauth.usersfile: "/auth/.htpasswd"
      traefik.http.routers.teslamate-insecure.rule: "Host(`${FQDN_TM}`)"
      traefik.http.routers.teslamate-insecure.middlewares: "redirect"
      traefik.http.routers.teslamate-ws.rule: "Host(`${FQDN_TM}`) && Path(`/live/websocket`)"
      traefik.http.routers.teslamate-ws.entrypoints: "websecure"
      traefik.http.routers.teslamate-ws.tls: ""
      traefik.http.routers.teslamate.rule: "Host(`${FQDN_TM}`)"
      traefik.http.routers.teslamate.middlewares: "teslamate-auth"
      traefik.http.routers.teslamate.entrypoints: "websecure"
      traefik.http.routers.teslamate.tls.certresolver: "tmhttpchallenge"
    cap_drop:
      - ALL

  database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${TM_DB_USER}
      - POSTGRES_PASSWORD=${TM_DB_PASS}
      - POSTGRES_DB=${TM_DB_NAME}
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PW}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SERVER_DOMAIN=${FQDN_TM}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

    volumes:
      - teslamate-grafana-data:/var/lib/grafana
    labels:
      traefik.enable: "true"
      traefik.port: "3000"
      traefik.http.middlewares.redirect.redirectscheme.scheme: "https"
      traefik.http.routers.grafana-insecure.rule: "Host(`${FQDN_TM}`)"
      traefik.http.routers.grafana-insecure.middlewares: "redirect"
      traefik.http.routers.grafana.rule: "Host(`${FQDN_TM}`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      traefik.http.routers.grafana.entrypoints: "websecure"
      traefik.http.routers.grafana.tls.certresolver: "tmhttpchallenge"

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  proxy:
    image: traefik:v2.7
    restart: always
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.tmhttpchallenge.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.tmhttpchallenge.acme.storage=/etc/acme/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd:/auth/.htpasswd
      - ./acme/:/etc/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:

**Comment by leeyxq** [comment]
Oh, sorry, it's because I set the wrong variable "TM_TZ", such as
TM_TZ=TM_TZ=Asia/Shanghai
Please close this issue

**Comment by JakobLichterfeld** [comment]
> Oh, sorry, it's because I set the wrong variable "TM_TZ", such as
> TM_TZ=TM_TZ=Asia/Shanghai
> Please close this issue

No worries, glad you solved your issue! Enjoy TeslaMate!
