### ISSUE TITLE
Terminate a drive or charge

### ISSUE THREAD

**Issue by hendrikp123** [teslamate-org/teslamate#4450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

since my car is parking in a garage with no cellular network, one of my drives is incomplete. So I tried to close it as explained on https://docs.teslamate.org/docs/maintenance/manually_fixing_data. 

Tried `bin/teslamate rpc \ "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 14) |> TeslaMate.Log.close_drive()"`  on the docker container bash and also `bin/teslamate rpc \ "TeslaMate.Repo.get(TeslaMate.Log.Drive, 14) |> TeslaMate.Log.close_drive()"` without `!` like explained in the other issues regarding this topic. 

I get no log or any information. Drive is still incomplete. Also checked the database directly, only start date is populated.  
But it seems the container restarts after both commands (see attached logs)

### Expected Behavior

Drive is closed

### Relevant log output

```shell
024-12-20 23:23:49.512 [info] System Info: Erlang/OTP 26 (jit)
2024-12-20 23:23:49.512 [info] Version: 1.32.0
2024-12-20 23:23:49.848 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (295.250 ms)
2024-12-20 23:23:49.848 [info] Refreshed api tokens
2024-12-20 23:23:49.853 [info] Scheduling token refresh in 6 h
2024-12-20 23:23:49.861 [info] Running TeslaMateWeb.Endpoint with cowboy 2.12.0 at :::4000 (http)
2024-12-20 23:23:49.861 [info] Access TeslaMateWeb.Endpoint at http://localhost
2024-12-20 23:23:50.045 [info] Starting logger for 'Klapperkiste'
2024-12-20 23:23:50.146 car_id=1 [info] Start / :offline
2024-12-20 23:24:52.751 [info] Migrations already up
2024-12-20 23:24:56.809 [info] System Info: Erlang/OTP 26 (jit)
2024-12-20 23:24:56.809 [info] Version: 1.32.0
2024-12-20 23:24:57.181 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (330.968 ms)
2024-12-20 23:24:57.181 [info] Refreshed api tokens
2024-12-20 23:24:57.186 [info] Scheduling token refresh in 6 h
2024-12-20 23:24:57.195 [info] Running TeslaMateWeb.Endpoint with cowboy 2.12.0 at :::4000 (http)
2024-12-20 23:24:57.196 [info] Access TeslaMateWeb.Endpoint at http://localhost
2024-12-20 23:24:57.433 [info] Starting logger for 'Klapperkiste'
2024-12-20 23:24:57.524 car_id=1 [info] Start / :offline
2024-12-20 23:25:16.357 [info] Migrations already up
2024-12-20 23:25:20.273 [info] System Info: Erlang/OTP 26 (jit)
2024-12-20 23:25:20.273 [info] Version: 1.32.0
2024-12-20 23:25:20.659 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (343.875 ms)
2024-12-20 23:25:20.659 [info] Refreshed api tokens
2024-12-20 23:25:20.664 [info] Scheduling token refresh in 6 h
2024-12-20 23:25:20.671 [info] Running TeslaMateWeb.Endpoint with cowboy 2.12.0 at :::4000 (http)
2024-12-20 23:25:20.672 [info] Access TeslaMateWeb.Endpoint at http://localhost
```

### Additional data

[drives2.csv](https://github.com/user-attachments/files/18216328/drives2.csv)

### Type of installation

Docker

### Version

v1.32.0

**Comment by hendrikp123** [comment]
bash and sh: same problem
also after running the command the docker container bash is closed automatically, so I'm on the OS level bash again

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. 

Not reproducible here.

> Tried bin/teslamate rpc \ "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 14) |> TeslaMate.Log.close_drive()" on the docker container bash and also bin/teslamate rpc \ "TeslaMate.Repo.get(TeslaMate.Log.Drive, 14) |> TeslaMate.Log.close_drive()" without ! like explained in the other issues regarding this topic.

As the command does not match the doc, it is expected to fail.

**Comment by hendrikp123** [comment]
Hi Jakob, thanks for the quick response!
I did use the command as states in the doc of where is the difference? If i use the bash in the Container directly or docker-Compose exec makes no difference for me on the result. How can I provide more info maybe other logs? Thanks! Great tool and work by the way :) greetings from Hamburg!

**Comment by JakobLichterfeld** [comment]
Hi Hendrik,

yes and no, the docs say `docker compose exec teslamate bin/teslamate rpc \
    "TeslaMate.Repo.get!(TeslaMate.Log.Drive, 9999) |> TeslaMate.Log.close_drive()"` 
    
In most cases this is an encoding issue with the termina the user uses or something similar.

In your case, the start date does look a bit fishy (`2024-12-19 18:04:26.31108`, the precision at the end is not expected, expected is `2024-12-19 16:40:08.591`)

**Comment by hendrikp123** [comment]
tried again, also manually typing in the command to avoid encoding issues due to copy&paste. No success. Also manually fixed the start date on the database directly, also no difference after that. Little bit lost now :)

**Comment by JakobLichterfeld** [comment]
What happens if you run: `docker compose exec database psql teslamate teslamate` and then `SELECT FROM drives WHERE id = 14;`?

**Comment by hendrikp123** [comment]
<img width="560" alt="image" src="https://github.com/user-attachments/assets/52dc8b4c-450b-4bad-b599-38aaf7ccc462" />

**Comment by hendrikp123** [comment]
<img width="344" alt="image" src="https://github.com/user-attachments/assets/02dfc72b-c06f-45c0-865d-ca8d97c405d9" />
got 1 row, only start date filled (now with correct precision) and car id = 1, other columns empty

**Comment by JakobLichterfeld** [comment]
ok, really strange behavior. So the drive does exist. @swiffer, do you have any other clues? I'm a bit puzzled.

**Comment by cwanja** [comment]
I do believe the code still works, I was able to close out two drives tonight. Here is the log of my script and my script for sharing purposes. 

```
Seeking for unclosed drives & charges...
Closing drive num: 3751...

19:54:44.692 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (571.191 ms)

19:54:45.706 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (1005.352 ms)
Closing drive num: 3753...

19:54:47.112 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (101.723 ms)

19:54:48.153 [info] GET https://nominatim.openstreetmap.org/reverse -> 200 (1035.648 ms)
Done.
pi@teslapi:~/Documents/teslamate $ cat close-drives-charges.sh 
#!/bin/bash
echo "Seeking for unclosed drives & charges..."

sql="select id from charging_processes where end_date is null and start_date <  now() + interval '-2 days' order by start_date;"
data=$(docker exec teslamate-database-1 bash -c "psql -d teslamate -U teslamate -t -c \"${sql}\"")
data=($data)

if [ "${data}" != "" ]; then
  for m in "${data[@]}"; do
    echo "Closing charge num: ${m}..."
    sudo docker exec  teslamate-teslamate-1 /opt/app/bin/teslamate rpc "TeslaMate.Repo.get(TeslaMate.Log.ChargingProcess,${m}) |> TeslaMate.Log.complete_charging_process()";
  done
fi

sql="select id from drives where end_date is null and start_date <  now() + interval '-2 days' order by start_date;"
data=$(docker exec teslamate-database-1 bash -c "psql -d teslamate -U teslamate -t -c \"${sql}\"")
data=($data)

if [ "${data}" != "" ]; then
  for m in "${data[@]}"; do
    echo "Closing drive num: ${m}..."
    sudo docker exec  teslamate-teslamate-1 /opt/app/bin/teslamate rpc "TeslaMate.Repo.get(TeslaMate.Log.Drive,${m}) |> TeslaMate.Log.close_drive()";
  done
fi

echo "Done."
```

**Comment by hendrikp123** [comment]
Thanks! The syntax of the commands in the script did not fix it either... it seems to be a problem with the docker configuration on home assistant OS. I created a backup and moved it to a local docker compose installation. There the command as stated in the manual did work as expected. Moved that via backup and restore to the HA OS installation and everything is fine for now. Still strange to me, that container is crashing while running the close_drive() command and no hints in the logs or anything, but that workaround solved it for me. Thanks for all the support! :)

**Comment by JakobLichterfeld** [comment]
Glad you solved it.

> it seems to be a problem with the docker configuration on home assistant OS

Please be sure to specify your installation method correctly when opening a ticket in the future. This will help us to resolve your issue within minutes, saving everyone time.
