### ISSUE TITLE
Multiple superchargers are split in two seperate chargers in charging stats

### ISSUE THREAD

**Issue by tomribbens** [teslamate-org/teslamate#4451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I noticed that my top location for supercharging is listed as two seperate charging stations.  Looking into it, I can see on the map multiple locations where Teslamate has attributed the charging to different charging stations.

### Expected Behavior

I would expect those stats to combine into 1 charging station.

### Relevant log output

```shell
Don't think logs are relevant here, will provide if indicated otherwise.
```

### Screenshots

![teslamate chargers](https://github.com/user-attachments/assets/b998304c-5ee2-478b-9a0a-3a5715a82544)

### Type of installation

Docker

### Version

1.32.0

**Comment by cwanja** [comment]
What are the addresses listed in TeslaMate? I assume OSM has them as separate locations - maybe one stall is tied to one 'location' and other stalls are separate. 

Have you considered adding a Geofence for the charging location?

**Comment by tomribbens** [comment]
They are listed as 
- Mercuriusstraat, Zaventem
- Zaventem Supercharger, Zaventem

They are literally right next to each other on the map as you can see.

But you are right, adding a Geofence also solves the problem, and I hadn't thought of that.

**Comment by cwanja** [comment]
It would seem the fencing from OSM is not inclusive of all the stalls at the Supercharger. If you park 'outside' OSMs fence, it seems to mark it as a city. If you park inside, it's identified as the Supercharger. 

OSM is open source. You could go make the change and it could get included in future updates.

**Comment by cwanja** [comment]
Glad the local geofence solves the issue.

**Comment by JakobLichterfeld** [comment]
Thanks for reporting.

> I would expect those stats to combine into 1 charging station.

Just make sure your GPS reports same position, or create a geofence in TeslaMate with bigger radius.
