### ISSUE TITLE
Charging data missing from dashboard and unable to correct

### ISSUE THREAD

**Issue by brianjniewohner** [teslamate-org/teslamate#4457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm inconsistently seeing charges at Superchargers not being fully recorded.  The charge ID shows up in the 'Incomplete Charges' section, and when following the _Manually fixing data_ doc a `** (FunctionClauseError) no function clause matching in Decimal.decimal/1` is returned.  This issue appears to be similar to issue #2994.  I also have a geo-fence for the Supercharger, but the costs are `NULL`.  Reviewing the relevant log data from when the charge started and ended, the same FunctionClauseError is shown there.

### Expected Behavior

Fully recorded charging session in the database and in the "Charges" table.

### Steps To Reproduce

1. Start charging at location.
2. End charging at location.
3. Open TeslaMate site, access Charges dashboard and find charge data.
4. Charge details not available, charge ID is located in 'Incomplete Charges'.
5. Open SSH to docker host and run the `TeslaMate.Log.complete_charging_process()`.  This returns function error.

### Relevant log output

```shell
2024-12-27 23:14:01.292 car_id=1 [info] Charging / SOC: 17% / Hy-Vee 90th & Center
2024-12-27 23:14:01.293 car_id=1 [info] Disconnecting ...
2024-12-27 23:27:22.240 [error] GenStateMachine :"1" terminating
** (FunctionClauseError) no function clause matching in Decimal.decimal/1
(decimal 2.1.1) Decimal.decimal(nil)
(decimal 2.1.1) lib/decimal.ex:996: Decimal.mult/2
(teslamate 1.32.0) lib/teslamate/log.ex:581: TeslaMate.Log.put_cost/2
(teslamate 1.32.0) lib/teslamate/log.ex:462: TeslaMate.Log.complete_charging_process/1
(teslamate 1.32.0) lib/teslamate/vehicles/vehicle.ex:925: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
(ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1400: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
(db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
(teslamate 1.32.0) lib/teslamate/vehicles/vehicle.ex:918: TeslaMate.Vehicles.Vehicle.handle_event/4
2024-12-27 23:27:22.998 car_id=1 [info] Start / :online
```

### Screenshots

My attempt to end the charge
![complete charge](https://github.com/user-attachments/assets/a3e02906-8c84-433d-8707-a37e22f08916)
The total charges that have been having the same issue.  Trying to manually end these charges produces the same error from above.
![incomplete_charges](https://github.com/user-attachments/assets/64e061e1-1bb6-4def-9b41-f86a98d091f9)

### Additional data

Adding charge data from the month of December, which includes 3 charging sessions that aren't properly recorded.
[charges.csv](https://github.com/user-attachments/files/18271587/charges.csv)
[charging_processes.csv](https://github.com/user-attachments/files/18271588/charging_processes.csv)

### Type of installation

Docker

### Version

v1.32.0

**Comment by mjyousse** [comment]
I'm having a similar issue, I was able to enter the price manually for that session, but now I am unable to. It redirects me to a page and says "Not Found"

**Comment by eliluong** [comment]
This is a guess, but the code that processes the charging session after finishing charging is expecting a number, but since you have NULL as the cost it is giving error. Are you able to enter a value for cost per kWh on the geofence?

**Comment by brianjniewohner** [comment]
I set the geo-fence to 0.0100, then tried running the command to end the charge.  I was able to get all the incomplete charges fixed and checking the charge data, I don't see any issues.  I'm glad it was a simple fix, but sad I didn't think to just set some number.
