### ISSUE TITLE
Total Cost Charges Tab is not updated if cost manually changed

### ISSUE THREAD

**Issue by pabloitaly** [teslamate-org/teslamate#808]
In the "Charges" tab, if I manually enter the "Cost" it is not automatically added to the total cost displayed at the bottom of the page

**Expected behavior**

change cose manually

- TeslaMate version: 1.19.4
- Type of installation: Docker 
- OS TeslaMate is installed on: Qnap
- User OS & Browser: Chrome - Safari
![Schermata 2020-06-24 alle 11 11 59](https://user-images.githubusercontent.com/67366620/85528028-ba9d7c00-b60b-11ea-936d-9cab3cc107c8.png)

- Others:

**Comment by ayonix** [comment]
@pabloitaly Is this still of interest? If so, how did you add the cost/could you provide the query?

**Comment by ogezue** [comment]
Would it be possible to set a rule here like I do with geofences? Whenever I charge here, the price is x. This prevents setting up geofences for every station by hand even if I visit it twice by year.
